### ISSUE TITLE
Uncaught TypeError: editor.languageMode.rowRangeForCodeFoldAtBufferRow is not a function

### ISSUE THREAD

**Issue by elben10** [nteract/hydrogen#1034]
When I run the following piece of code I get the following error _Uncaught TypeError_

    import numpy
    import pandas
    
    2+2

**Atom**: 1.22.0-beta0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.13
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 1.23.0

### Stack Trace

Uncaught TypeError: editor.languageMode.rowRangeForCodeFoldAtBufferRow is not a function

```
At /Users/jakobelben/.atom/packages/Hydrogen/lib/code-manager.js:314

TypeError: editor.languageMode.rowRangeForCodeFoldAtBufferRow is not a function
    at Object.findCodeBlock (/packages/Hydrogen/lib/code-manager.js:314:41)
    at Object.run (/packages/Hydrogen/lib/main.js:412:35)
    at HTMLElement.hydrogenRun (/packages/Hydrogen/lib/main.js:94:36)
    at CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  2x -2:37.7.0 editor:newline (input.hidden-input)
 24x -2:34.6.0 core:move-down (input.hidden-input)
     -2:29.3.0 core:backspace (input.hidden-input)
     -2:28 autocomplete-plus:confirm (input.hidden-input)
  3x -2:21.9.0 hydrogen:run (input.hidden-input)
     -1:00.6.0 core:select-all (input.hidden-input)
  4x -1:00.2.0 hydrogen:run (input.hidden-input)
  2x -0:52 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:16.5.0 hydrogen:run (input.hidden-input)
     -0:15.9.0 core:move-up (input.hidden-input)
     -0:15.2.0 core:select-left (input.hidden-input)
  3x -0:14.9.0 hydrogen:run (input.hidden-input)
  2x -0:10.9.0 editor:newline (input.hidden-input)
     -0:08.5.0 hydrogen:run (input.hidden-input)
     -0:07.8.0 core:select-all (input.hidden-input)
  2x -0:07.5.0 hydrogen:run (input.hidden-input)
```

### Non-Core Packages

```
atom-latex 0.8.2 
Hydrogen 1.23.0 
language-latex 1.1.1 
latex-autocomplete 1.0.0 
latex-completions 0.3.3 
```

**Comment by lgeiger** [comment]
Thanks for opening the issue. We need to fix this.

Atom 1.22 removed the unofficial `languageMode` API: https://github.com/atom/atom/pull/15713

It looks like `editor.tokenizedBuffer.getFoldableRangeContainingPoint()` implements this functionality now.

@elben10 would you be interested in sending a PR to fix this?
