### ISSUE TITLE
Uncaught TypeError: Cannot read property 'text/plain' of undefined

### ISSUE THREAD

**Issue by tkinter2** [nteract/hydrogen#1075]
[Enter steps to reproduce:]

1. ...unknown
2. ...unknown

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'text/plain' of undefined

```
At C:\Users\Timmis\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:36

TypeError: Cannot read property 'text/plain' of undefined
    at OutputArea.handleClick (/packages/Hydrogen/lib/components/output-area.js:34:52)
    at Object.cb (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:36:125)
    at Object.invokeGuardedCallback (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:35:21)
    at Object.invokeGuardedCallbackAndCatchFirstError (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:35:133)
    at gb (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:36:400)
    at Object.executeDispatchesInOrder (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:38:154)
    at Fb (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:46:103)
    at Hb (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:46:230)
    at Array.forEach (native)
    at Db (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:46:39)
    at Object.processEventQueue (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:49:254)
    at /packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:57:97)
    at xb (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:43:390)
    at batchedUpdates (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:190:243)
    at qb (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:41:344)
    at ob (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:41:278)
    at Object.batchedUpdates (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:42:85)
    at dispatchEvent (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:45:162)
```

### Commands

```
     -9:48.5.0 node-debugger:toggle-debugger (atom-pane.pane)
     -9:35.9.0 node-debugger:start-resume (atom-pane.pane)
     -9:19.1.0 git-time-machine:toggle (atom-pane.pane)
     -8:58.2.0 node-debugger:start-active-file (atom-pane.pane)
     -8:46.4.0 node-debugger:step-out (atom-pane.pane)
     -8:32.1.0 command-palette:toggle (atom-pane.pane)
     -7:52.3.0 script:kill-process (atom-pane.pane)
  2x -7:38.7.0 atom-clock:toggle (atom-pane.pane)
     -7:25.2.0 atom-clock:utc-mode (atom-pane.pane)
     -7:20.3.0 dev-live-reload:reload-all (atom-pane.pane)
     -7:00.2.0 whitespace:convert-all-tabs-to-spaces (atom-pane.pane)
  5x -5:18.3.0 github:discard-changes-in-selected-files (span.github-FilePatchListView-path)
     -4:36.3.0 core:confirm (span.github-FilePatchListView-path)
 12x -4:04.2.0 github:discard-changes-in-selected-files (div.github-FilePatchListView-item.is-modified.is-selected)
```

### Non-Core Packages

```
atom-clock 0.1.15 
atom-ftp-deployment 0.4.0 
busy-signal 1.4.3 
git-time-machine 1.5.9 
greyatom-hydrogen 1.9.0 
Hydrogen 2.0.1 
ink 0.7.7 
intentions 1.1.5 
language-coffee-script-angular 2.2.0 
linter 2.2.0 
linter-bootlint 1.1.0 
linter-ui-default 1.6.10 
node-debugger 1.10.1 
pristine-ui 1.1.10 
script 3.17.3 
the-matrix-syntax 0.6.0 
vim-mode-plus 1.15.0 
```

**Comment by lgeiger** [comment]
Could you add steps how to reproduce this issue?

**Comment by BenRussert** [comment]
If this is when you try to copy error output from the output pane I have a fix I can PR later.
