### ISSUE TITLE
Uncaught Error: Cannot find module '../build/Release/zmq.node'

### ISSUE THREAD

**Issue by Mahameda** [nteract/hydrogen#1082]
[Enter steps to reproduce:]

1. crash atom while installing a plugin
2. restart and crash it again
3. restart error apears

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.0.1

### Stack Trace

Uncaught Error: Cannot find module '../build/Release/zmq.node'

```
At C:\Users\Eigenaar\AppData\Local\atom\app-1.21.2\resources\app\static\<embedded>:1

Error: Cannot find module '../build/Release/zmq.node'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.21.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.21.2/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.21.2/resources/app/src/native-compile-cache.js:66:33)
    at /packages/Hydrogen/node_modules/zeromq/lib/index.js:6:11)
    at /packages/Hydrogen/node_modules/zeromq/lib/index.js:848:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.21.2/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.21.2/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.21.2/resources/app/src/native-compile-cache.js:66:33)
    at /packages/Hydrogen/node_modules/zeromq/index.js:2:18)
    at /packages/Hydrogen/node_modules/zeromq/index.js:3:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.21.2/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.21.2/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.21.2/resources/app/src/native-compile-cache.js:66:33)
    at /packages/Hydrogen/node_modules/jmp/index.js:37:11)
    at /packages/Hydrogen/node_modules/jmp/index.js:432:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.21.2/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.21.2/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

### Commands

```
     -2:30.3.0 core:paste (input.hidden-input)
  4x -2:28.4.0 core:backspace (input.hidden-input)
     -2:24.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
atom-clock 0.1.15 
emmet 2.4.3 
Hydrogen 2.0.1 
```

**Comment by lgeiger** [comment]
Have you tried reinstalling it via the command line?
```bash
apm uninstall hydrogen
apm install hydrogen
```

**Comment by Fartown** [comment]
i met the same question.
but the solution can not work.
Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
Hydrogen :2.4.1



module.js:549 throw err; ^

Error: Cannot find module '../build/Release/zmq.node' at Function.Module._resolveFilename (module.js:547:15) at Function.Module._load (module.js:474:25) at Module.require (module.js:596:17) at require (internal/module.js:11:18) at Object. (/Users/zchao/.nvm/versions/node/v8.10.0/lib/node_modules/ijavascript/node_modules/zeromq/lib/index.js:6:11) at Module._compile (module.js:652:30) at Object.Module._extensions..js (module.js:663:10) at Module.load (module.js:565:32) at tryModuleLoad (module.js:505:12) at Function.Module._load (module.js:497:3)

**Comment by Lee1125** [comment]
I have same problem. How to address it?

**Comment by Lee1125** [comment]
> Have you tried reinstalling it via the command line?
> 
> ```shell
> apm uninstall hydrogen
> apm install hydrogen
> ```

I tried in this method.But it can't work. How to address it?

**Comment by Lee1125** [comment]
> I'm sure the solution above will work, let us know if you have any questions!

I have same problem. How to address it?

**Comment by Lee1125** [comment]
> i met the same question.
> but the solution can not work.
> Atom : 1.26.1
> Electron: 1.7.11
> Chrome : 58.0.3029.110
> Node : 7.9.0
> Hydrogen :2.4.1
> 
> module.js:549 throw err; ^
> 
> Error: Cannot find module '../build/Release/zmq.node' at Function.Module._resolveFilename (module.js:547:15) at Function.Module._load (module.js:474:25) at Module.require (module.js:596:17) at require (internal/module.js:11:18) at Object. (/Users/zchao/.nvm/versions/node/v8.10.0/lib/node_modules/ijavascript/node_modules/zeromq/lib/index.js:6:11) at Module._compile (module.js:652:30) at Object.Module._extensions..js (module.js:663:10) at Module.load (module.js:565:32) at tryModuleLoad (module.js:505:12) at Function.Module._load (module.js:497:3)

Did you solve this problem?
