### ISSUE TITLE
Uncaught Error: Cannot find module 'lodash'

### ISSUE THREAD

**Issue by wi-bi** [nteract/hydrogen#1111]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.1.0

### Stack Trace

Uncaught Error: Cannot find module 'lodash'

```
At C:\Users\whbe\AppData\Local\atom\app-1.22.1\resources\app\static\<embedded>:1

Error: Cannot find module 'lodash'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.22.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.22.1/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.22.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/Hydrogen/lib/main.js:9:14)
    at /packages/Hydrogen/lib/main.js:557:24)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.22.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.22.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.22.1/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:903:35)
    at Package.module.exports.Package.activateConfig (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:301:18)
    at PackageDetailView.activateConfig (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/package-detail-view.js:279:25)
    at PackageDetailView.completeInitialization (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/package-detail-view.js:213:18)
    at PackageDetailView.loadPackage (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/package-detail-view.js:225:20)
    at new PackageDetailView (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/package-detail-view.js:100:16)
    at callback (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/settings-view.js:356:26)
    at SettingsView.getOrCreatePanel (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/settings-view.js:361:25)
    at SettingsView.showPanel (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/settings-view.js:419:30)
    at SettingsView.showDeferredPanel (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/settings-view.js:406:20)
    at SettingsView.initializePanels (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/settings-view.js:240:18)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/settings-view.js:118:26
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:27.1.0 application:reopen-project (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.10.3 
busy-signal 1.4.3 
Hydrogen 2.1.0 
intentions 1.1.5 
linter 2.2.0 
linter-flake8 2.2.1 
linter-ui-default 1.6.10 
python-autopep8 0.1.3 
python-indent 1.1.4 
script 3.17.3 
spacegray-atom-dark-syntax 1.3.2 
```

**Comment by BenRussert** [comment]
I'm sure the solution above will work, let us know if you have any questions!
