### ISSUE TITLE
install fails from "Install" pane

### ISSUE THREAD

**Issue by goi42** [nteract/hydrogen#1149]
**Description:**

Since at least the recent update, trying to install from the Install pane in preferences fails. From the command line, `apm install hydrogen` works fine.

**Steps to Reproduce:**

1. Find Hydrogen in "Install"
2. Click "Install"
3. Wait forever
4. Notice it fails
5. Install from command line

**Versions:**

Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Logs:**

```
Installing “Hydrogen@2.2.0” failed.Hide output…
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/michael/.atom/packages/Hydrogen/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Proxy.fs.readFileSync (fs.js:508:33)
    at Proxy.fs.readFileSync (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/asar-require/lib/require.js:86:27)
    at /Applications/Atom.app/Contents/Resources/app/apm/lib/install.js:476:42
    at fn (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:498:34)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

**Comment by lgeiger** [comment]
This looks like a bug on the Atom side: https://github.com/atom/settings-view/issues/1018

For now we recommend to install hydrogen from the command line.
