### ISSUE TITLE
Installing “Hydrogen@2.2.0” failed.

### ISSUE THREAD

**Issue by MichaelStetner** [nteract/hydrogen#1150]
**Description:**

Failed to install Hydrogen 

**Steps to Reproduce:**

1. Navigate to Settings -> Install
2. Search for Hydrogen and click Install

**Versions:**

Mac OS 10.11.6

Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Logs:**

```
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/stetnermit/.atom/packages/Hydrogen/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Proxy.fs.readFileSync (fs.js:508:33)
    at Proxy.fs.readFileSync (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/asar-require/lib/require.js:86:27)
    at /Applications/Atom.app/Contents/Resources/app/apm/lib/install.js:476:42
    at fn (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:498:34)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

**Comment by benmak11** [comment]
I got the same error as well... Anyone looking into this?

**Comment by MichaelStetner** [comment]
This seems like the same issue that is mentioned here: https://nteract.gitbooks.io/hydrogen/docs/Installation.html

Following the instructions from that page, I was able to install it from the command line by doing `apm install hydrogen`

**Comment by Chestergc** [comment]
That solved it for me as well, weird that when I checked for the file it mentioned it was clearly there and populated at the time of the error. The log I got for the error was the same as yours, besides the username obviously.

**Comment by cdarlint** [comment]
same here, and solved by apm as well

**Comment by lgeiger** [comment]
👍This will be fixed in the next Atom version.
