### ISSUE TITLE
hydrogen fails to update to 2.2.0

### ISSUE THREAD

**Issue by HaoyangFan** [nteract/hydrogen#1152]
**Description:**

When I tried to update hydrogen installed on my Atom from version 2.1.1 to 2.2.0, it always fails.

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?
Atom    : 1.23.1
Hydrogen: 2.1.1

**Logs:**

fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/HaoyangFan/.atom/packages/Hydrogen/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Proxy.fs.readFileSync (fs.js:508:33)
    at Proxy.fs.readFileSync (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/asar-require/lib/require.js:86:27)
    at /Applications/Atom.app/Contents/Resources/app/apm/lib/install.js:476:42
    at fn (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:498:34)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)

**Comment by HaoyangFan** [comment]
Sorry, I just find out that this issue is duplicate to #1151 #1150, and I solve this issue using the same way by running `apm install hydrogen`
