### ISSUE TITLE
Error installing on Mac

### ISSUE THREAD

**Issue by selfagency** [nteract/hydrogen#1157]
**Description:**

Throws error installing on Mac

**Steps to Reproduce:**

1. apm install Hydrogen

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?

Mac OS 10.13.2
Atom 1.23.1

**Logs:**

```
Installing Hydrogen to /Users/daniel/.atom/packages ✓
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/daniel/.atom/packages/Hydrogen/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Proxy.fs.readFileSync (fs.js:508:33)
    at Proxy.fs.readFileSync (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/asar-require/lib/require.js:86:27)
    at /Applications/Atom.app/Contents/Resources/app/apm/lib/install.js:476:42
    at fn (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:498:34)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

**Comment by nikitakit** [comment]
This looks like a duplicate of #1150. This is an Atom bug that should be fixed in a new release of atom, but there were some workarounds suggested to install hydrogen in the meantime.

**Comment by selfagency** [comment]
Thanks.

**Comment by selfagency** [comment]
Duplicate of #1150.
