### ISSUE TITLE
With Atom 1.23.1 update, Hydrogen package disappears and can't be installed

### ISSUE THREAD

**Issue by ctivanovich** [nteract/hydrogen#1160]
I updated to Atom 1.23.1 for windows, and discovered that Hydrogen had disappeared from my installed packages list. I checked the prior version, 1.22.1, and it was missing from that folder as well.

I tried to reinstall it, and got the following error:
```Installing “Hydrogen@2.2.0” failed.Hide output…
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\Christopher\.atom\packages\Hydrogen\package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Proxy.fs.readFileSync (fs.js:508:33)
    at Proxy.fs.readFileSync (C:\Users\Christopher\AppData\Local\atom\app-1.23.1\resources\app\apm\node_modules\asar-require\lib\require.js:86:27)
    at C:\Users\Christopher\AppData\Local\atom\app-1.23.1\resources\app\apm\lib\install.js:476:42
    at fn (C:\Users\Christopher\AppData\Local\atom\app-1.23.1\resources\app\apm\node_modules\async\lib\async.js:582:34)
    at Immediate.<anonymous> (C:\Users\Christopher\AppData\Local\atom\app-1.23.1\resources\app\apm\node_modules\async\lib\async.js:498:34)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)```

**Comment by ctivanovich** [comment]
Ah, this seems to have been noted in the documentation, and installing via command line is still possible:
[https://nteract.gitbooks.io/hydrogen/docs/Installation.html]

**Comment by lgeiger** [comment]
This is a upstream issue on Atom, which will be fixed in with the next version.
