### ISSUE TITLE
Installation failure on macOS 10.13

### ISSUE THREAD

**Issue by willingc** [nteract/hydrogen#1166]
<img width="476" alt="screenshot 2017-12-29 09 09 17" src="https://user-images.githubusercontent.com/2680980/34442622-33c98afc-ec78-11e7-908e-36076c1c469f.png">

```
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/carol/.atom/packages/Hydrogen/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Proxy.fs.readFileSync (fs.js:508:33)
    at Proxy.fs.readFileSync (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/asar-require/lib/require.js:86:27)
    at /Applications/Atom.app/Contents/Resources/app/apm/lib/install.js:476:42
    at fn (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:498:34)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

**Comment by lgeiger** [comment]
Unfortunately this is a upstream issue in Atom 1.23 (#1150) installing from the command line via `apm install hydrogen` should work though.

**Comment by willingc** [comment]
Got it. Thanks @lgeiger.
