### ISSUE TITLE
`requirejs is not defined` when run plotly-jupyter-scala

### ISSUE THREAD

**Issue by lovepocky** [nteract/hydrogen#1167]
**Description:**
result:
```javascript
ReferenceError: requirejs is not defined
    at eval (eval at runCodeHere (/Users/lovepocky/.atom/packages/Hydrogen/node_modules/@nteract/transforms/lib/javascript.js:29:12), <anonymous>:1:1)
    at runCodeHere (/Users/lovepocky/.atom/packages/Hydrogen/node_modules/@nteract/transforms/lib/javascript.js:29:12)
    at JavaScript.componentDidMount (/Users/lovepocky/.atom/packages/Hydrogen/node_modules/@nteract/transforms/lib/javascript.js:54:7)
    at commitLifeCycles (/Users/lovepocky/.atom/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:149:193)
    at b (/Users/lovepocky/.atom/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:158:229)
    at m (/Users/lovepocky/.atom/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:169:217)
    at w (/Users/lovepocky/.atom/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:168:413)
    at batchedUpdates (/Users/lovepocky/.atom/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:171:357)
    at tc (/Users/lovepocky/.atom/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:54:269)
    at reactionScheduler (/Users/lovepocky/.atom/packages/Hydrogen/node_modules/mobx/lib/mobx.js:3209:47)
    at runReactions (/Users/lovepocky/.atom/packages/Hydrogen/node_modules/mobx/lib/mobx.js:3185:5)
    at endBatch (/Users/lovepocky/.atom/packages/Hydrogen/node_modules/mobx/lib/mobx.js:2734:9)
    at endAction (/Users/lovepocky/.atom/packages/Hydrogen/node_modules/mobx/lib/mobx.js:951:5)
    at executeAction (/Users/lovepocky/.atom/packages/Hydrogen/node_modules/mobx/lib/mobx.js:918:9)
    at OutputStore.res (/Users/lovepocky/.atom/packages/Hydrogen/node_modules/mobx/lib/mobx.js:906:16)
    at /Users/lovepocky/.atom/packages/Hydrogen/lib/main.js:382:19
    at ZMQKernel.onIOMessage (/Users/lovepocky/.atom/packages/Hydrogen/lib/zmq-kernel.js:382:7)
    at Socket.<anonymous> (/Users/lovepocky/.atom/packages/Hydrogen/node_modules/jmp/index.js:350:17)
    at emitMany (events.js:127:13)
    at Socket.emit (events.js:201:7)
    at Socket._emitMessage (/Users/lovepocky/.atom/packages/Hydrogen/node_modules/zeromq/lib/index.js:640:15)
    at Socket._flushRead (/Users/lovepocky/.atom/packages/Hydrogen/node_modules/zeromq/lib/index.js:651:10)
    at Socket._flushReads (/Users/lovepocky/.atom/packages/Hydrogen/node_modules/zeromq/lib/index.js:687:15)
    at Object._zmq.onReadReady (/Users/lovepocky/.atom/packages/Hydrogen/node_modules/zeromq/lib/index.js:306:10)
```

**Steps to Reproduce:**

1.  code (example code from https://github.com/jupyter-scala/jupyter-scala):
```scala
import $ivy.`org.plotly-scala::plotly-jupyter-scala:0.3.0`

import plotly._
import plotly.element._
import plotly.layout._
import plotly.JupyterScala._

plotly.JupyterScala.init()

val (x, y) = Seq(
  "Banana" -> 10,
  "Apple" -> 8,
  "Grapefruit" -> 5
).unzip

Bar(x, y).plot()
```

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?

- macos 10.13.2

```bash
$ atom --version
Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
- hydrogen version is 2.2.0

You can get this information from copy and pasting the output of `atom --version`  from the command line.

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

- just get trival messages

**Comment by wadethestealth** [comment]
If this issue persists on a new version of hydrogen please open a new issue.
