### ISSUE TITLE
Hydrogen uninstalls spontaneously, then seemingly hangs on installation

### ISSUE THREAD

**Issue by Putnik1** [nteract/hydrogen#1173]
**Description:**

Hydrogen seemed to have been spontaneously uninstalled under Atom, while using it, with Cmd-Enter producing a line feed.  Installing it again, it seems to never indicate completion.  But restarting Atom it seems to be installed

**Steps to Reproduce:**

1. No specific step for Hydrogen to seemingly uninstall itself
2. Installing Hydrogen again by Atom Preferences...  +Install and locating Hydrogen to install

**Versions:**

MacOS 10.13.2,  Atom 1.23.1x64, Hydrogen 2.2.0

**Logs:**

Installing “Hydrogen@2.2.0” failed.Hide output…
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/david/.atom/packages/Hydrogen/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Proxy.fs.readFileSync (fs.js:508:33)
    at Proxy.fs.readFileSync (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/asar-require/lib/require.js:86:27)
    at /Applications/Atom.app/Contents/Resources/app/apm/lib/install.js:476:42
    at fn (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:498:34)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)

**Comment by lgeiger** [comment]
Please try installing it from the command line via `apm install hydrogen`.

**Comment by Putnik1** [comment]
Thanks, it of course works now :)
