### ISSUE TITLE
Can't install Hydrogen 2.2.1 on Atom 1.23.1 for MacOS High Sierra 10.13.2

### ISSUE THREAD

**Issue by MarkPuchalaII** [nteract/hydrogen#1177]
**Description:**

Hydrogen somehow uninstalled itself last night after I installed Java JDK 9

**Steps to Reproduce:**

1. Have macOS High Sierra
2. Have Atom
3. Install Hydrogen

**Versions:**
macOS High Sierra : version 10.13.2
atom.io :                    version 1.23.1
Hydrogen :                version 2.2.1

**Logs:**
Installing “Hydrogen@2.2.1” failed.
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/markpuchalaii/.atom/packages/Hydrogen/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Proxy.fs.readFileSync (fs.js:508:33)
    at Proxy.fs.readFileSync (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/asar-require/lib/require.js:86:27)
    at /Applications/Atom.app/Contents/Resources/app/apm/lib/install.js:476:42
    at fn (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:498:34)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)

**Comment by MarkPuchalaII** [comment]
For clarity, updating to Atom 1.23.2 allowed Hydrogen to install no problem,
so I assume that's where the bug is.

**Comment by lgeiger** [comment]
Thanks for reporting. Yes it was fixed in Atom 1.23.2
