### ISSUE TITLE
Killing kernel from Terminal severely confuses Hydrogen

### ISSUE THREAD

**Issue by nils-werner** [nteract/hydrogen#1237]
**Description:**

Sometimes you run a script that you cannot interrupt. For example a huge NumPy sum that spends most of the time NumPy. Ctrl+C would only work once the sum has returned.

So you go to the terminal, search for the PID of the process and `kill` it. No problem. But Hydrogen thinks the process is still running and will not accept commands.

Restarting the kernel stops at "Python 3 kernel restarting".

Shutting down the kernel makes the status bar go away, and any following commands will trigger a new kernel to be launched, but the UI does not reflect this.

Sometimes even an Atom restart is needed.

**Steps to Reproduce:**

1. Do a huge NumPy sum like `numpy.sum(numpy.random.rand(2812, 8, 200001), axis=-1)`
2. Kill the Python process
3. Try interacting with the Hydrogen UI.

**Versions:**

```
$ atom --version
Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

```
$ apm list
...
├── Hydrogen@2.2.2
...
```

**Comment by wadethestealth** [comment]
I think this was eventually fixed upstream as it is no longer reproducible.

**Comment by wadethestealth** [comment]
Nevermind, this is reproduced as follows.
1. Start an infinite loop.
2. Kill Python process running under Atom.
3. Attempt to restart via StatusBar.
4. Notice it "restarts". (It really doesn't) StatusBar now displays "Kernel | idle"
5. Attempt to run any line that goes through the kernel (aka not comments/markdown)
6. Notice it always fails.
7. Attempt to shutdown via StatusBar.
8. Notice it shuts down and refreshes ui.
9. Attempt to start new kernel by running a code line.
10. Observe it works, but also displays the following error.
```
[IPKernelApp] ERROR | Invalid Message Traceback (most recent call last): File "C:\Users\Wade\Desktop\testing\test\lib\site-packages\ipykernel\kernelbase.py", line 232, in dispatch_shell msg = self.session.deserialize(msg, content=True, copy=False) File "C:\Users\Wade\Desktop\testing\test\lib\site-packages\jupyter_client\session.py", line 923, in deserialize raise ValueError("Invalid Signature: %r" % signature) ValueError: Invalid Signature: b'2ccdcf3c2691d992e62629df0b46bbc6f361ed307b05c7946e556c076443749f' [IPKernelApp] ERROR | Invalid Message Traceback (most recent call last): File "C:\Users\Wade\Desktop\testing\test\lib\site-packages\ipykernel\kernelbase.py", line 232, in dispatch_shell msg = self.session.deserialize(msg, content=True, copy=False) File "C:\Users\Wade\Desktop\testing\test\lib\site-packages\jupyter_client\session.py", line 923, in deserialize raise ValueError("Invalid Signature: %r" % signature) ValueError: Invalid Signature: b'3741c44dbfe7e10f980dfea98d894e9de27c3adb7db1b11ce39cab27326d668b' [IPKernelApp] ERROR | Invalid Message Traceback (most recent call last): File "C:\Users\Wade\Desktop\testing\test\lib\site-packages\ipykernel\kernelbase.py", line 232, in dispatch_shell msg = self.session.deserialize(msg, content=True, copy=False) File "C:\Users\Wade\Desktop\testing\test\lib\site-packages\jupyter_client\session.py", line 923, in deserialize raise ValueError("Invalid Signature: %r" % signature) ValueError: Invalid Signature: b'df59ffeeced40983e07d4fcd647c7b437d974ebd634fdf545c706d3fa0ec0040'
```
