### ISSUE TITLE
Uncaught Error: Invariant violation: "this._disposables != null"

### ISSUE THREAD

**Issue by Chistabo** [nteract/hydrogen#1238]
[Enter steps to reproduce:]

1. Just hit [X] (Close()) of Atom's Diagnostics panel. Happens often.
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.2.3

### Stack Trace

Uncaught Error: Invariant violation: "this._disposables != null"

```
At C:\Users\Chi\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:168

Error: Invariant violation: "this._disposables != null"
    at DiagnosticsTable.componentWillUnmount (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-diagnostics-ui/lib/ui/DiagnosticsTable.js:132:13)
    at /packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:143:273)
    at /packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:143:411)
    at /packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:144:465)
    at commitDeletion (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:148:97)
    at /packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:158:23)
    at /packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:169:217)
    at /packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:168:413)
    at /packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:167:32)
    at /packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:165:441)
    at Object.updateContainer (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:175:31)
    at Pg (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:225:81)
    at /packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:228:69
    at Object.unbatchedUpdates (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:171:453)
    at Object.unmountComponentAtNode (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:228:41)
    at HTMLElement.detachedCallback (/packages/atom-ide-ui/modules/nuclide-commons-ui/ReactMountRootElement.js:35:23)
    at HTMLElement.PaneElement.itemRemoved (/app.asar/src/pane-element.js:199:29)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.removeItem (~/AppData/Local/atom/app-1.24.0/resources/app/src/pane.js:698:24)
    at Pane.destroyItem (~/AppData/Local/atom/app-1.24.0/resources/app/src/pane.js:775:16)
```

### Commands

```
     -4:10.9.0 editor:consolidate-selections (input.hidden-input)
     -4:10.9.0 core:cancel (input.hidden-input)
     -4:08.5.0 core:save (input.hidden-input)
  2x -4:01.6.0 code-format:format-code (input.hidden-input)
     -3:26.3.0 core:save (input.hidden-input)
  2x -3:14.1.0 code-format:format-code (input.hidden-input)
  2x -2:52.3.0 core:save (input.hidden-input)
     -2:39.4.0 code-format:format-code (input.hidden-input)
     -2:39 core:save (input.hidden-input)
     -2:34.6.0 code-format:format-code (input.hidden-input)
     -2:33.7.0 core:save (input.hidden-input)
     -2:04.6.0 tree-view:unfocus (div.tool-panel.tree-view)
     -2:03.8.0 editor:consolidate-selections (input.hidden-input)
     -2:03.8.0 core:cancel (input.hidden-input)
     -2:03.2.0 editor:consolidate-selections (input.hidden-input)
     -2:03.2.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.9.1 
atom-python-run 0.9.6 
autocomplete-python 1.10.5 
Hydrogen 2.2.3 
ide-python 0.8.0 
kite 0.69.0 
```

**Comment by lgeiger** [comment]
This is actual a error from `atom-ide-ui` that was fixed in the latest release: https://github.com/facebook-atom/atom-ide-ui/issues/169
