### ISSUE TITLE
Uncaught Error: Cannot find module '../kernel'

### ISSUE THREAD

**Issue by david8z** [nteract/hydrogen#1244]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.2.3

### Stack Trace

Uncaught Error: Cannot find module '../kernel'

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:1

Error: Cannot find module '../kernel'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (<embedded>:12159:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (<embedded>:11504:33)
    at /packages/Hydrogen/lib/components/kernel-monitor.js:25:15)
    at /packages/Hydrogen/lib/components/kernel-monitor.js:122:3)
    at Module.get_Module._compile (<embedded>:11544:36)
    at Object.value [as .js] (<embedded>:11795:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (<embedded>:11504:33)
    at /packages/Hydrogen/lib/panes/kernel-monitor.js:19:32)
    at /packages/Hydrogen/lib/panes/kernel-monitor.js:65:3)
    at Module.get_Module._compile (<embedded>:11544:36)
    at Object.value [as .js] (<embedded>:11795:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (<embedded>:11504:33)
    at /packages/Hydrogen/lib/main.js:67:27)
    at /packages/Hydrogen/lib/main.js:639:3)
    at Module.get_Module._compile (<embedded>:11544:36)
    at Object.value [as .js] (<embedded>:11795:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (<embedded>:96:26)
    at Package.requireMainModule (<embedded>:72932:33)
    at Package.activateConfig (<embedded>:72417:16)
    at PackageManager.module.exports.PackageManager.packageHasSettings (<embedded>:55526:20)
    at PackageCard.hasSettings (<embedded>:200191:40)
    at PackageCard.updateSettingsState (<embedded>:199836:22)
    at PackageCard.updateInterfaceState (<embedded>:199828:18)
    at <embedded>:200125:22
    at <embedded>:200208:17
    at Function.module.exports.Emitter.simpleDispatch (<embedded>:65825:20)
    at Emitter.module.exports.Emitter.emit (<embedded>:65941:34)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (<embedded>:56161:33)
    at <embedded>:56000:32
    at exit (<embedded>:55586:22)
    at triggerExitCallback (<embedded>:130187:17)
    at <embedded>:130200:17
    at Socket.<anonymous> (<embedded>:130069:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)

```

### Commands

```
     -3:57.1.0 package-generator:generate-package (div.tool-panel.tree-view)
     -2:58.1.0 core:backspace (input.hidden-input)
     -2:48.4.0 core:confirm (input.hidden-input)
     -2:45.3.0 core:copy (input.hidden-input)
     -2:35.6.0 core:cut (input.hidden-input)
     -2:25.7.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.10.5 
Hydrogen 2.2.3 
language-haskell 1.17.3 
language-x86-64-assembly 2.2.11 
script 3.17.3 
```

**Comment by BenRussert** [comment]
Hi, I am sorry nobody got to this. I am sure if you try installing again it will work.
