### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by adriaanbd** [nteract/hydrogen#1254]
[Enter steps to reproduce:]

1. Run first line of the script
2. When choose a kernel from the prompt
3. Re-size current script editor window left and right

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.3.0

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At C:\Users\u6031297\.atom\packages\Hydrogen\node_modules\mobx\lib\mobx.js:1797

RangeError: Maximum call stack size exceeded
    at setPropertyValue (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:1797:26)
    at /packages/Hydrogen/node_modules/mobx/lib/mobx.js:1780:17)
    at Function.assign (<anonymous>)
    at OutputStore.updatePosition (/packages/Hydrogen/lib/store/output.js:125:12)
    at executeAction (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:915:19)
    at OutputStore.res (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:906:16)
    at /packages/Hydrogen/lib/components/result-view/index.js:60:26
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/text-buffer/lib/display-marker.js:248:33)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.notifyObserversIfMarkerScreenPositionsChanged (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/text-buffer/lib/display-marker-layer.js:179:22)
    at displayMarkerLayersById.forEach (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/text-buffer/lib/display-layer.js:831:19)
    at Map.forEach (native)
    at DisplayLayer.notifyObserversIfMarkerScreenPositionsChanged (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/text-buffer/lib/display-layer.js:830:40)
    at DisplayLayer.reset (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/text-buffer/lib/display-layer.js:89:18)
    at TextEditor.update (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor.js:513:29)
    at TextEditor.setEditorWidthInChars (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor.js:1038:59)
    at TextEditorComponent.updateModelSoftWrapColumn (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:2140:30)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:367:16)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:274:16)
    at TextEditorComponent.pixelPositionForScreenPosition (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:206:18)
    at HTMLElement.pixelPositionForBufferPosition (/app.asar/src/text-editor-element.js:231:32)
    at /packages/Hydrogen/lib/components/result-view/index.js:61:38
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/text-buffer/lib/display-marker.js:248:33)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.notifyObserversIfMarkerScreenPositionsChanged (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/text-buffer/lib/display-marker-layer.js:179:22)
    at displayMarkerLayersById.forEach (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/text-buffer/lib/display-layer.js:831:19)
    at Map.forEach (native)
    at DisplayLayer.notifyObserversIfMarkerScreenPositionsChanged (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/text-buffer/lib/display-layer.js:830:40)
    at DisplayLayer.reset (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/text-buffer/lib/display-layer.js:89:18)
```

### Commands

```
     -2:07.7.0 core:backspace (input.hidden-input)
  3x -1:16.1.0 hydrogen:run (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-html-preview 0.2.5 
autocomplete-python 1.10.5 
city-lights-syntax 1.1.8 
city-lights-ui 1.3.3 
Hydrogen 2.3.0 
```

**Comment by wadethestealth** [comment]
Unable to reproduce on newest install of hydrogen. If you are able to reproduce on a new install of hydrogen please open a new issue
