### ISSUE TITLE
Uncaught Error: Cannot find module './kernel-manager'

### ISSUE THREAD

**Issue by maxster256** [nteract/hydrogen#1265]
[Enter steps to reproduce:]

1. Atom started.

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.3.0

### Stack Trace

Uncaught Error: Cannot find module './kernel-manager'

```
At module.js:472

Error: Cannot find module './kernel-manager'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/Hydrogen/lib/signal-list-view.js:21:22)
    at /packages/Hydrogen/lib/signal-list-view.js:120:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/Hydrogen/lib/main.js:35:23)
    at /packages/Hydrogen/lib/main.js:643:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at Package.activateConfig (/Applications/Atom.app/Contents/Resources/app/src/package.js:267:16)
    at PackageManager.module.exports.PackageManager.packageHasSettings (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:68:20)
    at PackageCard.hasSettings (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:794:40)
    at PackageCard.updateSettingsState (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:439:22)
    at PackageCard.updateInterfaceState (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:431:18)
    at new PackageCard (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:92:16)
    at PackageDetailView.completeInitialization (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:206:34)
    at PackageDetailView.loadPackage (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:225:20)
    at new PackageDetailView (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:100:16)
    at callback (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:366:26)
    at SettingsView.getOrCreatePanel (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:371:25)
    at SettingsView.showPanel (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:429:30)
    at SettingsView.showDeferredPanel (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:416:20)
    at SettingsView.initializePanels (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:250:18)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:122:26
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-html-entities 0.2.0 
autocomplete-java 1.2.7 
autocomplete-python 1.10.5 
color-picker 2.2.5 
gpp-compiler 3.0.7 
html-to-css 0.2.2 
Hydrogen 2.3.0 
language-65asm 5.0.0 
language-x86-64-assembly 2.2.11 
platformio-ide-terminal 2.8.1 
python-indent 1.1.4 
script 3.17.3 
```

**Comment by nikitakit** [comment]
Could you try reinstalling hydrogen using the command line?

```
apm uninstall hydrogen
apm install hydrogen
```

---

An aside for hydrogen devs: [a number of similar issues](https://github.com/nteract/hydrogen/issues?utf8=%E2%9C%93&q=%22Uncaught+Error%3A+Cannot+find+module%22) have been popping up during the past year. Reinstalling always seems to fix things.

But does anyone know why this is happening in the first place? There are enough bug reports to suggest a real problem with installation.

**Comment by maxster256** [comment]
That helped!

W dniu 22/03/18 20:37 Nikita Kitaev  <notifications@github.com> napisał:
