### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by hugeme** [nteract/hydrogen#1267]
Just opened a python or R script

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.12.5
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.3.0

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app/src/decoration-manager.js:191

Error: Cannot decorate a destroyed marker
    at DecorationManager.decorateMarker (/Applications/Atom.app/Contents/Resources/app/src/decoration-manager.js:183:27)
    at TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2137:41)
    at /packages/Hydrogen/lib/components/result-view/index.js:50:12)
    at Object._createResultBubble (/packages/Hydrogen/lib/main.js:383:29)
    at /packages/Hydrogen/lib/main.js:360:14
    at /packages/Hydrogen/lib/kernel-manager.js:85:22
    at /packages/Hydrogen/lib/zmq-kernel.js:58:26
    at ZMQKernel.onConnect (/packages/Hydrogen/lib/zmq-kernel.js:129:21)
    at emitThree (events.js:116:13)
    at Socket.emit (events.js:197:7)
    at Object.self._zmq.onMonitorEvent (/packages/Hydrogen/node_modules/zeromq/lib/index.js:543:12)
```

### Commands

```
     -0:53.2.0 intentions:highlight (input.hidden-input)
     -0:53.1.0 advanced-open-file:toggle (input.hidden-input)
  2x -0:50.1.0 core:backspace (input.hidden-input)
     -0:48.4.0 core:confirm (input.hidden-input)
  5x -0:45.1.0 core:backspace (input.hidden-input)
     -0:42.7.0 core:move-right (input.hidden-input)
     -0:41.5.0 hydrogen:run-and-move-down (input.hidden-input)
     -0:40.7.0 core:confirm (input.hidden-input)
     -0:35.3.0 core:copy (atom-notification.error.icon.icon-flame.native-key-bindings.has-close)
     -0:24.9.0 core:close (input.hidden-input)
     -0:22.2.0 intentions:highlight (input.hidden-input)
     -0:22 advanced-open-file:toggle (input.hidden-input)
     -0:19.5.0 core:confirm (input.hidden-input)
  4x -0:15.2.0 core:backspace (input.hidden-input)
  2x -0:12 core:move-right (input.hidden-input)
     -0:11.3.0 hydrogen:run-and-move-down (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
ask-stack 2.2.0 
atom-beautify 0.32.2 
atom-python-run 0.9.6 
auto-encoding 0.7.0 
auto-update-packages 1.0.1 
autocomplete-java 1.2.7 
autocomplete-paths 2.12.2 
autocomplete-python 1.10.5 
browser-plus 0.0.98 
build 0.70.0 
build-rscript 0.6.2 
busy 0.7.0 
busy-signal 1.4.3 
data-atom 0.29.0 
gist 1.1.0 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
Hydrogen 2.3.0 
hydrogen-launcher 1.2.1 
hyperclick 0.1.5 
intentions 1.1.5 
keybinding-cheatsheet 0.1.1 
kite 0.75.0 
language-latex 1.1.1 
language-markdown 0.25.1 
language-mongodb 0.3.1 
language-pgsql 0.2.3 
language-r 0.4.2 
language-scala 1.1.9 
language-sql-mysql 0.3.1 
latex 0.49.0 
latex-autocomplete 1.1.1 
latextools 0.8.5 
linter 2.2.0 
linter-ui-default 1.7.1 
MagicPython 1.0.12 
markdown-pdf 2.1.0 
markdown-preview-plus 2.5.6 
markdown-writer 2.7.3 
minimap-highlight-selected 4.6.1 
open-html-in-browser 0.2.1 
open-recent 5.0.0 
pandoc 0.2.2 
pdf-view 0.67.0 
platformio-ide-terminal 2.8.1 
pretty-json 2.0.0 
project-manager 3.3.5 
project-plus 1.0.0 
python-debugger 0.2.0 
python-indent 1.1.4 
python-tools 0.6.9 
qolor 0.4.2 
quick-query 0.12.4 
r-exec 0.5.0 
sbt 0.13.0 
scala-format 0.1.8 
script 3.17.3 
sync-settings 0.8.5 
tasks 2.10.1 
todo-show 2.2.0 
```

**Comment by BenRussert** [comment]
Are you able to reproduce this again? If so, please provide steps to repro so we can help!

**Comment by kylebarron** [comment]
Closing as stale

**Comment by Mioroxi** [comment]
Got the same error;
-> Install hydrogen@2.8.0 via apm
-> Install ijskernel
-> Try to execute javascript code 
Note that this was a fresh reinstallation

Think this line in particular is worth looking into;
`at Object.self._zmq.onMonitorEvent (~/.atom/packages/Hydrogen/node_modules/zeromq/lib/index.js:552:12)`
Best bet to fix is to reinstall atom completely and install nothing but the 2.8.0 release and isolate whatever it is
