### ISSUE TITLE
[Hydrogen] - Uncaught TypeError when using Altair Compound Charts

### ISSUE THREAD

**Issue by rpalloni** [nteract/hydrogen#1277]
**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Windows 10
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.3.0

If you run the code on Compound Charts in Hydrogen you get the following
https://altair-viz.github.io/user_guide/compound_charts.html

### Stack Trace

Uncaught TypeError: Cannot read property 'marktype' of undefined

```
At C:\Users\utente\.atom\packages\Hydrogen\node_modules\vega-scenegraph\src\render\canvas\CanvasHandler.js:183

TypeError: Cannot read property 'marktype' of undefined
    at CanvasHandler.prototype.pick (/packages/Hydrogen/node_modules/vega-scenegraph/src/render/canvas/CanvasHandler.js:183:25)
    at CanvasHandler.prototype.pickEvent (/packages/Hydrogen/node_modules/vega-scenegraph/src/render/canvas/CanvasHandler.js:172:15)
    at CanvasHandler.mousemove (/packages/Hydrogen/node_modules/vega-scenegraph/src/render/canvas/CanvasHandler.js:74:18)
    at /packages/Hydrogen/node_modules/vega-scenegraph/src/render/canvas/CanvasHandler.js:24:27)
```

### Commands

```
     -4:57.3.0 hydrogen:run (input.hidden-input)
     -4:54.8.0 core:backspace (input.hidden-input)
  3x -4:50.4.0 hydrogen:run (input.hidden-input)
  4x -1:52.8.0 editor:newline (input.hidden-input)
  3x -1:51.9.0 core:move-up (input.hidden-input)
     -1:50.6.0 core:paste (input.hidden-input)
     -1:46.1.0 editor:newline (input.hidden-input)
     -1:37.1.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:30.6.0 hydrogen:run (input.hidden-input)
  2x -0:46.7.0 core:backspace (input.hidden-input)
     -0:44.1.0 hydrogen:run (input.hidden-input)
  2x -0:38.7.0 core:undo (input.hidden-input)
     -0:34.9.0 core:backspace (input.hidden-input)
  2x -0:34.6.0 core:move-right (input.hidden-input)
     -0:34.1.0 core:backspace (input.hidden-input)
     -0:32.6.0 hydrogen:run (input.hidden-input)
```

### Non-Core Packages

```
atom-python-run 0.9.6 
atom-runner 2.7.1 
autocomplete-python 1.10.5 
d3-snippets 1.2.1 
Hydrogen 2.3.0 
python-debugger 0.2.0 
```

**Comment by nikitakit** [comment]
Could you possibly try running hydrogen from github master?

Support for Vega 3 / Vega-Lite 2 hasn't been published in a hydrogen release yet, but if that's the only issue then the version from github should work.
