### ISSUE TITLE
Uncaught TypeError: Cannot match against 'undefined' or 'null'.

### ISSUE THREAD

**Issue by schwaaweb** [nteract/hydrogen#1280]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.3.0
**User**: root

### Stack Trace

Uncaught TypeError: Cannot match against 'undefined' or 'null'.

```
At /Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:493

TypeError: Cannot match against 'undefined' or 'null'.
    at TextMateLanguageMode.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:493:38)
    at TextMateLanguageMode.endRowForCodeFoldAtRow (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:677:41)
    at TextMateLanguageMode.endRowForFoldAtRow (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:656:25)
    at TextMateLanguageMode.isFoldableAtRow (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:380:23)
    at TextEditor.isFoldableAtBufferRow (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3933:63)
    at Object.findCodeBlock (/packages/Hydrogen/lib/code-manager.js:320:25)
    at Object.run (/packages/Hydrogen/lib/main.js:437:35)
    at HTMLElement.hydrogenRunAndMoveDown (/packages/Hydrogen/lib/main.js:108:50)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -0:05.9.0 hydrogen:run-and-move-down (input.hidden-input)
```

### Non-Core Packages

```
Hydrogen 2.3.0 
hydrogen-launcher 1.2.1 
```

**Comment by BenRussert** [comment]
Do you have any more information on what you did just as the error was raised?

**Comment by schwaaweb** [comment]
Hello I have moved on from this error but I'm still stuck and am not sure where to turn.

I am just trying to get hydrogen to work at all and I am not sure how to go about it. I am in a course that uses jupyter notebooks on collab and I am trying to set up a local environment that will work offline and has a better connection to git and github.

I'm on OSX 10.13.4 as you can see above I'm running jupyter 4.4.0 and I'm able to run jupyter notebooks locally through the browser 
  e.g. [http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=thisenv#]

I am unable to run code through hydrogen and am at a lost on where to start or how to debug my progress.

I've tried somethings at this page but am unclear about what applies to my situation.

What meaningful info can I get from my environment in order to properly ask for help?

Is there information on how you start a new notebook from within Atom with Hydrogen, or how to load a jupyter notebook into Atom? A screencast would be great!

Any help is appreciated!

Thank you
- Darwin

**Comment by BenRussert** [comment]
For the most part hydrogen only supports plain text code files (e.g. `.py`, `.js`) as opposed to `.ipynb` notebooks. We do have a feature to convert a plain file to ipynb.

[Our documentation](https://nteract.gitbooks.io/hydrogen/) is a good resource to get started. Take a look there first and see if you have questions.

**Comment by schwaaweb** [comment]
I started out trying to run plaintext python. Here is an error that I get when I try to run jupyter notebook code:

![screen shot 2018-04-08 at 4 42 02 pm](https://user-images.githubusercontent.com/11635079/38472335-7bff9302-3b4c-11e8-915f-cee0973d26a5.png)

I have read the confused on what information I need to give hydrogen so it executes code using my local jupyter installation. This is not clear to me at the documentation link above.

**Comment by schwaaweb** [comment]
The code above is in plain text fyi

**Comment by BenRussert** [comment]
Your going to need to set the grammar to Python or just save as a .py file instead of .ipynb. you will also get syntax highlights for Python this way

**Comment by schwaaweb** [comment]
I was able to get this working by switching to .py files. Thanks you for your help. It would be helpful if the documentation explained the difference between running a jupyter notebook on anaconda or collab vs. running the same code within Hydrogen/Atom. Once I get a bit more comfortable with the environment I may document this. Thank you for your help!
