### ISSUE TITLE
Uncaught Error: Cannot find module './cjs/react.production.min.js'

### ISSUE THREAD

**Issue by Brian-ning** [nteract/hydrogen#1282]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.3.0

### Stack Trace

Uncaught Error: Cannot find module './cjs/react.production.min.js'

```
At module.js:472

Error: Cannot find module './cjs/react.production.min.js'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.25.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.25.1/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.25.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/Hydrogen/node_modules/react/index.js:4:20)
    at /packages/Hydrogen/node_modules/react/index.js:9:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.25.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.25.1/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.25.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/Hydrogen/lib/main.js:12:31)
    at /packages/Hydrogen/lib/main.js:568:24)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.25.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.25.1/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.25.1/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.25.1/resources/app/src/package.js:782:33)
    at Package.activateConfig (~/AppData/Local/atom/app-1.25.1/resources/app/src/package.js:267:16)
    at PackageManager.module.exports.PackageManager.packageHasSettings (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/settings-view/lib/package-manager.js:68:20)
    at PackageCard.hasSettings (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/settings-view/lib/package-card.js:794:40)
    at PackageCard.updateSettingsState (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/settings-view/lib/package-card.js:439:22)
    at PackageCard.updateInterfaceState (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/settings-view/lib/package-card.js:431:18)
```

### Commands

```
     -0:13 python-debugger:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-runner 2.7.1 
autocomplete-python 1.9.1 
Hydrogen 2.3.0 
hydrogen-launcher 1.2.1 
language-coffee-script-angular 2.2.0 
language-ember-script 0.2.0 
language-latex 1.1.1 
latex 0.44.0 
latex-completions 0.3.3 
python-debugger 0.2.0 
python-jedi 0.3.8 
python-tools 0.6.9 
terminal-plus 0.14.5 
```

**Comment by scienceyeaux** [comment]
Any luck fixing this issue?

**Comment by kylebarron** [comment]
When does this happen?

**Comment by scienceyeaux** [comment]
@kylebarron just uninstalled and reinstalled via apm and the problem was solved!

**Comment by kylebarron** [comment]
Great!
