### ISSUE TITLE
Uncaught Error: The module '/\?\$ATOM_HOME\packages\Hydrogen\node_modules\zeromq\build\Release\zm...

### ISSUE THREAD

**Issue by Kcpf** [nteract/hydrogen#1287]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.3.0

### Stack Trace

Uncaught Error: The module '\\?\C:\Users\Fernando\.atom\packages\Hydrogen\node_modules\zeromq\build\Release\zmq.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 53. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).

```
At ELECTRON_ASAR.js:173

Error: The module '\\?\C:\Users\Fernando\.atom\packages\Hydrogen\node_modules\zeromq\build\Release\zmq.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 53. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.25.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/Hydrogen/node_modules/zeromq/lib/index.js:6:11)
    at /packages/Hydrogen/node_modules/zeromq/lib/index.js:848:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.25.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.25.1/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.25.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/Hydrogen/node_modules/zeromq/index.js:2:18)
    at /packages/Hydrogen/node_modules/zeromq/index.js:3:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.25.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.25.1/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.25.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/Hydrogen/node_modules/jmp/index.js:37:11)
    at /packages/Hydrogen/node_modules/jmp/index.js:450:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.25.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.25.1/resources/app/src/compile-cache.js:240:29)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-python 1.10.5 
busy-signal 1.4.3 
file-icons 2.1.18 
highlight-selected 0.13.1 
Hydrogen 2.3.0 
intentions 1.1.5 
linter 2.2.0 
linter-flake8 2.3.0 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
python-autopep8 0.1.3 
```

**Comment by wadethestealth** [comment]
If you still have this issue on a new version of hydrogen, please open a new issue.
