### ISSUE TITLE
Error running Hydrogen

### ISSUE THREAD

**Issue by Salil03** [nteract/hydrogen#1299]
**Description:**

[Error while running hydrogen on python 3.4]

**Steps to Reproduce:**

1. [Install python 3.4]
2. [Install atom and hydrogen]
3. [open a .py file]
3. [run the code via hydrogen]

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?

You can get this information from copy and pasting the output of `atom --version`  from the command line.

Atom    : 1.26.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
OS : Windows 10 64-bit with 32-bit python 3.4

**Logs:**

```
Traceback (most recent call last): File "C:\Python34\lib\site-packages\tornado\ioloop.py", line 288, in current return IOLoop._ioloop_for_asyncio[loop] KeyError: <asyncio.windows_events._WindowsSelectorEventLoop object at 0x06A296F0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last): File "C:\Python34\lib\runpy.py", line 171, in _run_module_as_main "main", mod_spec) File "C:\Python34\lib\runpy.py", line 86, in _run_code exec(code, run_globals) File "C:\Python34\lib\site-packages\ipykernel_launcher.py", line 16, in app.launch_new_instance() File "C:\Python34\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance app.initialize(argv) File "", line 2, in initialize File "C:\Python34\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error return method(app, args, **kwargs) File "C:\Python34\lib\site-packages\ipykernel\kernelapp.py", line 465, in initialize self.init_kernel() File "C:\Python34\lib\site-packages\ipykernel\kernelapp.py", line 364, in init_kernel shell_stream = ZMQStream(self.shell_socket) File "C:\Python34\lib\site-packages\zmq\eventloop\zmqstream.py", line 108, in init self.io_loop = io_loop or IOLoop.instance() File "C:\Python34\lib\site-packages\zmq\eventloop\ioloop.py", line 105, in instance loop = ioloop.IOLoop.instance(args, kwargs) File "C:\Python34\lib\site-packages\tornado\ioloop.py", line 221, in instance return IOLoop.current() File "C:\Python34\lib\site-packages\tornado\ioloop.py", line 292, in current current = AsyncIOMainLoop(make_current=True) File "C:\Python34\lib\site-packages\tornado\util.py", line 312, in new instance.initialize(*args, init_kwargs) File "C:\Python34\lib\site-packages\tornado\platform\asyncio.py", line 182, in initialize super(AsyncIOMainLoop, self).initialize(asyncio.get_event_loop(), **kwargs) File "C:\Python34\lib\site-packages\tornado\platform\asyncio.py", line 53, in initialize if loop.is_closed(): AttributeError: '_WindowsSelectorEventLoop' object has no attribute 'is_closed'
```

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by nikitakit** [comment]
This is a bug on the Python/IPython side.

I don't know your requirements and don't use Windows, but my recommendations are:
* Upgrade to a newer version of Python (version 3.6, if possible)
* Make sure IPython/Jupyter installation is up-to-date
* [Anaconda](https://www.anaconda.com/downloads) tends to be a more reliable way of installing Python on Windows than the official downloads from python.org
