### ISSUE TITLE
Install error on windows (is python2 required for install?)

### ISSUE THREAD

**Issue by triceraflops** [nteract/hydrogen#1326]
**Description:**
I can't install hydrogen on windows.

It looks like a problem with python. npm-gyp seems to require python2, and it's failing on that.

I've installed python2 on my computer, but I'm not sure how to pass in the --python switch as suggested in the error log.

```
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "C:\Users\chnihal\AppData\Local\Continuum\Miniconda3\python.EXE" is v3.6.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
```

Is this real, or am I making some mistake?

I've uninstalled Atom and deleted all local data to see if that fixes it, but it's still the same error.

**Versions:**
Windows 7, SP1
Atom version: 1.27.2 x64

**Logs:**
```
> canvas@1.6.11 install C:\Users\chnihal\AppData\Local\Temp\apm-install-dir-11854-14492-4zwpu5.ezxquayvi\node_modules\Hydrogen\node_modules\canvas
> node-gyp rebuild


C:\Users\chnihal\AppData\Local\Temp\apm-install-dir-11854-14492-4zwpu5.ezxquayvi\node_modules\Hydrogen\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Users\chnihal\AppData\Local\atom\app-1.27.1\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\chnihal\AppData\Local\atom\app-1.27.1\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

> zeromq@4.6.0 install C:\Users\chnihal\AppData\Local\Temp\apm-install-dir-11854-14492-4zwpu5.ezxquayvi\node_modules\Hydrogen\node_modules\zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)


prebuild-install WARN install tunneling socket could not be established, statusCode=403

Downloading libzmq for Windows
Download finished

C:\Users\chnihal\AppData\Local\Temp\apm-install-dir-11854-14492-4zwpu5.ezxquayvi\node_modules\Hydrogen\node_modules\zeromq>if not defined npm_config_node_gyp (node "C:\Users\chnihal\AppData\Local\atom\app-1.27.1\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\chnihal\AppData\Local\atom\app-1.27.1\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
C:\Users\chnihal\AppData\Local\Temp\apm-install-dir-11854-14492-4zwpu5.ezxquayvi
`-- (empty)


gyp ERR! configure error 
gyp ERR! stack Error: Python executable "C:\Users\chnihal\AppData\Local\Continuum\Miniconda3\python.EXE" is v3.6.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Users\chnihal\AppData\Local\atom\app-1.27.1\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\Users\chnihal\AppData\Local\atom\app-1.27.1\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\chnihal\\AppData\\Local\\atom\\app-1.27.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\chnihal\\AppData\\Local\\atom\\app-1.27.1\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\chnihal\AppData\Local\Temp\apm-install-dir-11854-14492-4zwpu5.ezxquayvi\node_modules\Hydrogen\node_modules\canvas
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "C:\Users\chnihal\AppData\Local\Continuum\Miniconda3\python.EXE" is v3.6.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Users\chnihal\AppData\Local\atom\app-1.27.1\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\Users\chnihal\AppData\Local\atom\app-1.27.1\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\chnihal\\AppData\\Local\\atom\\app-1.27.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\chnihal\\AppData\\Local\\atom\\app-1.27.1\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\chnihal\AppData\Local\Temp\apm-install-dir-11854-14492-4zwpu5.ezxquayvi\node_modules\Hydrogen\node_modules\zeromq
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\chnihal\AppData\Local\Temp\apm-install-dir-11854-14492-4zwpu5.ezxquayvi\package.json'
npm WARN react-rangeslider@2.2.0 requires a peer of react@^0.14.0 || ^15.0.0 but none was installed.
npm WARN commonmark-react-renderer@4.3.4 requires a peer of commonmark@^0.27.0 || ^0.26.0 || ^0.24.0 but none was installed.
npm WARN apm-install-dir-11854-14492-4zwpu5.ezxquayvi No description
npm WARN apm-install-dir-11854-14492-4zwpu5.ezxquayvi No repository field.
npm WARN apm-install-dir-11854-14492-4zwpu5.ezxquayvi No README data
npm WARN apm-install-dir-11854-14492-4zwpu5.ezxquayvi No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.11 (node_modules\Hydrogen\node_modules\canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.11 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\chnihal\\AppData\\Local\\atom\\app-1.27.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\chnihal\\AppData\\Local\\atom\\app-1.27.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\chnihal\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\chnihal\\.atom\\.apmrc" "install" "C:\\Users\\chnihal\\AppData\\Local\\Temp\\d-11854-14492-y1gbib.swb4ndn29\\package.tgz" "--runtime=electron" "--target=1.7.15" "--arch=x64" "--global-style" "--msvs_version=2010"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! zeromq@4.6.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@4.6.0 install script 'node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zeromq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zeromq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zeromq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\chnihal\AppData\Local\Temp\apm-install-dir-11854-14492-4zwpu5.ezxquayvi\npm-debug.log
npm ERR! code 1
```

**Comment by triceraflops** [comment]
Ok, so it seems you definitely need python 2.7 to install Hydrogen on Windows.

From the command line
```
apm install hydrogen --python /path/to/python2
```

**Comment by BenRussert** [comment]
@triceraflops Sorry for the late response, thanks for solving and posting your solution! This line from your solution might be good to add to our docs:

```
apm install hydrogen --python /path/to/python2
```
We have seen issues in the past where gyp tried to use the wrong python executable even if 2.7 is installed. If you are interested in making a contribution I encourage you to submit a PR adding this snippet (or anything you think would help others) to our docs!
