### ISSUE TITLE
Cannot find module 'lodash'

### ISSUE THREAD

**Issue by bryceh29** [nteract/hydrogen#1331]
**Description:**

Hello. I am trying to get Hydrogen up and running on my machine with the handicap of not being able to use the Atom package manager. See [issue](https://discuss.atom.io/t/problem-searching-for-packages-within-atom/39039). Even with disabling ssl I can't use the atom package manager so I've been downloading packages manually and placing them in .atom/packages. 

**Steps to Reproduce:**

- Download hydrogen zip from [repo](https://github.com/nteract/hydrogen) 

- Unzip and place in .atom/packages directory

- Select the "Hydrogen: Start Local Kernel" from command pallete 

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?
Windows 7
Hydrogen 2.5.0
Atom 1.27.2
Electron 1.7.15
Chrome 58.0.3029.110
Node 7.9.0

**Logs:**

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [Hydrogen](ssh://git@github.com/nteract/hydrogen) package 2.5.0

### Stack Trace

Failed to activate the Hydrogen package

```
At Cannot find module 'lodash'

Error: Cannot find module 'lodash'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.27.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.27.2/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.27.2/resources/app/src/native-compile-cache.js:66:33)
    at /packages/hydrogen-2.5.0/lib/main.js:9:14)
    at /packages/hydrogen-2.5.0/lib/main.js:568:24)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.27.2/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.27.2/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.27.2/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.27.2/resources/app/src/package.js:782:33)
    at Package.activateNow (~/AppData/Local/atom/app-1.27.2/resources/app/src/package.js:220:40)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.event (~/AppData/Local/atom/app-1.27.2/resources/app/src/package.js:865:28)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.27.2/resources/app/src/command-registry.js:360:24)
    at Object.didConfirmSelection (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/command-palette/lib/command-palette-view.js:152:35)
    at SelectListView.confirmSelection (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/atom-select-list/src/select-list-view.js:401:26)
    at SelectListView.didClickItem (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/atom-select-list/src/select-list-view.js:287:16)
    at ListItemView.onclick (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/atom-select-list/src/select-list-view.js:222:37)
    at ListItemView.didClick (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/atom-select-list/src/select-list-view.js:449:16)
```

### Commands

```
     -0:33.4.0 command-palette:toggle (input.hidden-input)
     -0:27.2.0 hydrogen:start-local-kernel (input.hidden-input)
```

### Non-Core Packages

```
atom-js 1.2.0 
autocomplete-lodash 0.2.3 
Hydrogen 2.5.0 
iojs-v1.7.15 undefined 
jump-to-import 3.6.5 
mariana-syntax 0.2.0 
react 0.18.0 
zenburn 3.1.0 
```

**Notes:**

The below screenshot shows that I installed a lodash package. I didn't see any in the core packages. You can also see that while atom recognizes hydrogen it cannot fully load it

![image](https://user-images.githubusercontent.com/8051260/41368529-753368be-6eff-11e8-8544-c9c14c9db433.png)

"Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html). " - As far as that I am unable to as the package isn't fully working so I don't have the debug capability

**Comment by BenRussert** [comment]
You would have to install the dependencies with `apm install` from within the hydrogen directory after unzipping.

I get the impression the issue is you are on a network with a firewall that blocks access to the web by apps it doesn't recognize. I'm not sure apm install will work either if that's the case.

**Comment by bryceh29** [comment]
@BenRussert apm install does not work. However, I am installing the dependencies as I see them manually. I installed lodash but that doesn't seem to help. Potentially there is a manual way to list dependencies that I'm not aware of and then install all of them manually

**Comment by BenRussert** [comment]
Yes, lodash is one of many dependencies of hydrogen. I do not recommend trying this due to the time involved if you can even get it to work right. I’d suggest talking to your IT people to see if you can get them to install it.

**Comment by bryceh29** [comment]
Oh well, thanks for the time. IT won't mess with it. Guess I just won't be able to use it.

**Comment by BenRussert** [comment]
Sorry @bryceh29 those IT people can be pesky.
