### ISSUE TITLE
[Startup] RuntimeError: This event loop is already running

### ISSUE THREAD

**Issue by shekeru** [nteract/hydrogen#1357]
Not sure how to submit this correctly, but I thought it might be nice to report my error since the program kinda doesn't work. 
**OS**: `Windows 7 (64bit)`
**Python**: `3.6.1 (64bit)`
## Traceback
```py
Traceback (most recent call last): File "C:\Users\Shekels\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main "main", mod_spec) File "C:\Users\Shekels\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\Users\Shekels\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel_launcher.py", line 16, in app.launch_new_instance() File "C:\Users\Shekels\AppData\Local\Programs\Python\Python36\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance app.start() File "C:\Users\Shekels\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel\kernelapp.py", line 477, in start ioloop.IOLoop.instance().start() File "C:\Users\Shekels\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\platform\asyncio.py", line 132, in start self.asyncio_loop.run_forever() File "C:\Users\Shekels\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 408, in run_forever raise RuntimeError('This event loop is already running') RuntimeError: This event loop is already running
```
## Installed Packages:
```sh
altgraph==0.15
appdirs==1.4.3
arrow==0.12.1
astroid==1.5.2
asyncio==3.4.3
autopep8==1.3.5
base58==0.2.5
bcrypt==3.1.3
beautifulsoup4==4.6.0
bleach==2.0.0
boto3==1.4.4
botocore==1.5.44
bs4==0.0.1
bson==0.5.2
cached-property==1.3.0
cefpython3==57.0
certifi==2018.1.18
cffi==1.10.0
chardet==3.0.4
click==6.7
colorama==0.3.9
configparser==3.5.0
cycler==0.10.0
Cython==0.25.2
data==0.4
decorator==4.0.11
defusedxml==0.5.0
Django==2.0
docutils==0.13.1
EasyProcess==0.2.3
entrypoints==0.2.2
et-xmlfile==1.0.1
Flask==0.12.1
funcsigs==1.0.2
future==0.16.0
futures==3.1.1
gdbn==0.1
geos==0.2.0
gevent==1.2.2
gnumpy==0.2
greenlet==0.4.13
html5lib==0.999999999
idna==2.6
ipykernel==4.6.1
ipython==6.0.0
ipython-genutils==0.2.0
ipywidgets==7.1.1
isodate==0.5.4
isort==4.2.5
itsdangerous==0.24
jdcal==1.4
jedi==0.12.1
Jinja2==2.9.6
jmespath==0.9.2
joblib==0.11
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.2
jupyter-console==5.2.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.0
jupyter-core==4.4.0
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.4
jupyter-nbextensions-configurator==0.4.0
Kivy==1.10.0
Kivy-Garden==0.1.4
kivy.deps.glew==0.1.9
kivy.deps.sdl2==0.1.17
Lasagne==0.1
latex==0.6.4
lazy-object-proxy==1.3.1
lxml==3.7.3
macholib==1.9
MarkupSafe==1.0
matplotlib==2.0.2
mccabe==0.6.1
mistune==0.7.4
monkey==0.1
msgpack-python==0.4.8
mws==0.8.3
nbconvert==5.1.1
nbformat==4.3.0
notebook==5.0.0
numpy==1.12.1
oauthlib==2.1.0
olefile==0.44
openpyxl==2.5.4
pandocfilters==1.4.1
parso==0.3.1
pbr==4.1.0
pefile==2017.11.5
pickleshare==0.7.4
Pillow==4.2.0
pluggy==0.6.0
pony==0.7.2
prompt-toolkit==1.0.14
psycopg2==2.7.3.2
PyAudio==0.2.11
pycodestyle==2.4.0
pycountry==17.1.8
pycparser==2.17
pydocstyle==2.1.1
pyflakes==2.0.0
pygame==1.9.3
Pygments==2.2.0
PyInstaller==3.3.1
PyJWT==1.5.0
pylint==1.7.1
PyMySQL==0.7.11
PyNaCl==1.1.2
pynput==1.3.9
pyparsing==2.2.0
pyperclip==1.6.0
pypiwin32==220
PyQt5==5.9.2
pyscreenshot==0.4.2
pyspf==2.0.11
python-dateutil==2.7.0
python-language-server==0.19.0
pyttsx==1.2
pytz==2017.2
PyYAML==3.12
pyzmq==17.1.0
qtconsole==4.3.0
requests==2.19.1
requests-oauthlib==1.0.0
requests-toolbelt==0.8.0
rope==0.10.7
s3transfer==0.1.10
scikit-learn==0.19.0
selenium==3.11.0
Shapely==1.5.17
shutilwhich==1.1.0
simplegeneric==0.8.1
SimpleWebSocketServer==0.1.0
sip==4.19.6
six==1.11.0
snowballstemmer==1.2.1
speech==0.5.2
SpeechRecognition==3.8.1
stevedore==1.28.0
tabulate==0.7.7
tempdir==0.7.1
testpath==0.3
tornado==5.1
traitlets==4.3.2
tzwhere==2.3
urllib3==1.22
virtualenv==15.1.0
virtualenv-clone==0.3.0
virtualenvwrapper==4.8.2
wcwidth==0.1.7
webencodings==0.5.1
websocket==0.2.1
websocket-client==0.40.0
websockets==5.0.1
Werkzeug==0.12.1
widgetsnbextension==3.1.4
wrapt==1.10.10
yapf==0.22.0
zeep==2.0.0
zerorpc==0.6.1
zmq==0.0.0
```

**Comment by BenRussert** [comment]
I did some googling just now and found some people saying they fixed something similar by upgrading `ipykernel`. Can you try this?

**Comment by shekeru** [comment]
i think i tried that and i ended up with a different error
finally downgrading back to tornado 4.5.x fixed it lol

**Comment by BenRussert** [comment]
Glad you fixed it!
