### ISSUE TITLE
Installation error from Atom desktop

### ISSUE THREAD

**Issue by drmstwizard** [nteract/hydrogen#1362]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 7 Home Premium 
**Thrown From**: [Hydrogen](ssh://git@github.com/nteract/hydrogen) package 2.5.1

### Stack Trace

Uncaught Error: Cannot find module 'lodash'

```
At module.js:545

Error: Cannot find module 'lodash'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.28.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (<embedded>:12400:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (<embedded>:11744:33)
    at /packages/Hydrogen/lib/main.js:13:15)
    at /packages/Hydrogen/lib/main.js:643:3)
    at Module.get_Module._compile (<embedded>:11784:36)
    at Object.value [as .js] (<embedded>:12036:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (<embedded>:96:26)
    at Package.requireMainModule (<embedded>:74920:33)
    at Package.activateConfig (<embedded>:74405:16)
    at PackageManager.module.exports.PackageManager.packageHasSettings (<embedded>:57413:20)
    at PackageCard.hasSettings (<embedded>:219489:40)
    at PackageCard.updateSettingsState (<embedded>:219134:22)
    at PackageCard.updateInterfaceState (<embedded>:219126:18)
    at <embedded>:219423:22
    at <embedded>:219506:17
    at Function.module.exports.Emitter.simpleDispatch (<embedded>:68130:20)
    at Emitter.module.exports.Emitter.emit (<embedded>:68259:34)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (<embedded>:58004:33)
    at <embedded>:57843:32
    at exit (<embedded>:57473:22)
    at triggerExitCallback (<embedded>:131191:15)
    at ChildProcess.process.on (<embedded>:131221:15)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

```

### Commands

```
```

### Non-Core Packages

```
Hydrogen 2.5.1 
```

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?

You can get this information from copy and pasting the output of `atom --version`  from the command line.

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).

**Comment by Pixel860** [comment]
I tried installing it multiple times but it doesn't work.

**Comment by BenRussert** [comment]
Strange, I couldn't help but notice you don't have any other atom packages installed. Are you experiencing the issue when you try other packages? It could be an issue with a firewall.

**Comment by wadethestealth** [comment]
Since this is an old issue, and there have been many releases of atom and hydrogen. We are going to close this issue as is was most likely an old bad install
