### ISSUE TITLE
Allow for both stream and display_data responses for the same input code

### ISSUE THREAD

**Issue by kylebarron** [nteract/hydrogen#1371]
Edit 2: I discovered that the issue is that when a graph exists, I'm sending _multiple_ responses, first a `stream` response with any text, then also a `display_data` response for each graph. It appears that this is tripping up Hydrogen. When I respond with only a `stream` or with only one or more `display_data` responses, Hydrogen displays the results fine.

1. I'm guessing that if Jupyter Notebook supports this, Hydrogen should too?
2. How do other kernels return both text and images? It's hard to find documentation on this, but I know IPython can return both.

Edit: I only get the "Cannot read property `indexOf` of undefined" now. Removed initial JSON error.

**Description:**

I created a [Jupyter kernel](https://github.com/kylebarron/stata_kernel) today for [Stata](https://www.stata.com/), and I'm getting weird error messages through Hydrogen. I ordinarily wouldn't have thought them bugs with Hydrogen (and they may not be), but the code works with Jupyter Notebook, so I thought I'd post and see if anyone else had an idea.

<img width="802" alt="image" src="https://user-images.githubusercontent.com/15164633/43682495-c1b9d588-9844-11e8-8ab1-50df41e5708e.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/15164633/43682501-f91d3e48-9844-11e8-9378-b755c9b78af6.png">

**Steps to Reproduce:**

The error occurs when I use `Run` on the `scatter mpg price` line, which should return an SVG. I also get the same error when I run `clear`, which should return nothing. Unfortunately, Stata is proprietary software so it isn't reproducible by others.

**Versions:**

Mac, Hydrogen 2.5.1

**Logs:**

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [Hydrogen](ssh://git@github.com/nteract/hydrogen) package 2.5.1

### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of undefined

```
At /Users/kyle/.atom/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:212

TypeError: Cannot read property 'indexOf' of undefined
    at isSingeLine (/packages/hydrogen/lib/store/output.js:60:11)
    at OutputStore.get (/packages/hydrogen/lib/store/output.js:99:16)
    at trackDerivedFunction (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:3290:24)
    at ComputedValue.computeValue (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:779:19)
    at ComputedValue.trackAndCompute (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:764:29)
    at ComputedValue.get (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:722:26)
    at ObservableObjectAdministration.read (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:1018:33)
    at OutputStore.get (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:1226:68)
    at ResultViewComponent.render (/packages/Hydrogen/lib/components/result-view/result-view.js:105:30)
    at /packages/Hydrogen/node_modules/mobx/lib/mobx.js:239:15)
    at /packages/Hydrogen/node_modules/mobx-react/index.js:753:34
    at trackDerivedFunction (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:3290:24)
    at Reaction.track (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:3494:22)
    at /packages/Hydrogen/node_modules/mobx-react/index.js:748:18)
    at Lg (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:167:226)
    at Sg (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:180:75)
    at yh (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:202:22)
    at zh (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:203:234)
    at Wh (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:212:353)
    at Zh (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:211:278)
    at Xh (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:211:113)
    at ci (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:222:218)
    at reactionScheduler (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:3599:47)
    at runReactions (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:3575:5)
    at endBatch (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:3015:9)
    at endAction (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:230:5)
    at executeAction (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:198:9)
    at OutputStore.res (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:187:16)
    at /packages/Hydrogen/lib/main.js:392:19
    at /packages/Hydrogen/lib/kernel.js:346:9
    at /packages/Hydrogen/lib/kernel.js:290:9
    at wrappedOnResults (/packages/Hydrogen/lib/kernel.js:77:5)
    at future.onIOPub (/packages/Hydrogen/lib/ws-kernel.js:50:7)
    at KernelFutureHandler._handleIOPub (/packages/Hydrogen/node_modules/@jupyterlab/services/lib/kernel/future.js:193:13)
    at KernelFutureHandler.handleMsg (/packages/Hydrogen/node_modules/@jupyterlab/services/lib/kernel/future.js:168:22)
    at DefaultKernel._onWSMessage (/packages/Hydrogen/node_modules/@jupyterlab/services/lib/kernel/default.js:713:24)
    at WebSocket._ws.onmessage (/packages/Hydrogen/node_modules/@jupyterlab/services/lib/kernel/default.js:653:53)
    at WebSocket.onMessage (/packages/Hydrogen/node_modules/ws/lib/EventTarget.js:99:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver._receiver.onmessage (/packages/Hydrogen/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (/packages/Hydrogen/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/packages/Hydrogen/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/packages/Hydrogen/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/packages/Hydrogen/node_modules/ws/lib/Receiver.js:139:10)
    at Socket._ultron.on (/packages/Hydrogen/node_modules/ws/lib/WebSocket.js:138:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
     -7:09.2.0 command-palette:toggle (input.hidden-input)
     -7:08.0 core:confirm (input.hidden-input)
     -7:08.0 hydrogen:connect-to-remote-kernel (input.hidden-input)
  3x -7:07.8.0 core:confirm (input.hidden-input)
     -7:06.5.0 docblockr:parse-enter (input.hidden-input)
     -7:06.5.0 editor:newline (input.hidden-input)
     -7:06.0 core:backspace (input.hidden-input)
     -7:05.7.0 hydrogen:run (input.hidden-input)
     -7:05.0 core:move-down (input.hidden-input)
     -7:04.7.0 hydrogen:run (input.hidden-input)
     -7:03.4.0 editor:consolidate-selections (input.hidden-input)
     -7:03.4.0 core:cancel (input.hidden-input)
     -6:52.2.0 core:backspace (input.hidden-input)
     -6:51.7.0 core:save (input.hidden-input)
     -6:46.7.0 core:backspace (input.hidden-input)
     -6:46.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-alignment 0.13.0 
atom-beautify 0.32.5 
atom-clock 0.1.16 
atom-fuzzy-grep 0.17.2 
atom-gmail 0.1.2 
atom-ide-ui 0.13.0 
atom-language-r 1.4.8 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete-bibtex 1.2.1 
autocomplete-paths 2.12.2 
build 0.70.0 
build-cmake 0.11.0 
busy-signal 1.4.3 
change-case 0.6.5 
color-picker 2.3.0 
cson 2.0.1 
docblockr 0.13.7 
editor-stats 0.17.0 
editorconfig 2.2.2 
file-icons 2.1.22 
git-time-machine 2.1.0 
grammar-token-limit 0.1.1 
highlight-line 0.12.0 
highlight-selected 0.14.0 
Hydrogen 2.5.1 
hydrogen-launcher 1.2.2 
ide-bash 1.0.11 
ide-python 1.0.0 
ide-r 0.1.8 
ide-typescript 0.7.6 
ide-yaml 0.4.3 
indent-guide-improved 1.4.13 
insert-timestamp 0.2.4 
intentions 1.1.5 
language-cmake 1.1.0 
language-cython 0.3.0 
language-gitignore 0.3.0 
language-ini 1.20.0 
language-julia 0.16.0 
language-latex 1.1.1 
language-liquid 0.7.0 
language-markdown 0.25.1 
language-matlab 0.2.1 
language-mediawiki 2.2.0 
language-pfm 0.82.0 
language-r 0.4.2 
language-restructuredtext 1.1.2 
language-sas 0.2.4 
language-scheme 1.4.0 
language-stata 1.5.0 
language-weave 0.4.3 
latex 0.50.0 
latex-completions 0.3.5 
latexer 0.3.0 
linter 2.2.0 
linter-eslint 8.4.1 
linter-flake8 2.3.0 
linter-flow 5.6.1 
linter-gcc 0.7.1 
linter-jshint 3.1.8 
linter-mypy 2.6.2 
linter-shellcheck 1.4.7 
linter-ui-default 1.7.1 
MagicPython 1.0.12 
markdown-preview-enhanced 0.15.6 
markdown-preview-plus 3.3.3 
markdown-table-formatter 2.9.2 
markdown-writer 2.8.0 
minimap 4.29.8 
minimap-autohider 1.5.4 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
minimap-split-diff 0.3.7 
pdf-view 0.70.0 
pigments 0.40.2 
platformio-ide-terminal 2.8.3 
project-manager 3.3.6 
python-indent 1.1.5 
qolor 0.4.2 
regex-railroad-diagram 0.19.4 
remote-edit 1.9.0 
remote-ftp 2.2.0 
set-syntax 0.4.0 
sort-lines 0.18.0 
split-diff 1.5.2 
stata-exec 1.8.2 
sync-settings 0.8.6 
teletype 0.13.3 
toggle-quotes 1.1.0 
tree-view-git-status 1.5.0 
typewriter 0.7.1 
wordcount 3.0.0 
Zen 0.18.0 
```

**Comment by BenRussert** [comment]
In some of the screenshots it looks like you might need to rebuild hydrogen. You should be able to fix this with `apm install` from the cli inside the hydrogen folder of your dev install. 

Make sure to pull the recent changes as I was pretty active last night.

This is not the root cause, but just to clear that out of the way first

**Comment by BenRussert** [comment]
In the screenshot from notebook it looks like one graph is output in the end, is that what you expected from hydrogen?

**Comment by kylebarron** [comment]
No that's the Remote Edit package that failed rebuilding, not Hydrogen.

I'll try again on master later.

I expected a response similar to the one from the notebook. It seemed that the issue was that I couldn't return both a message on the `stdout` stream _and_ send a display message. The [docs](https://jupyter-client.readthedocs.io/en/stable/messaging.html#messages-on-the-iopub-pub-sub-channel) aren't too helpful to know which one to send or which type of results.

**Comment by kylebarron** [comment]
Unable to reproduce so I'll close.
