### ISSUE TITLE
Getting a traceback error when trying to run any line of code

### ISSUE THREAD

**Issue by scienceyeaux** [nteract/hydrogen#1402]
**Description:**

When I run a line using Hydrogen, I get the following error.

My attempts to troubleshoot this problem include:
1. Uninstalled/reinstalled hydrogen using apm
2. Ensured my python is included in PATH variable
![image](https://user-images.githubusercontent.com/36206562/45049467-b8d88200-b04c-11e8-8190-2c9436c3646a.png)
3. Ensured my python is up to date
![image](https://user-images.githubusercontent.com/36206562/45049649-3bf9d800-b04d-11e8-95f8-6abf594c1ca5.png)
4. Ensured ipython is up to date
![image](https://user-images.githubusercontent.com/36206562/45049878-ef62cc80-b04d-11e8-98c5-ba08495c20e2.png)

**Steps to Reproduce:**

1. Activate virtual env
2. Open Atom from cmd
![image](https://user-images.githubusercontent.com/36206562/45049543-f63d0f80-b04c-11e8-833b-5a0a827130ff.png)
3. Write a line of code (e.g. `print('Hello world')`)
![image](https://user-images.githubusercontent.com/36206562/45049573-0c4ad000-b04d-11e8-93b9-9687d59d21ad.png)
4. Run a hydrogen
5. Receive the following error:

Traceback (most recent call last): File "C:\Users\scienceyeaux\AppData\Local\Continuum\anaconda3\envs\sandbox\lib\runpy.py", line 193, in _run_module_as_main "main", mod_spec) File "C:\Users\scienceyeaux\AppData\Local\Continuum\anaconda3\envs\sandbox\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\Users\scienceyeaux\AppData\Local\Continuum\anaconda3\envs\sandbox\lib\site-packages\ipykernel_launcher.py", line 15, in from ipykernel import kernelapp as app File "C:\Users\scienceyeaux\AppData\Local\Continuum\anaconda3\envs\sandbox\lib\site-packages\ipykernel__init__.py", line 2, in from .connect import * File "C:\Users\scienceyeaux\AppData\Local\Continuum\anaconda3\envs\sandbox\lib\site-packages\ipykernel\connect.py", line 13, in from IPython.core.profiledir import ProfileDir File "C:\Users\scienceyeaux\AppData\Local\Continuum\anaconda3\envs\sandbox\lib\site-packages\IPython__init__.py", line 55, in from .terminal.embed import embed File "C:\Users\scienceyeaux\AppData\Local\Continuum\anaconda3\envs\sandbox\lib\site-packages\IPython\terminal\embed.py", line 17, in from IPython.terminal.ipapp import load_default_config File "C:\Users\scienceyeaux\AppData\Local\Continuum\anaconda3\envs\sandbox\lib\site-packages\IPython\terminal\ipapp.py", line 28, in from IPython.core.magics import ( File "C:\Users\scienceyeaux\AppData\Local\Continuum\anaconda3\envs\sandbox\lib\site-packages\IPython\core\magics__init__.py", line 18, in from .code import CodeMagics, MacroToEdit File "C:\Users\scienceyeaux\AppData\Local\Continuum\anaconda3\envs\sandbox\lib\site-packages\IPython\core\magics\code.py", line 23, in from urllib.request import urlopen File "C:\Users\scienceyeaux\AppData\Local\Continuum\anaconda3\envs\sandbox\lib\urllib\request.py", line 86, in import email File "C:\Users\scienceyeaux\Documents\Python Scripts\email.py", line 2, in import pandas as pd ModuleNotFoundError: No module named 'pandas'

**Versions:**

OS: Windows 10
Atom: 1.30.0
Hydrogen: 2.5.1

**Logs:**

![image](https://user-images.githubusercontent.com/36206562/45049263-1c15e480-b04c-11e8-93a6-ca98ef68b458.png)

**Comment by BenRussert** [comment]
Last line in the error message:
> "C:\Users\scienceyeaux\AppData\Local\Continuum\anaconda3\envs\sandbox\lib\urllib\request.py", line 86, in import email File "C:\Users\scienceyeaux\Documents\Python Scripts\email.py", line 2, in import pandas as pd ModuleNotFoundError: No module named 'pandas'

The error you are getting is a `ModuleNotFoundError` which is throwing because you dont have pandas installed. I can also see pandas missing in your `pip freeze` output above. SInce you are using conda, try installing pandas with `conda install pandas` after activating the `sandbox` env like you did above. Then run `atom .` in your terminal while in the project folder you want to open.

I'll close, but feel free to reply with questions, thanks!
