### ISSUE TITLE
Hydrogen breaks with a Python 3.7 env but works fine with a 3.6 one

### ISSUE THREAD

**Issue by Fercho120** [nteract/hydrogen#1405]
Hi everyone, I stumbled across an error that confused me a lot:

I have two Python environments managed with conda, one with 3.6 and the other with 3.7, when I try to run on Atom some basic code (for example a print command) selecting the 3.7 kernel I got an error saying that Atom was unable to load some DLL file, however with 3.6 all works fine.
Also if I execute Atom from anaconda's prompt with the 3.7 env active, I got no error
What could be the problem here?

This is a screenshot of the error:

![captura de pantalla 2018-09-07 14 28 09](https://user-images.githubusercontent.com/18184315/45239487-110cbf80-b2ab-11e8-9302-32e84b74dbcc.png)

I'm using:
Windows 10 64 Bits
Atom 1.3
Hydrogen 2.5.1

Error log:
Traceback (most recent call last): File "C:\Users\dfgr0\Anaconda3\envs\Test37\lib\runpy.py", line 193, in _run_module_as_main "main", mod_spec) File "C:\Users\dfgr0\Anaconda3\envs\Test37\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\Users\dfgr0\Anaconda3\envs\Test37\lib\site-packages\ipykernel_launcher.py", line 15, in from ipykernel import kernelapp as app File "C:\Users\dfgr0\Anaconda3\envs\Test37\lib\site-packages\ipykernel__init__.py", line 2, in from .connect import File "C:\Users\dfgr0\Anaconda3\envs\Test37\lib\site-packages\ipykernel\connect.py", line 18, in import jupyter_client File "C:\Users\dfgr0\Anaconda3\envs\Test37\lib\site-packages\jupyter_client__init__.py", line 4, in from .connect import File "C:\Users\dfgr0\Anaconda3\envs\Test37\lib\site-packages\jupyter_client\connect.py", line 23, in import zmq File "C:\Users\dfgr0\Anaconda3\envs\Test37\lib\site-packages\zmq__init__.py", line 47, in from zmq import backend File "C:\Users\dfgr0\Anaconda3\envs\Test37\lib\site-packages\zmq\backend__init__.py", line 40, in reraise(*exc_info) File "C:\Users\dfgr0\Anaconda3\envs\Test37\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise raise value File "C:\Users\dfgr0\Anaconda3\envs\Test37\lib\site-packages\zmq\backend__init__.py", line 27, in _ns = select_backend(first) File "C:\Users\dfgr0\Anaconda3\envs\Test37\lib\site-packages\zmq\backend\select.py", line 27, in select_backend mod = import(name, fromlist=public_api) File "C:\Users\dfgr0\Anaconda3\envs\Test37\lib\site-packages\zmq\backend\cython__init__.py", line 6, in from . import (constants, error, message, context, ImportError: DLL load failed: No se puede encontrar el m�dulo especificado.

**Comment by BenRussert** [comment]
>  if I execute Atom from anaconda's prompt with the 3.7 env active, I got no error
It sounds like you need to activate the env you want before starting up atom, whether in the anaconda prompt or another terminal like powershell or cmd. 

How are you starting atom when not using the anaconda prompt? The best way to do this is in a terminal with the env you want activated, then `cd` to your project folder and run `atom .`

**Comment by Fercho120** [comment]
> > if I execute Atom from anaconda's prompt with the 3.7 env active, I got no error
> > It sounds like you need to activate the env you want before starting up atom, whether in the anaconda prompt or another terminal like powershell or cmd.
> 
> How are you starting atom when not using the anaconda prompt? The best way to do this is in a terminal with the env you want activated, then `cd` to your project folder and run `atom .`

When not starting atom from anaconda prompt I simply open atom from direct access on desktop; nevertheless atom opened on that way detects and uses multiple python 3.6 ipykernels without problem. 
At the end I need to create a GUI and I wonder if the GUI should be launched from anaconda prompt or if is possible to launch it without using the prompt

**Comment by BenRussert** [comment]
> I wonder if the GUI should be launched from anaconda prompt or if is possible to launch it without using the prompt

Atom recommends starting from terminal.  This will make it simple to understand which environment you are launching atom in and which project/directory you want atom to open.  Plus, it is much more stylish :sunglasses:.

In your terminal of choice (e.g. powershell, cmd.exe, bash for windows, anaconda prompt):
```sh
cd .\my\project\folder
atom .
```

So if you want to change env, you just `activate my-env` and start atom again with `atom .`

**Comment by cehc84** [comment]
I had exactly the same issue. I was using Atom 1.34.0, Hydrogen 2.8.0, Anaconda 2018.12, conda 4.6.3, Python 3.7, Windows 10 Pro.  

I solved it by installing python 3.6 instead of 3.7. 

Now hydrogen works fine, my python script runs well, and I can still run Atom from the start menu.
