### ISSUE TITLE
Error when running empty code cell at end of file

### ISSUE THREAD

**Issue by nikitakit** [nteract/hydrogen#1468]
**Description:**

If the last line of a file is `# %%` and you place the cursor at the end of the line, the "Hydrogen: Run Cell" action results in an error.

This issue was originally reported in https://github.com/nikitakit/hydrogen-python/pull/21

The observation there was that hydrogen would pass a `code` value of `null` to the plugin. This makes no sense; the correct behavior would be to have `code` be the empty string and for no errors to be thrown.

**Steps to Reproduce:**

1. Add `# %%` as the last line of a Python file. Make sure there are no empty lines after it.
2. Place cursor at the end of the last line
3. Activate "Hydrogen: Run Cell"

**Versions:**

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.12.4
**Thrown From**: [Hydrogen](ssh://git@github.com/nteract/hydrogen) package 2.6.0

I'm on an old version of Atom right now, but based on the reports in https://github.com/nikitakit/hydrogen-python/pull/21 this issue applies to newer versions, too.

**Stack Trace**

Uncaught TypeError: Cannot read property 'match' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3872

TypeError: Cannot read property 'match' of undefined
    at TextEditor.isBufferRowCommented (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3872:61)
    at isBlank (/Users/kitaev/dev/hydrogen/lib/code-manager.js:64:55)
    at Object.escapeBlankRows (/Users/kitaev/dev/hydrogen/lib/code-manager.js:73:10)
    at Object.runCell (/Users/kitaev/dev/hydrogen/lib/main.js:520:32)
    at HTMLElement.hydrogenRunCellAndMoveDown (/Users/kitaev/dev/hydrogen/lib/main.js:110:55)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:110:40)
```

**Comment by kylebarron** [comment]
Regardless of whether `hydrogen-python` is activated or not, I can't reproduce this on 
```
> atom --version
Atom    : 1.33.0
Electron: 2.0.11
Chrome  : 61.0.3163.100
Node    : 8.9.3
```
