### ISSUE TITLE
Stata kernel problem

### ISSUE THREAD

**Issue by LordLTSmash** [nteract/hydrogen#1472]
**Description:**

When trying to run Stata code from Atom by pressing Ctrl + Enter:

Traceback (most recent call last): File "C:\Users\MartinezVelasco\Anaconda3\lib\runpy.py", line 183, in _run_module_as_main mod_name, mod_spec, code = _get_module_details(mod_name, _Error) File "C:\Users\MartinezVelasco\Anaconda3\lib\runpy.py", line 142, in _get_module_details return _get_module_details(pkg_main_name, error) File "C:\Users\MartinezVelasco\Anaconda3\lib\runpy.py", line 109, in _get_module_details import(pkg_name) File "C:\Users\MartinezVelasco\Anaconda3\lib\site-packages\stata_kernel__init__.py", line 5, in from .kernel import StataKernel File "C:\Users\MartinezVelasco\Anaconda3\lib\site-packages\stata_kernel\kernel.py", line 6, in from PIL import Image File "C:\Users\MartinezVelasco\Anaconda3\lib\site-packages\PIL\Image.py", line 64, in from . import _imaging as core ImportError: DLL load failed: No se puede encontrar el módulo especificado.

**Steps to Reproduce:**

1. Start Atom
2. Press Ctrl-Enter over some Stata code

**Versions:**

Windows 7
Atom 1.32.2 x64
Anaconda 3 5.3.0 x64
Hydrogen 2.6.0
Stata IC 15.1

**Logs:**

VM22 <embedded>:11 'Hydrogen.kernelspec' could not set the default. Attempted default: undefined; Schema: {}

  | setDefaults | @ | VM22 <embedded>:11
-- | -- | -- | --
  | transact | @ | VM22 <embedded>:11
  | transact | @ | VM22 <embedded>:11
  | setDefaults | @ | VM22 <embedded>:11
  | transact | @ | VM22 <embedded>:11
  | transact | @ | VM22 <embedded>:11
  | setSchema | @ | VM22 <embedded>:11
  | registerConfigSchemaFromMainModule | @ | VM22 <embedded>:11
  | activateNow | @ | VM22 <embedded>:11
  | activationCommandSubscriptions.add.commandRegistry.onWillDispatch.n | @ | VM22 <embedded>:14
  | simpleDispatch | @ | VM22 <embedded>:11
  | emit | @ | VM22 <embedded>:11
  | handleCommandEvent | @ | VM22 <embedded>:11
  | t.exports.KeymapManager.dispatchCommandEvent | @ | VM22 <embedded>:11
  | t.exports.KeymapManager.handleKeyboardEvent | @ | VM22 <embedded>:11
  | handleDocumentKeyEvent

**Comment by kylebarron** [comment]
It looks like a Pillow dependency isn't found. From an Anaconda terminal, can you try running:
```
conda install -c conda-forge pillow
```

**Comment by kylebarron** [comment]
That's good to know, and I'm glad it's working for you. If you have any more similar issues in the future that are specific to Stata, a better place to file an issue would be:

https://github.com/kylebarron/stata_kernel/issues
