### ISSUE TITLE
Toggle Watches and Output Area Fails

### ISSUE THREAD

**Issue by jkroes** [nteract/hydrogen#1473]
**Description:**

Toggling watches or the output area writes an error to the console.

**Steps to Reproduce:**

1. In Terminal: atom -d
2. Open a Python file in Atom
3. Hydrogen: Start Local Kernel (Python 3)
4. Hydrogen: Toggle Output Area [A blank pane opens if no code has been run yet.]
5. Run some code.
6. Errors are displayed in the developer console.

**Versions:**

Atom    : 1.32.2
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
Hydrogen: 2.6.0

Package                Version
---------------------- -------
astroid                2.0.4
autopep8               1.4.2
backcall               0.1.0
colorama               0.4.0
decorator              4.3.0
future                 0.17.1
ipykernel              5.1.0
ipython                7.1.1
ipython-genutils       0.2.0
isort                  4.3.4
jedi                   0.13.1
jupyter-client         5.2.3
jupyter-core           4.4.0
lazy-object-proxy      1.3.1
mccabe                 0.6.1
parso                  0.3.1
pickleshare            0.7.5
pip                    18.1
pluggy                 0.8.0
prompt-toolkit         2.0.7
pycodestyle            2.4.0
pydocstyle             3.0.0
pyflakes               2.0.0
Pygments               2.2.0
pylint                 2.1.1
python-dateutil        2.7.5
python-jsonrpc-server  0.0.2
python-language-server 0.20.0
pyzmq                  17.1.2
rope                   0.11.0
setuptools             39.0.1
six                    1.11.0
snowballstemmer        1.2.1
tornado                5.1.1
traitlets              4.3.2
wcwidth                0.1.7
wrapt                  1.10.11
yapf                   0.24.0

**Logs:**

C:\Users\jkroes\AppData\Local\atom\app-1.32.2\resources\app.asar\src\config.js:1087 'Hydrogen.kernelspec' could not set the default. Attempted default: undefined; Schema: {}
setDefaults @ C:\Users\jkroes\AppData\Local\atom\app-1.32.2\resources\app.asar\src\config.js:1087

C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react\cjs\react.development.js:225 
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `OutputArea`.
    in OutputArea
warningWithoutStack @ C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react\cjs\react.development.js:225

Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `OutputArea`.
    at invariant (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:55:15)
    at createFiberFromTypeAndProps (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:9958:11)
    at createFiberFromElement (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:9979:15)
    at createChild (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:13148:28)
    at reconcileChildrenArray (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:13399:25)
    at reconcileChildFibers (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:13722:14)
    at reconcileChildren (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:14078:28)
    at updateHostComponent (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:14423:3)
    at beginWork (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:15087:14)
    at performUnitOfWork (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:17820:12)
    at workLoop (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:17860:24)
    at HTMLUnknownElement.callCallback (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:149:14)
    at Object.invokeGuardedCallbackDev (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:199:16)
    at invokeGuardedCallback (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:256:31)
    at replayUnitOfWork (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:17107:5)
    at renderRoot (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:17979:13)
    at performWorkOnRoot (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:18837:7)
    at performWork (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:18749:7)
    at performSyncWork (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:18723:3)
    at batchedUpdates$1 (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:18936:7)
    at reactionScheduler (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\mobx\lib\mobx.js:1724:47)
    at runReactions$$1 (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\mobx\lib\mobx.js:1700:5)
    at endBatch$$1 (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\mobx\lib\mobx.js:1412:9)
    at endAction (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\mobx\lib\mobx.js:613:5)
    at executeAction$$1 (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\mobx\lib\mobx.js:581:9)
    at Store.res (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\mobx\lib\mobx.js:570:16)
    at file:///C:/Users/jkroes/.atom/packages/Hydrogen/lib/kernel-manager.js:83:13
    at file:///C:/Users/jkroes/.atom/packages/Hydrogen/lib/zmq-kernel.js:59:26
    at ZMQKernel.onConnect (file:///C:/Users/jkroes/.atom/packages/Hydrogen/lib/zmq-kernel.js:127:21)
    at emitThree (events.js:136:13)
C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:15749 The above error occurred in the <div> component:
    in div (created by OutputArea)
    in OutputArea

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:15749
C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:18807 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `OutputArea`.
    at invariant (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:55:15)
    at createFiberFromTypeAndProps (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:9958:11)
    at createFiberFromElement (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:9979:15)
    at createChild (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:13148:28)
    at reconcileChildrenArray (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:13399:25)
    at reconcileChildFibers (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:13722:14)
    at reconcileChildren (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:14078:28)
    at updateHostComponent (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:14423:3)
    at beginWork (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:15087:14)
    at performUnitOfWork (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:17820:12)
    at workLoop (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:17860:24)
    at renderRoot (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:17946:7)
    at performWorkOnRoot (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:18837:7)
    at performWork (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:18749:7)
    at performSyncWork (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:18723:3)
    at batchedUpdates$1 (C:\Users\jkroes\.atom\packages\hydrogen-python\node_modules\react-dom\cjs\react-dom.development.js:18936:7)
    at reactionScheduler (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\mobx\lib\mobx.js:1724:47)
    at runReactions$$1 (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\mobx\lib\mobx.js:1700:5)
    at endBatch$$1 (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\mobx\lib\mobx.js:1412:9)
    at endAction (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\mobx\lib\mobx.js:613:5)
    at executeAction$$1 (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\mobx\lib\mobx.js:581:9)
    at Store.res (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\mobx\lib\mobx.js:570:16)
    at file:///C:/Users/jkroes/.atom/packages/Hydrogen/lib/kernel-manager.js:83:13
    at file:///C:/Users/jkroes/.atom/packages/Hydrogen/lib/zmq-kernel.js:59:26
    at ZMQKernel.onConnect (file:///C:/Users/jkroes/.atom/packages/Hydrogen/lib/zmq-kernel.js:127:21)
    at emitThree (events.js:136:13)
    at Socket.emit (events.js:217:7)
    at Object.self._zmq.onMonitorEvent (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\zeromq\lib\index.js:543:12)

**Comment by jkroes** [comment]
Python environment:

Package                Version
---------------------- -------
astroid                2.0.4
autopep8               1.4.2
backcall               0.1.0
colorama               0.4.0
decorator              4.3.0
future                 0.17.1
ipykernel              5.1.0
ipython                7.1.1
ipython-genutils       0.2.0
isort                  4.3.4
jedi                   0.13.1
jupyter-client         5.2.3
jupyter-core           4.4.0
lazy-object-proxy      1.3.1
mccabe                 0.6.1
parso                  0.3.1
pickleshare            0.7.5
pip                    18.1
pluggy                 0.8.0
prompt-toolkit         2.0.7
pycodestyle            2.4.0
pydocstyle             3.0.0
pyflakes               2.0.0
Pygments               2.2.0
pylint                 2.1.1
python-dateutil        2.7.5
python-jsonrpc-server  0.0.2
python-language-server 0.20.0
pyzmq                  17.1.2
rope                   0.11.0
setuptools             39.0.1
six                    1.11.0
snowballstemmer        1.2.1
tornado                5.1.1
traitlets              4.3.2
wcwidth                0.1.7
wrapt                  1.10.11
yapf                   0.24.0

**Comment by BenRussert** [comment]
I can't reproduce this with what you've provided. I did notice that you started atom with `atom -d`, this means you will be using a local dev copy of hydrogen if you have one linked. You can check what is linked with `apm links`.

I would try reinstalling hydrogen and running `atom .` to start atom unless you want to use a dev package.

**Comment by jkroes** [comment]
The problem persists with a non-development instance of Atom and a newly installed Hydrogen package.

**Comment by jkroes** [comment]
Uninstalling hydrogen-python produced a different error message:

<embedded>:11 'Hydrogen.kernelspec' could not set the default. Attempted default: undefined; Schema: {}
setDefaults @ <embedded>:11
C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:179 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at ca (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:13:316)
    at t (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:14:166)
    at $e (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:117:40)
    at C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:150:81
    at P (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:154:38)
    at yg (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:171:94)
    at fh (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:204:22)
    at gh (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:205:274)
    at Jh (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:220:348)
    at Kh (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:219:144)
    at nh (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:216:261)
    at Tf (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:214:85)
    at Qh (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:233:14)
    at Rh (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:233:92)
    at Xh.render (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:241:109)
    at C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:244:417
    at Oh (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:231:234)
    at $h (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:244:350)
    at Object.render (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:246:329)
    at reactFactory (file:///C:/Users/jkroes/.atom/packages/Hydrogen/lib/utils.js:24:12)
    at new WatchesPane (file:///C:/Users/jkroes/.atom/packages/Hydrogen/lib/panes/watches.js:18:5)
    at file:///C:/Users/jkroes/.atom/packages/Hydrogen/lib/main.js:212:20
    at Workspace.createItemForURI (C:\Users\jkroes\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:430067)
    at Workspace.open (C:\Users\jkroes\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:427925)
    at Workspace.toggle (C:\Users\jkroes\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:429374)
    at HTMLElement.hydrogenToggleWatches (file:///C:/Users/jkroes/.atom/packages/Hydrogen/lib/main.js:111:57)
    at CommandRegistry.handleCommandEvent (C:\Users\jkroes\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:347327)
    at Object.didConfirmSelection (C:\Users\jkroes\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:690277)
    at SelectListView.confirmSelection (C:\Users\jkroes\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:855336)
    at HTMLDivElement.core:confirm (C:\Users\jkroes\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:850215)
    at CommandRegistry.handleCommandEvent (C:\Users\jkroes\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:347327)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (C:\Users\jkroes\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:1227611)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (C:\Users\jkroes\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:1223745)
    at WindowEventHandler.handleDocumentKeyEvent (C:\Users\jkroes\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:282763)
Hg @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:179
Pg.c.callback @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:190
uf @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:128
tf @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:128
Mh @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:229
Jh @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:220
Kh @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:219
nh @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:216
Tf @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:214
Qh @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:233
Rh @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:233
Xh.render @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:241
(anonymous) @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:244
Oh @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:231
$h @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:244
render @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:246
reactFactory @ utils.js:24
WatchesPane @ watches.js:18
(anonymous) @ main.js:212
createItemForURI @ VM22 <embedded>:11
open @ VM22 <embedded>:11
toggle @ VM22 <embedded>:11
hydrogenToggleWatches @ main.js:111
handleCommandEvent @ VM22 <embedded>:11
didConfirmSelection @ VM22 <embedded>:11
confirmSelection @ VM22 <embedded>:11
core:confirm @ VM22 <embedded>:11
handleCommandEvent @ VM22 <embedded>:11
t.exports.KeymapManager.dispatchCommandEvent @ VM22 <embedded>:11
t.exports.KeymapManager.handleKeyboardEvent @ VM22 <embedded>:11
handleDocumentKeyEvent @ VM22 <embedded>:11
C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:13 Uncaught (in promise) Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at ca (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:13:316)
    at t (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:14:166)
    at $e (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:117:40)
    at C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:150:81
    at P (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:154:38)
    at yg (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:171:94)
    at fh (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:204:22)
    at gh (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:205:274)
    at Jh (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:220:348)
    at Kh (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:219:144)
    at nh (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:216:261)
    at Tf (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:214:85)
    at Qh (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:233:14)
    at Rh (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:233:92)
    at Xh.render (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:241:109)
    at C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:244:417
    at Oh (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:231:234)
    at $h (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:244:350)
    at Object.render (C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:246:329)
    at reactFactory (file:///C:/Users/jkroes/.atom/packages/Hydrogen/lib/utils.js:24:12)
    at new WatchesPane (file:///C:/Users/jkroes/.atom/packages/Hydrogen/lib/panes/watches.js:18:5)
    at file:///C:/Users/jkroes/.atom/packages/Hydrogen/lib/main.js:212:20
    at Workspace.createItemForURI (C:\Users\jkroes\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:430067)
    at Workspace.open (C:\Users\jkroes\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:427925)
    at Workspace.toggle (C:\Users\jkroes\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:429374)
    at HTMLElement.hydrogenToggleWatches (file:///C:/Users/jkroes/.atom/packages/Hydrogen/lib/main.js:111:57)
    at CommandRegistry.handleCommandEvent (C:\Users\jkroes\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:347327)
    at Object.didConfirmSelection (C:\Users\jkroes\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:690277)
    at SelectListView.confirmSelection (C:\Users\jkroes\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:855336)
    at HTMLDivElement.core:confirm (C:\Users\jkroes\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:850215)
    at CommandRegistry.handleCommandEvent (C:\Users\jkroes\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:347327)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (C:\Users\jkroes\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:1227611)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (C:\Users\jkroes\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:1223745)
    at WindowEventHandler.handleDocumentKeyEvent (C:\Users\jkroes\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11:282763)
ca @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:13
t @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:14
$e @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:117
(anonymous) @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:150
P @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:154
yg @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:171
fh @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:204
gh @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:205
Jh @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:220
Kh @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:219
nh @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:216
Tf @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:214
Qh @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:233
Rh @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:233
Xh.render @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:241
(anonymous) @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:244
Oh @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:231
$h @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:244
render @ C:\Users\jkroes\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:246
reactFactory @ utils.js:24
WatchesPane @ watches.js:18
(anonymous) @ main.js:212
createItemForURI @ VM22 <embedded>:11
open @ VM22 <embedded>:11
toggle @ VM22 <embedded>:11
hydrogenToggleWatches @ main.js:111
handleCommandEvent @ VM22 <embedded>:11
didConfirmSelection @ VM22 <embedded>:11
confirmSelection @ VM22 <embedded>:11
core:confirm @ VM22 <embedded>:11
handleCommandEvent @ VM22 <embedded>:11
t.exports.KeymapManager.dispatchCommandEvent @ VM22 <embedded>:11
t.exports.KeymapManager.handleKeyboardEvent @ VM22 <embedded>:11
handleDocumentKeyEvent @ VM22 <embedded>:11
Promise rejected (async)
handleCommandEvent @ VM22 <embedded>:11
didConfirmSelection @ VM22 <embedded>:11
confirmSelection @ VM22 <embedded>:11
core:confirm @ VM22 <embedded>:11
handleCommandEvent @ VM22 <embedded>:11
t.exports.KeymapManager.dispatchCommandEvent @ VM22 <embedded>:11
t.exports.KeymapManager.handleKeyboardEvent @ VM22 <embedded>:11
handleDocumentKeyEvent @ VM22 <embedded>:11

**Comment by wadethestealth** [comment]
This config setting causing a fail was removed upstream. Therefore this issue no longer exists.
