### ISSUE TITLE
Issue with Hydrogen and Miniconda

### ISSUE THREAD

**Issue by silvestre125** [nteract/hydrogen#1500]
**Description:**

When I try to run code on atom with hydrogen, it raise and error in a red screen. I have tried reinstalling atom and miniconda. I have already installed the ipython kernel. I have followed the instructions from https://nteract.io/kernels/python.

**Steps to Reproduce:**

1. [First Step]
2. [Second Step]

**Versions:**

Windows 10 64bit 10.0.17763 comp. 17763
Atom    : 1.33.1
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
Hydrogen : 2.7.0

**Plugins:**

Do you have any Hydrogen plugins installed and active?
Neither, only hydrogen.

**Logs:**

Traceback (most recent call last): 
  File "C:\Users\********\Miniconda3\lib\runpy.py", line 193, in _run_module_as_main "main", mod_spec) 
  File "C:\Users\********\Miniconda3\lib\runpy.py", line 85, in _run_code exec(code, run_globals) 
  File "C:\Users\********\Miniconda3\lib\site-packages\ipykernel_launcher.py", line 15, in from ipykernel import kernelapp as app 
  File "C:\Users\********\Miniconda3\lib\site-packages\ipykernel__init__.py", line 2, in from .connect import 
  File "C:\Users\********\Miniconda3\lib\site-packages\ipykernel\connect.py", line 18, in import jupyter_client 
  File "C:\Users\********\Miniconda3\lib\site-packages\jupyter_client__init__.py", line 4, in from .connect import 
  File "C:\Users\********\Miniconda3\lib\site-packages\jupyter_client\connect.py", line 23, in import zmq 
  File "C:\Users\********\Miniconda3\lib\site-packages\zmq__init__.py", line 47, in from zmq import backend 
  File "C:\Users\********\Miniconda3\lib\site-packages\zmq\backend__init__.py", line 40, in reraise(*exc_info) 
  File "C:\Users\********\Miniconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise raise value 
  File "C:\Users\********\Miniconda3\lib\site-packages\zmq\backend__init__.py", line 27, in _ns = select_backend(first) 
  File "C:\Users\********\Miniconda3\lib\site-packages\zmq\backend\select.py", line 27, in select_backend mod = import(name, fromlist=public_api) 
  File "C:\Users\********\Miniconda3\lib\site-packages\zmq\backend\cython__init__.py", line 6, in from . import (constants, error, message, context, ImportError: DLL load failed: No se puede encontrar el m�dulo especificado.

Thanks in advance.

**Comment by lgeiger** [comment]
It looks like there's something wrong with your miniconda installation. I'd try to upgrade miniconda or reinstall it, to see if it fixes your problem.

**Comment by silvestre125** [comment]
After reinstalling Miniconda and Atom, the error is the following:
![image](https://user-images.githubusercontent.com/46159929/50561219-dec71800-0d08-11e9-81ce-f408909eaa24.png)
I have installed ipython too (in root env, and my python3.7 env)
How can I configure the system path manually in Hydrogen?
Can I give you more information in order to help me?
Thanks.

**Comment by kylebarron** [comment]
Type
```
jupyter kernelspec list --json
```
and it should show which Python executable is called. Does it work if you run `jupyter notebook`?

**Comment by silvestre125** [comment]
The output of
`jupyter kernelspec list --json`
on root env  (and my python37) is
`{
  "kernelspecs": {
    "python3": {
      "resource_dir": "C:\\Users\\*****\\AppData\\Roaming\\jupyter\\kernels\\python3",
      "spec": {
        "argv": [
          "C:\\Users\\*****\\Miniconda3\\python.exe",
          "-m",
          "ipykernel_launcher",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "Python 3",
        "language": "python",
        "interrupt_mode": "signal",
        "metadata": {}
      }
    }
  }
}`
After execute 
`jupyter notebook`
I have the next output:
`Error executing Jupyter command 'notebook': [Errno 'jupyter-notebook' not found] 2`
I have installed Jupyter notebooks on my env python37, and it opens and works properly.
When I try to execute some code on Atom (with Jupyter notebooks running in Chrome), the error is the same:
![image](https://user-images.githubusercontent.com/46159929/50572314-9e75a180-0dbd-11e9-8938-9fcadb4429e0.png)
I have tried installing jupyter on my root env, but the error is the same.

**Comment by wadethestealth** [comment]
All related issues: 
#1684, #1665, #1550, #1517, #1500, #1405 
Solutions:
#1405
https://github.com/ContinuumIO/anaconda-issues/issues/10422#issuecomment-448185070
https://stackoverflow.com/questions/52821162/jupyter-notebook-failed-to-load-dll
