### ISSUE TITLE
Hydrogen Restart Kernel throws error message

### ISSUE THREAD

**Issue by FranciscoRZ** [nteract/hydrogen#1516]
Hello everyone, 

First of all, many thanks to the Hydrogen developers, it's a great tool.
I'm having trouble when I restart my python kernel from the command palette. Apparently it's not a known issue yet so below is the error report I get. It's not blocking, but I currently have to restart Atom to get it to work properly.

Thanks again, 

Francisco

********** HYDROGEN ERRROR REPORT **********

[Enter steps to reproduce:]

1. Control+ P (Command Palette)
2. Hydrogen: Restart Kernel and Re-evaluate bubbles

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Windows 7
**Thrown From**: [Hydrogen](ssh://git@github.com/nteract/hydrogen) package 2.7.0

### Stack Trace

Uncaught TypeError: Cannot read property 'match' of undefined

```
At C:\Users\F_REYZALUAR\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11

TypeError: Cannot read property 'match' of undefined
    at TextEditor.isBufferRowCommented (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:44757)
    at isBlank (/packages/Hydrogen/lib/code-manager.js:64:55)
    at Object.escapeBlankRows (/packages/Hydrogen/lib/code-manager.js:73:10)
    at /packages/Hydrogen/lib/main.js:490:36)
    at /packages/Hydrogen/lib/main.js:492:8
    at arrayEach (/packages/Hydrogen/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/packages/Hydrogen/node_modules/lodash/lodash.js:9344:14)
    at Object._runAll (/packages/Hydrogen/lib/main.js:486:7)
    at Object.runAll (/packages/Hydrogen/lib/main.js:466:12)
    at /packages/Hydrogen/lib/main.js:411:33
    at /packages/Hydrogen/lib/zmq-kernel.js:203:24
    at ZMQKernel.onConnect (/packages/Hydrogen/lib/zmq-kernel.js:127:21)
    at emitThree (events.js:141:20)
    at Socket.emit (events.js:217:7)
    at Object.self._zmq.onMonitorEvent (/packages/Hydrogen/node_modules/zeromq/lib/index.js:552:12)
```

### Commands

```
     -2:32.6.0 hydrogen:run (input.hidden-input)
     -2:32.6.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
     -1:11.2.0 core:backspace (input.hidden-input)
     -1:10.1.0 intentions:highlight (input.hidden-input)
     -1:09.9.0 core:save (input.hidden-input)
     -1:06.7.0 intentions:highlight (input.hidden-input)
     -1:06.4.0 command-palette:toggle (input.hidden-input)
     -1:02.9.0 editor:select-to-beginning-of-word (input.hidden-input)
     -1:02.7.0 core:backspace (input.hidden-input)
     -1:01.4.0 intentions:highlight (input.hidden-input)
  2x -1:01.1.0 command-palette:toggle (input.hidden-input)
     -0:50 intentions:highlight (input.hidden-input)
     -0:49.5.0 command-palette:toggle (input.hidden-input)
     -0:47.3.0 core:move-down (input.hidden-input)
     -0:47.1.0 core:confirm (input.hidden-input)
     -0:47.1.0 hydrogen:restart-kernel-and-re-evaluate-bubbles (input.hidden-input)
```

### Non-Core Packages

```
atom-file-icons 0.6.0 
atom-language-r 1.4.8 
atom-material-ui 2.1.3 
autocomplete-python 1.11.0 
autocomplete-R 0.6.0 
busy-signal 2.0.0 
goto-definition 1.3.4 
Hydrogen 2.7.0 
hydrogen-launcher 1.2.2 
ide-r 0.1.8 
intentions 1.1.5 
kite 0.140.0 
linter 2.3.0 
linter-flake8 2.4.0 
linter-lintr 1.1.4 
linter-ui-default 1.7.1 
minimap 4.29.9 
platformio-ide-terminal 2.8.4 
rbox 0.5.0 
script 3.18.1 
```

**Comment by FranciscoRZ** [comment]
Clarification: kernel restart seems to work fine after a second call.
This is probably a very minor issue, just thought you might want to know.
