### ISSUE TITLE
Unable to run code with Anaconda

### ISSUE THREAD

**Issue by ssuds** [nteract/hydrogen#1533]
**Description:**

Unable to run python code with Anaconda python installation.

**Steps to Reproduce:**

1. Open Python 3 script in Atom
2. Attempt to run script.
3. Error occurs (pasted below in Logs section)

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?
Windows 7
Atom 1.34.0 x64
Hydrogen 2.8.0
Python 3.4.3 (Anaconda 64 bit)

**Plugins:**

Do you have any Hydrogen plugins installed and active?
None

**Logs:**

Traceback (most recent call last): File "C:\Anaconda3\lib\runpy.py", line 170, in _run_module_as_main "main", mod_spec) File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in from ipykernel import kernelapp as app File "C:\Anaconda3\lib\site-packages\ipykernel__init__.py", line 2, in from .connect import * File "C:\Anaconda3\lib\site-packages\ipykernel\connect.py", line 13, in from IPython.core.profiledir import ProfileDir File "C:\Anaconda3\lib\site-packages\IPython__init__.py", line 49, in from .terminal.embed import embed File "C:\Anaconda3\lib\site-packages\IPython\terminal\embed.py", line 18, in from IPython.terminal.interactiveshell import TerminalInteractiveShell File "C:\Anaconda3\lib\site-packages\IPython\terminal\interactiveshell.py", line 16, in from prompt_toolkit.document import Document File "C:\Anaconda3\lib\site-packages\prompt_toolkit__init__.py", line 16, in from .interface import CommandLineInterface File "C:\Anaconda3\lib\site-packages\prompt_toolkit\interface.py", line 19, in from .application import Application, AbortAction File "C:\Anaconda3\lib\site-packages\prompt_toolkit\application__init__.py", line 2, in from .application import Application File "C:\Anaconda3\lib\site-packages\prompt_toolkit\application\application.py", line 3, in from prompt_toolkit.buffer import Buffer File "C:\Anaconda3\lib\site-packages\prompt_toolkit\buffer.py", line 9, in from .completion import Completer, Completion, CompleteEvent File "C:\Anaconda3\lib\site-packages\prompt_toolkit\completion__init__.py", line 2, in from .base import Completion, Completer, ThreadedCompleter, DummyCompleter, DynamicCompleter, CompleteEvent, merge_completers, get_common_complete_suffix File "C:\Anaconda3\lib\site-packages\prompt_toolkit\completion\base.py", line 4, in from prompt_toolkit.eventloop import generator_to_async_generator, AsyncGeneratorItem ImportError: cannot import name 'generator_to_async_generator'

**Comment by kylebarron** [comment]
You may want to check out https://github.com/ipython/ipython/issues/11270#issuecomment-427448691

**Comment by ssuds** [comment]
Bingo, reinstalling ipython did the trick. Thanks @kylebarron!
