### ISSUE TITLE
Import Error: DLL load failed for a cython __init__ call

### ISSUE THREAD

**Issue by ctivanovich** [nteract/hydrogen#1550]
Hydrogen is unable to run code in an Atom .py file. I had no problems running code until a few days ago, possibly this changed because I updated my Python packages and perhaps something broke.

OS: Windows 10
Atom: 1.34.0
Python: 3.6.8
Hydrogen: 2.8.0

**Logs:**
Traceback (most recent call last): File "C:\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main "main", mod_spec) File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in from ipykernel import kernelapp as app File "C:\Anaconda3\lib\site-packages\ipykernel__init__.py", line 2, in from .connect import File "C:\Anaconda3\lib\site-packages\ipykernel\connect.py", line 18, in import jupyter_client File "C:\Anaconda3\lib\site-packages\jupyter_client__init__.py", line 4, in from .connect import File "C:\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 23, in import zmq File "C:\Anaconda3\lib\site-packages\zmq__init__.py", line 47, in from zmq import backend File "C:\Anaconda3\lib\site-packages\zmq\backend__init__.py", line 40, in reraise(*exc_info) File "C:\Anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise raise value File "C:\Anaconda3\lib\site-packages\zmq\backend__init__.py", line 27, in _ns = select_backend(first) File "C:\Anaconda3\lib\site-packages\zmq\backend\select.py", line 27, in select_backend mod = import(name, fromlist=public_api) File "C:\Anaconda3\lib\site-packages\zmq\backend\cython__init__.py", line 6, in from . import (constants, error, message, context, ImportError: DLL load failed: The specified module could not be found.

**Comment by nl-datascience** [comment]
Dear all,

I am facing the same issue.

OS: Windows 10
Atom: 1.34.0
Python: Python 3.7.0
Hydrogen: 2.8.0

**Logs:**
Traceback (most recent call last): File "C:\Users\m-a.nehrkorn-ludwig\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main "main", mod_spec) File "C:\Users\m-a.nehrkorn-ludwig\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\Users\m-a.nehrkorn-ludwig\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in from ipykernel import kernelapp as app File "C:\Users\m-a.nehrkorn-ludwig\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel__init__.py", line 2, in from .connect import File "C:\Users\m-a.nehrkorn-ludwig\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\connect.py", line 18, in import jupyter_client File "C:\Users\m-a.nehrkorn-ludwig\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyter_client__init__.py", line 4, in from .connect import File "C:\Users\m-a.nehrkorn-ludwig\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyter_client\connect.py", line 23, in import zmq File "C:\Users\m-a.nehrkorn-ludwig\AppData\Local\Continuum\anaconda3\lib\site-packages\zmq__init__.py", line 47, in from zmq import backend File "C:\Users\m-a.nehrkorn-ludwig\AppData\Local\Continuum\anaconda3\lib\site-packages\zmq\backend__init__.py", line 40, in reraise(*exc_info) File "C:\Users\m-a.nehrkorn-ludwig\AppData\Local\Continuum\anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise raise value File "C:\Users\m-a.nehrkorn-ludwig\AppData\Local\Continuum\anaconda3\lib\site-packages\zmq\backend__init__.py", line 27, in _ns = select_backend(first) File "C:\Users\m-a.nehrkorn-ludwig\AppData\Local\Continuum\anaconda3\lib\site-packages\zmq\backend\select.py", line 27, in select_backend mod = import(name, fromlist=public_api) File "C:\Users\m-a.nehrkorn-ludwig\AppData\Local\Continuum\anaconda3\lib\site-packages\zmq\backend\cython__init__.py", line 6, in from . import (constants, error, message, context, ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

Thanks!

**Comment by Nicbecoz** [comment]
Hi, 

I faced a similar issue too. 

Install Hydrogen 2.8 successfully. 
Selected Hydrogen: Start local kernel, then selected Python 3
No error up to this point

Tried to run some code but got this error below:

**Traceback (most recent call last): File "C:\Users\Nic\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main "main", mod_spec) File "C:\Users\Nic\Anaconda3\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\Users\Nic\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in from ipykernel import kernelapp as app File "C:\Users\Nic\Anaconda3\lib\site-packages\ipykernel__init__.py", line 2, in from .connect import File "C:\Users\Nic\Anaconda3\lib\site-packages\ipykernel\connect.py", line 18, in import jupyter_client File "C:\Users\Nic\Anaconda3\lib\site-packages\jupyter_client__init__.py", line 4, in from .connect import File "C:\Users\Nic\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 23, in import zmq File "C:\Users\Nic\Anaconda3\lib\site-packages\zmq__init__.py", line 47, in from zmq import backend File "C:\Users\Nic\Anaconda3\lib\site-packages\zmq\backend__init__.py", line 40, in reraise(*exc_info) File "C:\Users\Nic\Anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise raise value File "C:\Users\Nic\Anaconda3\lib\site-packages\zmq\backend__init__.py", line 27, in _ns = select_backend(first) File "C:\Users\Nic\Anaconda3\lib\site-packages\zmq\backend\select.py", line 28, in select_backend mod = import(name, fromlist=public_api) File "C:\Users\Nic\Anaconda3\lib\site-packages\zmq\backend\cython__init__.py", line 6, in from . import (constants, error, message, context, ImportError: DLL load failed: The specified module could not be found.**

Windows 10 Pro Version	10.0.17763 Build 17763
Atom 1.35.1 x64
Hydrogen 2.8
Python 3.7.2 installed via Anaconda - Conda 4.6.8

Atom    : 1.35.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

no other plugins installed

Debug console did not show anything
![image](https://user-images.githubusercontent.com/37495541/54927974-26e38880-4f4e-11e9-90b2-f8b9afb6aaa4.png)

**Comment by danhamill** [comment]
I have the same issue.  I had to re-install anaconda recently and can't get hydrogen to connect to the remote kernel.
```
Windows 10
Atom 1.35.1 x64
conda-build version: 3.17.8
python version : 3.7.3.final.0
Hydrogen 2.8.0
pyzmq 18.0.0
ipykernel 5.1.0

jupyter                   1.0.0               
jupyter_client            5.2.4 
jupyter_console           6.0.0 
jupyter_core              4.4.0
jupyterlab                0.35.4
jupyterlab_server         0.2.0   
```
No other plugins installed.

When I connect try and connect to kernel `base`:
```
Traceback (most recent call last): File "C:\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main "main", mod_spec) File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code exec(code, run_globals) 
File "C:\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in from ipykernel import kernelapp as app 
File "C:\Anaconda3\lib\site-packages\ipykernel__init__.py", line 2, in from .connect import 
File "C:\Anaconda3\lib\site-packages\ipykernel\connect.py", line 18, in import jupyter_client
File "C:\Anaconda3\lib\site-packages\jupyter_client__init__.py", line 4, in from .connect import 
File "C:\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 23, in import zmq 
File "C:\Anaconda3\lib\site-packages\zmq__init__.py", line 47, in from zmq import backend 
File "C:\Anaconda3\lib\site-packages\zmq\backend__init__.py", line 40, in reraise(*exc_info) 
File "C:\Anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise raise value 
File "C:\Anaconda3\lib\site-packages\zmq\backend__init__.py", line 27, in _ns = select_backend(first) 
File "C:\Anaconda3\lib\site-packages\zmq\backend\select.py", line 28, in select_backend mod = import(name, fromlist=public_api) 
File "C:\Anaconda3\lib\site-packages\zmq\backend\cython__init__.py", line 6, in from . import (constants, error, message, context, 
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by wadethestealth** [comment]
All related issues: 
#1684, #1665, #1550, #1517, #1500, #1405 
Solutions:
#1405
https://github.com/ContinuumIO/anaconda-issues/issues/10422#issuecomment-448185070
https://stackoverflow.com/questions/52821162/jupyter-notebook-failed-to-load-dll
