### ISSUE TITLE
Uncaught Error: Cannot find module 'collapse-white-space'

### ISSUE THREAD

**Issue by gunwoo7** [nteract/hydrogen#1554]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Unknown Windows version
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.8.0

### Stack Trace

Uncaught Error: Cannot find module 'collapse-white-space'

```
At module.js:545

Error: Cannot find module 'collapse-white-space'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.34.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:154667)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at /packages/Hydrogen/node_modules/remark-parse/lib/util/normalize.js:3:26)
    at /packages/Hydrogen/node_modules/remark-parse/lib/util/normalize.js:13:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at /packages/Hydrogen/node_modules/remark-parse/lib/tokenize/footnote-definition.js:4:17)
    at /packages/Hydrogen/node_modules/remark-parse/lib/tokenize/footnote-definition.js:187:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at /packages/Hydrogen/node_modules/remark-parse/lib/parser.js:112:13)
    at /packages/Hydrogen/node_modules/remark-parse/lib/parser.js:154:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
```

### Commands

```
  2x -3:49.3.0 core:backspace (input.hidden-input)
 45x -2:31.9.0 core:move-up (button.btn.btn-default.selected)
```

### Non-Core Packages

```
Hydrogen 2.8.0 
```

**Comment by kylebarron** [comment]
It looks like Hydrogen didn't install fully. You should try reinstalling.

**Comment by gunwoo7** [comment]
Ok. It works properly. Thank you
