### ISSUE TITLE
Uncaught Error: Cannot find module 'ansi-to-react'

### ISSUE THREAD

**Issue by DizzyNDL** [nteract/hydrogen#1560]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 7 Home Premium 
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.8.0

### Stack Trace

Uncaught Error: Cannot find module 'ansi-to-react'

```
At module.js:545

Error: Cannot find module 'ansi-to-react'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.34.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:154667)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at /packages/Hydrogen/node_modules/@nteract/transforms/lib/text.js:24:20)
    at /packages/Hydrogen/node_modules/@nteract/transforms/lib/text.js:59:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at /packages/Hydrogen/node_modules/@nteract/transforms/lib/index.js:22:36)
    at /packages/Hydrogen/node_modules/@nteract/transforms/lib/index.js:104:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at /packages/Hydrogen/lib/store/output.js:3:52)
    at /packages/Hydrogen/lib/store/output.js:67:33)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
```

### Commands

```
```

### Non-Core Packages

```
atom-php-navigation 0.7.0 
autocomplete-python 1.12.0 
git-auto-stash 0.2.4 
git-control 0.9.0 
git-diff-details 1.4.0 
git-links 0.3.3 
git-projects-manager 1.0.0 
git-status-utils 0.2.0 
git-tabs 0.3.0 
git-time-machine 2.1.0 
greppen-grok 0.2.1 
Hydrogen 2.8.0 
moonlight 0.11.0 
tree-view-git-status 1.5.2 
```

**Comment by kylebarron** [comment]
Can you try reinstalling?

**Comment by DizzyNDL** [comment]
Yeah i just ended up having to reinstall Atom. Thanks
