### ISSUE TITLE
"No Output to Display", Nothing Runs

### ISSUE THREAD

**Issue by erileff** [nteract/hydrogen#1561]
**Description:**

Nothing happens when I try to run code. I'm fairly new at using Terminal to do anything significant (and honestly this process has taught me a lot). I had some trouble installing the JavaScript kernel, but managed to get it figured out. However, nothing is happening. The output area says "No output to display," no bubbles have ever come up, and nothing is printed in the dev tools console when I've tried.

I've looked at related issues and nothing has helped.

**Steps to Reproduce:**

I'm not sure how to give steps to reproduce since it's the only thing that happens?

**Versions:**
I'm on Mac OS 10.14.1.

Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Plugins:**

Do you have any Hydrogen plugins installed and active?
- [ ] hydrogen-python
- [x] Hydrogen Launcher
- [ ] Data Explorer

**Logs:**
<img width="440" alt="screenshot at feb 28 13-51-29" src="https://user-images.githubusercontent.com/7518276/53590547-03e8d300-3b60-11e9-95ed-d0df52d2085a.png">
<img width="434" alt="screenshot at feb 28 13-51-45" src="https://user-images.githubusercontent.com/7518276/53590552-077c5a00-3b60-11e9-8087-54e8e21515fb.png">

That's all from just trying to run these:
<img width="400" alt="screenshot at feb 28 13-52-19" src="https://user-images.githubusercontent.com/7518276/53590576-1400b280-3b60-11e9-8d91-6ae01d55ee3d.png">

**Comment by kylebarron** [comment]
Does it work in Jupyter notebook?

**Comment by erileff** [comment]
When I tried to start a new JS notebook, I kept getting this:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
    result = await result
  File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/usr/local/lib/python3.7/site-packages/notebook/services/sessions/handlers.py", line 73, in post
    type=mtype))
  File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/usr/local/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/usr/local/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/jupyter_client/manager.py", line 259, in start_kernel
    **kw)
  File "/usr/local/lib/python3.7/site-packages/jupyter_client/manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/usr/local/lib/python3.7/site-packages/jupyter_client/launcher.py", line 138, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ijskernel': 'ijskernel'
```
I've done a ton more trying to figure out why ijskernel isn't there. I've uninstalled & reinstalled multiple things, tons of searching for similar issues and trying those solutions -- way too many to list. 

Update: After _hours_ of trying to fix this, I decided to try installing IJS through conda. And... it worked. If anyone else ever has these types of issues: try that! I can now use Jupyter and, best of all, Hydrogen works.

<img width="148" alt="screenshot at mar 02 20-59-03" src="https://user-images.githubusercontent.com/7518276/53689895-06008c80-3d2e-11e9-9cc0-01535f6e236d.png">
I'm ecstatic that it's now working! :)
