### ISSUE TITLE
Uncaught Error: Cannot find module '@nteract/vega-embed-v2'

### ISSUE THREAD

**Issue by Sergeileduc** [nteract/hydrogen#1576]
[Steps to reproduce:]

1. Install Hydrogen

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: linux 4.20.16-112.current
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.8.0

### Stack Trace

Uncaught Error: Cannot find module '@nteract/vega-embed-v2'

```
At module.js:545

Error: Cannot find module '@nteract/vega-embed-v2'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:154667)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145974)
    at /packages/Hydrogen/node_modules/@nteract/transform-vega/lib/index.js:34:42)
    at /packages/Hydrogen/node_modules/@nteract/transform-vega/lib/index.js:178:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145974)
    at /packages/Hydrogen/lib/components/result-view/transforms.js:8:56)
    at /packages/Hydrogen/lib/components/result-view/transforms.js:20:40)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145974)
    at /packages/Hydrogen/lib/store/output.js:8:25)
    at /packages/Hydrogen/lib/store/output.js:67:33)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
```

### Commands

```
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
auto-create-files 0.2.1 
autocomplete-python 1.14.0 
busy-signal 2.0.1 
diff-pane 0.3.0 
file-icons 2.1.31 
file-type-icons 1.3.4 
git-log 0.4.1 
Hydrogen 2.8.0 
intentions 1.1.5 
language-ignore 1.8.0 
linter 2.3.0 
linter-flake8 2.4.0 
linter-ui-default 1.7.1 
python-indent 1.1.7 
script-runner 2.3.1 
split-diff 1.6.0 
```

**Comment by BenRussert** [comment]
I'm not able to reproduce. Can you try `apm install hydrogen` again? Reopen if you still have the issue.
