### ISSUE TITLE
Uncaught Error: Cannot find module './../kernel-manager'

### ISSUE THREAD

**Issue by StOwl** [nteract/hydrogen#1577]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.8.0

### Stack Trace

Uncaught Error: Cannot find module './../kernel-manager'

```
At module.js:545

Error: Cannot find module './../kernel-manager'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.35.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (<embedded>:11:154667)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (<embedded>:11:145974)
    at /packages/Hydrogen/lib/store/index.js:37:22)
    at /packages/Hydrogen/lib/store/index.js:323:3)
    at Module.get_Module._compile (<embedded>:11:146684)
    at Object.value [as .js] (<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (<embedded>:11:145974)
    at /packages/Hydrogen/lib/utils.js:67:14)
    at /packages/Hydrogen/lib/utils.js:257:3)
    at Module.get_Module._compile (<embedded>:11:146684)
    at Object.value [as .js] (<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (<embedded>:11:145974)
    at /packages/Hydrogen/lib/kernel-picker.js:21:14)
    at /packages/Hydrogen/lib/kernel-picker.js:99:3)
    at Module.get_Module._compile (<embedded>:11:146684)
    at Object.value [as .js] (<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (<embedded>:11:145974)
    at /packages/Hydrogen/lib/main.js:23:21)
    at /packages/Hydrogen/lib/main.js:671:3)
    at Module.get_Module._compile (<embedded>:11:146684)
    at Object.value [as .js] (<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (<embedded>:1:666612)
    at Package.requireMainModule (<embedded>:11:3027983)
    at Package.activateConfig (<embedded>:11:3017342)
    at PackageManager.t.exports.PackageManager.packageHasSettings (<embedded>:11:892635)
    at PackageCard.hasSettings (<embedded>:14:2933981)
    at PackageCard.updateSettingsState (<embedded>:14:2924261)
    at PackageCard.updateInterfaceState (<embedded>:14:2924084)
    at <embedded>:14:2932214
    at <embedded>:14:2934232
    at Function.simpleDispatch (<embedded>:11:1172354)
    at Emitter.emit (<embedded>:11:1173795)
    at PackageManager.t.exports.PackageManager.emitPackageEvent (<embedded>:11:901815)
    at <embedded>:11:899224
    at r (<embedded>:11:893754)
    at o (<embedded>:14:1033430)
    at ChildProcess.n.process.on.e (<embedded>:14:1033636)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

```

### Commands

```
     -7:04.0 core:paste (input.hidden-input)
  7x -7:03.2.0 core:move-up (input.hidden-input)
     -7:02.0 core:move-down (input.hidden-input)
     -7:00.3.0 core:cut (input.hidden-input)
     -6:58.9.0 core:move-up (input.hidden-input)
  3x -6:58.7.0 editor:newline (input.hidden-input)
  3x -6:58.1.0 core:move-up (input.hidden-input)
     -6:57.4.0 core:paste (input.hidden-input)
  2x -6:56.5.0 core:move-down (input.hidden-input)
     -6:55.9.0 core:backspace (input.hidden-input)
 15x -6:54.7.0 core:move-down (input.hidden-input)
     -6:51.9.0 console:toggle (input.hidden-input)
     -5:37.2.0 core:select-all (input.hidden-input)
     -5:37 core:cut (input.hidden-input)
     -5:36.2.0 core:paste (input.hidden-input)
  2x -4:50.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
Hydrogen 2.8.0 
```

**Comment by BenRussert** [comment]
I'm fairly confident you can reinstall to fix this issue. Make sure you're on a good internet connection when you do.

If that doesnt solve, feel free to reopen. Thanks!
