### ISSUE TITLE
don't work

### ISSUE THREAD

**Issue by F45W** [nteract/hydrogen#1579]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: elementary OS
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.8.0

### Stack Trace

Uncaught TypeError: (0 , _util.promisify) is not a function

```
At /home/f45w/.atom/packages/Hydrogen/lib/import-notebook.js:15

TypeError: (0 , _util.promisify) is not a function
    at /packages/Hydrogen/lib/import-notebook.js:15:19)
    at /packages/Hydrogen/lib/import-notebook.js:148:2)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/Hydrogen/lib/main.js:57:47)
    at /packages/Hydrogen/lib/main.js:588:24)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/opt/atom/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/opt/atom/resources/app/src/package.js:782:33)
    at Package.activateConfig (/opt/atom/resources/app/src/package.js:267:16)
    at PackageManager.module.exports.PackageManager.packageHasSettings (/opt/atom/resources/app/node_modules/settings-view/lib/package-manager.js:68:20)
    at PackageCard.hasSettings (/opt/atom/resources/app/node_modules/settings-view/lib/package-card.js:794:40)
    at PackageCard.updateSettingsState (/opt/atom/resources/app/node_modules/settings-view/lib/package-card.js:439:22)
    at PackageCard.updateInterfaceState (/opt/atom/resources/app/node_modules/settings-view/lib/package-card.js:431:18)
    at /opt/atom/resources/app/node_modules/settings-view/lib/package-card.js:728:22
    at /opt/atom/resources/app/node_modules/settings-view/lib/package-card.js:811:17
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (/opt/atom/resources/app/node_modules/settings-view/lib/package-manager.js:659:33)
    at /opt/atom/resources/app/node_modules/settings-view/lib/package-manager.js:498:32
    at exit (/opt/atom/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/opt/atom/resources/app/src/buffered-process.js:267:15)
    at bufferStream (/opt/atom/resources/app/src/buffered-process.js:288:15)
    at Socket.stream.on (/opt/atom/resources/app/src/buffered-process.js:164:13)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
```

### Commands

```
  5x -7:38.5.0 tree-view:reveal-active-file (div.line)
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
Hydrogen 2.8.0 
minimap 4.29.9 
```

**Comment by kylebarron** [comment]
You need to update your version of Atom to a more recent one.
