### ISSUE TITLE
Uncaught TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by wutangclancee** [nteract/hydrogen#1603]
[Enter steps to reproduce:]

1. Shutdown python3.6.6 kernel in virtual environment.

**Atom**: 1.36.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.9.0

### Stack Trace

Uncaught TypeError: Cannot read property 'get' of undefined

```
At C:\Users\*******\.atom\packages\Hydrogen\lib\store\index.js:175

TypeError: Cannot read property 'get' of undefined
    at /packages/Hydrogen/lib/store/index.js:175:23
    at Array.filter (<anonymous>)
    at Store.getFilesForKernel (/packages/Hydrogen/lib/store/index.js:171:27)
    at Store.deleteKernel (/packages/Hydrogen/lib/store/index.js:154:24)
    at /packages/Hydrogen/node_modules/mobx/lib/mobx.js:604:22)
    at Store.res (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:595:16)
    at Kernel.destroy (/packages/Hydrogen/lib/kernel.js:399:11)
    at /packages/Hydrogen/lib/main.js:334:14)
    at Object.handleKernelCommand (/packages/Hydrogen/lib/main.js:344:4)
    at SignalListView.signalListView.onConfirmed (/packages/Hydrogen/lib/main.js:292:14)
    at Object.didConfirmSelection (/packages/Hydrogen/lib/signal-list-view.js:40:36)
    at SelectListView.confirmSelection (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:400:20)
    at SelectListView.didClickItem (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:286:10)
    at ListItemView.onclick (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:221:31)
    at ListItemView.didClick (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:448:10)
```

### Commands

```
     -3:13.7.0 core:backspace (input.hidden-input)
     -3:13.1.0 core:move-down (input.hidden-input)
     -3:12.9.0 core:move-right (input.hidden-input)
     -3:12.6.0 core:backspace (input.hidden-input)
     -3:12 core:save (input.hidden-input)
  6x -3:11.1.0 editor:move-to-end-of-word (input.hidden-input)
     -3:09.6.0 editor:newline (input.hidden-input)
     -3:09.2.0 core:save (input.hidden-input)
     -3:06.4.0 hydrogen:run (input.hidden-input)
     -3:06.4.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
     -2:49 editor:newline (input.hidden-input)
     -2:47.2.0 core:save (input.hidden-input)
     -2:46.6.0 core:select-all (input.hidden-input)
     -0:56.5.0 application:new-file (input.hidden-input)
     -0:54.8.0 core:paste (input.hidden-input)
  2x -0:53.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-python-virtualenv 1.0.2 
block-select 1.0.0 
git-plus 8.6.2 
goto-definition 1.3.4 
Hydrogen 2.9.0 
kite 0.156.0 
```

**Comment by shr00mie** [comment]
samesies

[Enter steps to reproduce:]
this doesn't seem to happen all the time, but as of late, i've been getting this error when attempting to shut down a kernel via hydrogen. i'll mess around a bit more and see if i can determine if it's only on shutting down the last live kernel or any. i'm leaning towards the former.

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.9.0


### Stack Trace

Uncaught TypeError: Cannot read property 'get' of undefined

```
At C:\Users\The Russian\.atom\packages\Hydrogen\lib\store\index.js:175

TypeError: Cannot read property 'get' of undefined
    at /packages/Hydrogen/lib/store/index.js:175:23
    at Array.filter (<anonymous>)
    at Store.getFilesForKernel (/packages/Hydrogen/lib/store/index.js:171:27)
    at Store.deleteKernel (/packages/Hydrogen/lib/store/index.js:154:24)
    at /packages/Hydrogen/node_modules/mobx/lib/mobx.js:604:22)
    at Store.res (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:595:16)
    at Kernel.destroy (/packages/Hydrogen/lib/kernel.js:399:11)
    at /packages/Hydrogen/lib/main.js:334:14)
    at Object.handleKernelCommand (/packages/Hydrogen/lib/main.js:344:4)
    at SignalListView.signalListView.onConfirmed (/packages/Hydrogen/lib/main.js:292:14)
    at Object.didConfirmSelection (/packages/Hydrogen/lib/signal-list-view.js:40:36)
    at SelectListView.confirmSelection (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:400:20)
    at SelectListView.didClickItem (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:286:10)
    at ListItemView.onclick (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:221:31)
    at ListItemView.didClick (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:448:10)
```

### Commands

```
```

### Non-Core Packages

```
atom-eclipse-syntax 0.0.6 
autocomplete 0.47.0 
autocomplete-bash-builtins 0.3.5 
busy-signal 2.0.1 
city-lights-ui 1.5.3 
docker 0.8.0 
file-icons 2.1.32 
Hydrogen 2.9.0 
intentions 1.1.5 
language-docker 1.1.8 
language-powershell 5.0.0 
linter 2.3.0 
linter-ui-default 1.7.1 
markdown-writer 2.11.5 
minimap 4.29.9 
monokai 0.24.0 
monokai-dark 1.5.0 
monokai-seti 0.9.0 
python-snippets 1.9.0 
remote-sync 4.1.8 
seti-ui 1.11.0 
split-diff 1.6.0 
teletype 0.13.4 
wakatime 7.0.9 
```

**Comment by wadethestealth** [comment]
Was able to reproduce this error by calling run cell on an untitled file that came from importing a jupyter notebook. My assumption is that its the grammar name that is messing up. Potentially grammar changing could cause this.

**Comment by areteaudio** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.5
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.9.0


### Stack Trace

Uncaught TypeError: Cannot read property 'get' of undefined

```
At /Users/johncasey/.atom/packages/Hydrogen/node_modules/mobx/lib/mobx.js:2207

TypeError: Cannot read property 'get' of undefined
    at extendObservableObjectWithProperties (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:2207:30)
    at Function.object (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:546:13)
    at deepEnhancer (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:382:27)
    at /packages/Hydrogen/node_modules/mobx/lib/mobx.js:708:23)
    at ObservableObjectAdministration.addObservableProp (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:3926:26)
    at /packages/Hydrogen/node_modules/mobx/lib/mobx.js:428:36
    at decorate (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:339:17)
    at decoratorFactory (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:360:30)
    at extendObservableObjectWithProperties (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:2212:36)
    at Function.object (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:546:13)
    at deepEnhancer (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:382:27)
    at /packages/Hydrogen/node_modules/mobx/lib/mobx.js:708:23)
    at ObservableObjectAdministration.addObservableProp (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:3926:26)
    at Object.propertyCreator (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:428:36)
    at initializeInstance (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:327:15)
    at /packages/Hydrogen/node_modules/mobx/lib/mobx.js:314:17)
    at ZMQKernel.setExecutionState (/packages/Hydrogen/lib/kernel-transport.js:33:24)
    at executeAction (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:616:22)
    at ZMQKernel.res (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:607:16)
    at ZMQKernel.onConnect (/packages/Hydrogen/lib/zmq-kernel.js:126:16)
    at emitThree (events.js:136:13)
    at Socket.emit (events.js:217:7)
    at Object.self._zmq.onMonitorEvent (/packages/Hydrogen/node_modules/zeromq/lib/index.js:552:12)
```

### Commands

```
     -1:25.1.0 application:add-project-folder (atom-pane.pane.active)
     -1:09.3.0 hydrogen-launcher:launch-terminal (input.hidden-input)
     -0:56.3.0 hydrogen-launcher:launch-jupyter-console (input.hidden-input)
     -0:48.8.0 hydrogen:run (ul.list-inline.tab-bar.inset-panel)
     -0:40.8.0 hydrogen:connect-to-remote-kernel (ul.list-inline.tab-bar.inset-panel)
     -0:36.5.0 hydrogen-launcher:launch-jupyter-console (ul.list-inline.tab-bar.inset-panel)
     -0:19 hydrogen-launcher:launch-jupyter-console-in-platformio-terminal (input.hidden-input)
     -0:10.8.0 hydrogen:run-all-above (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.16 
Hydrogen 2.9.0 
hydrogen-launcher 1.2.2 
hydrogen-python 0.0.8 
language-latex 1.2.0 
latex 0.50.2 
latex-autocomplete 1.1.1 
pdf-view 0.71.0 
platformio-ide-terminal 2.9.1 
python-debugger 0.2.0 
thesaurus 0.3.0 
```

Steps to reproduce.

Open python script in Atom editor(any .py file)
Run Hydrogen: Run All


OSX 10.14.5
Atom 1.38.1

**Comment by wadethestealth** [comment]
@areteaudio please open a new issue as your issue is most likely not related
