### ISSUE TITLE
Installation error on Windows: zeromq@5.1.0 install

### ISSUE THREAD

**Issue by pepicello** [nteract/hydrogen#1689]
**Description:**

Installation fails on windows, either via Atom GUI or cmd (apm). I noticed that the same error happens when running:

    npm install zeromq

**Steps to Reproduce:**

    apm install hydrogen --python [path-to-python2]

**Versions:**

OS Version: Windows 7 64bit
Atom Version: 1.38.2
Electron Version: 2.0.18
Node Version: 8.9.3
Hydrogen Version: 2.9.0 (latest)

**Logs:**

```
9678 verbose stack Error: zeromq@5.1.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
9678 verbose stack Exit status 1
9678 verbose stack     at EventEmitter.<anonymous> (C:\Users\[user]\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
9678 verbose stack     at emitTwo (events.js:126:13)
9678 verbose stack     at EventEmitter.emit (events.js:214:7)
9678 verbose stack     at ChildProcess.<anonymous> (C:\Users\[user]\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
9678 verbose stack     at emitTwo (events.js:126:13)
9678 verbose stack     at ChildProcess.emit (events.js:214:7)
9678 verbose stack     at maybeClose (internal/child_process.js:925:16)
9678 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
9679 verbose pkgid zeromq@5.1.0
9680 verbose cwd C:\Users\[user]\AppData\Local\Temp\apm-install-dir-119315-20252-tmh3rj.1qhh
9681 verbose Windows_NT 6.1.7601
9682 verbose argv "C:\\Users\\[user]\\AppData\\Local\\atom\\app-1.36.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\[user]\\AppData\\Local\\atom\\app-1.36.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\[user]\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\[user]\\.atom\\.apmrc" "install" "https://www.atom.io/api/packages/hydrogen/versions/2.9.0/tarball" "--runtime=electron" "--target=2.0.18" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--global-style" "--msvs_version=2015"
9683 verbose node v8.9.3
9684 verbose npm  v6.2.0
9685 error code ELIFECYCLE
9686 error errno 1
9687 error zeromq@5.1.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
9687 error Exit status 1
9688 error Failed at the zeromq@5.1.0 install script.
9688 error This is probably not a problem with npm. There is likely additional logging output above.
9689 verbose exit [ 1, true ]
```

Thank you!

**Comment by aviatesk** [comment]
Could you give me what `apm --version` says on your machine ?

**Comment by pepicello** [comment]
apm  2.1.7
npm  6.2.0
node 8.9.3 x64
atom 1.38.2
python
git
visual studio 2015

**Comment by aviatesk** [comment]
Seems fine. Can you try to reinstall with python 3 ?

**Comment by wadethestealth** [comment]
Python 2 has so known issues with hydrogen you can search all our issues to see info about it. Also just note that 2.10.2 is the latest version of hydrogen.

**Comment by pepicello** [comment]
I use Python 3 but I am using Python 2 for the installation as I otherwise get the same issues as in #1431. Regarding the version, I get the same results with 2.10.2.

I cannot seem to specify a specific version in apm, sadly, as this feature is still WIP (PR: https://github.com/atom/apm/pull/773), but I remember having managed to install Hydrogen 2.6.0 (using Python 2) on the same system. This error happens either when updating, or on a fresh install.

**Comment by wadethestealth** [comment]
Just a quick question. When you launch atom are you able to run any hydrogen commands and get the red bug as described in our troubleshooting guide?

**Comment by pepicello** [comment]
On the working version of Atom + Hydrogen 2.6.0, Hydrogen works just fine, but if I run the update via GUI, I get this:
![capture](https://user-images.githubusercontent.com/15961048/60452021-87592480-9c25-11e9-92dd-7b9e66e2853c.png)

With error message:

```
> zeromq@5.1.0 install C:\Users\gpepe\AppData\Local\Temp\apm-install-dir-11961-17348-jxs4ir.j0zq\node_modules\Hydrogen\node_modules\zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)


prebuild-install WARN install self signed certificate in certificate chain

Downloading libzmq for Windows
Download finished

C:\Users\[user]\AppData\Local\Temp\apm-install-dir-11961-17348-jxs4ir.j0zq\node_modules\Hydrogen\node_modules\zeromq>if not defined npm_config_node_gyp (node "C:\Users\[user]\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\[user]\AppData\Local\atom\app-1.38.2\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Users\\[user]\\AppData\\Local\\atom\\app-1.38.2\\resources\\app\\apm\\bin\\node.exe',
gyp verb cli   'C:\\Users\\[user]\\AppData\\Local\\atom\\app-1.38.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.9.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Python27\python.exe" in the PATH
gyp verb `which` failed Error: not found: C:\Python27\python.exe
gyp verb `which` failed     at getNotFoundError (C:\Users\[user]\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\[user]\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\[user]\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\[user]\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\[user]\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\[user]\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  C:\Python27\python.exe { Error: not found: C:\Python27\python.exe
gyp verb `which` failed     at getNotFoundError (C:\Users\[user]\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\[user]\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\[user]\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\[user]\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\[user]\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\[user]\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
gyp verb could not find "C:\Python27\python.exe". checking python launcher 
gyp verb could not find "C:\Python27\python.exe". guessing location 
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "C:\Python27\python.exe", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\[user]\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Users\[user]\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Users\[user]\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\[user]\\AppData\\Local\\atom\\app-1.38.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\[user]\\AppData\\Local\\atom\\app-1.38.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\[user]\AppData\Local\Temp\apm-install-dir-11961-17348-jxs4ir.j0zq\node_modules\Hydrogen\node_modules\zeromq
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\[user]\AppData\Local\Temp\apm-install-dir-11961-17348-jxs4ir.j0zq\package.json'
npm WARN react-rangeslider@2.2.0 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN vega-themes@2.3.0 requires a peer of vega@* but none is installed. You must install peer dependencies yourself.
npm WARN vega-lite@2.7.0 requires a peer of vega@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN apm-install-dir-11961-17348-jxs4ir.j0zq No description
npm WARN apm-install-dir-11961-17348-jxs4ir.j0zq No repository field.
npm WARN apm-install-dir-11961-17348-jxs4ir.j0zq No README data
npm WARN apm-install-dir-11961-17348-jxs4ir.j0zq No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq@5.1.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@5.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by wadethestealth** [comment]
I recommend reading nodejs/node-gyp#1337 and nodejs/node-gyp#1268. They both seem to have work arounds for now. Seems like gyp needs to update from Python 2.7 but seems like they don't want/care to.

**Comment by pepicello** [comment]
Most workarounds in those issues involve the use of Python 2. I seem to successfully do that in my case (original log in the first post), and I still get that error.

I have found a similar issue: https://github.com/nteract/hydrogen/issues/1352, but the solution does not work for me (I do not have that key in the registry).

I think the problem runs deeper than this, as the log looks almost identical to others I have found around other node packages:

- https://github.com/zeromq/zeromq.js/issues/177
- https://github.com/zeromq/zeromq.js/issues/245
- https://github.com/wavebox/waveboxapp/issues/454
- https://github.com/nodegit/nodegit/issues/1471

It looks like it is some issue due to the compiler/visual studio. Since that is something I cannot change from my side, I might give up with updating Hydrogen. Thank you for your help, anyway.

**Comment by wadethestealth** [comment]
If you don't have that key you should set it. That why the error is showing up because it can't find the key

**Comment by wadethestealth** [comment]
In any case you could always download the files from the repo and install. There are plenty of ways to upgrade

**Comment by wadethestealth** [comment]
> gyp verb check python checking for Python executable "C:\Python27\python.exe" in the PATH
≥ Error: Can't find Python executable "C:\Python27\python.exe", you can set the PYTHON env variable.

**Comment by n-riesco** [comment]
@pepicello The log in [this comment](https://github.com/nteract/hydrogen/issues/1689#issuecomment-507337098) reports node-gyp fails because `C:\Python27\python.exe` doens't exist. Is that so?

Would it be an option for you to install Python 2 in `C:\Python27\python.exe`?

You my be affected by https://github.com/atom/apm/issues/818 .

**Comment by pepicello** [comment]
Sorry for the confusion, the two issues mixed up! To clarify: I cannot choose the python version when trying to install via GUI. Since I use Python 3, the error from the GUI is related to not finding Python 2. But I am not attached to the GUI installation, so I tried to install from CLI, using apm, setting the python executable in apm, which I described in the first comment: https://github.com/nteract/hydrogen/issues/1689#issue-462645172. Here is a longer log of the same issue. For some reason, the console output showed more error than the log, so here is the console output:

<details>

```
gyp verb check python version `C:\Users\[user]\AppData\Local\Continuum\anaconda3\envs\py2\python.EXE
-c "import platform; print(platform.python_version());"` returned: "2.7.16\r\n"
gyp verb get node dir compiling against --target node version: 2.0.18
gyp verb command install [ '2.0.18' ]
gyp verb install input version string "2.0.18"
gyp verb install installing version: iojs-2.0.18
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: iojs-2.0.18
gyp verb build dir attempting to create "build" dir: C:\Users\[user]\AppData\Local\Temp\apm-install-d
ir-11963-6488-1jhv6l9.v57x\node_modules\Hydrogen\node_modules\zeromq\build
gyp verb build dir "build" dir needed to be created? C:\Users\[user]\AppData\Local\Temp\apm-install-d
ir-11963-6488-1jhv6l9.v57x\node_modules\Hydrogen\node_modules\zeromq\build
gyp verb build/config.gypi creating config file
gyp sill build/config.gypi { target_defaults:
gyp sill build/config.gypi    { cflags: [],
gyp sill build/config.gypi      default_configuration: 'Release',
gyp sill build/config.gypi      defines: [],
gyp sill build/config.gypi      include_dirs: [],
gyp sill build/config.gypi      libraries: [] },
gyp sill build/config.gypi   variables:
gyp sill build/config.gypi    { asan: 0,
gyp sill build/config.gypi      coverage: false,
gyp sill build/config.gypi      debug_devtools: 'node',
gyp sill build/config.gypi      debug_http2: false,
gyp sill build/config.gypi      debug_nghttp2: false,
gyp sill build/config.gypi      force_dynamic_crt: 0,
gyp sill build/config.gypi      host_arch: 'x64',
gyp sill build/config.gypi      icu_data_file: 'icudt59l.dat',
gyp sill build/config.gypi      icu_data_in: '..\\..\\deps/icu-small\\source/data/in\\icudt59l.dat',

gyp sill build/config.gypi      icu_endianness: 'l',
gyp sill build/config.gypi      icu_gyp_path: 'tools/icu/icu-generic.gyp',
gyp sill build/config.gypi      icu_locales: 'en,root',
gyp sill build/config.gypi      icu_path: 'deps/icu-small',
gyp sill build/config.gypi      icu_small: true,
gyp sill build/config.gypi      icu_ver_major: '59',
gyp sill build/config.gypi      node_byteorder: 'little',
gyp sill build/config.gypi      node_enable_d8: false,
gyp sill build/config.gypi      node_enable_v8_vtunejit: false,
gyp sill build/config.gypi      node_install_npm: true,
gyp sill build/config.gypi      node_module_version: 57,
gyp sill build/config.gypi      node_no_browser_globals: false,
gyp sill build/config.gypi      node_prefix: '/usr/local',
gyp sill build/config.gypi      node_release_urlbase: 'https://nodejs.org/download/release/',
gyp sill build/config.gypi      node_shared: false,
gyp sill build/config.gypi      node_shared_cares: false,
gyp sill build/config.gypi      node_shared_http_parser: false,
gyp sill build/config.gypi      node_shared_libuv: false,
gyp sill build/config.gypi      node_shared_openssl: false,
gyp sill build/config.gypi      node_shared_zlib: false,
gyp sill build/config.gypi      node_tag: '',
gyp sill build/config.gypi      node_use_bundled_v8: true,
gyp sill build/config.gypi      node_use_dtrace: false,
gyp sill build/config.gypi      node_use_etw: true,
gyp sill build/config.gypi      node_use_lttng: false,
gyp sill build/config.gypi      node_use_openssl: true,
gyp sill build/config.gypi      node_use_perfctr: true,
gyp sill build/config.gypi      node_use_v8_platform: true,
gyp sill build/config.gypi      node_without_node_options: false,
gyp sill build/config.gypi      openssl_fips: '',
gyp sill build/config.gypi      openssl_no_asm: 0,
gyp sill build/config.gypi      shlib_suffix: 'so.57',
gyp sill build/config.gypi      target_arch: 'x64',
gyp sill build/config.gypi      v8_enable_gdbjit: 0,
gyp sill build/config.gypi      v8_enable_i18n_support: 1,
gyp sill build/config.gypi      v8_enable_inspector: 1,
gyp sill build/config.gypi      v8_no_strict_aliasing: 1,
gyp sill build/config.gypi      v8_optimized_debug: 0,
gyp sill build/config.gypi      v8_promise_internal_field_count: 1,
gyp sill build/config.gypi      v8_random_seed: 0,
gyp sill build/config.gypi      v8_trace_maps: 0,
gyp sill build/config.gypi      v8_use_snapshot: true,
gyp sill build/config.gypi      want_separate_host_toolset: 0,
gyp sill build/config.gypi      nodedir: 'C:\\Users\\[user]\\.atom\\.node-gyp\\.node-gyp\\iojs-2.0.18
',
gyp sill build/config.gypi      copy_dev_lib: true,
gyp sill build/config.gypi      standalone_static_library: 1,
gyp sill build/config.gypi      access: '',
gyp sill build/config.gypi      allow_same_version: '',
gyp sill build/config.gypi      also: '',
gyp sill build/config.gypi      always_auth: '',
gyp sill build/config.gypi      audit: 'true',
gyp sill build/config.gypi      auth_type: 'legacy',
gyp sill build/config.gypi      bin_links: 'true',
gyp sill build/config.gypi      browser: '',
gyp sill build/config.gypi      ca: '',
gyp sill build/config.gypi      cache: 'C:\\Users\\[user]\\.atom\\.apm',
gyp sill build/config.gypi      cache_lock_retries: '10',
gyp sill build/config.gypi      cache_lock_stale: '60000',
gyp sill build/config.gypi      cache_lock_wait: '10000',
gyp sill build/config.gypi      cache_max: 'Infinity',
gyp sill build/config.gypi      cache_min: '10',
gyp sill build/config.gypi      cert: '',
gyp sill build/config.gypi      cidr: '',
gyp sill build/config.gypi      color: 'true',
gyp sill build/config.gypi      commit_hooks: 'true',
gyp sill build/config.gypi      depth: 'Infinity',
gyp sill build/config.gypi      description: 'true',
gyp sill build/config.gypi      dev: '',
gyp sill build/config.gypi      dist_url: 'https://atom.io/download/electron',
gyp sill build/config.gypi      dry_run: '',
gyp sill build/config.gypi      editor: 'notepad.exe',
gyp sill build/config.gypi      engine_strict: '',
gyp sill build/config.gypi      fetch_retries: '2',
gyp sill build/config.gypi      fetch_retry_factor: '10',
gyp sill build/config.gypi      fetch_retry_maxtimeout: '60000',
gyp sill build/config.gypi      fetch_retry_mintimeout: '10000',
gyp sill build/config.gypi      force: '',
gyp sill build/config.gypi      git: 'git',
gyp sill build/config.gypi      git_tag_version: 'true',
gyp sill build/config.gypi      global: '',
gyp sill build/config.gypi      globalconfig: 'C:\\Users\\[user]\\.atom\\.apm\\.apmrc',
gyp sill build/config.gypi      globalignorefile: 'C:\\Users\\[user]\\AppData\\Local\\atom\\app-1.38.
2\\resources\\app\\apm\\bin\\etc\\npmignore',
gyp sill build/config.gypi      global_style: 'true',
gyp sill build/config.gypi      group: '',
gyp sill build/config.gypi      ham_it_up: '',
gyp sill build/config.gypi      heading: 'npm',
gyp sill build/config.gypi      https_proxy: '',
gyp sill build/config.gypi      if_present: '',
gyp sill build/config.gypi      ignore_prepublish: '',
gyp sill build/config.gypi      ignore_scripts: '',
gyp sill build/config.gypi      init_author_email: '',
gyp sill build/config.gypi      init_author_name: '',
gyp sill build/config.gypi      init_author_url: '',
gyp sill build/config.gypi      init_license: 'ISC',
gyp sill build/config.gypi      init_module: 'C:\\Users\\[user]\\.atom\\.node-gyp\\.npm-init.js',
gyp sill build/config.gypi      init_version: '1.0.0',
gyp sill build/config.gypi      json: '',
gyp sill build/config.gypi      key: '',
gyp sill build/config.gypi      legacy_bundling: '',
gyp sill build/config.gypi      link: '',
gyp sill build/config.gypi      local_address: '',
gyp sill build/config.gypi      logs_max: '10',
gyp sill build/config.gypi      long: '',
gyp sill build/config.gypi      maxsockets: '50',
gyp sill build/config.gypi      message: '%s',
gyp sill build/config.gypi      metrics_registry: 'https://registry.npmjs.org/',
gyp sill build/config.gypi      node_gyp: 'C:\\Users\\[user]\\AppData\\Local\\atom\\app-1.38.2\\resou
rces\\app\\apm\\bin\\\\..\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp sill build/config.gypi      node_options: '',
gyp sill build/config.gypi      node_version: '8.9.3',
gyp sill build/config.gypi      no_proxy: '',
gyp sill build/config.gypi      offline: '',
gyp sill build/config.gypi      onload_script: '',
gyp sill build/config.gypi      only: '',
gyp sill build/config.gypi      optional: 'true',
gyp sill build/config.gypi      otp: '',
gyp sill build/config.gypi      package_lock: 'true',
gyp sill build/config.gypi      package_lock_only: '',
gyp sill build/config.gypi      parseable: '',
gyp sill build/config.gypi      prefer_offline: '',
gyp sill build/config.gypi      prefer_online: '',
gyp sill build/config.gypi      prefix: 'C:\\Users\\[user]\\AppData\\Local\\atom\\app-1.38.2\\resourc
es\\app\\apm\\bin',
gyp sill build/config.gypi      production: '',
gyp sill build/config.gypi      progress: '',
gyp sill build/config.gypi      read_only: '',
gyp sill build/config.gypi      rebuild_bundle: 'true',
gyp sill build/config.gypi      registry: 'https://registry.npmjs.org/',
gyp sill build/config.gypi      rollback: 'true',
gyp sill build/config.gypi      runtime: 'electron',
gyp sill build/config.gypi      save: 'true',
gyp sill build/config.gypi      save_bundle: '',
gyp sill build/config.gypi      save_dev: '',
gyp sill build/config.gypi      save_exact: '',
gyp sill build/config.gypi      save_optional: '',
gyp sill build/config.gypi      save_prefix: '^',
gyp sill build/config.gypi      save_prod: '',
gyp sill build/config.gypi      scope: '',
gyp sill build/config.gypi      scripts_prepend_node_path: 'warn-only',
gyp sill build/config.gypi      script_shell: '',
gyp sill build/config.gypi      searchexclude: '',
gyp sill build/config.gypi      searchlimit: '20',
gyp sill build/config.gypi      searchopts: '',
gyp sill build/config.gypi      searchstaleness: '900',
gyp sill build/config.gypi      send_metrics: '',
gyp sill build/config.gypi      shell: 'C:\\Windows\\system32\\cmd.exe',
gyp sill build/config.gypi      shrinkwrap: 'true',
gyp sill build/config.gypi      sign_git_commit: '',
gyp sill build/config.gypi      sign_git_tag: '',
gyp sill build/config.gypi      sso_poll_frequency: '500',
gyp sill build/config.gypi      sso_type: 'oauth',
gyp sill build/config.gypi      strict_ssl: '',
gyp sill build/config.gypi      tag: 'latest',
gyp sill build/config.gypi      tag_version_prefix: 'v',
gyp sill build/config.gypi      target: '2.0.18',
gyp sill build/config.gypi      timing: '',
gyp sill build/config.gypi      tmp: 'C:\\Users\\[user]\\AppData\\Local\\Temp',
gyp sill build/config.gypi      umask: '0000',
gyp sill build/config.gypi      unicode: '',
gyp sill build/config.gypi      unsafe_perm: 'true',
gyp sill build/config.gypi      update_notifier: 'true',
gyp sill build/config.gypi      usage: '',
gyp sill build/config.gypi      user: '',
gyp sill build/config.gypi      userconfig: 'C:\\Users\\[user]\\.atom\\.apmrc',
gyp sill build/config.gypi      user_agent: 'npm/6.2.0 node/v8.9.3 win32 x64',
gyp sill build/config.gypi      version: '',
gyp sill build/config.gypi      versions: '',
gyp sill build/config.gypi      viewer: 'browser' } }
gyp verb build/config.gypi writing out config file: C:\Users\[user]\AppData\Local\Temp\apm-install-di
r-11963-6488-1jhv6l9.v57x\node_modules\Hydrogen\node_modules\zeromq\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Users\[user]\AppData\Local\Temp\apm-install-dir-11963
-6488-1jhv6l9.v57x\node_modules\Hydrogen\node_modules\zeromq\config.gypi
gyp verb common.gypi checking for gypi file: C:\Users\[user]\AppData\Local\Temp\apm-install-dir-11963
-6488-1jhv6l9.v57x\node_modules\Hydrogen\node_modules\zeromq\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\[user]\AppData\Local\Continuum\anaconda3\envs\py2\python.EXE
gyp info spawn args [ 'C:\\Users\\[user]\\AppData\\Local\\atom\\app-1.38.2\\resources\\app\\apm\\node
_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\[user]\\AppData\\Local\\Temp\\apm-install-dir-11963-6488-1jhv6l9.v5
7x\\node_modules\\Hydrogen\\node_modules\\zeromq\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\[user]\\AppData\\Local\\atom\\app-1.38.2\\resources\\app\\apm\\node
_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\[user]\\.atom\\.node-gyp\\.node-gyp\\iojs-2.0.18\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\[user]\\.atom\\.node-gyp\\.node-gyp\\iojs-2.0.18',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\[user]\\AppData\\Local\\atom\\app-1.38.2\\resources\
\app\\apm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\[user]\\AppData\\Local\\Temp\\apm-install-dir-119
63-6488-1jhv6l9.v57x\\node_modules\\Hydrogen\\node_modules\\zeromq',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\[user]\\AppData\\Local\\Temp\\apm-install-dir-11963-6488-1jhv6l9.v5
7x\\node_modules\\Hydrogen\\node_modules\\zeromq\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\[user]\.atom\.node-gyp\.node-gyp\iojs-2.0.18
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp verb "Release" dir needed to be created? C:\Users\[user]\.atom\.node-gyp\.node-gyp\iojs-2.0.18\Re
lease
gyp verb copying "iojs.lib" for x64 C:\Users\[user]\.atom\.node-gyp\.node-gyp\iojs-2.0.18\Release\ioj
s.lib
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit c
ode: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\[user]\AppData\Local\atom\app-1.38.2\resources\ap
p\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\[user]\\AppData\\Local\\atom\\app-1.38.2\\resources\\app\\apm\\bin\\node
.exe" "C:\\Users\\[user]\\AppData\\Local\\atom\\app-1.38.2\\resources\\app\\apm\\node_modules\\node-g
yp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\[user]\AppData\Local\Temp\apm-install-dir-11963-6488-1jhv6l9.v57x\node_modules\
Hydrogen\node_modules\zeromq
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\[user]\AppData\Local\Temp\apm-insta
ll-dir-11963-6488-1jhv6l9.v57x\package.json'
npm WARN react-rangeslider@2.2.0 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed.
You must install peer dependencies yourself.
npm WARN vega-lite@2.7.0 requires a peer of vega@^3.0.0 || ^4.0.0 but none is installed. You must in
stall peer dependencies yourself.
npm WARN vega-themes@2.3.0 requires a peer of vega@* but none is installed. You must install peer de
pendencies yourself.
npm WARN apm-install-dir-11963-6488-1jhv6l9.v57x No description
npm WARN apm-install-dir-11963-6488-1jhv6l9.v57x No repository field.
npm WARN apm-install-dir-11963-6488-1jhv6l9.v57x No README data
npm WARN apm-install-dir-11963-6488-1jhv6l9.v57x No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq@5.1.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && n
ode-gyp rebuild)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zeromq@5.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

</details>

As you can see, Python 2 is picked up, but the installation still fails.
Among the extra interesting lines in this log, this one seems to indicates a compiler error:

```
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit c
ode: 1
```

**Comment by n-riesco** [comment]
OK, it looks like `node-gyp@3.4.0` is now choking on your installation of VS build tools.

The [usual recommendation](https://github.com/nodejs/node-gyp#on-windows) is to install `npm install --global --production windows-build-tools` (though, this hasn't always worked for me).

**Comment by pepicello** [comment]
> 
> 
> OK, it looks like `node-gyp@3.4.0` is now choking on your installation of VS build tools.
> 
> The [usual recommendation](https://github.com/nodejs/node-gyp#on-windows) is to install `npm install --global --production windows-build-tools` (though, this hasn't always worked for me).

This did not work, but I have eventually fixed it by re-installing VS and VS C++ Build Tools. Thanks anyway for the help!
