### ISSUE TITLE
Failed to activate hydrogen after installation error (hydrogen 2.10.2)

### ISSUE THREAD

**Issue by Tbosa** [nteract/hydrogen#1690]
**Description:**  

Since I installed the last hydrogen version 2.10.2, I can't run any python code.
Furthermore, I did not get this error using previous hydrogen version 2.10.0.

To be complete, I think I did a mistake while installing hydrogen 2.10.2 because it raised me an error during the installation and I just overlooked it and then restarted atom. 
This installation failure might be the same than the one described there #1689

**Steps to Reproduce:**

1. Open ``.py`` file
2. ``Ctrl+enter`` to run any line code

**Versions:**

OS Version : Microsoft Windows 10.0.17134.829

Atom : 1.38.2
Electron : 2.0.18
Chrome : 61.0.3163.100
Node : 8.9.3

hydrogen version : 2.10.2

**Plugins:**

Do you have any Hydrogen plugins installed and active?
- [X] hydrogen-python 0.0.8
- [ ] Hydrogen Launcher
- [ ] Data Explorer

**Logs:**  

Failed to activate the Hydrogen package

### Stack Trace
```
Cannot find module './lib/parse'

Error: Cannot find module './lib/parse'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.38.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:155156)
    at Module.require (/app.asar/static/index.js:53:43)
    at require (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:146462)
    at /packages/Hydrogen/node_modules/spawnteract/node_modules/cross-spawn/index.js:4:15)
    at /packages/Hydrogen/node_modules/spawnteract/node_modules/cross-spawn/index.js:41:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:146462)
    at /packages/Hydrogen/node_modules/spawnteract/node_modules/execa/index.js:5:20)
    at /packages/Hydrogen/node_modules/spawnteract/node_modules/execa/index.js:368:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:146462)
    at /packages/Hydrogen/node_modules/spawnteract/index.js:35:15)
    at /packages/Hydrogen/node_modules/spawnteract/index.js:228:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
```
### Non-Core Packages

```
file-icons 2.1.33 
highlight-selected 0.16.0 
Hydrogen 2.10.2 
hydrogen-python 0.0.8 
language-r 0.4.2 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
python-autopep8 0.1.3 
```

**Comment by aviatesk** [comment]
Hi, did you try to re-install Hydrogen ?
If not, please do so.

**Comment by Tbosa** [comment]
First I tried to uninstall it using apm command in CLI : ``apm uninstall hydrogen``

__Output__:
``Uninstalling hydrogen failed``  
``Failed to delete hydrogen: EPERM: operation not permitted, unlink 'C:\Users\barbo\.atom\packages\hydrogen\node_modules\zeromq\build\Release\zmq.node'``

**Comment by aviatesk** [comment]
Not sure why this kind of permission prob happens here, but you can manually delete the whole Hydrogen directory in `.atom/packages` and then run `apm install hydrogen`

**Comment by Tbosa** [comment]
It works. Thank you for your time @aviatesk

**Comment by mechloz** [comment]
> Not sure why this kind of permission prob happens here, but you can manually delete the whole Hydrogen directory in `.atom/packages` and then run `apm install hydrogen`

having the exact same issue but this wont work for me. any suggestions?

**Comment by wadethestealth** [comment]
@mechloz If you are experiencing,

>EPERM: operation not permitted, unlink 'C:\Users\barbo\.atom\packages\hydrogen\node_modules\zeromq\build\Release\zmq.node

Then you have some program using or holding this resource, most commonly disabling antivirus solves this, but this could be caused by other instances of atom. Try closing all programs plus antivirus to uninstall. If you are facing the first issue there is a problem with your connectivity or your atom downloading that dependency
