### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '$ATOM_HOME/packages\Hydrogen\node_modul...

### ISSUE THREAD

**Issue by aniljezz** [nteract/hydrogen#1694]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.10.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\pc\.atom\packages\Hydrogen\node_modules\lodash\lodash.js'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat 'C:\Users\pc\.atom\packages\Hydrogen\node_modules\lodash\lodash.js'
    at Object.realpathSync (fs.js:1661:15)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:336:29)
    at toRealPath (module.js:163:13)
    at tryFile (module.js:159:22)
    at tryPackage (module.js:140:10)
    at Function.Module._findPath (module.js:217:20)
    at Module._resolveFilename (module.js:541:25)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.38.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:155156)
    at Module.require (/app.asar/static/index.js:53:43)
    at require (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:146462)
    at /packages/Hydrogen/lib/main.js:15:15)
    at /packages/Hydrogen/lib/main.js:707:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:1:688769)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:3550661)
    at Package.activateConfig (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:3540020)
    at PackageManager.t.exports.PackageManager.packageHasSettings (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:928165)
    at PackageCard.hasSettings (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:14:2562012)
    at PackageCard.updateSettingsState (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:14:2552292)
    at PackageCard.updateInterfaceState (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:14:2552115)
    at ~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:14:2560245
    at ~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:14:2562263
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:1206583)
    at Emitter.emit (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:1208024)
    at PackageManager.t.exports.PackageManager.emitPackageEvent (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:937622)
    at ~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:934754
    at r (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:929284)
    at n (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:14:1119384)
    at ChildProcess.o.process.on.e (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:14:1119590)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
```

### Non-Core Packages

```
Hydrogen 2.10.2 
```

**Comment by wadethestealth** [comment]
Please try installing hydrogen via the GUI or `apm install hydrogen` which ever you haven't tried, but to be safe I would try to install again same way as before

**Comment by wadethestealth** [comment]
Has grown stale
