### ISSUE TITLE
Hydrogen install throws deprecation error.

### ISSUE THREAD

**Issue by Helveg** [nteract/hydrogen#1708]
### Prerequisites

* [x] Have you checked the solutions in our [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) for common problems ?
* [x] Have you checked that your issue [isn't already filed](https://github.com/nteract/hydrogen/issues) ?

### Description

I clicked the install button in the Install Packages Settings pane.

### Steps to Reproduce

1. Click install

### Versions

OS version:
Windows 10

> `atom --version`

```
Atom    : 1.38.2
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

> `apm --version`

```
npm  6.2.0
node 8.9.3 x64
atom 1.38.2
python
git 2.21.0.windows.1
visual studio
```

Hydrogen version:

2.10.3

### Plugins

Have you installed and activated any of the Hydrogen plugins below ?
- [ ] hydrogen-python
- [ ] Hydrogen Launcher
- [ ] Data Explorer

### Logs

```
> zeromq@5.1.0 install C:\Users\robin\AppData\Local\Temp\apm-install-dir-119612-14548-89rboi.tqmg6\node_modules\Hydrogen\node_modules\zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)


prebuild-install WARN install getaddrinfo ENOTFOUND github-production-release-asset-2e65be.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com:443

Downloading libzmq for Windows

npm WARN deprecated json-parser@1.1.5: `json-parser` is deprecated. Please use `comment-json` instead
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND github-production-release-asset-2e65be.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com:443
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\robin\AppData\Local\Temp\apm-install-dir-119612-14548-89rboi.tqmg6\package.json'
npm WARN react-rangeslider@2.2.0 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN vega-themes@2.3.0 requires a peer of vega@* but none is installed. You must install peer dependencies yourself.
npm WARN vega-lite@2.7.0 requires a peer of vega@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN apm-install-dir-119612-14548-89rboi.tqmg6 No description
npm WARN apm-install-dir-119612-14548-89rboi.tqmg6 No repository field.
npm WARN apm-install-dir-119612-14548-89rboi.tqmg6 No README data
npm WARN apm-install-dir-119612-14548-89rboi.tqmg6 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq@5.1.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@5.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\robin\.atom\.apm\_logs\2019-07-12T09_38_46_504Z-debug.log

1,132,909
Hydrogen2.10.3Run code interactively, inspect data, and plot. All the power of Jupyter kernels, inside your favorite text editor.
nteract
Install
26,302
hydrogen-python0.0.8Python language-specific extensions for hydrogen
nikitakit
Install
1,209
hydrogen-auth0.0.2A brute-force approach to remote gateway authentication
nikitakit
Install
3,944
hydrogen-xdbg0.0.4Improved live coding for Python 3
nikitakit
Install
33,434
hydrogen-launcher1.2.2Launch terminals and jupyter consoles connected to hydrogen
lgeiger
Install
122
hydrogen-cell-separator0.4.1Atom package to improve identification of cells by separating them with a horizontal line.
jhabriel
Install
2,013
greyatom-hydrogen1.9.0Run code and get results inline using Jupyter kernels like IPython, IJulia, and iTorch
greyatom-edu-tech
Install
79
cell-navigation0.1.0Navigate, move and select code cells defined by `# %%`. Enhance your coding experience with Hydrogen and Jupytext.
hoishing
Install
2,607
nitrogen0.1.12Nitrogen: Nitrous meets Atom
nitrous-io
Install
7,062
data-explorer0.7.0Automatic data visualization with the nteract data-explorer
BenRussert
Install
313
cert-tweaks0.1.0Add extra certificates to Atom's trust store
nikitakit
Install
43
language-nitrogen0.2.0Nitrogen language support in Atom
nitrogen-lang
Install
68
language-nitrogen-vm0.1.4Nitrogen VM language support for Atom
jonahisadev
Install
1,716
atom-hydra0.2.10Live coding hydra from within atom
ojack
Install
64
doge-img0.4.0Simple way to add doge to your website
DemSquirrel
Install
3,775
doge0.1.3such atom. wow.
tylerl0706
Install
894
ipynb0.2.0Reserved package
rgbkrk
Install
1,093
drop-up0.5.0Drag and drop image files to editor, upload and insert link, GitHub style.
sikhapol
Install
4,141
drag-drop-text0.1.4Drag and drop text (and cut/copy/paste) with only the mouse.
mark-hahn
Install
12
ProgDT1.0.1Gets the Programmer's Date &&|| Time!
DocCodes
Install
75
gammboge4.2.0JavaScript autocompletion and suggestion
Gabriel-Mtz
Install
420
js-test-gen-atom0.2.0Js-test-gen-atom generates test templates from your default/named exports.
js-test-gen
Install
92
droiuby0.0.2An atom package for the Droiuby framework
jedld
Install
54
cursor-drop0.2.2Create multiple cursors via the keyboard
ahuth
Install
8,173
android0.1.0Android development package for Atom
dalinaum
Install
66
eyedrops0.1.2Blurs editor tabs to protect the guilty
GEOFBOT
Install
5,951
language-weave0.6.4Support for Weave.jl and Pweave
JunoLab
Install
157
abjadcompile0.1.18Render algorithmically generated music scores in Atom.
jefftrevino
Install
255
atom-together0.3.1Work together via IP
MonochromeSun
Install
833
dsl-progress0.28.0A package for develop with 4GL Progress
akaytatsu
Install
Featured Packages
1,132,909
Hydrogen2.10.3Run code interactively, inspect data, and plot. All the power of Jupyter kernels, inside your favorite text editor.
nteract
Install
614,629
atom-clock0.1.17Display a customizable clock in the status bar.
b3by
Install
97,435
hey-pane1.1.2Atom Plugin to enlarge the active pane, either with a shortcut or with a super handy follow mode. Inspired by Origami for Sublime Text.
timomeh
Install
57,852
scroll-through-time0.3.1Two fingers scroll moves through time instead of space
mathieudutour
Install
803,712
teletype0.13.4Share your workspace with team members and collaborate on code in real time
atom
Install
76,323
zentabs0.8.9Keep the opened tabs amount below specified limit
ArnaudRinquin
Install
1,065,660
atom-material-syntax1.0.8A dark syntax theme for Atom that uses Google's Material Design color palette
silvestreh
Install
1,700,683
atom-material-ui2.1.3A dynamic UI theme for Atom that follows Google's Material Design Guidelines
atom-material
Install
Git
GitHub
Unstaged Changes
Stage All
Staged Changes
Unstage All
See All Staged Changes
 
Commit message
     

Commit to 3.7-rework
72
robin.deschepper93@gmail.com's avatar'
exclude .pyc files from the repository
Undo
41m
scasali84@gmail.com's avatar'
structure file and NEST
4d
scasali84@gmail.com's avatar'
first upload - first example files
4d
scasali84@gmail.com's avatar'
Initial commit
4d
00Settings
3.7-reworkPublishGitHubGit (0)5 updates
```

### Expected behavior

The installation to succeed

**Comment by BenRussert** [comment]
`Error: getaddrinfo ENOTFOUND github-production-release-asset-2e65be.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com:443
    at errnoException (dns.js:50:10)`

Wild guess, but are you on a corporate network or someplace you might be blocked by a firewall? Do other atom packages install properly?

**Comment by Helveg** [comment]
On a university network yes! That might be possible, we also couldn't
download Git, another amazonaws server that we couldn't reach. I'll let you
know once I can get access from another network.

Thanks

**Comment by Helveg** [comment]
That was the issue, thanks.

**Comment by wesinator** [comment]
Having the same issue, weirdly on ISP network that appears to be using Google DNS 
https://issuetracker.google.com/issues/144182685
