### ISSUE TITLE
Unexpected Token L

### ISSUE THREAD

**Issue by kescobo** [nteract/hydrogen#171]
[Enter steps to reproduce below:]

1. Open python or julia file
2. `alt-cmd-enter` or command pallet - `Hydrogen: Run`

After this, hydrogen is disabled and won't run without restarting.

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.4
**Thrown From**: [Hydrogen](https://github.com/willwhitney/hydrogen) package, v0.7.0

### Stack Trace

Failed to activate the Hydrogen package

```
At Unexpected token L

SyntaxError: Unexpected token L
    at Object.parse (native)
    at Object.<anonymous> (/Users/KBLaptop/.atom/packages/hydrogen/lib/kernel-manager.coffee:11:22)
    at Object.memoized [as getAvailableKernels] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7912:27)
    at /Users/KBLaptop/.atom/packages/hydrogen/lib/autocomplete-provider.coffee:6:37
    at Object.<anonymous> (/Users/KBLaptop/.atom/packages/hydrogen/lib/autocomplete-provider.coffee:5:41)
    at Object.<anonymous> (/Users/KBLaptop/.atom/packages/hydrogen/lib/autocomplete-provider.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/KBLaptop/.atom/packages/hydrogen/lib/main.coffee:13:24)
    at Object.<anonymous> (/Users/KBLaptop/.atom/packages/hydrogen/lib/main.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:172:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:800:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
```

### Commands

```
     -0:40.7.0 core:save (atom-text-editor.editor.is-focused)
  7x -0:15.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:03.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:02.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:00.8.0 hydrogen:run-and-move-down (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "Hydrogen": {
    "grammarToKernel": "{\"python\":\"Python 3\"}"
  }
}
```

### Installed Packages

```coffee
# User
Hydrogen, v0.7.0
jupyter-notebook, v0.0.9
language-julia, v0.5.0

# Dev
No dev packages
```

**Comment by slavaGanzin** [comment]
@kescobo Here we go again. Please paste here output of this two commands:
```jupyter kernelspec list --json
ipython kernelspec list --json```

I think I should add ignoring of stderr.

**Comment by kescobo** [comment]
Heh, yeah - no kidding. It worked for a sec after I upgraded, then the next day... Ugh. Sorry for the bother. 

```
KBonham:~ KBLaptop$ jupyter kernelspec list --json
{
  "kernelspecs": {
    "julia-0.5": {
      "resources_dir": "/Users/KBLaptop/Library/Jupyter/kernels/julia-0.5",
      "spec": {
        "env": {},
        "argv": [
          "/Users/KBLaptop/julia/usr/bin/julia",
          "-i",
          "-F",
          "/Users/KBLaptop/.julia/v0.5/IJulia/src/kernel.jl",
          "{connection_file}"
        ],
        "language": "julia",
        "display_name": "Julia 0.5.0-dev"
      }
    },
    "julia-0.4": {
      "resources_dir": "/Users/KBLaptop/Library/Jupyter/kernels/julia-0.4",
      "spec": {
        "env": {},
        "argv": [
          "/Users/KBLaptop/julia/usr/bin/julia",
          "-i",
          "-F",
          "/Users/KBLaptop/.julia/v0.4/IJulia/src/kernel.jl",
          "{connection_file}"
        ],
        "language": "julia",
        "display_name": "Julia 0.4.3-pre"
      }
    },
    "python3": {
      "resources_dir": "/Users/KBLaptop/Library/Jupyter/kernels/python3",
      "spec": {
        "env": {},
        "argv": [
          "/Users/KBLaptop/miniconda3/bin/python",
          "-m",
          "ipykernel",
          "-f",
          "{connection_file}"
        ],
        "language": "python",
        "display_name": "Python 3"
      }
    }
  }
}
```
And... 
```
{
  "kernelspecs": {
    "julia-0.4": {
      "spec": {
        "display_name": "Julia 0.4.3-pre",
        "env": {},
        "argv": [
          "/Users/KBLaptop/julia/usr/bin/julia",
          "-i",
          "-F",
          "/Users/KBLaptop/.julia/v0.4/IJulia/src/kernel.jl",
          "{connection_file}"
        ],
        "language": "julia"
      },
      "resources_dir": "/Users/KBLaptop/Library/Jupyter/kernels/julia-0.4"
    },
    "python3": {
      "spec": {
        "display_name": "Python 3",
        "env": {},
        "argv": [
          "/Users/KBLaptop/miniconda3/bin/python",
          "-m",
          "ipykernel",
          "-f",
          "{connection_file}"
        ],
        "language": "python"
      },
      "resources_dir": "/Users/KBLaptop/Library/Jupyter/kernels/python3"
    },
    "julia-0.5": {
      "spec": {
        "display_name": "Julia 0.5.0-dev",
        "env": {},
        "argv": [
          "/Users/KBLaptop/julia/usr/bin/julia",
          "-i",
          "-F",
          "/Users/KBLaptop/.julia/v0.5/IJulia/src/kernel.jl",
          "{connection_file}"
        ],
        "language": "julia"
      },
      "resources_dir": "/Users/KBLaptop/Library/Jupyter/kernels/julia-0.5"
    }
  }
}
```

**Comment by n-riesco** [comment]
Please, could you open the dev console in atom (shift-ctrl-i), run the following code and see whether you get the same error?

```
> var out = require("child_process").spawnSync('jupyter',['kernelspec','list', '--json']).stdout.toString()
undefined
> JSON.parse(out)
```

**Comment by kescobo** [comment]
Doesn't seem to.

```
>  var out = require("child_process").spawnSync('jupyter',['kernelspec','list', '--json']).stdout.toString()
<- undefined
```
```
>  JSON.parse(out)
<- Object {kernelspecs: Object}
     kernelspecs: Object
     __proto__: Object
```

Looks like I can expand `kernelspecs` and `__proto__`, not sure how to send along all of the info.

**Comment by n-riesco** [comment]
No need to post all the info. The fact that doesn't throws an error is confusing enough.

Your first log indicates that the error is happening somewhere in [this lines](https://github.com/nteract/hydrogen/blob/80874a9a2141e5f506ae1d28c678e10edc31c8f1/lib/kernel-manager.coffee#L9-L14) more specifically in the `parse` function.

Could you confirm that you can still reproduce this issue despite the above code running fine?

**Comment by kescobo** [comment]
Confirmed. I opened a new python file, typed `2+2` and then `Hydrogen: Run` and it pops up.

**Comment by n-riesco** [comment]
@kescobo If you need a workaround for the time being, I would revert to Hydrogen version 0.6.5:

```
$ apm install Hydrogen@0.6.5
Installing Hydrogen@0.6.5 to /home/user/.atom/packages ✓
```

**Comment by kescobo** [comment]
That works, though now I need to figure out a way to select the python kernel again :-).

**Comment by slavaGanzin** [comment]
Will fix when merged https://github.com/nteract/hydrogen/pull/177

**Comment by n-riesco** [comment]
@kescobo Hydrogen v0.7.1 has just been released. Could you test whether it works in your machine?

**Comment by n-riesco** [comment]
#177 already merged

**Comment by kescobo** [comment]
@n-riesco Sorry I missed your comment from a month ago - it just popped up again with your most recent comment.

Just installed 0.7.2 and python kernels works like a charm (including switching between 2 and 3). I've having issues with my julia kernel but I'm pretty sure that's on my end. Will open up another issue if I can't solve it.

**Comment by n-riesco** [comment]
@kescobo Thanks!
