### ISSUE TITLE
itorch hydrogen does not work after update

### ISSUE THREAD

**Issue by szagoruyko** [nteract/hydrogen#172]
Trying to run hydrogen after update results in this:

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [Hydrogen](https://github.com/willwhitney/hydrogen) package, v0.7.0

### Stack Trace

Failed to activate the Hydrogen package

```
At Cannot read property 'toString' of null

TypeError: Cannot read property 'toString' of null
  at Object.<anonymous> (/Users/szagoruyko/.atom/packages/Hydrogen/lib/kernel-manager.coffee:10:88)
  at Object.memoized [as getAvailableKernels] (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7912:27)
  at /Users/szagoruyko/.atom/packages/Hydrogen/lib/autocomplete-provider.coffee:6:37
  at Object.<anonymous> (/Users/szagoruyko/.atom/packages/Hydrogen/lib/autocomplete-provider.coffee:5:41)
  at Object.<anonymous> (/Users/szagoruyko/.atom/packages/Hydrogen/lib/autocomplete-provider.coffee:1:1)
  at Module._compile (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .coffee] (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/szagoruyko/.atom/packages/Hydrogen/lib/main.coffee:13:24)
  at Object.<anonymous> (/Users/szagoruyko/.atom/packages/Hydrogen/lib/main.coffee:1:1)
  at Module._compile (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .coffee] (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
  at Package.module.exports.Package.activateNow (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/package.js:172:16)
  at /opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/package.js:800:25
  at Function.module.exports.Emitter.simpleDispatch (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
  at CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
  at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/opt/homebrew-cask/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1013:28)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)

```

### Commands

```
     -0:01.1.0 hydrogen:run (atom-text-editor.editor.is-focused.vim-mode.normal-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "nuclide-remote-projects",
      "tree-view"
    ]
  },
  "Hydrogen": {}
}
```

### Installed Packages

```coffee
# User
Hydrogen, v0.7.0
autocomplete-bibtex, v0.6.2
language-lua, v0.9.4
language-matlab, v0.2.0
latex, v0.29.0
latexer, v0.2.9
markdown-preview, v0.157.3
minimap, v4.19.0
nuclide, v0.114.0
vim-mode, v0.64.0

# Dev
No dev packages
```

**Comment by n-riesco** [comment]
This bug is **"almost"** fixed in [this commit](https://github.com/nteract/hydrogen/commit/2d372b5b5b7bfc86bad8dd34de9371f661de7582).

It still throws if `jupyter` and `ipython` aren't installed.

CC @lgeiger

**Comment by slavaGanzin** [comment]
@szagoruyko do you have ipython in your PATH?

```$ ipython --version```

**Comment by szagoruyko** [comment]
@slavaGanzin @n-riesco thanks, adding anaconda/bin to PATH solves the issue.

**Comment by slavaGanzin** [comment]
This should be fixed when dependecies.js would be released.

@szagoruyko Thanks for your patience
