### ISSUE TITLE
Uncaught Error: Cannot find module './kernel-picker'

### ISSUE THREAD

**Issue by DanielTeal** [nteract/hydrogen#1720]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.0 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Home
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.10.3

### Stack Trace

Uncaught Error: Cannot find module './kernel-picker'

```
At internal/modules/cjs/loader.js:604

Error: Cannot find module './kernel-picker'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.39.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (<embedded>:11:155394)
    at Module.require (/app.asar/static/index.js:60:43)
    at require (<embedded>:11:146719)
    at /packages/Hydrogen/lib/main.js:25:21)
    at /packages/Hydrogen/lib/main.js:707:3)
    at Module.get_Module._compile (<embedded>:11:147410)
    at Object.value [as .js] (<embedded>:11:150958)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:71:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (<embedded>:1:725913)
    at Package.requireMainModule (<embedded>:11:3553599)
    at Package.activateConfig (<embedded>:11:3542887)
    at PackageManager.packageHasSettings (<embedded>:11:929110)
    at PackageCard.hasSettings (<embedded>:14:2570026)
    at PackageCard.updateSettingsState (<embedded>:14:2560306)
    at PackageCard.updateInterfaceState (<embedded>:14:2560129)
    at <embedded>:14:2568259
    at <embedded>:14:2570277
    at Function.simpleDispatch (<embedded>:11:1207528)
    at Emitter.emit (<embedded>:11:1208969)
    at PackageManager.emitPackageEvent (<embedded>:11:938567)
    at <embedded>:11:935699
    at r (<embedded>:11:930229)
    at n (<embedded>:14:1127227)
    at ChildProcess.o.process.on.e (<embedded>:14:1127433)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)

```

### Commands

```
     -8:54.3.0 application:new-file (div.am-panel.tool-panel.panel-bottom.native-key-bindings.script-view)
     -8:34.6.0 welcome:show (input.hidden-input)
     -8:22.4.0 core:confirm (input.hidden-input)
  3x -5:27.3.0 core:backspace (input.hidden-input)
  2x -5:21.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.2.6 
autocomplete-python 1.14.1 
busy-signal 2.0.1 
file-icons 2.1.33 
Hydrogen 2.10.3 
intentions 1.1.5 
linter 2.3.0 
linter-flake8 2.4.0 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-find-and-replace 4.5.2 
predawn-syntax 1.0.4 
python-autopep8 0.1.3 
script 3.18.1 
```

**Comment by wadethestealth** [comment]
I am assuming this is just a bad install. Try uninstalling and reinstalling. You should try both atom GUI and apm cli

**Comment by DanielTeal** [comment]
Atom has it labeled as installed, and it won't uninstall either.

**Comment by wadethestealth** [comment]
If it won't uninstall, just delete it from your packages folder also if when you try to load hydrogen and there is a red bug button on the bottom bar use that as described in our troubleshooting documentation
