### ISSUE TITLE
Uncaught Error: Cannot find module './autocomplete-provider'

### ISSUE THREAD

**Issue by abhinavkavuri** [nteract/hydrogen#1722]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.10.3

### Stack Trace

Uncaught Error: Cannot find module './autocomplete-provider'

```
At internal/modules/cjs/loader.js:604

Error: Cannot find module './autocomplete-provider'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.39.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:155394)
    at Module.require (/app.asar/static/index.js:60:43)
    at require (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:146719)
    at /packages/Hydrogen/lib/main.js:39:30)
    at /packages/Hydrogen/lib/main.js:638:24)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:147410)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:150958)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:71:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:1:712926)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:3553046)
    at Package.activateConfig (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:3542334)
    at PackageDetailView.activateConfig (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:14:823126)
    at PackageDetailView.completeInitialization (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:14:821824)
    at PackageDetailView.loadPackage (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:14:822058)
    at new PackageDetailView (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:14:818644)
    at SettingsView.getOrCreatePanel (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:951189)
    at SettingsView.showPanel (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:951910)
    at HTMLButtonElement.clickHandler (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:14:2556030)
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 2.0.1 
Hydrogen 2.10.3 
intentions 1.1.5 
linter 2.3.0 
linter-ui-default 1.7.1 
```

**Comment by wadethestealth** [comment]
Similar to #1720. I am assuming this is just a bad install. Try uninstalling and reinstalling. You should try both atom GUI and apm cli

**Comment by abhinavkavuri** [comment]
@wadethestealth Worked like a charm 👍. Had to manually delete Hydrogen from packages folder and re-install Atom again, then reinstalled Ipython via pip and it worked 💯
