### ISSUE TITLE
Altair plotting broken as of Altair v3

### ISSUE THREAD

**Issue by andybrnr** [nteract/hydrogen#1730]
### Description

Altair 3.x appears to have made some architectural changes that break rendering with Hydrogen. Believe that the root of the issue is in changes made in the newer version of Vega-Lite. I've verified that a conda environment with Altair 2.2.2 generates working plots in a Jupyter notebook and with Hydrogen. If I upgrade the environment to Altair to 3.1.0, plots no longer render and an error is returned (details below).

### Steps to Reproduce

1) Create a conda environment with the latest version of altair, e.g. follow directions here: https://altair-viz.github.io/getting_started/installation.html#quick-start-altair-notebook

2) Open a new .py file in Atom, example code
```
import altair as alt
from vega_datasets import data

# for the notebook only (not for JupyterLab) run this command once per session
alt.renderers.enable('notebook')

iris = data.iris()

alt.Chart(iris).mark_point().encode(
    x='petalLength',
    y='petalWidth',
    color='species'
)
```

3) Connect to the conda environment and run the code block. On my system, this throws the following error:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.isAbsolute (path.js:1146:5)
    at Function.Module._findPath (internal/modules/cjs/loader.js:229:12)
    at Module._resolveFilename (internal/modules/cjs/loader.js:599:25)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155394)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:60:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146719)
    at eval (eval at runCodeHere (/Users/andrewberner/.atom/packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/javascript.js:16:16), <anonymous>:8:1)
    at runCodeHere (/Users/andrewberner/.atom/packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/javascript.js:16:16)
    at JavaScript.componentDidMount (/Users/andrewberner/.atom/packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/javascript.js:34:9)
    at Vh (/Users/andrewberner/.atom/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:216:198)
    at Zh (/Users/andrewberner/.atom/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:220:182)
    at /Users/andrewberner/.atom/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:250:268
    at Object.exports.unstable_runWithPriority (/Users/andrewberner/.atom/packages/Hydrogen/node_modules/scheduler/cjs/scheduler.production.min.js:18:163)
    at Fi (/Users/andrewberner/.atom/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:250:203)
    at Di (/Users/andrewberner/.atom/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:249:383)
    at Yh (/Users/andrewberner/.atom/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:248:144)
    at Gi (/Users/andrewberner/.atom/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:250:420)
    at reactionScheduler (/Users/andrewberner/.atom/packages/Hydrogen/node_modules/mobx/lib/mobx.js:1807:47)
    at runReactions (/Users/andrewberner/.atom/packages/Hydrogen/node_modules/mobx/lib/mobx.js:1783:5)
    at endBatch (/Users/andrewberner/.atom/packages/Hydrogen/node_modules/mobx/lib/mobx.js:1486:9)
    at endAction (/Users/andrewberner/.atom/packages/Hydrogen/node_modules/mobx/lib/mobx.js:660:5)
    at executeAction (/Users/andrewberner/.atom/packages/Hydrogen/node_modules/mobx/lib/mobx.js:627:13)
    at OutputStore.res (/Users/andrewberner/.atom/packages/Hydrogen/node_modules/mobx/lib/mobx.js:607:16)
    at /Users/andrewberner/.atom/packages/Hydrogen/lib/main.js:415:25
    at /Users/andrewberner/.atom/packages/Hydrogen/lib/kernel.js:381:9
    at /Users/andrewberner/.atom/packages/Hydrogen/lib/kernel.js:312:9
    at wrappedOnResults (/Users/andrewberner/.atom/packages/Hydrogen/lib/kernel.js:78:5)
    at future.onIOPub (/Users/andrewberner/.atom/packages/Hydrogen/lib/ws-kernel.js:49:7)
```

4) Identical error can be generated with the underlying vega-lite spec directly from ipyvega:
```
import pandas as pd
from vega import VegaLite
from vega_datasets import data

df = data.cars()

VegaLite({
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "mark": "point",
  "encoding": {
    "y": {"type": "quantitative", "field": "Acceleration"},
    "x": {"type": "quantitative", "field": "Horsepower"}
  }
}, df)
```

### Versions

OS version:
OS X Mojave

```
Atom    : 1.39.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
```

```
apm  2.2.4
npm  6.2.0
node 8.9.3 x64
atom 1.39.1
python 3.6.8
git 2.20.1
```

Hydrogen version:
2.10.3

**Comment by wadethestealth** [comment]
2.10.3 doesnt support Altair 3

**Comment by andybrnr** [comment]
Sorry, should've searched the closed issues more carefully - see this was picked up a month ago in #1700. Appreciate the response.

**Comment by rpalloni** [comment]
> 2.10.3 doesnt support Altair 3. It will in 2.11.0

Hello, I'm in hydrogen 2.14 / atom 1.44 / Ubuntu 18.04 / python 3.7 / altair 2 (or 4) and I cannot plot images with the following code. Which version of Hydrogen / Altair should I use?

import altair as alt

-- load a simple dataset as a pandas DataFrame
from vega_datasets import data
cars = data.cars()

fig = alt.Chart(cars).mark_point().encode(
x='Horsepower',
y='Miles_per_Gallon',
color='Origin',
).interactive()

fig

-- fig.to_dict() data are in

It does not seems to be an Altair issue as it works in Jupyter Notebook
altair-viz/altair#765

**Comment by vipinkashyap** [comment]
Any update on this problem. I am running into a similar issue
