### ISSUE TITLE
Can't get R to work in Atom on Windows 10

### ISSUE THREAD

**Issue by tlcaputi** [nteract/hydrogen#1742]
### Prerequisites

* [ ] Have you checked the solutions in our [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) for common problems ?
* [ ] Have you checked that your issue [isn't already filed](https://github.com/nteract/hydrogen/issues) ?

### Description

I can't get Hydrogen to run any R code within Atom. The code is there, I hit Shift+Enter, and it just advances to the next line without running anything. Occasionally (but not always), it will give this error:

[IPKernelApp] ERROR | Invalid Message Traceback (most recent call last): File "C:\Users\tcapu\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 234, in dispatch_shell msg = self.session.deserialize(msg, content=True, copy=False) File "C:\Users\tcapu\Anaconda3\lib\site-packages\jupyter_client\session.py", line 923, in deserialize raise ValueError("Invalid Signature: %r" % signature) ValueError: Invalid Signature: b'2544794458c882815449de78afb2b3b48930a5d51683dba538f268232250374b'

### Steps to Reproduce

1. Install Anaconda3.7, Atom 1.39.1, and Hydrogen
2. Run IRkernel::installspec() in R
3. Attempt to run any R code in Atom

### Versions

OS version:
Windows 10

> `atom --version`

```
Atom    : 1.40.0
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
```

> `apm --version`

```
apm  2.4.2
npm  6.2.0
node 10.2.1 x64
atom 1.40.0
python 3.6.8
git 2.22.0.windows.1
visual studio

```

Hydrogen version:

```
Hydrogen
├── 2.10.3
├── https://github.com/nteract/hydrogen
├── Run code interactively, inspect data, and plot. All the power of Jupyter kernels, inside your favorite text editor.
├── 1195831 downloads
└── 654 stars
```

### Plugins

Have you installed and activated any of the Hydrogen plugins below ?
- [ ] hydrogen-python
- [ ] Hydrogen Launcher
- [ ] Data Explorer

### Expected behavior

Run R code

### Screenshots

![image](https://user-images.githubusercontent.com/29004856/63107596-3beba300-bf53-11e9-8022-16cf23194854.png)

[If applicable, add screenshots to help explain your problem.]

### Additional context

[Add any other context about the problem here.]

**Comment by wadethestealth** [comment]
To install IRKernel:
```r
install.packages(c('repr', 'IRdisplay', 'evaluate', 'crayon', 'pbdZMQ', 'devtools', 'uuid', 'digest'))
devtools::install_github('IRkernel/IRkernel')
IRkernel::installspec()
```

**Comment by wadethestealth** [comment]
After further review, this could be an issue unrelated to your installation, but I am unsure of a root cause.

cc: @BenRussert @aviatesk

**Comment by wadethestealth** [comment]
I saw this issue report recently with #1237, but am unsure how your workflow relates to the same issue still

**Comment by Ujustwaite** [comment]
Same issue. Clean install and have similar symptoms. R kernel is detected by hydrogen on launch of atom and listed in popup dialog, but no code execution occurs. I don't get the error that the user does which appears to be related to the Python kernel and not R, but just don't get any execution. 

Have language-r grammar installed. 

`jupyter kernelspec list`

shows the ir kernel as present and available, reinforcing that atom is able to detect.
