### ISSUE TITLE
Issue when running Hydrogen

### ISSUE THREAD

**Issue by jumbi533** [nteract/hydrogen#1747]
When I try to run the Hydrogen package (with Ctrl+Enter) I get the following error:

    Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main "main", fname, loader, pkg_name)

**Comment by Purukitto** [comment]
This is usually caused by missing packages

**Comment by jumbi533** [comment]
I found the rebuild button in Atom and rebuilt Hydrogen. I also restarted it just for extra measure and the issue is still here.
When I try to run Hydrogen in Atom, an error box appears in the bottom right displaying this message:

> Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main

**Comment by wadethestealth** [comment]
Apologies for the late reply, but to diagnose your issue will will need more stack trace. Try opening the console `ctrl+shift+i` on windows to find a more complete stack trace of your error

**Comment by jumbi533** [comment]
I'm currently running Linux. `crtl+shift+i` opens an "inspect element" type view. Is this intended? If so, where in this menu would I find the complete stack trace?

**Comment by wadethestealth** [comment]
Yes that is intended. There is a tab labeled console. Most error log are outputted there.

**Comment by wadethestealth** [comment]
No activity for 30 days.
