### ISSUE TITLE
Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by aseem-hegshetye** [nteract/hydrogen#1759]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Ubuntu 18.04.2
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.12.0

### Stack Trace

Uncaught Error: Module did not self-register.

```
At ELECTRON_ASAR.js:166

Error: Module did not self-register.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/zeromq/lib/index.js:6:11)
    at /packages/Hydrogen/node_modules/zeromq/lib/index.js:857:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/zeromq/index.js:2:18)
    at /packages/Hydrogen/node_modules/zeromq/index.js:3:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/jmp/index.js:37:11)
    at /packages/Hydrogen/node_modules/jmp/index.js:450:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/lib/zmq-kernel.js:3:20)
```

### Commands

```
     -5:19.9.0 hydrogen:run-and-move-down (input.hidden-input)
     -5:01.4.0 intentions:highlight (input.hidden-input)
     -5:01.2.0 settings-view:open (input.hidden-input)
     -2:21.4.0 hydrogen:run-and-move-down (input.hidden-input)
     -2:19.2.0 intentions:highlight (input.hidden-input)
     -2:19.1.0 hydrogen:run (input.hidden-input)
     -2:18 core:move-down (input.hidden-input)
  2x -2:17.5.0 core:move-right (input.hidden-input)
     -2:16.5.0 intentions:highlight (input.hidden-input)
     -2:15.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-console 0.4.6 
autoclose-html 0.23.0 
block-comment 0.4.3 
busy-signal 2.0.1 
Hydrogen 2.12.0 
intentions 1.1.5 
language-vue 0.25.0 
lorem 4.0.0 
node-debug 0.1.7 
```

**Comment by wadethestealth** [comment]
There are no reproduction steps here, so I am going to close this issue.
