### ISSUE TITLE
Uncaught TypeError: Socket is closed

### ISSUE THREAD

**Issue by woshizk** [nteract/hydrogen#1764]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Ubuntu 18.04.3
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.12.0

### Stack Trace

Uncaught TypeError: Socket is closed

```
At /home/kai/.atom/packages/Hydrogen/node_modules/zeromq/lib/index.js:734

TypeError: Socket is closed
    at Socket.close (/packages/Hydrogen/node_modules/zeromq/lib/index.js:734:13)
    at ZMQKernel.destroy (/packages/Hydrogen/lib/zmq-kernel.js:395:22)
    at Kernel.destroy (/packages/Hydrogen/lib/kernel.js:435:20)
    at /packages/Hydrogen/lib/main.js:300:14)
    at Object.handleKernelCommand (/packages/Hydrogen/lib/main.js:310:4)
    at SignalListView.signalListView.onConfirmed (/packages/Hydrogen/lib/services/consumed/status-bar/status-bar.js:59:14)
    at Object.didConfirmSelection (/packages/Hydrogen/lib/services/consumed/status-bar/signal-list-view.js:40:36)
    at SelectListView.confirmSelection (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:400:20)
    at SelectListView.didClickItem (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:286:10)
    at ListItemView.onclick (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:221:31)
    at ListItemView.didClick (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:448:10)
```

### Commands

```
     -2:00.2.0 editor:newline (input.hidden-input)
     -1:59.4.0 core:move-up (input.hidden-input)
     -1:58.7.0 snippets:next-tab-stop (input.hidden-input)
     -1:58.7.0 snippets:expand (input.hidden-input)
     -1:58.7.0 editor:indent (input.hidden-input)
  4x -1:53.5.0 autocomplete-plus:confirm (input.hidden-input)
     -1:43.4.0 core:save (input.hidden-input)
     -1:12 hydrogen:run-and-move-down (input.hidden-input)
     -1:12 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
  4x -0:31.7.0 core:backspace (input.hidden-input)
  2x -0:29.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
Hydrogen 2.12.0 
```

**Comment by wadethestealth** [comment]
Please edit in or comment reproduction steps

**Comment by wadethestealth** [comment]
Seems related to #1760 but the ws kernel version
