### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, unlink '~/Library/Jupyter/runtime/kernel-ddf3a...

### ISSUE THREAD

**Issue by ahriley** [nteract/hydrogen#1765]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.12.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, unlink '/Users/alexanderriley/Library/Jupyter/runtime/kernel-ddf3ab5a-e37a-4e7a-ace0-3ea2eaeaa206.json'

```
At fs.js:143

Error: ENOENT: no such file or directory, unlink '/Users/alexanderriley/Library/Jupyter/runtime/kernel-ddf3ab5a-e37a-4e7a-ace0-3ea2eaeaa206.json'
    at Object.fs.unlinkSync (fs.js:1061:3)
    at ZMQKernel.destroy (/packages/Hydrogen/lib/zmq-kernel.js:393:8)
    at Kernel.destroy (/packages/Hydrogen/lib/kernel.js:435:20)
    at /packages/Hydrogen/lib/main.js:300:14)
    at Object.handleKernelCommand (/packages/Hydrogen/lib/main.js:310:4)
    at SignalListView.signalListView.onConfirmed (/packages/Hydrogen/lib/services/consumed/status-bar/status-bar.js:59:14)
    at Object.didConfirmSelection (/packages/Hydrogen/lib/services/consumed/status-bar/signal-list-view.js:40:36)
    at SelectListView.confirmSelection (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:400:20)
    at SelectListView.didClickItem (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:286:10)
    at ListItemView.onclick (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:221:31)
    at ListItemView.didClick (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:448:10)
```

### Commands

```
     -3:07.3.0 core:backspace (input.hidden-input)
     -3:05.9.0 core:save (input.hidden-input)
     -3:03.1.0 editor:toggle-line-comments (input.hidden-input)
     -3:02.7.0 core:save (input.hidden-input)
     -2:58.7.0 hydrogen:run (input.hidden-input)
     -2:58.7.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
     -2:45.6.0 core:copy (input.hidden-input)
     -2:43.2.0 core:paste (input.hidden-input)
     -2:40.7.0 core:backspace (input.hidden-input)
     -2:40 core:save (input.hidden-input)
     -2:36.9.0 hydrogen:run (input.hidden-input)
     -2:36.9.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
     -0:24.6.0 core:backspace (input.hidden-input)
  2x -0:19.4.0 core:save (input.hidden-input)
  3x -0:16.1.0 core:backspace (input.hidden-input)
  2x -0:14.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
Hydrogen 2.12.0 
language-latex 1.2.0 
latex 0.50.2 
pdf-view 0.72.0 
```

**Comment by ahriley** [comment]
Looks like this is the same issue as #1760
