### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, unlink '~/Library/Jupyter/runtime/kernel-07ace...

### ISSUE THREAD

**Issue by alanpang1990301** [nteract/hydrogen#1767]
[Enter steps to reproduce:]

Click interrupt kernel.

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.12.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, unlink '/Users/alanpang/Library/Jupyter/runtime/kernel-07ace1fb-742c-4b45-bb2b-757b0ad39bd7.json'

```
At fs.js:143

Error: ENOENT: no such file or directory, unlink '/Users/alanpang/Library/Jupyter/runtime/kernel-07ace1fb-742c-4b45-bb2b-757b0ad39bd7.json'
    at Object.fs.unlinkSync (fs.js:1061:3)
    at ZMQKernel.destroy (/packages/Hydrogen/lib/zmq-kernel.js:393:8)
    at Kernel.destroy (/packages/Hydrogen/lib/kernel.js:435:20)
    at /packages/Hydrogen/lib/main.js:300:14)
    at Object.handleKernelCommand (/packages/Hydrogen/lib/main.js:310:4)
    at SignalListView.signalListView.onConfirmed (/packages/Hydrogen/lib/services/consumed/status-bar/status-bar.js:59:14)
    at Object.didConfirmSelection (/packages/Hydrogen/lib/services/consumed/status-bar/signal-list-view.js:40:36)
    at SelectListView.confirmSelection (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:400:20)
    at SelectListView.didClickItem (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:286:10)
    at ListItemView.onclick (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:221:31)
    at ListItemView.didClick (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:448:10)
```

### Commands

```
     -0:21.1.0 hydrogen:run-and-move-down (input.hidden-input)
     -0:21.1.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:21 hydrogen:run-and-move-down (input.hidden-input)
     -0:21 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:20.9.0 hydrogen:run-and-move-down (input.hidden-input)
     -0:20.9.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:20.8.0 hydrogen:run-and-move-down (input.hidden-input)
     -0:20.8.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:20.8.0 hydrogen:run-and-move-down (input.hidden-input)
     -0:20.8.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:20.7.0 hydrogen:run-and-move-down (input.hidden-input)
     -0:20.7.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:20.6.0 hydrogen:run-and-move-down (input.hidden-input)
     -0:20.6.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:20.5.0 hydrogen:run-and-move-down (input.hidden-input)
     -0:20.5.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
Hydrogen 2.12.0 
```

**Comment by aviatesk** [comment]
Seems like an error is caused by Jupyter kernel itself, not from Hydrogen.

Try again kernel installation steps.

**Comment by aviatesk** [comment]
Ah we have the issue report [here](https://github.com/nteract/hydrogen/issues/1760) and please watch that instead.
