### ISSUE TITLE
Uncaught Error: Cannot find module '@nteract/presentational-components'

### ISSUE THREAD

**Issue by DannyDannyDanny** [nteract/hydrogen#1769]
I recently updated hydrogen and now it crashes on start:

Using Conda Prompt:
1. `cd path/to/project`
2. `conda activate envname`
2. `atom .`
3. Uncaught Error thrown at launch

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.12.0

### Stack Trace

Uncaught Error: Cannot find module '@nteract/presentational-components'

```
At internal/modules/cjs/loader.js:604

Error: Cannot find module '@nteract/presentational-components'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/markdown/lib/index.js:14:37)
    at /packages/Hydrogen/node_modules/@nteract/markdown/lib/index.js:29:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/markdown.js:13:36)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/markdown.js:27:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/index.js:11:18)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/index.js:20:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
```

### Commands

```
N/A
```

### Non-Core Packages

```
atom-file-icons 0.7.1 
atom-vim-like-tab 1.5.3 
autocomplete-python 1.16.0 
bracket-colorizer 1.4.0 
git-history 3.3.0 
git-log 0.4.1 
Hydrogen 2.12.0 
kite 0.170.0 
minimap 4.29.9 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-pigments 0.2.2 
pigments 0.40.2 
python-autopep8 0.1.3 
relative-numbers 0.9.0 
theme-switcher 1.1.0 
vim-mode-plus 1.36.1 
vim-mode-plus-keymaps-for-surround 0.2.1 
vim-mode-zz 0.2.0 
vim-modeline 0.5.2 
```

**Comment by DannyDannyDanny** [comment]
Tried so far:
* Restarted machine ✅  
* Atom safe mode ✅ (starts fine - but no packages run)
* reinstall hydrogen via atom UI ✅ 
* reinstall hydrogen via conda prompt ✅ 
* uninstall hydrogen, resinstall: `apm install hydrogen@2.10.3` 🚧  **in progress**


 uninstall, reinstall,

**Comment by wadethestealth** [comment]
I am looking into the cause of this as it's seems many are having this issue please follow #1768 for updates
