### ISSUE TITLE
Installing “hydrogen@2.12.0” failed.

### ISSUE THREAD

**Issue by fengxueyezebra** [nteract/hydrogen#1777]
C:\Users\Admin\AppData\Local\atom\app-1.40.1\resources\app\apm\lib\install.js:239
            if (body.releases.latest) {
                              ^

TypeError: Cannot read property 'latest' of undefined
    at C:\Users\Admin\AppData\Local\atom\app-1.40.1\resources\app\apm\lib\install.js:239:31
    at Request._callback (C:\Users\Admin\AppData\Local\atom\app-1.40.1\resources\app\apm\lib\request.js:56:22)
    at Request.self.callback (C:\Users\Admin\AppData\Local\atom\app-1.40.1\resources\app\apm\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (C:\Users\Admin\AppData\Local\atom\app-1.40.1\resources\app\apm\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (C:\Users\Admin\AppData\Local\atom\app-1.40.1\resources\app\apm\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1090:12)

**Comment by wadethestealth** [comment]
This error report has nothing to do with hydrogen but rather your atom/apm installation. Please open an issue over at atom or apm, or message them on slack.
