### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, unlink '~/Library/Jupyter/runtime/kernel-2c70a...

### ISSUE THREAD

**Issue by 77QingLiu** [nteract/hydrogen#1778]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.5
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.12.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, unlink '/Users/liuqing/Library/Jupyter/runtime/kernel-2c70ad34-a293-4fbb-9d55-098c51049bb5.json'

```
At fs.js:143

Error: ENOENT: no such file or directory, unlink '/Users/liuqing/Library/Jupyter/runtime/kernel-2c70ad34-a293-4fbb-9d55-098c51049bb5.json'
    at Object.fs.unlinkSync (fs.js:1061:3)
    at ZMQKernel.destroy (/packages/Hydrogen/lib/zmq-kernel.js:393:8)
    at Kernel.destroy (/packages/Hydrogen/lib/kernel.js:435:20)
    at /packages/Hydrogen/lib/main.js:300:14)
    at Object.handleKernelCommand (/packages/Hydrogen/lib/main.js:310:4)
    at SignalListView.signalListView.onConfirmed (/packages/Hydrogen/lib/services/consumed/status-bar/status-bar.js:59:14)
    at Object.didConfirmSelection (/packages/Hydrogen/lib/services/consumed/status-bar/signal-list-view.js:40:36)
    at SelectListView.confirmSelection (/packages/git-plus/node_modules/atom-select-list/src/select-list-view.js:400:20)
    at SelectListView.didClickItem (/packages/git-plus/node_modules/atom-select-list/src/select-list-view.js:286:10)
    at ListItemView.onclick (/packages/git-plus/node_modules/atom-select-list/src/select-list-view.js:221:31)
    at ListItemView.didClick (/packages/git-plus/node_modules/atom-select-list/src/select-list-view.js:448:10)
```

### Commands

```
     -9:22.4.0 hydrogen:run-and-move-down (input.hidden-input)
     -9:22.4.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -9:20.3.0 hydrogen:clear-results (input.hidden-input)
     -8:56.1.0 hydrogen:run (input.hidden-input)
     -8:56.1.0 autocomplete-plus:cancel (atom-text-editor.editor.has-selection.is-focused)
     -8:20.6.0 hydrogen:clear-results (input.hidden-input)
     -8:20.3.0 hydrogen:run (input.hidden-input)
     -8:20.3.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -5:35.4.0 core:save (input.hidden-input)
     -5:13.3.0 core:backspace (input.hidden-input)
     -5:11.9.0 core:save (input.hidden-input)
     -5:09.4.0 hydrogen:run-and-move-down (input.hidden-input)
     -5:09.4.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -5:05.3.0 hydrogen:run (input.hidden-input)
     -5:05.3.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
cert-tweaks 0.1.0 
copy-with-syntax 0.0.3 
file-icons 2.1.25 
git-plus 8.6.1 
Hydrogen 2.12.0 
hydrogen-auth 0.0.2 
hydrogen-launcher 1.2.2 
hydrogen-python 0.0.7 
minimap 4.29.9 
```

**Comment by wadethestealth** [comment]
#1760
