### ISSUE TITLE
Failed to activate the Hydrogen package

### ISSUE THREAD

**Issue by Alexander-Serov** [nteract/hydrogen#1779]
[Enter steps to reproduce:]

1. Updated Hydrogen to 2.12.0 (and a bunch of other packages) through Atom interface
2. Stopped working
3. Nothing from the previous issues (reinstalling, rebuilding) helped: https://github.com/nteract/hydrogen/issues/1591
https://github.com/nteract/hydrogen/issues/1690
4. Downgraded to v. 2.8.0 and everything works fine!

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Home
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.12.0

### Stack Trace

Uncaught Error: Cannot find module '@nteract/presentational-components'

```
At internal/modules/cjs/loader.js:604

Error: Cannot find module '@nteract/presentational-components'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/markdown/lib/index.js:14:37)
    at /packages/Hydrogen/node_modules/@nteract/markdown/lib/index.js:29:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/markdown.js:13:36)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/markdown.js:27:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/index.js:11:18)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/index.js:20:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/index.js:24:28)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/index.js:27:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.7.0
atom-beautify 0.33.4
atom-ide-ui 0.13.0
atom-python-test 0.10.0
auto-detect-indentation 1.3.0
autocomplete-python 1.16.0
busy-signal 2.0.1
file-icons 2.1.35
git-plus 8.7.1
git-time-machine 2.1.0
go-debug 1.6.2
go-plus 6.1.0
go-signature-statusbar 1.2.3
goto-definition 1.3.4
hey-pane 1.2.0
highlight-selected 0.16.0
Hydrogen 2.12.0
intentions 1.1.5
kite 0.171.0
linter 2.3.1
linter-flake8 2.4.0
linter-pycodestyle 2.1.3
linter-pydocstyle 0.4.7
linter-python 3.1.2
linter-python-pep8 0.2.0
linter-ui-default 1.8.0
mariana-syntax 0.2.0
minimap 4.29.9
pigments 0.40.2
python-debugger 0.2.0
python-tools 0.6.9
split-diff 1.6.0
sync-settings 0.8.6
teletype 0.13.4
todo-show 2.3.2
tool-bar 1.1.12
zentabs 0.8.9
```

**Comment by wadethestealth** [comment]
#1768

**Comment by pietermdevries** [comment]
I got this bug today when I upgraded.
[Enter steps to reproduce:]

1. upgrade
2. cry

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.13.1


### Stack Trace

Failed to activate the Hydrogen package

```
At Unexpected token export

/Users/pieterdevries/.atom/packages/Hydrogen/node_modules/react-syntax-highlighter/dist/esm/styles/prism/vs.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { export default {
                                                                                                                                                           ^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:74:7)
    at NativeCompileCache.runInThisContext (/private/var/folders/p8/k7qb4ln558ng_mp839yppl8c0000gn/T/AppTranslocation/B9688DBD-EBB5-450C-8FAA-CA0F5DB6D7FE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146322)
    at Module.get_Module._compile (/private/var/folders/p8/k7qb4ln558ng_mp839yppl8c0000gn/T/AppTranslocation/B9688DBD-EBB5-450C-8FAA-CA0F5DB6D7FE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147206)
    at Object.value [as .js] (/private/var/folders/p8/k7qb4ln558ng_mp839yppl8c0000gn/T/AppTranslocation/B9688DBD-EBB5-450C-8FAA-CA0F5DB6D7FE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/private/var/folders/p8/k7qb4ln558ng_mp839yppl8c0000gn/T/AppTranslocation/B9688DBD-EBB5-450C-8FAA-CA0F5DB6D7FE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/syntax-highlighter/index.js:15:30)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/syntax-highlighter/index.js:46:3)
    at Module.get_Module._compile (/private/var/folders/p8/k7qb4ln558ng_mp839yppl8c0000gn/T/AppTranslocation/B9688DBD-EBB5-450C-8FAA-CA0F5DB6D7FE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/private/var/folders/p8/k7qb4ln558ng_mp839yppl8c0000gn/T/AppTranslocation/B9688DBD-EBB5-450C-8FAA-CA0F5DB6D7FE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/private/var/folders/p8/k7qb4ln558ng_mp839yppl8c0000gn/T/AppTranslocation/B9688DBD-EBB5-450C-8FAA-CA0F5DB6D7FE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/components/source.js:15:46)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/components/source.js:51:3)
    at Module.get_Module._compile (/private/var/folders/p8/k7qb4ln558ng_mp839yppl8c0000gn/T/AppTranslocation/B9688DBD-EBB5-450C-8FAA-CA0F5DB6D7FE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/private/var/folders/p8/k7qb4ln558ng_mp839yppl8c0000gn/T/AppTranslocation/B9688DBD-EBB5-450C-8FAA-CA0F5DB6D7FE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/private/var/folders/p8/k7qb4ln558ng_mp839yppl8c0000gn/T/AppTranslocation/B9688DBD-EBB5-450C-8FAA-CA0F5DB6D7FE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/components/input.js:16:18)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/components/input.js:52:3)
    at Module.get_Module._compile (/private/var/folders/p8/k7qb4ln558ng_mp839yppl8c0000gn/T/AppTranslocation/B9688DBD-EBB5-450C-8FAA-CA0F5DB6D7FE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
```

### Commands

```
  6x -4:57.9.0 core:move-up (input.hidden-input)
     -4:55.5.0 hydrogen:run-and-move-down (input.hidden-input)
```

### Non-Core Packages

```
Hydrogen 2.13.1 
python-black 0.7.0 
script 3.18.1 
```

**Comment by pedrofale** [comment]
I also got this today after upgrading.

**Comment by hragbalian** [comment]
Same. 

Unexpected token export
Hide Stack Trace
/Users/hragbalian/.atom/packages/Hydrogen/node_modules/react-syntax-highlighter/dist/esm/styles/prism/vs.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { export default {
                                                                                                                                                           ^^^^^^
SyntaxError: Unexpected token export
    at new Script (vm.js:79:7)
    at NativeCompileCache.runInThisContext (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146322)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147206)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at Object.<anonymous> (/Users/hragbalian/.atom/packages/Hydrogen/node_modules/@nteract/presentational-components/lib/syntax-highlighter/index.js:15:30)
    at Object.<anonymous> (/Users/hragbalian/.atom/packages/Hydrogen/node_modules/@nteract/presentational-components/lib/syntax-highlighter/index.js:46:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at Object.<anonymous> (/Users/hragbalian/.atom/packages/Hydrogen/node_modules/@nteract/presentational-components/lib/components/source.js:15:46)
    at Object.<anonymous> (/Users/hragbalian/.atom/packages/Hydrogen/node_modules/@nteract/presentational-components/lib/components/source.js:51:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at Object.<anonymous> (/Users/hragbalian/.atom/packages/Hydrogen/node_modules/@nteract/presentational-components/lib/components/input.js:16:18)
    at Object.<anonymous> (/Users/hragbalian/.atom/packages/Hydrogen/node_modules/@nteract/presentational-components/lib/components/input.js:52:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
