### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, unlink '~/Library/Jupyter/runtime/kernel-c0601...

### ISSUE THREAD

**Issue by lkondapi** [nteract/hydrogen#1780]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.12.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, unlink '/Users/lkondapi/Library/Jupyter/runtime/kernel-c0601500-e3f7-46e6-9814-568132358ad7.json'

```
At fs.js:143

Error: ENOENT: no such file or directory, unlink '/Users/lkondapi/Library/Jupyter/runtime/kernel-c0601500-e3f7-46e6-9814-568132358ad7.json'
    at Object.fs.unlinkSync (fs.js:1061:3)
    at ZMQKernel.destroy (/packages/Hydrogen/lib/zmq-kernel.js:393:8)
    at Kernel.destroy (/packages/Hydrogen/lib/kernel.js:435:20)
    at /packages/Hydrogen/lib/main.js:300:14)
    at Object.handleKernelCommand (/packages/Hydrogen/lib/main.js:310:4)
    at SignalListView.signalListView.onConfirmed (/packages/Hydrogen/lib/services/consumed/status-bar/status-bar.js:59:14)
    at Object.didConfirmSelection (/packages/Hydrogen/lib/services/consumed/status-bar/signal-list-view.js:40:36)
    at SelectListView.confirmSelection (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:400:20)
    at SelectListView.didClickItem (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:286:10)
    at ListItemView.onclick (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:221:31)
    at ListItemView.didClick (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:448:10)
```

### Commands

```
     -0:52.5.0 hydrogen:run-and-move-down (input.hidden-input)
     -0:52.5.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:51.7.0 hydrogen:run-and-move-down (input.hidden-input)
     -0:51.7.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:51.3.0 hydrogen:run-and-move-down (input.hidden-input)
     -0:51.3.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:48.9.0 hydrogen:run-and-move-down (input.hidden-input)
     -0:48.9.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
     -0:39.3.0 hydrogen:run-and-move-down (input.hidden-input)
     -0:39.3.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
     -0:31.7.0 core:backspace (input.hidden-input)
     -0:30.8.0 core:save (input.hidden-input)
     -0:29.7.0 hydrogen:run-and-move-down (input.hidden-input)
     -0:29.7.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:25 hydrogen:run-and-move-down (input.hidden-input)
     -0:25 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
```

### Non-Core Packages

```
atom-clock 0.1.17 
file-header 1.13.9 
Hydrogen 2.12.0 
pretty-json 2.1.2 
python-debugger 0.2.0 
```

**Comment by wadethestealth** [comment]
#1760
