### ISSUE TITLE
Uncaught Error: Cannot find module 'trough'

### ISSUE THREAD

**Issue by swordsandblades** [nteract/hydrogen#1782]
[Enter steps to reproduce:]

1. ...removed Hydrogen package from Atom and tried reinstalling it.
2. ...error was through

**Atom**: 1.40.1 ia32
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Home
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.12.0

### Stack Trace

Uncaught Error: Cannot find module 'trough'

```
At internal/modules/cjs/loader.js:604

Error: Cannot find module 'trough'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/unified/index.js:7:14)
    at /packages/Hydrogen/node_modules/unified/index.js:468:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/react-markdown/lib/react-markdown.js:13:15)
    at /packages/Hydrogen/node_modules/react-markdown/lib/react-markdown.js:136:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/markdown/lib/index.js:16:42)
    at /packages/Hydrogen/node_modules/@nteract/markdown/lib/index.js:29:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/markdown.js:13:36)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/markdown.js:27:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-json 5.5.2 
city-lights-ui 1.5.3 
essence-dark-syntax 0.2.1 
Hydrogen 2.12.0 
json-converter 0.2.4 
minimap 4.29.9 
pretty-json 2.1.2 
statusbar-datetime 0.9.7 
```

**Comment by wadethestealth** [comment]
unsure of how you could be coming across this error, but this is definitely a corrupt install. To fix your issue without reinstalling, if you have npm installed you can `cd` into the hydrogen package and then you can run `npm install trough` in your terminal. However I can't guarantee you wont run into many more problems. Please reinstall either through the command line by deleteing hydrogen and running `apm install hydrogen`, or the install packages tab in your application.
