### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, unlink '~/Library/Jupyter/runtime/kernel-a2915...

### ISSUE THREAD

**Issue by aaronwflee** [nteract/hydrogen#1783]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.4
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.12.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, unlink '/Users/alee/Library/Jupyter/runtime/kernel-a29151ea-2daf-48f1-9070-7a595cb699cb.json'

```
At fs.js:143

Error: ENOENT: no such file or directory, unlink '/Users/alee/Library/Jupyter/runtime/kernel-a29151ea-2daf-48f1-9070-7a595cb699cb.json'
    at Object.fs.unlinkSync (fs.js:1061:3)
    at ZMQKernel.destroy (/packages/Hydrogen/lib/zmq-kernel.js:393:8)
    at Kernel.destroy (/packages/Hydrogen/lib/kernel.js:435:20)
    at /packages/Hydrogen/lib/main.js:300:14)
    at Object.handleKernelCommand (/packages/Hydrogen/lib/main.js:310:4)
    at SignalListView.signalListView.onConfirmed (/packages/Hydrogen/lib/services/consumed/status-bar/status-bar.js:59:14)
    at Object.didConfirmSelection (/packages/Hydrogen/lib/services/consumed/status-bar/signal-list-view.js:40:36)
    at SelectListView.confirmSelection (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:400:20)
    at SelectListView.didClickItem (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:286:10)
    at ListItemView.onclick (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:221:31)
    at ListItemView.didClick (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:448:10)
```

### Commands

```
     -0:32.5.0 core:move-down (input.hidden-input)
  7x -0:32.1.0 core:move-up (input.hidden-input)
  2x -0:30.5.0 core:move-down (input.hidden-input)
     -0:30 editor:toggle-line-comments (input.hidden-input)
     -0:29.1.0 core:move-to-top (input.hidden-input)
     -0:28.7.0 core:move-down (input.hidden-input)
     -0:28.3.0 editor:select-smaller-syntax-node (input.hidden-input)
  2x -0:25.9.0 core:select-down (input.hidden-input)
     -0:25.3.0 hydrogen:run (input.hidden-input)
     -0:25.3.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
 31x -0:24.9.0 core:move-down (input.hidden-input)
  6x -0:21.3.0 core:move-up (input.hidden-input)
     -0:19.8.0 hydrogen:run (input.hidden-input)
     -0:19.8.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:19.3.0 core:move-down (input.hidden-input)
     -0:19 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
delete-lines 0.5.0 
docblock-python 0.15.0 
highlight-selected 0.16.0 
Hydrogen 2.12.0 
linter 2.3.0 
minimap 4.29.9 
minimap-autohider 1.6.0 
nord-atom-syntax 0.10.0 
nord-atom-ui 0.12.0 
seti-syntax 1.2.0 
seti-ui 1.11.0 
```

**Comment by wadethestealth** [comment]
#1781
