### ISSUE TITLE
Having Issues with running JavaScript

### ISSUE THREAD

**Issue by KHarrison99** [nteract/hydrogen#1787]
Hello, I am trying hydrogen and atom for first time.

I have installed iPython and got it working correctly. Very happy with the functionality.

I tried installing iJavascript, managed to get it installed successfully.

I am running latest Linux Mint, latest Atom and latest iJavascript versions.

It discovered the kernel correctly for iJavaScript.

When I try to run basic commands like prompt() or alert() I receive the same error.

Example:
`prompt("test");`

Output:
```
evalmachine.<anonymous>:1
prompt('test');
^

ReferenceError: prompt is not defined
    at evalmachine.<anonymous>:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at run ([eval]:1054:15)
    at onRunRequest ([eval]:888:18)
    at onMessage ([eval]:848:13)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
```

**Comment by wadethestealth** [comment]
This is an ijavascript issue.
