### ISSUE TITLE
I can't update to v2.12.1 using Atom 1.40.1

### ISSUE THREAD

**Issue by arsari** [nteract/hydrogen#1788]
The error that shows is the one below:

<img width="613" alt="Screenshot 2019-10-05 11 41 37" src="https://user-images.githubusercontent.com/22566231/66257301-52e58f00-e765-11e9-9e93-bbb092521246.png">

**Comment by wadethestealth** [comment]
Im sorry, but we are going to need a full issue log to be able to diagnose this

**Comment by arsari** [comment]
Please, how I can get the full issue report in Atom?

**Comment by wadethestealth** [comment]
A formmated copy paste of the log file mentioned in your picture hopefully contains said issue report

**Comment by arsari** [comment]
Attach please find the debug log.

__________________________________________

**Comment by wadethestealth** [comment]
If you have replied via email, attachments are not transferred. Also it is better for you to copy-paste text as to protect us and other users from potentially harmful files.

**Comment by arsari** [comment]
Sorry… Here is the content of the log.

~~~
0 info it worked if it ends with ok
1 verbose cli [ '/Applications/Atom.app/Contents/Resources/app/apm/bin/node',
1 verbose cli   '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   '/Users/arsari/.atom/.apm/.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   '/Users/arsari/.atom/.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/hydrogen/versions/2.12.1/tarball',
1 verbose cli   '--target=3.1.10',
1 verbose cli   '--disturl=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style' ]
2 info using npm@6.2.0
3 info using node@v10.2.1
4 verbose npm-session 0be30895f61f7ce8
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://www.atom.io/api/packages/hydrogen/versions/2.12.1/tarball 882ms
8 silly pacote remote manifest for undefined@https://www.atom.io/api/packages/hydrogen/versions/2.12.1/tarball fetched in 898ms
9 timing stage:loadCurrentTree Completed in 1052ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 0ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule Hydrogen@2.12.1 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/atom-select-list 253ms (from cache)
18 silly pacote range manifest for atom-select-list@^0.7.0 fetched in 257ms
19 silly resolveWithNewModule atom-select-list@0.7.2 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/@babel%2fruntime-corejs2 558ms (from cache)
21 silly pacote range manifest for @babel/runtime-corejs2@^7.0.0 fetched in 561ms
22 silly resolveWithNewModule @babel/runtime-corejs2@7.6.2 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/anser 579ms (from cache)
24 silly pacote range manifest for anser@^1.4.8 fetched in 580ms
25 silly resolveWithNewModule anser@1.4.8 checking installable status
26 http fetch GET 304 https://registry.npmjs.org/escape-string-regexp 55ms (from cache)
27 silly pacote range manifest for escape-string-regexp@^2.0.0 fetched in 56ms
28 silly resolveWithNewModule escape-string-regexp@2.0.0 checking installable status
29 http fetch GET 304 https://registry.npmjs.org/escape-carriage 393ms (from cache)
30 silly pacote range manifest for escape-carriage@^1.2.0 fetched in 394ms
31 silly resolveWithNewModule escape-carriage@1.3.0 checking installable status
32 http fetch GET 304 https://registry.npmjs.org/lodash 62ms (from cache)
33 silly pacote range manifest for lodash@^4.14.0 fetched in 64ms
34 silly resolveWithNewModule lodash@4.17.15 checking installable status
35 http fetch GET 304 https://registry.npmjs.org/kernelspecs 134ms (from cache)
36 silly pacote range manifest for kernelspecs@^2.0.0 fetched in 136ms
37 silly resolveWithNewModule kernelspecs@2.0.0 checking installable status
38 http fetch GET 304 https://registry.npmjs.org/mobx 64ms (from cache)
39 silly pacote range manifest for mobx@^5.1.1 fetched in 69ms
40 silly resolveWithNewModule mobx@5.14.0 checking installable status
41 http fetch GET 304 https://registry.npmjs.org/jmp 416ms (from cache)
42 silly pacote range manifest for jmp@^2.0.0 fetched in 417ms
43 silly resolveWithNewModule jmp@2.0.0 checking installable status
44 http fetch GET 304 https://registry.npmjs.org/react 61ms (from cache)
45 silly pacote range manifest for react@^16.8.6 fetched in 65ms
46 silly resolveWithNewModule react@16.10.2 checking installable status
47 http fetch GET 304 https://registry.npmjs.org/mathjax-electron 415ms (from cache)
48 silly pacote range manifest for mathjax-electron@^3.0.0 fetched in 416ms
49 silly resolveWithNewModule mathjax-electron@3.0.0 checking installable status
50 http fetch GET 304 https://registry.npmjs.org/@nteract%2foutputs 1139ms (from cache)
51 silly pacote range manifest for @nteract/outputs@^2.1.5 fetched in 1140ms
52 silly resolveWithNewModule @nteract/outputs@2.3.2 checking installable status
53 http fetch GET 304 https://registry.npmjs.org/react-dom 78ms (from cache)
54 silly pacote range manifest for react-dom@^16.8.6 fetched in 84ms
55 silly resolveWithNewModule react-dom@16.10.2 checking installable status
56 http fetch GET 304 https://registry.npmjs.org/@nteract%2fcommutable 1156ms (from cache)
57 silly pacote range manifest for @nteract/commutable@^7.0.0 fetched in 1158ms
58 silly resolveWithNewModule @nteract/commutable@7.1.4 checking installable status
59 http fetch GET 304 https://registry.npmjs.org/@nteract%2fplotly 1172ms (from cache)
60 silly pacote range manifest for @nteract/plotly@^1.48.3 fetched in 1175ms
61 silly resolveWithNewModule @nteract/plotly@1.49.1 checking installable status
62 http fetch GET 304 https://registry.npmjs.org/@nteract%2ftransform-vega 1187ms (from cache)
63 silly pacote range manifest for @nteract/transform-vega@^6.0.0 fetched in 1191ms
64 silly resolveWithNewModule @nteract/transform-vega@6.0.2 checking installable status
65 http fetch GET 304 https://registry.npmjs.org/@nteract%2fmathjax 1194ms (from cache)
66 silly pacote range manifest for @nteract/mathjax@^4.0.0 fetched in 1196ms
67 silly resolveWithNewModule @nteract/mathjax@4.0.0 checking installable status
68 http fetch GET 304 https://registry.npmjs.org/@nteract%2fmarkdown 1208ms (from cache)
69 silly pacote range manifest for @nteract/markdown@^4.0.0 fetched in 1214ms
70 silly resolveWithNewModule @nteract/markdown@4.0.3 checking installable status
71 http fetch GET 304 https://registry.npmjs.org/strip-indent 66ms (from cache)
72 http fetch GET 304 https://registry.npmjs.org/mobx-react 407ms (from cache)
73 silly pacote range manifest for strip-indent@^3.0.0 fetched in 73ms
74 silly resolveWithNewModule strip-indent@3.0.0 checking installable status
75 silly pacote range manifest for mobx-react@^6.0.0 fetched in 412ms
76 silly resolveWithNewModule mobx-react@6.1.3 checking installable status
77 http fetch GET 304 https://registry.npmjs.org/tildify 66ms (from cache)
78 silly pacote range manifest for tildify@^2.0.0 fetched in 67ms
79 silly resolveWithNewModule tildify@2.0.0 checking installable status
80 http fetch GET 304 https://registry.npmjs.org/ws 55ms (from cache)
81 silly pacote range manifest for ws@^3.3.1 fetched in 59ms
82 silly resolveWithNewModule ws@3.3.3 checking installable status
83 http fetch GET 304 https://registry.npmjs.org/uuid 84ms (from cache)
84 silly pacote range manifest for uuid@^3.2.1 fetched in 86ms
85 silly resolveWithNewModule uuid@3.3.3 checking installable status
86 http fetch GET 304 https://registry.npmjs.org/xmlhttprequest 66ms (from cache)
87 silly pacote range manifest for xmlhttprequest@^1.8.0 fetched in 67ms
88 silly resolveWithNewModule xmlhttprequest@1.8.0 checking installable status
89 http fetch GET 304 https://registry.npmjs.org/@jupyterlab%2fservices 1291ms (from cache)
90 silly pacote range manifest for @jupyterlab/services@^0.52.0 fetched in 1295ms
91 silly resolveWithNewModule @jupyterlab/services@0.52.0 checking installable status
92 http fetch GET 304 https://registry.npmjs.org/react-rangeslider 418ms (from cache)
93 silly pacote range manifest for react-rangeslider@^2.1.0 fetched in 420ms
94 silly resolveWithNewModule react-rangeslider@2.2.0 checking installable status
95 http fetch GET 304 https://registry.npmjs.org/spawnteract 409ms (from cache)
96 silly pacote range manifest for spawnteract@^5.1.0 fetched in 410ms
97 silly resolveWithNewModule spawnteract@5.1.0 checking installable status
98 http fetch GET 304 https://registry.npmjs.org/react-table 423ms (from cache)
99 silly pacote range manifest for react-table@^6.10.0 fetched in 430ms
100 silly resolveWithNewModule react-table@6.10.3 checking installable status
101 http fetch GET 304 https://registry.npmjs.org/regenerator-runtime 64ms (from cache)
102 silly pacote range manifest for regenerator-runtime@^0.13.2 fetched in 65ms
103 silly resolveWithNewModule regenerator-runtime@0.13.3 checking installable status
104 http fetch GET 304 https://registry.npmjs.org/core-js 69ms (from cache)
105 silly pacote range manifest for core-js@^2.6.5 fetched in 73ms
106 silly resolveWithNewModule core-js@2.6.9 checking installable status
107 http fetch GET 304 https://registry.npmjs.org/@phosphor%2fcoreutils 932ms (from cache)
108 silly pacote range manifest for @phosphor/coreutils@^1.3.0 fetched in 933ms
109 silly resolveWithNewModule @phosphor/coreutils@1.3.1 checking installable status
110 http fetch GET 304 https://registry.npmjs.org/@phosphor%2falgorithm 954ms (from cache)
111 silly pacote range manifest for @phosphor/algorithm@^1.1.2 fetched in 955ms
112 silly resolveWithNewModule @phosphor/algorithm@1.2.0 checking installable status
113 http fetch GET 304 https://registry.npmjs.org/@phosphor%2fsignaling 959ms (from cache)
114 silly pacote range manifest for @phosphor/signaling@^1.2.2 fetched in 961ms
115 silly resolveWithNewModule @phosphor/signaling@1.3.0 checking installable status
116 http fetch GET 304 https://registry.npmjs.org/@phosphor%2fdisposable 963ms (from cache)
117 silly pacote range manifest for @phosphor/disposable@^1.1.2 fetched in 963ms
118 silly resolveWithNewModule @phosphor/disposable@1.3.0 checking installable status
119 http fetch GET 304 https://registry.npmjs.org/@jupyterlab%2fobservables 1019ms (from cache)
120 silly pacote range manifest for @jupyterlab/observables@^0.2.0 fetched in 1022ms
121 silly resolveWithNewModule @jupyterlab/observables@0.2.0 checking installable status
122 http fetch GET 304 https://registry.npmjs.org/@jupyterlab%2fcoreutils 1039ms (from cache)
123 silly pacote range manifest for @jupyterlab/coreutils@^0.13.0 fetched in 1042ms
124 silly resolveWithNewModule @jupyterlab/coreutils@0.13.0 checking installable status
125 http fetch GET 304 https://registry.npmjs.org/url-parse 80ms (from cache)
126 http fetch GET 304 https://registry.npmjs.org/moment 83ms (from cache)
127 silly pacote range manifest for url-parse@~1.1.9 fetched in 84ms
128 silly resolveWithNewModule url-parse@1.1.9 checking installable status
129 silly pacote range manifest for moment@~2.17.1 fetched in 86ms
130 silly resolveWithNewModule moment@2.17.1 checking installable status
131 http fetch GET 304 https://registry.npmjs.org/ajv 88ms (from cache)
132 silly pacote range manifest for ajv@~5.1.6 fetched in 94ms
133 silly resolveWithNewModule ajv@5.1.6 checking installable status
134 http fetch GET 304 https://registry.npmjs.org/minimist 94ms (from cache)
135 silly pacote range manifest for minimist@~1.2.0 fetched in 95ms
136 silly resolveWithNewModule minimist@1.2.0 checking installable status
137 http fetch GET 304 https://registry.npmjs.org/comment-json 398ms (from cache)
138 silly pacote range manifest for comment-json@^1.1.3 fetched in 400ms
139 silly resolveWithNewModule comment-json@1.1.3 checking installable status
140 http fetch GET 304 https://registry.npmjs.org/path-posix 644ms (from cache)
141 silly pacote range manifest for path-posix@~1.0.0 fetched in 645ms
142 silly resolveWithNewModule path-posix@1.0.0 checking installable status
143 http fetch GET 304 https://registry.npmjs.org/json-stable-stringify 70ms (from cache)
144 silly pacote range manifest for json-stable-stringify@^1.0.1 fetched in 71ms
145 silly resolveWithNewModule json-stable-stringify@1.0.1 checking installable status
146 http fetch GET 304 https://registry.npmjs.org/json-schema-traverse 75ms (from cache)
147 silly pacote range manifest for json-schema-traverse@^0.3.0 fetched in 76ms
148 silly resolveWithNewModule json-schema-traverse@0.3.1 checking installable status
149 http fetch GET 304 https://registry.npmjs.org/co 77ms (from cache)
150 silly pacote range manifest for co@^4.6.0 fetched in 79ms
151 silly resolveWithNewModule co@4.6.0 checking installable status
152 http fetch GET 304 https://registry.npmjs.org/jsonify 82ms (from cache)
153 silly pacote range manifest for jsonify@~0.0.0 fetched in 83ms
154 silly resolveWithNewModule jsonify@0.0.0 checking installable status
155 http fetch GET 304 https://registry.npmjs.org/json-parser 399ms (from cache)
156 silly pacote range manifest for json-parser@^1.0.0 fetched in 400ms
157 silly resolveWithNewModule json-parser@1.1.5 checking installable status
158 http fetch GET 304 https://registry.npmjs.org/esprima 64ms (from cache)
159 silly pacote range manifest for esprima@^2.7.0 fetched in 65ms
160 silly resolveWithNewModule esprima@2.7.3 checking installable status
161 http fetch GET 304 https://registry.npmjs.org/requires-port 61ms (from cache)
162 silly pacote range manifest for requires-port@1.0.x fetched in 62ms
163 silly resolveWithNewModule requires-port@1.0.0 checking installable status
164 http fetch GET 304 https://registry.npmjs.org/querystringify 83ms (from cache)
165 silly pacote range manifest for querystringify@~1.0.0 fetched in 84ms
166 silly resolveWithNewModule querystringify@1.0.0 checking installable status
167 http fetch GET 304 https://registry.npmjs.org/@phosphor%2fmessaging 943ms (from cache)
168 silly pacote range manifest for @phosphor/messaging@^1.2.2 fetched in 945ms
169 silly resolveWithNewModule @phosphor/messaging@1.3.0 checking installable status
170 http fetch GET 304 https://registry.npmjs.org/@phosphor%2fcollections 1087ms (from cache)
171 silly pacote range manifest for @phosphor/collections@^1.2.0 fetched in 1088ms
172 silly resolveWithNewModule @phosphor/collections@1.2.0 checking installable status
173 http fetch GET 304 https://registry.npmjs.org/immutable 68ms (from cache)
174 silly pacote range manifest for immutable@^4.0.0-rc.12 fetched in 71ms
175 silly resolveWithNewModule immutable@4.0.0-rc.12 checking installable status
176 http fetch GET 304 https://registry.npmjs.org/react-markdown 420ms (from cache)
177 silly pacote range manifest for react-markdown@^4.0.0 fetched in 423ms
178 silly resolveWithNewModule react-markdown@4.2.2 checking installable status
179 http fetch GET 304 https://registry.npmjs.org/@nteract%2fpresentational-components 989ms (from cache)
180 silly pacote range manifest for @nteract/presentational-components@^3.0.7 fetched in 990ms
181 silly resolveWithNewModule @nteract/presentational-components@3.0.7 checking installable status
182 http fetch GET 304 https://registry.npmjs.org/react-syntax-highlighter 68ms (from cache)
183 silly pacote range manifest for react-syntax-highlighter@^9.0.0 fetched in 73ms
184 silly resolveWithNewModule react-syntax-highlighter@9.0.1 checking installable status
185 http fetch GET 304 https://registry.npmjs.org/styled-components 74ms (from cache)
186 silly fetchPackageMetaData error for styled-components@^4.1.3 Unexpected end of JSON input while parsing near '...0.4\r\nComment: https'
187 http fetch GET 304 https://registry.npmjs.org/@blueprintjs%2fselect 937ms (from cache)
188 silly pacote range manifest for @blueprintjs/select@^3.2.0 fetched in 939ms
189 silly resolveWithNewModule @blueprintjs/select@3.10.0 checking installable status
190 http fetch GET 304 https://registry.npmjs.org/@blueprintjs%2fcore 990ms (from cache)
191 silly pacote range manifest for @blueprintjs/core@^3.7.0 fetched in 1000ms
192 silly resolveWithNewModule @blueprintjs/core@3.18.1 checking installable status
193 timing stage:rollbackFailedOptional Completed in 1ms
194 timing stage:runTopLevelLifecycles Completed in 9255ms
195 silly saveTree apm-install-dir-11995-3229-1nbsh38.0jm
195 silly saveTree `-- Hydrogen@2.12.1
195 silly saveTree   +-- @babel/runtime-corejs2@7.6.2
195 silly saveTree   | +-- core-js@2.6.9
195 silly saveTree   | `-- regenerator-runtime@0.13.3
195 silly saveTree   +-- @jupyterlab/services@0.52.0
195 silly saveTree   | +-- @jupyterlab/coreutils@0.13.0
195 silly saveTree   | | +-- @phosphor/algorithm@1.2.0
195 silly saveTree   | | +-- @phosphor/coreutils@1.3.1
195 silly saveTree   | | +-- @phosphor/disposable@1.3.0
195 silly saveTree   | | | `-- @phosphor/signaling@1.3.0
195 silly saveTree   | | +-- @phosphor/signaling@1.3.0
195 silly saveTree   | | +-- ajv@5.1.6
195 silly saveTree   | | | +-- co@4.6.0
195 silly saveTree   | | | +-- json-schema-traverse@0.3.1
195 silly saveTree   | | | `-- json-stable-stringify@1.0.1
195 silly saveTree   | | |   `-- jsonify@0.0.0
195 silly saveTree   | | +-- comment-json@1.1.3
195 silly saveTree   | | | `-- json-parser@1.1.5
195 silly saveTree   | | |   `-- esprima@2.7.3
195 silly saveTree   | | +-- minimist@1.2.0
195 silly saveTree   | | +-- moment@2.17.1
195 silly saveTree   | | +-- path-posix@1.0.0
195 silly saveTree   | | `-- url-parse@1.1.9
195 silly saveTree   | |   +-- querystringify@1.0.0
195 silly saveTree   | |   `-- requires-port@1.0.0
195 silly saveTree   | +-- @jupyterlab/observables@0.2.0
195 silly saveTree   | | `-- @phosphor/messaging@1.3.0
195 silly saveTree   | |   `-- @phosphor/collections@1.2.0
195 silly saveTree   | +-- @phosphor/algorithm@1.2.0
195 silly saveTree   | +-- @phosphor/coreutils@1.3.1
195 silly saveTree   | +-- @phosphor/disposable@1.3.0
195 silly saveTree   | `-- @phosphor/signaling@1.3.0
195 silly saveTree   +-- @nteract/commutable@7.1.4
195 silly saveTree   | +-- immutable@4.0.0-rc.12
195 silly saveTree   | `-- uuid@3.3.3
195 silly saveTree   +-- @nteract/markdown@4.0.3
195 silly saveTree   | +-- @nteract/mathjax@4.0.0
195 silly saveTree   | +-- @nteract/presentational-components@3.0.7
195 silly saveTree   | | +-- @blueprintjs/core@3.18.1
195 silly saveTree   | | +-- @blueprintjs/select@3.10.0
195 silly saveTree   | | `-- react-syntax-highlighter@9.0.1
195 silly saveTree   | `-- react-markdown@4.2.2
195 silly saveTree   +-- @nteract/mathjax@4.0.0
195 silly saveTree   +-- @nteract/outputs@2.3.2
195 silly saveTree   +-- @nteract/plotly@1.49.1
195 silly saveTree   +-- @nteract/transform-vega@6.0.2
195 silly saveTree   | `-- lodash@4.17.15
195 silly saveTree   +-- anser@1.4.8
195 silly saveTree   +-- atom-select-list@0.7.2
195 silly saveTree   +-- escape-carriage@1.3.0
195 silly saveTree   +-- escape-string-regexp@2.0.0
195 silly saveTree   +-- jmp@2.0.0
195 silly saveTree   +-- kernelspecs@2.0.0
195 silly saveTree   +-- lodash@4.17.15
195 silly saveTree   +-- mathjax-electron@3.0.0
195 silly saveTree   +-- mobx-react@6.1.3
195 silly saveTree   +-- mobx@5.14.0
195 silly saveTree   +-- react-dom@16.10.2
195 silly saveTree   +-- react-rangeslider@2.2.0
195 silly saveTree   +-- react-table@6.10.3
195 silly saveTree   +-- react@16.10.2
195 silly saveTree   +-- spawnteract@5.1.0
195 silly saveTree   +-- strip-indent@3.0.0
195 silly saveTree   +-- tildify@2.0.0
195 silly saveTree   +-- uuid@3.3.3
195 silly saveTree   +-- ws@3.3.3
195 silly saveTree   `-- xmlhttprequest@1.8.0
196 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...0.4\r\nComment: https'
196 verbose stack     at JSON.parse (<anonymous>)
196 verbose stack     at parseJson (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
196 verbose stack     at consumeBody.call.then.buffer (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50)
196 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
197 verbose cwd /private/tmp/apm-install-dir-11995-3229-1nbsh38.0jm
198 verbose Darwin 18.7.0
199 verbose argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/arsari/.atom/.apm/.apmrc" "--userconfig" "/Users/arsari/.atom/.apmrc" "install" "https://www.atom.io/api/packages/hydrogen/versions/2.12.1/tarball" "--target=3.1.10" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
200 verbose node v10.2.1
201 verbose npm  v6.2.0
202 error Unexpected end of JSON input while parsing near '...0.4\r\nComment: https'
203 verbose exit [ 1, true ]
~~~
__________________________________________

**Comment by wadethestealth** [comment]
Something is wrong with your installation method. Assuming you are using the Atom GUI and not apm, I would recommend opening an issue over on atom/atom and see if they can help you. Most likely reinstalling atom will work though.

**Comment by arsari** [comment]
Ok. Will check.

**Comment by Gobayli** [comment]
Sam here, the error message showed:

`Installing “Hydrogen@2.12.1” failed.Hide output…

npm WARN deprecated json-parser@1.1.5: `json-parser` is deprecated. Please use `comment-json` instead
npm ERR! Unexpected end of JSON input while parsing near '...ntime":"^6.7.5","babe'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Kopi\.atom\.apm\_logs\2019-10-08T14_45_17_624Z-debug.log`

**Comment by wadethestealth** [comment]
@Gobayli please refer to atom or apm for this issue, hydrogen is not responsible for this issue.
