### ISSUE TITLE
Unexpected end of input

### ISSUE THREAD

**Issue by YugoCode** [nteract/hydrogen#179]
[Enter steps to reproduce below:]

1. I just installed hydrogen successfully and after pressing Alt+Shift+Enter of a simple hello world script I get this error.

**Atom Version**: 1.5.3
**System**: Ubuntu 15.10
**Thrown From**: [Hydrogen](https://github.com/willwhitney/hydrogen) package, v0.7.0

### Stack Trace

Failed to activate the Hydrogen package

```
At Unexpected end of input

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Object.<anonymous> (/home/yugo/.atom/packages/Hydrogen/lib/kernel-manager.coffee:11:22)
    at Object.memoized [as getAvailableKernels] (/home/yugo/.atom/packages/Hydrogen/node_modules/lodash/index.js:7912:27)
    at /home/yugo/.atom/packages/Hydrogen/lib/autocomplete-provider.coffee:6:37
    at Object.<anonymous> (/home/yugo/.atom/packages/Hydrogen/lib/autocomplete-provider.coffee:5:41)
    at Object.<anonymous> (/home/yugo/.atom/packages/Hydrogen/lib/autocomplete-provider.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/yugo/.atom/packages/Hydrogen/lib/main.coffee:13:24)
    at Object.<anonymous> (/home/yugo/.atom/packages/Hydrogen/lib/main.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:720:27)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:172:16)
    at /usr/share/atom/resources/app.asar/src/package.js:800:25
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:20)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
```

### Commands

```
  2x -0:00.8.0 hydrogen:run (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "script"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Hydrogen, v0.7.0

# Dev
No dev packages
```

**Comment by YugoCode** [comment]
I didn't notice that `pip install ipython[notebook]` terminated with an error, I fixed it and now it is working.
