### ISSUE TITLE
Failed to activate the Hydrogen package

### ISSUE THREAD

**Issue by jdknox** [nteract/hydrogen#180]
It seems like Hydrogen now requires libzmq5 instead of libzmq3, is this correct?  Hydrogen (0.7.0) was working fine for me until I updated to 0.7.1.  I cannot roll back now, however, since I get the same error.  I'm trying to figure out if I did something else to break this on my end...

[Enter steps to reproduce below:]

```
$ apm install hydrogen
Installing hydrogen to /home/knox/.atom/packages l✓
$ atom .
# Failure then occurs when running hydrogen in any python file
```

**Atom Version**: 1.5.3
**System**: Ubuntu Xenial
**Thrown From**: [Hydrogen](https://github.com/willwhitney/hydrogen) package, v0.7.1

### Stack Trace

Failed to activate the Hydrogen package

```
At libzmq.so.5: cannot open shared object file: No such file or directory

Error: libzmq.so.5: cannot open shared object file: No such file or directory
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:137:20)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at bindings (/home/knox/.atom/packages/Hydrogen.old/node_modules/zmq/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/knox/.atom/packages/Hydrogen.old/node_modules/zmq/lib/index.js:6:30)
    at Module.contents.overrideModuleCompile.Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.keys.forEach.Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/knox/.atom/packages/Hydrogen.old/node_modules/zmq/index.js:2:18)
    at Module.contents.overrideModuleCompile.Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.keys.forEach.Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/knox/.atom/packages/Hydrogen.old/lib/main.coffee:4:7)
    at Object.<anonymous> (/home/knox/.atom/packages/Hydrogen.old/lib/main.coffee:1:1)
    at Module.contents.overrideModuleCompile.Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.keys.forEach.Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:720:27)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:172:16)
    at /usr/share/atom/resources/app.asar/src/package.js:800:25
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:20)
    at __bind (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.__bind (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:01.0 hydrogen:run (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-python"
    ],
    "themes": [
      "one-dark-ui",
      "pumpkin-syntax"
    ]
  },
  "Hydrogen": {
    "languageMappings": "{\"magicpython\": \"python\"}"
  }
}
```

### Installed Packages

```coffee
# User
Hydrogen, v0.7.1
MagicPython, v0.5.8
autocomplete-python, v1.6.1
browser-plus, v0.0.54
color-picker, v2.1.1
language-latex, v0.6.1
latex, v0.29.0
latexer, v0.3.0
linter, v1.11.3
linter-chktex, v1.2.5
linter-flake8, v1.12.0
live-doc-viewer, v1.0.6
method-separator, v0.1.4
minimap, v4.19.0
pigments, v0.24.2
pumpkin-syntax, v0.1.0
python-indent, v0.4.0
python-iresolve, v0.0.3
python-tools, v0.6.7
react, v0.14.1

# Dev
No dev packages
```

**Comment by rgbkrk** [comment]
We tend to require `libzmq3`, there is no libzmq 5 (4.1 was the last release of libzmq, with 4.2 likely to come down the pipe relatively soon). What does `apt-cache search libzmq` show?

**Comment by jdknox** [comment]
For some reason, the `libzmq` 4.1 lib is named libzmq.so.5 on my machine.  I have anaconda installed and it uses the same naming convention in my conda env lib directory:
```
$ ls /path/to/anaconda/atom/lib/libzmq*
libzmq.a
libzmq.la
libzmq.so
libzmq.so.5
libzmq.so.5.0.0

$ conda list
# packages in environment at /path/to/anaconda:
#
# . . .  
zeromq                    4.1.3                         
# . . .
```
Even zeromq.org [references](http://zeromq.org/build:_start) libzmq.so.5 for zeromq 4.1, which I admit, confuses me (see Running Example heading about halfway down that link).

Here is the result of running the apt-cache search, although I suspect the anaconda libs might override this:
```
$ apt-cache search libzmq
libjeromq-java - Java implementation of the ZeroMQ messaging library
libxs-compat-libzmq-dev - Crossroads I/O 'libzmq' compatibility library (header files)
libxs-compat-libzmq1 - Crossroads I/O 'libzmq' compatibility library (shared library)
libzeromq-perl - messaging library using ZeroMQ
libzmq-dbg - lightweight messaging kernel (debugging symbols)
libzmq-dev - lightweight messaging kernel (development files)
libzmq-java - ZeroMQ Java bindings (jzmq)
libzmq-java-doc - Documentation for ZeroMQ Java bindings (jzmq)
libzmq-jni - ZeroMQ Java bindings (jzmq)
libzmq1 - lightweight messaging kernel (shared library)
libzmq3 - lightweight messaging kernel (shared library)
libzmq3-dbg - lightweight messaging kernel (debugging symbols)
libzmq3-dev - lightweight messaging kernel (development files)
libzmqpp-dev - High-level C++ bindings for zeromq3 - development files
libzmqpp3 - High-level C++ bindings for zeromq3
```

**Comment by jdknox** [comment]
I've got Hydrogen working again!  It feels like a blindfold has been lifted; Hydrogen has spoiled me. :-)

For what it's worth, I removed all traces of zeromq, ipython and Hydrogen, reinstalled them all using my anaconda env instead of using pip, then deleted atom's compile-cache folder.  In the end I had to install Hydrogen 0.7.0 and zeromq 4.0.5 to get it to work.  Thanks for helping me look into this.

Should I close this, or could there be a genuine issue with Hydrogen 0.7.1?

**Comment by n-riesco** [comment]
On 01/03/16 07:27, Jeff wrote:
> [...] then deleted atom's compile-cache folder.


Personally, I think what fixed your problem was removing the cache folder.


> Should I close this, or could there be a genuine issue with Hydrogen 0.7.1?


Have you tried to upgrade to 0.7.1? If you do so, make sure the libraries in your environment (pip or anaconda) are the same as those used to install Atom and the plugins.

**Comment by slavaGanzin** [comment]
Just curious. Would ```apm rebuild``` fix this issue?

**Comment by n-riesco** [comment]
A word of caution: `apm rebuild` should be run on the same folder Hydrogen was installed.

**Comment by hastebrot** [comment]
I have the same problem.

- Ubuntu 16.04
- Atom 1.11.2
- Hydrogen 0.15.0

**Comment by hastebrot** [comment]
Fixed, by installing `libzmq.so.1` vis `sudo apt install libzmq-dev`.

**Comment by Ben-Gillman** [comment]
I am having this same issue but I am unable to install Lodash directly. I need to install it from source. 

When I try to run Python code using Hydrogen (Packages -> Hydrogen -> Run) I receive the below error:
`Cannot find module 'lodash'
`

I am behind a proxy and cannot simply run `$ npm install lodash --save` as described [here](http://stackoverflow.com/questions/27431187/cannot-find-module-lodash)

I have manually downloaded lodash from [here](https://github.com/lodash/lodash/releases/tag/4.15.0-npm-packages) and put them on my computer in this directory "C:\Users\...\AppData\Local\atom\app-1.12.4\resources\lodash-4.15.0-npm-packages"

Is there a way I can resolve this error given I have the source file in that location?

**Comment by lgeiger** [comment]
@Ben-Gillman In Hydrogen 1.0 we changed the installation method so this issue isn't relevant anymore.

What happens if you install hydrogen with  `apm install hydrogen`?

**Comment by Ben-Gillman** [comment]
I am unable to run `apm install hydrogen` because I am behind this proxy. When I run this code I receive the error `Request for package information failed: tunneling socket could not be established, cause=write EPROTO 0:error...`

I had to install Hydrogen 1.0 from source, from [here](https://github.com/nteract/hydrogen/releases/tag/v1.0.0). It lives in "C:\Users\...\AppData\Local\atom\hydrogen-1.0.0"

**Comment by lgeiger** [comment]
Just copying the hydrogen folder won't install all the dependencies.

I would try install the dev version as described [here](https://github.com/nteract/hydrogen#development). But I'm not sure if this works inside a proxy.

**Comment by Ben-Gillman** [comment]
@lgeiger Unfortunately, I receive the same error when I run `apm develop hydrogen` as I do when I run `apm install hydrogen`.

I am willing to install the dependencies manually if there are not too many
