### ISSUE TITLE
When Python global path is not correctly defined no error message is shown and Hydrogen silently fails

### ISSUE THREAD

**Issue by jhack-jos** [nteract/hydrogen#1802]
### Prerequisites

* [ ] Have you checked the solutions in our [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) for common problems ? YES
* [ ] Have you checked that your issue [isn't already filed](https://github.com/nteract/hydrogen/issues) ? YES

### Description

If the Python global path is not correctly set, Hydrogen fails without showing any message to the Atom user.

### Steps to Reproduce

1. Install Anaconda with the default settings (also allowing registration of Anaconda Python to the global path)
==> Python fails to be added to the global path and cmd -> Python says "File not found"
2. Install Atom
3. Install Hydrogen
4. Install IJavascript
   conda install nodejs
   npm -g IJavascript
   ijsinstall
5. Hydrogen: Update Kernels
6. IJavascript found!
7. Open a js file and run Hydrogen: Run from the command palette or SHIFT+ENTER
==> cursor goes to the next line and nothing happens
8. What happened?!
   a) CTRL+SHIFT+I
   b) Look into the console
   c) See that an error was thrown related to "Python

### Versions

OS version:
Windows 10

> `atom --version`

`1.41.0`, the latest Atom version

```

> `apm --version`
<!-- Paste the the output of `apm --version` in the backticks below -->
```

```

Hydrogen version:
<!-- You can check this information in the settings view or via running `apm show hydrogen` -->
[2.31.1] , the latest Hydrogen version as of now

### Plugins

Have you installed and activated any of the Hydrogen plugins below ?
- [ ] hydrogen-python
- [ ] Hydrogen Launcher
- [ ] Data Explorer
None of them

### Logs

[Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html).]
Uncaught (in promise) Error: UNKNOWN: unknown error, lstat 'C:\Users\myUser\AppData\Local\Microsoft\WindowsApps\python.EXE'
    at Object.realpathSync (fs.js:1435:7)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at pathext.some.ext (C:\Users\myUser\.atom\packages\Hydrogen\node_modules\jupyter-paths\index.js:55:44)
    at Array.some (<anonymous>)
    at PATH.some.bin (C:\Users\myUser\.atom\packages\Hydrogen\node_modules\jupyter-paths\index.js:48:20)
    at Array.some (<anonymous>)
    at guessSysPrefix (C:\Users\myUser\.atom\packages\Hydrogen\node_modules\jupyter-paths\index.js:44:8)
    at dataDirs (C:\Users\myUser\.atom\packages\Hydrogen\node_modules\jupyter-paths\index.js:200:19)
    at Promise (C:\Users\myUser\.atom\packages\Hydrogen\node_modules\jupyter-paths\index.js:196:15)
    at new Promise (<anonymous>)
    at Object.dataDirs (C:\Users\myUser\.atom\packages\Hydrogen\node_modules\jupyter-paths\index.js:193:12)
    at Object.findAll (C:\Users\myUser\.atom\packages\Hydrogen\node_modules\kernelspecs\lib\traverse.js:91:13)
    at KernelManager.<anonymous> (file:///C:/Users/myUser/.atom/packages/Hydrogen/lib/kernel-manager.js:89:34)
    at Generator.next (<anonymous>)
    at step (C:\Users\myUser\.atom\packages\Hydrogen\lib\kernel-manager.js:11:273)
    at C:\Users\myUser\.atom\packages\Hydrogen\lib\kernel-manager.js:11:443
    at new Promise (<anonymous>)
    at KernelManager.<anonymous> (C:\Users\myUser\.atom\packages\Hydrogen\lib\kernel-manager.js:11:99)
    at KernelManager.<anonymous> (file:///C:/Users/myUser/.atom/packages/Hydrogen/lib/kernel-manager.js:136:36)
    at Generator.next (<anonymous>)
    at step (C:\Users\myUser\.atom\packages\Hydrogen\lib\kernel-manager.js:11:273)
    at C:\Users\myUser\.atom\packages\Hydrogen\lib\kernel-manager.js:11:443
    at new Promise (<anonymous>)
    at KernelManager.<anonymous> (C:\Users\myUser\.atom\packages\Hydrogen\lib\kernel-manager.js:11:99)
    at KernelManager.<anonymous> (file:///C:/Users/myUser/.atom/packages/Hydrogen/lib/kernel-manager.js:104:17)
    at Generator.next (<anonymous>)
    at step (C:\Users\myUser\.atom\packages\Hydrogen\lib\kernel-manager.js:11:273)
    at C:\Users\myUser\.atom\packages\Hydrogen\lib\kernel-manager.js:11:443
    at new Promise (<anonymous>)
    at KernelManager.<anonymous> (C:\Users\myUser\.atom\packages\Hydrogen\lib\kernel-manager.js:11:99)

### Expected behavior

[I expected a message to be shown saying the following:
"Python is not installed or Python is not corretly registered in the global system PATH. Please install Python or add it to your global system PATH if already installed for Hydrogen to correctly connect to the kernel.]

### Screenshots

[If applicable, add screenshots to help explain your problem.]

### Additional context

[Add any other context about the problem here.]

**Comment by wadethestealth** [comment]
I don't know if we can truly tell that python path is incorrect. But we could do a catch all that let's users know python was not installed correctly and provide a stack trace. I'll look into for you.

**Comment by jhack-jos** [comment]
@wadethestealth Thank you! I think that would be a great addiction to have for all the users that are experiencing problems during the installation.

**Comment by jj-404** [comment]
Hi, do you have any new information on how to resolve this bug?
Thank you

**Comment by wadethestealth** [comment]
@jj-404 you set your python path to a valid install of python. This issue is only open to track better reporting of these errors and is not an actual issue.

**Comment by JonnytheMarketer** [comment]
> @jj-404 you set your python path to a valid install of python. This issue is only open to track better reporting of these errors and is not an actual issue.

How do we change python path?

**Comment by wadethestealth** [comment]
@jonnythemarketer it's in your systems environment variables or your kernel.json file depending on how you set everything up. A quick google search can show you where to locate both of these options.

**Comment by JonnytheMarketer** [comment]
@wadethestealth , thanks for the help. I've updated the Path variable. However, hydrogren is still pointing to the same location in OPs screenshot 'Microsoft\WindowsApps\python.exe'. This is not the path listed in my environment variable.

**Comment by wadethestealth** [comment]
@jonnythemarketer there are two types of environment variables one for system wide and one for a specific user. Check both for that path and modify to the correct python path

**Comment by JonnytheMarketer** [comment]
@wadethestealth , Sorry I'm an idiot. There are two OK buttons you have to hit to save changes, the updates werent being saved because I was closing menus before hitting the second ok. Confirming this fixed my problem. I hit a slew of other problems but Google searches solved all of those.

Thanks again for your help!
