### ISSUE TITLE
Unable to install Hydrogen 2.13.1

### ISSUE THREAD

**Issue by mdsutcliffe** [nteract/hydrogen#1804]
[Enter steps to reproduce:]
I first received this error when trying to start hydrogen:
https://github.com/nteract/hydrogen/issues/1779
I attempted to resolve it using the linked solution (adding a line to dependencies in .atom packages)
That didn't fix it, so I uninstalled Hydrogen, restarted my computer, and then followed the steps below.

1. Atom preferences
2. Install tab
3. Install Hydrogen

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.13.1

### Stack Trace

Uncaught SyntaxError: Unexpected token export

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

/Users/mdsutcliffe/.atom/packages/Hydrogen/node_modules/react-syntax-highlighter/dist/esm/styles/prism/vs.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { export default {
                                                                                                                                                           ^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:79:7)
    at NativeCompileCache.runInThisContext (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146322)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147206)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/syntax-highlighter/index.js:15:30)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/syntax-highlighter/index.js:46:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/components/source.js:15:46)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/components/source.js:51:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/components/input.js:16:18)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/components/input.js:52:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
```

### Commands

```
```

### Non-Core Packages

```
Hydrogen 2.13.1 
```

**Comment by mdsutcliffe** [comment]
Note: Also happens on a fresh install of Atom.

**Comment by jazzlw** [comment]
This happened to me as well, after upgrading to 2.13.1 (I believe from 2.13.0). Hydrogen was working fine before upgrade.
I tried downgrading to 2.13.0 and it didn't help.
Downgraded to 2.8.0 and it seems to be working again.

**Comment by wadethestealth** [comment]
Just updated from 2.13.0 to 2.13.1 and I am also seeing this. I'll try to investigate.

**Comment by Xavier-JS** [comment]
I've got the same problem from updating it to 2.13.1. How do I downgrade to a lower version?

**Comment by jazzlw** [comment]
@Xavier-JS 
apm install hydrogen@2.8.0

**Comment by wadethestealth** [comment]
Discussion about hot-fixing the issue: https://nteract.slack.com/archives/C0HSD7MMZ/p1572409625104700.

Unfortunately, the assumed working solution doesn't work since nteract/outputs still uses latest package, and thus I have reverted hydrogen v2.13.2.

Will investigate this again tomorrow.

**Comment by quigsj** [comment]
Is this a recent issue? I did not have this problem two days ago.

**Comment by wadethestealth** [comment]
@quigsj yes see the first referenced issue

**Comment by wadethestealth** [comment]
The offending PR should be reversed now, and you should be able to install 2.13.1. Thanks for your patience.

**Comment by pietermdevries** [comment]
This is still continuing.

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.13.1


### Stack Trace

Uncaught SyntaxError: Unexpected token export

```
At /private/var/folders/p8/k7qb4ln558ng_mp839yppl8c0000gn/T/AppTranslocation/B9688DBD-EBB5-450C-8FAA-CA0F5DB6D7FE/d/Atom.app/Contents/Resources/app/static/<embedded>:11

/Users/pieterdevries/.atom/packages/Hydrogen/node_modules/react-syntax-highlighter/dist/esm/styles/prism/vs.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { export default {
                                                                                                                                                           ^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:74:7)
    at NativeCompileCache.runInThisContext (/private/var/folders/p8/k7qb4ln558ng_mp839yppl8c0000gn/T/AppTranslocation/B9688DBD-EBB5-450C-8FAA-CA0F5DB6D7FE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146322)
    at Module.get_Module._compile (/private/var/folders/p8/k7qb4ln558ng_mp839yppl8c0000gn/T/AppTranslocation/B9688DBD-EBB5-450C-8FAA-CA0F5DB6D7FE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147206)
    at Object.value [as .js] (/private/var/folders/p8/k7qb4ln558ng_mp839yppl8c0000gn/T/AppTranslocation/B9688DBD-EBB5-450C-8FAA-CA0F5DB6D7FE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/private/var/folders/p8/k7qb4ln558ng_mp839yppl8c0000gn/T/AppTranslocation/B9688DBD-EBB5-450C-8FAA-CA0F5DB6D7FE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/syntax-highlighter/index.js:15:30)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/syntax-highlighter/index.js:46:3)
    at Module.get_Module._compile (/private/var/folders/p8/k7qb4ln558ng_mp839yppl8c0000gn/T/AppTranslocation/B9688DBD-EBB5-450C-8FAA-CA0F5DB6D7FE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/private/var/folders/p8/k7qb4ln558ng_mp839yppl8c0000gn/T/AppTranslocation/B9688DBD-EBB5-450C-8FAA-CA0F5DB6D7FE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/private/var/folders/p8/k7qb4ln558ng_mp839yppl8c0000gn/T/AppTranslocation/B9688DBD-EBB5-450C-8FAA-CA0F5DB6D7FE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/components/source.js:15:46)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/components/source.js:51:3)
    at Module.get_Module._compile (/private/var/folders/p8/k7qb4ln558ng_mp839yppl8c0000gn/T/AppTranslocation/B9688DBD-EBB5-450C-8FAA-CA0F5DB6D7FE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/private/var/folders/p8/k7qb4ln558ng_mp839yppl8c0000gn/T/AppTranslocation/B9688DBD-EBB5-450C-8FAA-CA0F5DB6D7FE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/private/var/folders/p8/k7qb4ln558ng_mp839yppl8c0000gn/T/AppTranslocation/B9688DBD-EBB5-450C-8FAA-CA0F5DB6D7FE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/components/input.js:16:18)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/components/input.js:52:3)
    at Module.get_Module._compile (/private/var/folders/p8/k7qb4ln558ng_mp839yppl8c0000gn/T/AppTranslocation/B9688DBD-EBB5-450C-8FAA-CA0F5DB6D7FE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
```

### Commands

```
```

### Non-Core Packages

```
Hydrogen 2.13.1 
python-black 0.7.0 
script 3.18.1 
```

**Comment by Seviks** [comment]
This is still a problem.

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: WS24
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.13.1


### Stack Trace

Uncaught SyntaxError: Unexpected token export

```
At C:\Dev\Atom\resources\app\static\<embedded>:11

C:\Dev\.atom\packages\Hydrogen\node_modules\react-syntax-highlighter\dist\esm\styles\prism\vs.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { export default {
                                                                                                                                                           ^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:74:7)
    at NativeCompileCache.runInThisContext (C:/Dev/Atom/resources/app/static/<embedded>:11:146322)
    at Module.get_Module._compile (C:/Dev/Atom/resources/app/static/<embedded>:11:147206)
    at Object.value [as .js] (C:/Dev/Atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (C:/Dev/Atom/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/syntax-highlighter/index.js:15:30)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/syntax-highlighter/index.js:46:3)
    at Module.get_Module._compile (C:/Dev/Atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (C:/Dev/Atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (C:/Dev/Atom/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/components/source.js:15:46)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/components/source.js:51:3)
    at Module.get_Module._compile (C:/Dev/Atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (C:/Dev/Atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (C:/Dev/Atom/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/components/input.js:16:18)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/components/input.js:52:3)
    at Module.get_Module._compile (C:/Dev/Atom/resources/app/static/<embedded>:11:147429)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-language-r 1.4.8 
Hydrogen 2.13.1 
hydrogen-launcher 1.2.2 
ide-python 1.5.0 
ide-r 0.1.8 
language-stata 1.7.3 
minimap 4.29.9 
platformio-ide-terminal 2.10.0 
```

**Comment by wadethestealth** [comment]
This appears to still be an issue, and I am currently trying to investigate the fix.

**Comment by mashu** [comment]
Whats the temporal walk-around? Downgrade to previous Hydrogen 2.12 ? How to do that from Atom?

**Comment by wadethestealth** [comment]
2.12 - 2.9 may 2.8 does. Use the apm command above @mashu

**Comment by wadethestealth** [comment]
This issue is technically solved, but now all users will face #1811, so do not reinstall just yet and follow #1811 for any further updates.

**Comment by wadethestealth** [comment]
Everyone please reinstall hydrogen now, publish has been fixed

**Comment by SemanticBeeng** [comment]
[Enter steps to reproduce:]

1. Fresh Atom install


**Atom**: 1.42.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 16.04.2
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.13.1


### Stack Trace

Failed to activate the Hydrogen package

```
At Invalid or unexpected token

/home/nickdsc/.atom/packages/Hydrogen/node_modules/github-markdown-css/github-markdown.css:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { @font-face {
                                                                                                                                                           ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:79:7)
    at NativeCompileCache.runInThisContext (/usr/share/atom/resources/app/static/<embedded>:11:146322)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147206)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/markdown/lib/markdown-render.js:18:1)
    at /packages/Hydrogen/node_modules/@nteract/markdown/lib/markdown-render.js:31:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/markdown/lib/index.js:6:43)
    at /packages/Hydrogen/node_modules/@nteract/markdown/lib/index.js:11:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/markdown.js:13:36)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/markdown.js:27:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/index.js:11:18)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/index.js:20:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/index.js:24:28)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/index.js:27:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/lib/components/result-view/display.js:5:38)
    at /packages/Hydrogen/lib/components/result-view/display.js:80:23)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/lib/store/output.js:8:25)
    at /packages/Hydrogen/lib/store/output.js:62:33)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/lib/store/watch.js:3:30)
    at /packages/Hydrogen/lib/store/watch.js:10:32)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/lib/store/watches.js:5:43)
    at /packages/Hydrogen/lib/store/watches.js:13:34)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/lib/kernel.js:14:28)
    at /packages/Hydrogen/lib/kernel.js:187:28)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/lib/kernel-manager.js:7:37)
    at /packages/Hydrogen/lib/kernel-manager.js:178:35)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/lib/store/index.js:21:36)
    at /packages/Hydrogen/lib/store/index.js:297:31)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/lib/utils.js:10:30)
    at /packages/Hydrogen/lib/utils.js:293:2)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/lib/panes/inspector.js:5:26)
    at /packages/Hydrogen/lib/panes/inspector.js:11:35)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/lib/main.js:13:26)
    at /packages/Hydrogen/lib/main.js:574:24)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:689402)
    at Package.requireMainModule (/usr/share/atom/resources/app/static/<embedded>:11:3220707)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:3208691)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.o (/usr/share/atom/resources/app/static/<embedded>:14:1879)
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1211760)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1213201)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:349017)
    at KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:1252387)
    at KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1248521)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:284591)
```

### Commands

```
     -2:10.3.0 hydrogen:run-cell (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.6.0 
Hydrogen 2.13.1 
hydrogen-launcher 1.2.2 
hydrogen-python 0.0.8 
ide-python 1.5.0 
MagicPython 1.1.1 
script 3.25.0 
```
