### ISSUE TITLE
Cannot find module 'react-syntax-highlighter/...'

### ISSUE THREAD

**Issue by jesusloplar** [nteract/hydrogen#1813]
I have tried to use this workaround https://github.com/nteract/hydrogen/issues/1768#issue-491598253

I am having a problem with the 'react-syntax-highlighter' module. Could you help me out, please?

[Enter steps to reproduce:]

1. Open atom from terminal with `atom .`
2. Try to execute a line of code in an R file.

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.1
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.13.1

### Stack Trace

Failed to activate the Hydrogen package

```
At Cannot find module 'react-syntax-highlighter/dist/esm/styles/prism/vs'

Error: Cannot find module 'react-syntax-highlighter/dist/esm/styles/prism/vs'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/syntax-highlighter/index.js:15:30)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/syntax-highlighter/index.js:46:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/components/source.js:15:46)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/components/source.js:51:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/components/input.js:16:18)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/components/input.js:52:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/index.js:10:17)
    at /packages/Hydrogen/node_modules/@nteract/presentational-components/lib/index.js:23:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
```

### Commands

```
     -0:09.5.0 hydrogen:run-and-move-down (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
auto-update-packages 1.0.1 
autocomplete-R 0.6.0 
busy-signal 2.0.1 
file-icons 2.1.36 
highlight-selected 0.16.0 
Hydrogen 2.13.1 
hydrogen-cell-separator 0.4.1 
hydrogen-python 0.0.8 
ide-python 1.5.0 
ide-r 0.1.8 
intentions 1.1.5 
language-r 0.4.2 
linter 2.3.1 
linter-flake8 2.4.0 
linter-ui-default 1.8.0 
open-recent 5.0.0 
pigments 0.40.2 
platformio-ide-terminal 2.10.0 
react 0.18.0 
teletype 0.13.4 
```

**Comment by wadethestealth** [comment]
See #1812.
