### ISSUE TITLE
Uncaught Error: Cannot find module './existing-kernel-picker'

### ISSUE THREAD

**Issue by jakewilliami** [nteract/hydrogen#1822]
[Enter steps to reproduce:]

1. Try installing Hydrogen 2.13.1
2. Gets error.

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.6
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.13.1

### Stack Trace

Uncaught Error: Cannot find module './existing-kernel-picker'

```
At internal/modules/cjs/loader.js:586

Error: Cannot find module './existing-kernel-picker'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/lib/main.js:63:29)
    at /packages/Hydrogen/lib/main.js:631:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:688212)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3220564)
    at Package.activateConfig (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3209852)
    at PackageManager.packageHasSettings (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:933491)
    at PackageCard.hasSettings (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2612928)
    at PackageCard.updateSettingsState (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2603208)
    at PackageCard.updateInterfaceState (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2603031)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2611161
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2613179
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1211909)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1213350)
    at PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:942948)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:940080
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:934610)
    at n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1128169)
    at e.bufferStream (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1128257)
    at Socket.e.on (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1126925)
    at Socket.emit (events.js:187:15)
    at Pipe._handle.close (net.js:606:12)
```

### Commands

```
     -3:25.8.0 core:confirm (input.hidden-input)
  2x -0:50.8.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-language-r 1.4.8 
Hydrogen 2.13.1 
ide-r 0.1.8 
styri-syntax 1.0.0 
syrinx-dark-syntax 0.5.0 
```

**Comment by wadethestealth** [comment]
how are you attempting to install hydrogen? Have you tried using the command line? This bug is most likely unique to you and your install method/environment.

**Comment by wadethestealth** [comment]
Stale

**Comment by jakewilliami** [comment]
I cannot remember the details of this issue but I think it was simply a kernel issue (i.e., didn't have appropriate kernels) rather than a Hydrogen issue.  Sorry for issuing this in Hydrogen.
