### ISSUE TITLE
Uncaught Error: Cannot find module './lodash'

### ISSUE THREAD

**Issue by Kopp27486** [nteract/hydrogen#1823]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.1
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.13.1

### Stack Trace

Uncaught Error: Cannot find module './lodash'

```
At internal/modules/cjs/loader.js:586

Error: Cannot find module './lodash'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/lodash/index.js:1:173)
    at /packages/Hydrogen/node_modules/lodash/index.js:2:3)
    at Module.get_Module._compile (<embedded>:11:147429)
    at Object.value [as .js] (<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (<embedded>:11:146745)
    at /packages/Hydrogen/lib/main.js:13:15)
    at /packages/Hydrogen/lib/main.js:631:3)
    at Module.get_Module._compile (<embedded>:11:147429)
    at Object.value [as .js] (<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (<embedded>:1:688212)
    at Package.requireMainModule (<embedded>:11:3220564)
    at Package.activateConfig (<embedded>:11:3209852)
    at PackageManager.packageHasSettings (<embedded>:11:933491)
    at PackageCard.hasSettings (<embedded>:14:2612928)
    at PackageCard.updateSettingsState (<embedded>:14:2603208)
    at PackageCard.updateInterfaceState (<embedded>:14:2603031)
    at <embedded>:14:2611161
    at <embedded>:14:2613179
    at Function.simpleDispatch (<embedded>:11:1211909)
    at Emitter.emit (<embedded>:11:1213350)
    at PackageManager.emitPackageEvent (<embedded>:11:942948)
    at <embedded>:11:940080
    at r (<embedded>:11:934610)
    at n (<embedded>:14:1128169)
    at ChildProcess.o.process.on.e (<embedded>:14:1128375)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)

```

### Commands

```
     -2:34.5.0 settings-view:open (input.hidden-input)
     -2:29.2.0 core:confirm (input.hidden-input)
  8x -0:13.9.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-latex 0.8.11 
autoclose-html 0.23.0 
busy-signal 2.0.1 
color-picker 2.3.0 
emmet 2.4.3 
erb-helper 1.1.0 
erb-snippets 1.1.0 
file-icons 2.1.36 
Hydrogen 2.13.1 
hydrogen-python 0.0.8 
ide-python 1.5.0 
indent-guide-improved 1.4.13 
intentions 1.1.5 
language-haml 0.32.1 
language-latex 1.2.0 
language-r 0.4.2 
latex 0.50.2 
latex-completions 0.3.6 
linter 2.3.1 
linter-python-pep8 0.2.0 
linter-ui-default 1.8.0 
minimap 4.29.9 
minimap-pigments 0.2.2 
open-in-browsers 0.0.30 
pdf-view 0.72.0 
pigments 0.40.2 
pretty-json 2.1.2 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by wadethestealth** [comment]
how are you attempting to install hydrogen? Have you tried using the command line? This bug is most likely unique to you and your install method/environment.

**Comment by Kopp27486** [comment]
I’ve done it with the package installer in ATOM, but it works now. I Installed the missing package seperately and it works now. 

Thank you for your reply.
