### ISSUE TITLE
Installation of hydrogen 2.13.1 on Atom 1.34.0 64 bits for linux failed.

### ISSUE THREAD

**Issue by Fercho120** [nteract/hydrogen#1844]
Hi I've used Hydrogen on Atom for a few years, nevertheless I was working with other tools so stopped using it for a while, now I just needed to do some stuff on jupyter so I tried to update it, to 2.13.1, since the update failed and here in hydrogen's github says that the build is passing, I've uninstalled Hydrogen and trying to reinstalling it, but that also doesn't worked. Do you have any idea about this being an Hydrogen or Atom Issue? This is my Atom's console error log:

Installing package hydrogen failed Error: Installing “hydrogen@2.13.1” failed.
    at /usr/share/atom/resources/app/static/<embedded>:11:917154
    at r (/usr/share/atom/resources/app/static/<embedded>:11:911606)
    at o (/usr/share/atom/resources/app/static/<embedded>:14:1037724)
    at t.bufferStream (/usr/share/atom/resources/app/static/<embedded>:14:1037878)
    at Socket.e.on (/usr/share/atom/resources/app/static/<embedded>:14:1036480)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12) 
> zeromq@5.2.0 install /tmp/apm-install-dir-1191116-16603-194nsgl.5x64/node_modules/Hydrogen/node_modules/zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)

npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
module.js:538
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-1191116-16603-194nsgl.5x64/node_modules/Hydrogen/node_modules/zeromq/scripts/prebuild-install.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
module.js:538
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-1191116-16603-194nsgl.5x64/node_modules/Hydrogen/node_modules/zeromq/scripts/preinstall.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-1191116-16603-194nsgl.5x64/package.json'
npm WARN react-rangeslider@2.2.0 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN apm-install-dir-1191116-16603-194nsgl.5x64 No description
npm WARN apm-install-dir-1191116-16603-194nsgl.5x64 No repository field.
npm WARN apm-install-dir-1191116-16603-194nsgl.5x64 No README data
npm WARN apm-install-dir-1191116-16603-194nsgl.5x64 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq@5.2.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@5.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fercho/.atom/.apm/_logs/2019-12-16T21_31_25_260Z-debug.log

Thanks for your help!

**Comment by wadethestealth** [comment]
Related to #1776, but I closed it there because the reporter did not respond. I believe this is an issue related to a bad installation of apm.

**Comment by wadethestealth** [comment]
I could be wrong, but this also may be a side effect of us using zeromq v5 instead of v6. I think until we upgrade there is no way of telling, but I am going to work on our upgrade, and hopefully either a re-installation or this upgrade resolves the issue.

**Comment by wadethestealth** [comment]
@n-riesco do you know if this is zeromq version related?

**Comment by n-riesco** [comment]
@wadethestealth Hydrogen is still using zeromq v5.
I installed Hydrogen on Ubuntu 18.04 this week without a problem.
The error is triggered while running the script to download the zeromq binary.

@Fercho120 Have you tried to install Hydrogen again? This may just be a temporary network failure.

**Comment by karldw** [comment]
For what it's worth, I'm running into a very similar installation error with hydrogen 0.14.1 on ubuntu 20.04. It seems like issue #1922 is also similar. If I can do anything to help debug, let me know.

<details>

<summary>
Tail of `apm install hydrogen --verbose`
</summary>

```
Making install in doc
make[1]: Entering directory '/tmp/apm-install-dir-2020419-60087-isha57.umxt/node_modules/Hydrogen/node_modules/zeromq/zmq/zeromq-4.2.2/doc'
make[2]: Entering directory '/tmp/apm-install-dir-2020419-60087-isha57.umxt/node_modules/Hydrogen/node_modules/zeromq/zmq/zeromq-4.2.2/doc'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Leaving directory '/tmp/apm-install-dir-2020419-60087-isha57.umxt/node_modules/Hydrogen/node_modules/zeromq/zmq/zeromq-4.2.2/doc'
make[1]: Leaving directory '/tmp/apm-install-dir-2020419-60087-isha57.umxt/node_modules/Hydrogen/node_modules/zeromq/zmq/zeromq-4.2.2/doc'
make[1]: Entering directory '/tmp/apm-install-dir-2020419-60087-isha57.umxt/node_modules/Hydrogen/node_modules/zeromq/zmq/zeromq-4.2.2'
make[2]: Entering directory '/tmp/apm-install-dir-2020419-60087-isha57.umxt/node_modules/Hydrogen/node_modules/zeromq/zmq/zeromq-4.2.2'
 /usr/bin/mkdir -p '/tmp/apm-install-dir-2020419-60087-isha57.umxt/node_modules/Hydrogen/node_modules/zeromq/scripts/../zmq/include'
 /usr/bin/mkdir -p '/tmp/apm-install-dir-2020419-60087-isha57.umxt/node_modules/Hydrogen/node_modules/zeromq/scripts/../zmq/lib/pkgconfig'
 /usr/bin/install -c -m 644 include/zmq.h include/zmq_utils.h '/tmp/apm-install-dir-2020419-60087-isha57.umxt/node_modules/Hydrogen/node_modules/zeromq/scripts/../zmq/include'
 /usr/bin/install -c -m 644 src/libzmq.pc '/tmp/apm-install-dir-2020419-60087-isha57.umxt/node_modules/Hydrogen/node_modules/zeromq/scripts/../zmq/lib/pkgconfig'
 /usr/bin/mkdir -p '/tmp/apm-install-dir-2020419-60087-isha57.umxt/node_modules/Hydrogen/node_modules/zeromq/scripts/../zmq/lib'
 /bin/bash ./libtool   --mode=install /usr/bin/install -c   src/libzmq.la '/tmp/apm-install-dir-2020419-60087-isha57.umxt/node_modules/Hydrogen/node_modules/zeromq/scripts/../zmq/lib'
libtool: install: /usr/bin/install -c src/.libs/libzmq.lai /tmp/apm-install-dir-2020419-60087-isha57.umxt/node_modules/Hydrogen/node_modules/zeromq/scripts/../zmq/lib/libzmq.la
libtool: install: /usr/bin/install -c src/.libs/libzmq.a /tmp/apm-install-dir-2020419-60087-isha57.umxt/node_modules/Hydrogen/node_modules/zeromq/scripts/../zmq/lib/libzmq.a
libtool: install: chmod 644 /tmp/apm-install-dir-2020419-60087-isha57.umxt/node_modules/Hydrogen/node_modules/zeromq/scripts/../zmq/lib/libzmq.a
libtool: install: ranlib /tmp/apm-install-dir-2020419-60087-isha57.umxt/node_modules/Hydrogen/node_modules/zeromq/scripts/../zmq/lib/libzmq.a
libtool: finish: PATH="/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/tmp/apm-install-dir-2020419-60087-isha57.umxt/node_modules/Hydrogen/node_modules/zeromq/node_modules/.bin:/tmp/apm-install-dir-2020419-60087-isha57.umxt/node_modules/Hydrogen/node_modules/.bin:/tmp/apm-install-dir-2020419-60087-isha57.umxt/node_modules/.bin:/usr/share/atom/resources/app/apm/bin:..." ldconfig -n /tmp/apm-install-dir-2020419-60087-isha57.umxt/node_modules/Hydrogen/node_modules/zeromq/scripts/../zmq/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /tmp/apm-install-dir-2020419-60087-isha57.umxt/node_modules/Hydrogen/node_modules/zeromq/scripts/../zmq/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /usr/bin/mkdir -p '/tmp/apm-install-dir-2020419-60087-isha57.umxt/node_modules/Hydrogen/node_modules/zeromq/scripts/../zmq/bin'
  /bin/bash ./libtool   --mode=install /usr/bin/install -c tools/curve_keygen '/tmp/apm-install-dir-2020419-60087-isha57.umxt/node_modules/Hydrogen/node_modules/zeromq/scripts/../zmq/bin'
libtool: install: /usr/bin/install -c tools/curve_keygen /tmp/apm-install-dir-2020419-60087-isha57.umxt/node_modules/Hydrogen/node_modules/zeromq/scripts/../zmq/bin/curve_keygen
make[2]: Leaving directory '/tmp/apm-install-dir-2020419-60087-isha57.umxt/node_modules/Hydrogen/node_modules/zeromq/zmq/zeromq-4.2.2'
make[1]: Leaving directory '/tmp/apm-install-dir-2020419-60087-isha57.umxt/node_modules/Hydrogen/node_modules/zeromq/zmq/zeromq-4.2.2'
Succesfully build libzmq on Tue May 19 2020 16:13:43 GMT-0700 (PDT)
Aborted (core dumped)
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-2020419-60087-isha57.umxt/package.json'
npm WARN apm-install-dir-2020419-60087-isha57.umxt No description
npm WARN apm-install-dir-2020419-60087-isha57.umxt No repository field.
npm WARN apm-install-dir-2020419-60087-isha57.umxt No README data
npm WARN apm-install-dir-2020419-60087-isha57.umxt No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! zeromq@5.2.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the zeromq@5.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

</details>
