### ISSUE TITLE
Hydrogen fails to start

### ISSUE THREAD

**Issue by Doekeb** [nteract/hydrogen#1865]
### Prerequisites

* [x] Have you checked the solutions in our [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) for common problems ?
* [x] Have you checked that your issue [isn't already filed](https://github.com/nteract/hydrogen/issues) ?

### Description

Hydrogen fails to start, even with a fresh install.

### Steps to Reproduce

1. (re)install Hydrogen and kernels.
2. Open, e.g., a python file and attempt to start hydrogen by evaluating a cell.

### Versions

OS version:
Linux Mint 19.3

> `atom --version`

```
Atom    : 1.36.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

> `apm --version`

```
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.36.1
python 2.7.17
git 2.17.1
```

Hydrogen version:

2.13.1

### Plugins

Have you installed and activated any of the Hydrogen plugins below ?
- [ ] hydrogen-python
- [ ] Hydrogen Launcher
- [ ] Data Explorer

### Stack Trace

Uncaught SyntaxError: Invalid or unexpected token

```
At /usr/share/atom/resources/app/static/<embedded>:11

SyntaxError: Invalid or unexpected token
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146559)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150329)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146072)
    at /packages/Hydrogen/node_modules/@nteract/markdown/lib/markdown-render.js:18:1)
    at /packages/Hydrogen/node_modules/@nteract/markdown/lib/markdown-render.js:31:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146782)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150329)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146072)
    at /packages/Hydrogen/node_modules/@nteract/markdown/lib/index.js:6:43)
    at /packages/Hydrogen/node_modules/@nteract/markdown/lib/index.js:11:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146782)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150329)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146072)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/markdown.js:13:36)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/markdown.js:27:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146782)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150329)
    at Module.load (module.js:561:32)
```

### Commands

```
     -7:34.8.0 intentions:highlight (input.hidden-input)
     -7:32.2.0 window:toggle-dev-tools (input.hidden-input)
     -7:07.1.0 intentions:highlight (input.hidden-input)
     -7:06.9.0 window:toggle-dev-tools (input.hidden-input)
     -7:06.4.0 intentions:highlight (input.hidden-input)
  3x -7:06.2.0 window:toggle-dev-tools (input.hidden-input)
     -5:57.9.0 intentions:highlight (input.hidden-input)
     -5:56.9.0 settings-view:open (input.hidden-input)
     -5:14.9.0 core:close (input.hidden-input)
     -5:14 intentions:highlight (input.hidden-input)
     -5:12.5.0 command-palette:toggle (input.hidden-input)
     -5:11.6.0 editor:consolidate-selections (input.hidden-input)
     -5:11.6.0 core:cancel (input.hidden-input)
     -5:11.2.0 intentions:highlight (input.hidden-input)
     -5:11.1.0 settings-view:open (input.hidden-input)
     -1:20.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-glossaries 0.3.1 
autocomplete-latex-cite 0.3.5 
autocomplete-latex-references 0.3.2 
bibtex-helper 2.0.0 
busy-signal 2.0.1 
grammar-token-limit 0.1.1 
Hydrogen 2.13.1 
intentions 1.1.5 
language-haskell 1.19.2 
language-latex 1.2.0 
language-sage 0.3.2 
latex 0.50.2 
latex-autocomplete 1.1.1 
linter 2.3.1 
linter-chktex 1.4.0 
linter-ui-default 1.8.1 
minimap 4.29.9 
print-code 0.7.1 
```

### Expected behavior

Hydrogen starts and evaluates the cell

**Comment by Monduiz** [comment]
I have this issue after updating to 2.13.1. Going back to 2.8.

**Comment by iuvbio** [comment]
Same here with 2.13.1

**Comment by Doekeb** [comment]
The most recent working version for me is 2.9.0.

**Comment by guyujun** [comment]
same problem with macSO python3.7 Atom1.43

**Comment by wadethestealth** [comment]
#1854
