### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by vaowel** [nteract/hydrogen#1866]
###  Stack trace 

**SyntaxError: Invalid or unexpected token**
  ```
  at new Script (vm.js:74:7)
    at NativeCompileCache.runInThisContext (/Users/vaowel/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:146322)
    at Module.get_Module._compile (/Users/vaowel/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:147206)
    at Object.value [as .js] (/Users/vaowel/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (file:///Users/vaowel/Desktop/Atom.app/Contents/Resources/app.asar/static/index.js:72:46)
    at require (/Users/vaowel/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at Object.<anonymous> (/Users/vaowel/.atom/packages/Hydrogen/node_modules/@nteract/markdown/lib/markdown-render.js:18:1)
    at Object.<anonymous> (/Users/vaowel/.atom/packages/Hydrogen/node_modules/@nteract/markdown/lib/markdown-render.js:31:3)
    at Module.get_Module._compile (/Users/vaowel/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Users/vaowel/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (file:///Users/vaowel/Desktop/Atom.app/Contents/Resources/app.asar/static/index.js:72:46)
    at require (/Users/vaowel/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at Object.<anonymous> (/Users/vaowel/.atom/packages/Hydrogen/node_modules/@nteract/markdown/lib/index.js:6:43)
    at Object.<anonymous> (/Users/vaowel/.atom/packages/Hydrogen/node_modules/@nteract/markdown/lib/index.js:11:3)
    at Module.get_Module._compile (/Users/vaowel/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Users/vaowel/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (file:///Users/vaowel/Desktop/Atom.app/Contents/Resources/app.asar/static/index.js:72:46)
    at require (/Users/vaowel/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at Object.<anonymous> (/Users/vaowel/.atom/packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/markdown.js:13:36)
    at Object.<anonymous> (/Users/vaowel/.atom/packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/markdown.js:27:3)
    at Module.get_Module._compile (/Users/vaowel/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)


```

**I tried  apm install hydrogen@2.8.0 but the build failed, it read:** 

```

npm WARN deprecated @nteract/transforms@4.4.7: This package has been deprecated. Please access each transform through its own package.
npm WARN deprecated @nteract/display-area@4.4.8: This package has been deprecated in favor of @nteract/outputs.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated json-parser@1.1.5: `json-parser` is deprecated. Please use `comment-json` instead
configure: WARNING: Cannot find libunwind
```

**I also uploaded the _log file found from the /.atom/.apm/_logs**
[2020-01-25T08_31_47_443Z-debug.log](https://github.com/nteract/hydrogen/files/4111762/2020-01-25T08_31_47_443Z-debug.log)

**Comment by avatar101** [comment]
I'm facing the same issue when trying to install Hydrogen 2.13.1. I'm using Windows 8.1

**Comment by wadethestealth** [comment]
#1854
