### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by houzeyu2683** [nteract/hydrogen#1870]
In windows 10. I get this error.
```
C:\Users\Greg\AppData\Local\atom\app-1.38.0-beta0\resources\app\static\<embedded>:11
Hide Stack Trace
SyntaxError: Invalid or unexpected token
    at Module.get_Module._compile (C:\Users\Greg\AppData\Local\atom\app-1.38.0-beta0\resources\app\static\<embedded>:11:146949)
    at Object.value [as .js] (C:\Users\Greg\AppData\Local\atom\app-1.38.0-beta0\resources\app\static\<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///C:/Users/Greg/AppData/Local/atom/app-1.38.0-beta0/resources/app.asar/static/index.js:60:45)
    at require (C:\Users\Greg\AppData\Local\atom\app-1.38.0-beta0\resources\app\static\<embedded>:11:146462)
    at Object.<anonymous> (C:\Users\Greg\.atom\packages\Hydrogen\node_modules\@nteract\markdown\lib\markdown-render.js:18:1)
    at Object.<anonymous> (C:\Users\Greg\.atom\packages\Hydrogen\node_modules\@nteract\markdown\lib\markdown-render.js:31:3)
    at Module.get_Module._compile (C:\Users\Greg\AppData\Local\atom\app-1.38.0-beta0\resources\app\static\<embedded>:11:147172)
    at Object.value [as .js] (C:\Users\Greg\AppData\Local\atom\app-1.38.0-beta0\resources\app\static\<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///C:/Users/Greg/AppData/Local/atom/app-1.38.0-beta0/resources/app.asar/static/index.js:60:45)
    at require (C:\Users\Greg\AppData\Local\atom\app-1.38.0-beta0\resources\app\static\<embedded>:11:146462)
    at Object.<anonymous> (C:\Users\Greg\.atom\packages\Hydrogen\node_modules\@nteract\markdown\lib\index.js:6:43)
    at Object.<anonymous> (C:\Users\Greg\.atom\packages\Hydrogen\node_modules\@nteract\markdown\lib\index.js:11:3)
    at Module.get_Module._compile (C:\Users\Greg\AppData\Local\atom\app-1.38.0-beta0\resources\app\static\<embedded>:11:147172)
    at Object.value [as .js] (C:\Users\Greg\AppData\Local\atom\app-1.38.0-beta0\resources\app\static\<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
```
How to install older version of hydrogen in **windows** environment?

**Comment by p-desaintchamas** [comment]
I don't know if it is the same bug, I got redirected to this issue. 
Manjaro for me 

                                         ^
SyntaxError: Invalid or unexpected token
    at new Script (vm.js:79:7)
    at NativeCompileCache.runInThisContext (/usr/lib/atom/src/native-compile-cache.js:43:20)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:100:36)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/node_modules/@nteract/markdown/lib/markdown-render.js:18:1)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/node_modules/@nteract/markdown/lib/markdown-render.js:31:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/node_modules/@nteract/markdown/lib/index.js:6:43)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/node_modules/@nteract/markdown/lib/index.js:11:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/markdown.js:13:36)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/markdown.js:27:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/index.js:11:18)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/index.js:20:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/node_modules/@nteract/outputs/lib/index.js:24:28)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/node_modules/@nteract/outputs/lib/index.js:27:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/lib/components/result-view/display.js:5:38)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/lib/components/result-view/display.js:80:23)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/lib/store/output.js:8:25)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/lib/store/output.js:62:33)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/lib/store/watch.js:3:30)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/lib/store/watch.js:10:32)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/lib/store/watches.js:5:43)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/lib/store/watches.js:13:34)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/lib/kernel.js:14:28)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/lib/kernel.js:187:28)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/lib/kernel-manager.js:7:37)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/lib/kernel-manager.js:178:35)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/lib/store/index.js:21:36)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/lib/store/index.js:297:31)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/lib/utils.js:10:30)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/lib/utils.js:293:2)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/lib/panes/inspector.js:5:26)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/lib/panes/inspector.js:11:35)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/lib/main.js:13:26)
    at Object.<anonymous> (/home/philippe/.atom/packages/Hydrogen/lib/main.js:574:24)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at Package.requireMainModule (/usr/lib/atom/src/package.js:907:27)
    at Package.activateConfig (/usr/lib/atom/src/package.js:291:10)
    at PackageManager.module.exports.PackageManager.packageHasSettings (/usr/lib/atom/node_modules/settings-view/lib/package-manager.js:54:14)
    at PackageCard.hasSettings (/usr/lib/atom/node_modules/settings-view/lib/package-card.js:795:34)
    at PackageCard.updateSettingsState (/usr/lib/atom/node_modules/settings-view/lib/package-card.js:441:16)
    at PackageCard.updateInterfaceState (/usr/lib/atom/node_modules/settings-view/lib/package-card.js:433:12)
    at /usr/lib/atom/node_modules/settings-view/lib/package-card.js:729:16
    at /usr/lib/atom/node_modules/settings-view/lib/package-card.js:812:11
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (/usr/lib/atom/node_modules/settings-view/lib/package-manager.js:662:27)
    at /usr/lib/atom/node_modules/settings-view/lib/package-manager.js:484:26
    at exit (/usr/lib/atom/node_modules/settings-view/lib/package-manager.js:114:16)
    at triggerExitCallback (/usr/lib/atom/src/buffered-process.js:280:9)
    at bufferStream (/usr/lib/atom/src/buffered-process.js:301:9)
    at Socket.stream.on (/usr/lib/atom/src/buffered-process.js:169:7)
    at Socket.emit (events.js:187:15)
    at Pipe._handle.close (net.js:606:12)

**Comment by houzeyu2683** [comment]
I solve this problem, the first thing is install apm after enter the virtual environment.
`conda activate py37`
`pip install apm`
And you can use apm to install hydrogen.
`apm install hydrogen@2.8.0`

**Comment by dmurphy0516** [comment]
Do you have to go back as far as v2.8.0?

**Comment by wadethestealth** [comment]
For right now yes @dmurphy0516

**Comment by houzeyu2683** [comment]
Yes, it work in other issue, so I just try to use `apm` and install in win10.

**Comment by diotro** [comment]
Yo, sorry. Until you fix this, nah.

I shouldn't have to install another package to use a package; especially one that executes and runs code inline from within the editor. [IDE]

To be frank, this is a little suspicious. I wish there was an open source police department, and court 'system.'

Why? 

- _Sneaky_ code. 
- _Obfuscated_ code.
- _Encrypted_ code. 
- Repos designed as _double duties_. 
- Now running out of the github?

What is open source turning into? This is actually pissing me off. 

**DOES ANYONE KNOW WHAT F███NG OPEN MEANS, ANYMORE?**


Sorry for the rant, and the whitespace, and the carriage returns.
🔥🔥🔥🔥🔥⛺️🔥🔥🔥🔥🔥
I'm on a campfire typewriter.

**Comment by p-desaintchamas** [comment]
Does not work for me : asks me for a command between create, query, 
I suspect that hydrogen is not entirely available for Manjaro, I bult the archlinux bin atom package, to have the latest compatibility but it did not help. 

I thus managed to configurate jupyterlab with R, Julia and python, so I should be able to do it as well with atom... 
If anyone has some insights on a working preocedure to install hydrogen for manjaro, don't hesitate !

**Comment by Prashantmdgl9** [comment]
I installed atom fresh, installed all packages from start but this issue persists.
Ughh..very irritating. 
Is there any other package through which I can execute my code line by line on atom?

**Comment by wadethestealth** [comment]
@diotro This is an extremely offense comment that is coming from misinformation and a misunderstanding of hydrogen.

Firstly, Hydrogen is not a standalone package. It is specifically a way to use Jupyter Kernels (These are the things that make jupyter notebooks work) inside Atom. You specifically have to install a jupyter kernel yourself because kernels are dependent on the language you wish to execute lucky for you (these are also open source even the offical ones created by jupyter). This also means though that even including the outside packages is entirely open source (you can view every single character and every line of code) and not the least bit sneaky.

I am assuming you are referring to this comment by @houzeyu2683 
> I solve this problem, the first thing is install apm after enter the virtual environment.
`conda activate py37`
`pip install apm`
And you can use apm to install hydrogen.
`apm install hydrogen@2.8.0`

In which this user simply misunderstood what was happening.

Firstly to run a jupyter kernel in atom, if you use a virtual environment (extremely common in the python world) you must activate it (this user is using conda, which is a trusted python environment but this is not required and there are other options)

Second `apm` is "Atom's package manager" this is default in every single atom installation and requires no new installation and is actually require for atom to even work, however the command may not be accessible until you add atom to your system environment variables

Thirdly the issue you face is #1854 and is already be documented for over a month. Please see this issue for an explanation and workaround to your issue.
