### ISSUE TITLE
Uncaught Error: Cannot find module 'mobx-react'

### ISSUE THREAD

**Issue by bgouveia343** [nteract/hydrogen#1871]
[Enter steps to reproduce:]

1. Error thrown after clicking "Install" in atom's "Install Packages" -> "Hydrogen" -> "Install".

**Atom**: 1.43.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.2
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.13.1

### Stack Trace

Uncaught Error: Cannot find module 'mobx-react'

```
At internal/modules/cjs/loader.js:586

Error: Cannot find module 'mobx-react'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/lib/components/result-view/display.js:4:28)
    at /packages/Hydrogen/lib/components/result-view/display.js:80:23)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/lib/store/output.js:8:25)
    at /packages/Hydrogen/lib/store/output.js:62:33)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/lib/store/watch.js:3:30)
    at /packages/Hydrogen/lib/store/watch.js:10:32)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
```

### Commands

```
     -5:08.6.0 core:save (input.hidden-input)
  9x -2:23.4.0 core:backspace (input.hidden-input)
     -1:04.4.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
autocomplete-python 1.16.0 
file-icons 2.1.38 
Hydrogen 2.13.1 
kite 0.177.0 
script 3.25.0 
```

**Comment by ggpablo** [comment]
I have the same problem. Sure wish that someone could help us.

**Comment by wadethestealth** [comment]
Hydrogen 2.13 is currently broken due to outside dependencies please install v2.8.0

**Comment by ggpablo** [comment]
That's exactly what I did. It seems that Hydrogen 2.8.0 is the one to go with, from what I read in some comments.
For now it's the most stable one. 
For those who are in interest, this is what I did : 
- first step => uninstall Hydrogen 2.13.1 package from Atom ;
- 2nd step => open Terminal and enter the following comand line : apm install hydrohen@2.8.0 - - verbose (or only apm install hydrohen@2.8.0). For now I don't know what's the purpose of "- - verbose" but at least I got Hydrogen back on track ;-) 

Wish to thank you @wadethestealth for your reply. It confirms and is coherent with what I find elsewhere.

**Comment by wadethestealth** [comment]
@ggpablo I am hydrogen's maintainer and know most everything about the code base. Ever since y2.9 ironicly the update I joined hydrogen, we use a more up to date package that is meant for a webpack context (which hydrogen is not). Because of this published versions of our dependencies can have errors that I have to deal with outside of hydrogen, but they require lots of work and or time which is why we specifically revert to 2.8 and why it takes so long to solve the issues.

That is just some background to most of today's install problems.

**Comment by ggpablo** [comment]
Oh, that's good to know. It's then a matter of time. No worries, I understand perfectly. At least Hydrogen 2.8.0 works.
Keep up the good work ;-)

**Comment by wadethestealth** [comment]
Please see #1854
