### ISSUE TITLE
Failed to activate the Hydrogen package

### ISSUE THREAD

**Issue by jbinagia** [nteract/hydrogen#1873]
I get the following error when attempting to launch the Hydrogen kernel. 

**Atom**: 1.40.1 ia32
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Home
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.8.0

### Stack Trace

Failed to activate the Hydrogen package

```
At A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\Jeremy\.atom\packages\Hydrogen\node_modules\zeromq\build\Release\zmq.node

Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\Jeremy\.atom\packages\Hydrogen\node_modules\zeromq\build\Release\zmq.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/zeromq/lib/index.js:6:11)
    at /packages/Hydrogen/node_modules/zeromq/lib/index.js:857:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/zeromq/index.js:2:18)
    at /packages/Hydrogen/node_modules/zeromq/index.js:3:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
    at /packages/Hydrogen/node_modules/jmp/index.js:37:11)
    at /packages/Hydrogen/node_modules/jmp/index.js:450:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
```

### Commands

```
     -0:49.7.0 hydrogen:run-all (input.hidden-input)
```

### Non-Core Packages

```
atom-latex 0.9.1 
autocomplete-python 1.16.0 
data-explorer 0.7.0 
Hydrogen 2.8.0 
hydrogen-cell-separator 0.4.1 
hydrogen-launcher 1.2.2 
indent-detective 0.4.0 
ink 0.11.8 
julia-client 0.11.3 
kite 0.177.0 
language-fortran 2.1.10 
language-julia 0.19.2 
language-latex 1.2.0 
language-markdown 0.37.0 
latex 0.50.2 
latex-completions 0.3.6 
markdown-preview-enhanced 0.17.5 
markdown-scroll-sync 2.1.2 
markdown-writer 2.11.9 
pdf-view 0.72.0 
pen-paper-coffee-syntax 0.17.0 
remote-ftp 2.2.4 
script 3.25.0 
split-diff 1.6.1 
tool-bar 1.2.0 
```

**Comment by wadethestealth** [comment]
Not too sure what could cause this just yet. My basic assumption is the hydrogen doesn't have the admin permissions to initialize dlls on your machine, but I have never actually had anyone run into this issue.

**Comment by apivan19** [comment]
I am getting the same issue

C:\Users\Admin\.atom\packages\Hydrogen\node_modules\github-markdown-css\github-markdown.css:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { @font-face {
                                                                                                                                                           ^
SyntaxError: Invalid or unexpected token
    at new Script (vm.js:79:7)
    at NativeCompileCache.runInThisContext (C:\Users\Admin\AppData\Local\atom\app-1.43.0\resources\app\static\<embedded>:11:146322)
    at Module.get_Module._compile (C:\Users\Admin\AppData\Local\atom\app-1.43.0\resources\app\static\<embedded>:11:147206)
    at Object.value [as .js] (C:\Users\Admin\AppData\Local\atom\app-1.43.0\resources\app\static\<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///C:/Users/Admin/AppData/Local/atom/app-1.43.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\Admin\AppData\Local\atom\app-1.43.0\resources\app\static\<embedded>:11:146745)
    at Object.<anonymous> (C:\Users\Admin\.atom\packages\Hydrogen\node_modules\@nteract\markdown\lib\markdown-render.js:18:1)
    at Object.<anonymous> (C:\Users\Admin\.atom\packages\Hydrogen\node_modules\@nteract\markdown\lib\markdown-render.js:31:3)
    at Module.get_Module._compile (C:\Users\Admin\AppData\Local\atom\app-1.43.0\resources\app\static\<embedded>:11:147429)
    at Object.value [as .js] (C:\Users\Admin\AppData\Local\atom\app-1.43.0\resources\app\static\<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///C:/Users/Admin/AppData/Local/atom/app-1.43.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\Admin\AppData\Local\atom\app-1.43.0\resources\app\static\<embedded>:11:146745)
    at Object.<anonymous> (C:\Users\Admin\.atom\packages\Hydrogen\node_modules\@nteract\markdown\lib\index.js:6:43)
    at Object.<anonymous> (C:\Users\Admin\.atom\packages\Hydrogen\node_modules\@nteract\markdown\lib\index.js:11:3)
    at Module.get_Module._compile (C:\Users\Admin\AppData\Local\atom\app-1.43.0\resources\app\static\<embedded>:11:147429)
    at Object.value [as .js] (C:\Users\Admin\AppData\Local\atom\app-1.43.0\resources\app\static\<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///C:/Users/Admin/AppData/Local/atom/app-1.43.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\Admin\AppData\Local\atom\app-1.43.0\resources\app\static\<embedded>:11:146745)
    at Object.<anonymous> (C:\Users\Admin\.atom\packages\Hydrogen\node_modules\@nteract\outputs\lib\components\media\markdown.js:13:36)
    at Object.<anonymous> (C:\Users\Admin\.atom\packages\Hydrogen\node_modules\@nteract\outputs\lib\components\media\markdown.js:27:3)
    at Module.get_Module._compile (C:\Users\Admin\AppData\Local\atom\app-1.43.0\resources\app\static\<embedded>:11:147429)

**Comment by wadethestealth** [comment]
@apivan19 this is not the same error. Please see #1870

**Comment by n-riesco** [comment]
@jbinagia That looks like a problem with the installation of zeromq (I don't think zeromq distributes binaries for ia32). How did you install hydrogen?

**Comment by jbinagia** [comment]
@n-riesco I was running into another open issue on the latest version and saw a suggestion to try version 2.8. So I uninstalled and installed manually, i.e. `apm install hydrogen@2.8.0`.

**Comment by n-riesco** [comment]
The error with Hydrogen@2.13.1 looks like #1870

I'd try to find out where Hydrogen and zeromq are installed and removed them, before reinstalling `apm install hydrogen@2.8.0`. As far as I know, zeromq doesn't distribute 32bit binaries, so for this to succeed you need to have some build tools (see https://github.com/nodejs/node-gyp#on-windows ).

Any error messages when running `apm install hydrogen@2.8.0`?

**Comment by jonathan-gabriel** [comment]
I am getting same issue on MacOS while installing Hydrogen on Atom.

MacOS Mojave 10.14.4
Atom 1.43.0 x64
Electron 4.2.7
Node v10.11.0


`(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { @font-face {
                                                                                                                                                           ^
SyntaxError: Invalid or unexpected token
    at new Script (vm.js:79:7)
    at NativeCompileCache.runInThisContext (/private/var/folders/sw/cnbwj3gs6hlcn0wshq_tys4m0000gn/T/AppTranslocation/F17C414E-90C1-49AF-8769-239664F7291D/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146322)
    at Module.get_Module._compile (/private/var/folders/sw/cnbwj3gs6hlcn0wshq_tys4m0000gn/T/AppTranslocation/F17C414E-90C1-49AF-8769-239664F7291D/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147206)
    at Object.value [as .js] (/private/var/folders/sw/cnbwj3gs6hlcn0wshq_tys4m0000gn/T/AppTranslocation/F17C414E-90C1-49AF-8769-239664F7291D/d/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///private/var/folders/sw/cnbwj3gs6hlcn0wshq_tys4m0000gn/T/AppTranslocation/F17C414E-90C1-49AF-8769-239664F7291D/d/Atom.app/Contents/Resources/app.asar/static/index.js:72:46)
    at require (/private/var/folders/sw/cnbwj3gs6hlcn0wshq_tys4m0000gn/T/AppTranslocation/F17C414E-90C1-49AF-8769-239664F7291D/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at Object.<anonymous> (/Users/jgmoreno/.atom/packages/Hydrogen/node_modules/@nteract/markdown/lib/markdown-render.js:18:1)
    at Object.<anonymous> (/Users/jgmoreno/.atom/packages/Hydrogen/node_modules/@nteract/markdown/lib/markdown-render.js:31:3)
    at Module.get_Module._compile (/private/var/folders/sw/cnbwj3gs6hlcn0wshq_tys4m0000gn/T/AppTranslocation/F17C414E-90C1-49AF-8769-239664F7291D/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/private/var/folders/sw/cnbwj3gs6hlcn0wshq_tys4m0000gn/T/AppTranslocation/F17C414E-90C1-49AF-8769-239664F7291D/d/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///private/var/folders/sw/cnbwj3gs6hlcn0wshq_tys4m0000gn/T/AppTranslocation/F17C414E-90C1-49AF-8769-239664F7291D/d/Atom.app/Contents/Resources/app.asar/static/index.js:72:46)
    at require (/private/var/folders/sw/cnbwj3gs6hlcn0wshq_tys4m0000gn/T/AppTranslocation/F17C414E-90C1-49AF-8769-239664F7291D/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at Object.<anonymous> (/Users/jgmoreno/.atom/packages/Hydrogen/node_modules/@nteract/markdown/lib/index.js:6:43)
    at Object.<anonymous> (/Users/jgmoreno/.atom/packages/Hydrogen/node_modules/@nteract/markdown/lib/index.js:11:3)
    at Module.get_Module._compile (/private/var/folders/sw/cnbwj3gs6hlcn0wshq_tys4m0000gn/T/AppTranslocation/F17C414E-90C1-49AF-8769-239664F7291D/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/private/var/folders/sw/cnbwj3gs6hlcn0wshq_tys4m0000gn/T/AppTranslocation/F17C414E-90C1-49AF-8769-239664F7291D/d/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///private/var/folders/sw/cnbwj3gs6hlcn0wshq_tys4m0000gn/T/AppTranslocation/F17C414E-90C1-49AF-8769-239664F7291D/d/Atom.app/Contents/Resources/app.asar/static/index.js:72:46)
    at require (/private/var/folders/sw/cnbwj3gs6hlcn0wshq_tys4m0000gn/T/AppTranslocation/F17C414E-90C1-49AF-8769-239664F7291D/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at Object.<anonymous> (/Users/jgmoreno/.atom/packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/markdown.js:13:36)
    at Object.<anonymous> (/Users/jgmoreno/.atom/packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/markdown.js:27:3)
    at Module.get_Module._compile (/private/var/folders/sw/cnbwj3gs6hlcn0wshq_tys4m0000gn/T/AppTranslocation/F17C414E-90C1-49AF-8769-239664F7291D/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)`

**Comment by n-riesco** [comment]
@jonathan-gabriel Have you tried to install v2.8.0 with `apm install hydrogen@2.8.0`?

**Comment by apivan19** [comment]
So i was actually getting two different errors based on some unknown criteria. Uninstalling Hydrogen from atom and then installing v2.8.0 via apm fixed both of them. Is 2.8 the last stable release?

**Comment by n-riesco** [comment]
@apivan19 One of Hydrogen dependencies seems to be broken (issue #1870 )

---

@wadethestealth How about republishing v2.8.0 as v2.14.0 so that new users don't face #1870 ?

**Comment by wadethestealth** [comment]
@n-riesco that's a pretty good idea

**Comment by wadethestealth** [comment]
Please see #1854
