### ISSUE TITLE
Uncaught Error: Cannot find module './cjs/react.production.min.js'Require stack:- $ATOM_HOME/pa...

### ISSUE THREAD

**Issue by SilaEsme** [nteract/hydrogen#1937]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.1

### Stack Trace

Uncaught Error: Cannot find module './cjs/react.production.min.js'
Require stack:
- C:\Users\silae\.atom\packages\Hydrogen\node_modules\react\index.js
- C:\Users\silae\.atom\packages\Hydrogen\lib\main.js
- C:\Users\silae\AppData\Local\atom\app-1.47.0\resources\app.asar\static\index.html

```
At internal/modules/cjs/loader.js:686

Error: Cannot find module './cjs/react.production.min.js'
Require stack:
- C:\Users\silae\.atom\packages\Hydrogen\node_modules\react\index.js
- C:\Users\silae\.atom\packages\Hydrogen\lib\main.js
- C:\Users\silae\AppData\Local\atom\app-1.47.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.47.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (<embedded>:11:155434)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (<embedded>:11:146766)
    at /packages/Hydrogen/node_modules/react/index.js:4:20)
    at /packages/Hydrogen/node_modules/react/index.js:9:3)
    at Module.get_Module._compile (<embedded>:11:147450)
    at Object.value [as .js] (<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (<embedded>:11:146766)
    at /packages/Hydrogen/lib/main.js:19:14)
    at /packages/Hydrogen/lib/main.js:633:3)
    at Module.get_Module._compile (<embedded>:11:147450)
    at Object.value [as .js] (<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (<embedded>:1:735013)
    at Package.requireMainModule (<embedded>:11:3310163)
    at Package.activateConfig (<embedded>:11:3299451)
    at PackageManager.packageHasSettings (<embedded>:11:920062)
    at PackageCard.hasSettings (<embedded>:14:2543563)
    at PackageCard.updateSettingsState (<embedded>:14:2533843)
    at PackageCard.updateInterfaceState (<embedded>:14:2533666)
    at <embedded>:14:2541796
    at <embedded>:14:2543814
    at Function.simpleDispatch (<embedded>:11:1201250)
    at Emitter.emit (<embedded>:11:1202691)
    at PackageManager.emitPackageEvent (<embedded>:11:929519)
    at <embedded>:11:926651
    at r (<embedded>:11:921181)
    at n (<embedded>:14:1063434)
    at ChildProcess.<anonymous> (<embedded>:14:1063640)
    at ChildProcess.emit (events.js:194:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)

```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.18 
Hydrogen 2.14.1 
```

**Comment by wuxx1016** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.6


### Stack Trace

Uncaught Error: Cannot find module './cjs/react.production.min.js'
Require stack:
- C:\Users\wuxx1\.atom\packages\Hydrogen\node_modules\react\index.js
- C:\Users\wuxx1\.atom\packages\Hydrogen\lib\main.js
- C:\Users\wuxx1\AppData\Local\atom\app-1.52.0\resources\app.asar\static\index.html

```
At internal/modules/cjs/loader.js:630

Error: Cannot find module './cjs/react.production.min.js'
Require stack:
- C:\Users\wuxx1\.atom\packages\Hydrogen\node_modules\react\index.js
- C:\Users\wuxx1\.atom\packages\Hydrogen\lib\main.js
- C:\Users\wuxx1\AppData\Local\atom\app-1.52.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.52.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/node_modules/react/index.js:4:20)
    at /packages/Hydrogen/node_modules/react/index.js:9:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/lib/main.js:12:31)
    at /packages/Hydrogen/lib/main.js:567:24)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:1:735077)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:3303573)
    at Package.activateConfig (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:3292861)
    at PackageDetailView.activateConfig (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:14:782397)
    at PackageDetailView.completeInitialization (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:14:781095)
    at PackageDetailView.loadPackage (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:14:781329)
    at new PackageDetailView (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:14:777915)
    at SettingsView.getOrCreatePanel (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:931401)
    at SettingsView.showPanel (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:932122)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.18 
Hydrogen 2.14.6 
hydrogen-xdbg 0.0.4 
```

Same issue here.

**Comment by speed-shot-77** [comment]
I've got the same problem when I run project with parcel serve.
I deleted the .parcel-cache folder in the project root directory, and it worked for me.
Hope my advice will be helpful.
Thanks.
