### ISSUE TITLE
Uncaught TypeError: Cannot read property 'coordinates' of undefined

### ISSUE THREAD

**Issue by jcalvillo** [nteract/hydrogen#1943]
> Timeseries not rendered correctly

1. create dataframe with timeseries
```
from pandas import Timestamp
testdf = pd.DataFrame({'date': {0: Timestamp('2020-02-27 00:00:00'),
                                1: Timestamp('2020-02-28 00:00:00'),
                                2: Timestamp('2020-02-29 00:00:00'),
                                3: Timestamp('2020-03-01 00:00:00'),
                                4: Timestamp('2020-03-02 00:00:00'),
                                5: Timestamp('2020-03-03 00:00:00'),
                                6: Timestamp('2020-03-04 00:00:00'),
                                7: Timestamp('2020-03-05 00:00:00'),
                                8: Timestamp('2020-03-06 00:00:00'),
                                9: Timestamp('2020-03-07 00:00:00')},
                       'value': {0: 46,
                                 1: 54,
                                 2: 69,
                                 3: 70,
                                 4: 53,
                                 5: 46,
                                 6: 46,
                                 7: 44,
                                 8: 56,
                                 9: 66}})

testdf
```

2. click `line chart` in Data Explorer

<hr>

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.14.6
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.1

### Stack Trace

Uncaught TypeError: Cannot read property 'coordinates' of undefined

```
At /Users/jlc/.atom/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:52

TypeError: Cannot read property 'coordinates' of undefined
    at exports.semioticLineChart (/packages/data-explorer/node_modules/@nteract/data-explorer/lib/charts/line.js:57:38)
    at DataExplorer.updateChart (/packages/data-explorer/node_modules/@nteract/data-explorer/lib/index.js:132:35)
    at DataExplorer.setView (/packages/data-explorer/node_modules/@nteract/data-explorer/lib/index.js:198:18)
    at onClick (/packages/data-explorer/node_modules/@nteract/data-explorer/lib/components/Toolbar.js:50:111)
    at Object.ba (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:14:84)
    at ja (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:14:238)
    at ka (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:14:292)
    at oa (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:15:72)
    at lc (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:52:170)
    at jc (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:51:255)
    at mc (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:52:334)
    at sc (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:56:10)
    at Ia (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:287:189)
    at Ma (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:19:57)
    at Rc (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:70:279)
    at id (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:69:102)
    at exports.unstable_runWithPriority (/packages/Hydrogen/node_modules/scheduler/cjs/scheduler.production.min.js:19:467)
    at cg (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:122:325)
    at Ga (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:287:48)
    at gd (/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:68:371)
```

### Commands

```
     -1:41 core:select-all (input.hidden-input)
     -1:26.9.0 hydrogen:run-all-above (div.line.cursor-line)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-toolbar 0.1.6 
autoclose-html 0.23.0 
autocomplete-python 1.16.0 
busy-signal 2.0.1 
color-picker 2.3.0 
data-atom 0.29.1 
data-explorer 0.7.0 
file-icons 2.1.41 
highlight-selected 0.17.0 
Hydrogen 2.14.1 
hydrogen-cell-separator 0.4.1 
hydrogen-launcher 1.2.2 
hydrogen-python 0.0.8 
hydrogen-xdbg 0.0.4 
intentions 1.1.5 
kite 0.184.0 
language-liquid 0.7.0 
linter 2.3.1 
linter-csslint 2.0.6 
linter-htmlhint 1.6.3 
linter-jscs 4.2.4 
linter-jshint 3.1.19 
linter-jsonlint 1.4.0 
linter-markdown 5.2.11 
linter-pylint 2.1.1 
linter-ui-default 1.8.1 
linter-write-good 0.9.3 
linter-xmllint 1.4.4 
markdown-folding 0.3.1 
markdown-image-paste 2.5.2 
markdown-preview-plus 3.11.5 
markdown-scroll-sync 2.1.2 
markdown-writer 2.11.10 
merge-conflicts 1.4.5 
minimap 4.29.9 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
monokai-seti 0.9.0 
native-ui 0.27.0 
oceanic-next 1.0.0 
pigments 0.40.2 
platformio-ide-terminal 2.10.0 
project-manager 3.3.8 
regex-railroad-diagram 0.19.4 
remote-ftp 2.2.4 
tablr 1.8.3 
tool-bar 1.3.0 
tool-bar-markdown-writer 0.5.1 
wakatime 9.0.2 
```

**Comment by jcalvillo** [comment]
closing due to age.
