### ISSUE TITLE
Uncaught Error: Cannot find module '$ATOM_HOME/packages\Hydrogen\node_modules\mobx\lib\index.js'....

### ISSUE THREAD

**Issue by dillontherrien** [nteract/hydrogen#1944]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0-nightly1 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.1

### Stack Trace

Uncaught Error: Cannot find module 'C:\Users\ipops\.atom\packages\Hydrogen\node_modules\mobx\lib\index.js'. Please verify that the package.json has a valid "main" entry

```
At internal/modules/cjs/loader.js:248

Error: Cannot find module 'C:\Users\ipops\.atom\packages\Hydrogen\node_modules\mobx\lib\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:240:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:378:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:670:27)
    at Module._resolveFilename (~/AppData/Local/atom-nightly/app-1.48.0-nightly1/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom-nightly/app-1.48.0-nightly1/resources/app/static/<embedded>:11:155434)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom-nightly/app-1.48.0-nightly1/resources/app/static/<embedded>:11:146766)
    at /packages/Hydrogen/lib/main.js:11:23)
    at /packages/Hydrogen/lib/main.js:577:24)
    at Module.get_Module._compile (~/AppData/Local/atom-nightly/app-1.48.0-nightly1/resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (~/AppData/Local/atom-nightly/app-1.48.0-nightly1/resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (~/AppData/Local/atom-nightly/app-1.48.0-nightly1/resources/app/static/<embedded>:1:735013)
    at Package.requireMainModule (~/AppData/Local/atom-nightly/app-1.48.0-nightly1/resources/app/static/<embedded>:11:3307162)
    at Package.activateConfig (~/AppData/Local/atom-nightly/app-1.48.0-nightly1/resources/app/static/<embedded>:11:3296450)
    at PackageManager.packageHasSettings (~/AppData/Local/atom-nightly/app-1.48.0-nightly1/resources/app/static/<embedded>:11:919960)
    at PackageCard.hasSettings (~/AppData/Local/atom-nightly/app-1.48.0-nightly1/resources/app/static/<embedded>:14:2538160)
    at PackageCard.updateSettingsState (~/AppData/Local/atom-nightly/app-1.48.0-nightly1/resources/app/static/<embedded>:14:2528440)
    at PackageCard.updateInterfaceState (~/AppData/Local/atom-nightly/app-1.48.0-nightly1/resources/app/static/<embedded>:14:2528263)
    at new PackageCard (~/AppData/Local/atom-nightly/app-1.48.0-nightly1/resources/app/static/<embedded>:14:2519860)
    at PackageDetailView.completeInitialization (~/AppData/Local/atom-nightly/app-1.48.0-nightly1/resources/app/static/<embedded>:14:755194)
    at PackageDetailView.loadPackage (~/AppData/Local/atom-nightly/app-1.48.0-nightly1/resources/app/static/<embedded>:14:755761)
    at new PackageDetailView (~/AppData/Local/atom-nightly/app-1.48.0-nightly1/resources/app/static/<embedded>:14:752347)
    at SettingsView.getOrCreatePanel (~/AppData/Local/atom-nightly/app-1.48.0-nightly1/resources/app/static/<embedded>:11:942039)
    at SettingsView.showPanel (~/AppData/Local/atom-nightly/app-1.48.0-nightly1/resources/app/static/<embedded>:11:942760)
    at SettingsView.showDeferredPanel (~/AppData/Local/atom-nightly/app-1.48.0-nightly1/resources/app/static/<embedded>:11:942684)
```

### Commands

```
```

### Non-Core Packages

```
atom-discord 2.0.2 
Hydrogen 2.14.1 
```

**Comment by matthew-brett** [comment]
See gh-1945 - commenting there.

**Comment by tomato-300yen** [comment]
find out solution to this issue
see #1945
