### ISSUE TITLE
Uncaught Error: Cannot find module '$ATOM_HOME/packages\Hydrogen\node_modules\@nteract\mathjax\li...

### ISSUE THREAD

**Issue by alvivanco** [nteract/hydrogen#1946]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.1

### Stack Trace

Uncaught Error: Cannot find module 'C:\Users\aleja\.atom\packages\Hydrogen\node_modules\@nteract\mathjax\lib\index.js'. Please verify that the package.json has a valid "main" entry

```
At internal/modules/cjs/loader.js:248

Error: Cannot find module 'C:\Users\aleja\.atom\packages\Hydrogen\node_modules\@nteract\mathjax\lib\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:240:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:378:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:670:27)
    at Module._resolveFilename (C:/ProgramData/aleja/atom/app-1.47.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (C:/ProgramData/aleja/atom/app-1.47.0/resources/app/static/<embedded>:11:155434)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (C:/ProgramData/aleja/atom/app-1.47.0/resources/app/static/<embedded>:11:146766)
    at /packages/Hydrogen/node_modules/@nteract/markdown/lib/markdown-render.js:13:30)
    at /packages/Hydrogen/node_modules/@nteract/markdown/lib/markdown-render.js:30:3)
    at Module.get_Module._compile (C:/ProgramData/aleja/atom/app-1.47.0/resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (C:/ProgramData/aleja/atom/app-1.47.0/resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (C:/ProgramData/aleja/atom/app-1.47.0/resources/app/static/<embedded>:11:146766)
    at /packages/Hydrogen/node_modules/@nteract/markdown/lib/index.js:6:43)
    at /packages/Hydrogen/node_modules/@nteract/markdown/lib/index.js:11:3)
    at Module.get_Module._compile (C:/ProgramData/aleja/atom/app-1.47.0/resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (C:/ProgramData/aleja/atom/app-1.47.0/resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (C:/ProgramData/aleja/atom/app-1.47.0/resources/app/static/<embedded>:11:146766)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/markdown.js:13:36)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/markdown.js:27:3)
    at Module.get_Module._compile (C:/ProgramData/aleja/atom/app-1.47.0/resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (C:/ProgramData/aleja/atom/app-1.47.0/resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
```

### Commands

```
```

### Non-Core Packages

```
atom-runner 2.7.1 
Hydrogen 2.14.1 
```

**Comment by AverageComet250** [comment]
I had the same issue too and went looking for the module.It turns out that ther is no lib folder and thus no index.js. When you think about it, it's quite a big mistake, so I don't know how this happened. DISCLAIMER: I do not contribute to this atom plugin.

**Comment by alvivanco** [comment]
I "figured it out". I had to install an older version of hydrogen (2.8.0). It works now.

**Comment by matthew-brett** [comment]
See gh-1945.

**Comment by tomato-300yen** [comment]
find out solution to this issue.
see #1945
