### ISSUE TITLE
Uncaught Error: Cannot find module '$ATOM_HOME/packages/Hydrogen/node_modules/ansi-to-react/lib/i...

### ISSUE THREAD

**Issue by hpmarshall** [nteract/hydrogen#1948]
[Enter steps to reproduce:]

1. Running macOS Catalina 10.15.5
2. removed atom and all associated files to do a clean install
3. installed atom
4. attempted to install Hydrogen

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.5
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.1

### Stack Trace

Uncaught Error: Cannot find module '/Users/hpm/.atom/packages/Hydrogen/node_modules/ansi-to-react/lib/index.js'. Please verify that the package.json has a valid "main" entry

```
At internal/modules/cjs/loader.js:248

Error: Cannot find module '/Users/hpm/.atom/packages/Hydrogen/node_modules/ansi-to-react/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:240:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:378:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:670:27)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155434)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146766)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/kernel-output-error.js:13:41)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/kernel-output-error.js:44:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146766)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/index.js:14:29)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/index.js:27:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146766)
    at /packages/Hydrogen/lib/components/result-view/display.js:5:38)
    at /packages/Hydrogen/lib/components/result-view/display.js:82:23)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
```

### Commands

```
```

### Non-Core Packages

```
Hydrogen 2.14.1 
```

**Comment by Fredeli** [comment]
Having the same issue...

**Comment by ozika** [comment]
Ubuntu 18.04, Atom 1.47, fresh clean install 
SAME issue

**Comment by OscarWan** [comment]
Same issue with the same version of Mac Catalina

**Comment by MrPrules** [comment]
Same issue on WIndows 10

**Comment by Ghamalam** [comment]
Same issue on Windows 10

**Comment by hpmarshall** [comment]
I managed to get this to work again by downgrading hydrogen:

>>apm install hydrogen@2.8.0


-------------------------------------------------
Hans-Peter Marshall, Associate Professor
Cryosphere Geophysics And Remote Sensing (CryoGARS)
Department of Geosciences, Boise State University
1910 University Dr., ERB 3155
Boise, ID 83725-1536
http://earth.boisestate.edu/cryogars
Twitter: @snowradar
hpmarshall@boisestate.edu
(208) 426-1416 (o)
(208) 426-4061 (f)

**Comment by hpmarshall** [comment]
If you are having this problem, I managed to get everything to work by reverting to Hydrogen 2.8:

>>apm install hydrogen@2.8.0

**Comment by Ghamalam** [comment]
> If you are having this problem, I managed to get everything to work by reverting to Hydrogen 2.8:
> 
> > > apm install hydrogen@2.8.0

I installed v2.9.0 before seeing this comment and that does indeed work. Thank you

**Comment by tomato-300yen** [comment]
Solution to this problem! Enjoy your Hydrogen!
https://github.com/tomato-300yen/ansi_to_react_lib_for_hydrogen

**Comment by MrPrules** [comment]
> 
> 
> Solution to this problem! Enjoy your Hydrogen!
> https://github.com/tomato-300yen/ansi_to_react_lib_for_hydrogen

This fix worked for me. Had to check gh-1945 for the next error 
Thanks for help
