### ISSUE TITLE
Uncaught Error: Cannot find module '$ATOM_HOME/packages\Hydrogen\node_modules\ansi-to-react\lib\i...

### ISSUE THREAD

**Issue by Fredeli** [nteract/hydrogen#1949]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: DESKTOP-ALR8G7B
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.1

### Stack Trace

Uncaught Error: Cannot find module 'C:\Users\FrederikElischberger\.atom\packages\Hydrogen\node_modules\ansi-to-react\lib\index.js'. Please verify that the package.json has a valid "main" entry

```
At internal/modules/cjs/loader.js:248

Error: Cannot find module 'C:\Users\FrederikElischberger\.atom\packages\Hydrogen\node_modules\ansi-to-react\lib\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:240:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:378:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:670:27)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.47.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:155434)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:146766)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/kernel-output-error.js:13:41)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/kernel-output-error.js:44:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:146766)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/index.js:14:29)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/index.js:27:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:146766)
    at /packages/Hydrogen/lib/components/result-view/display.js:5:38)
    at /packages/Hydrogen/lib/components/result-view/display.js:82:23)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
```

### Commands

```
```

### Non-Core Packages

```
darkpython-syntax 0.5.0 
Hydrogen 2.14.1 
ide-python 1.5.0 
python-tools 0.6.9 
```

**Comment by AdamRj-765** [comment]
A brand new installation of Atom and then installing atom-clock just prior to install of the Hydrogen module. Throws this error.  Any help would be appreciated. 

Uncaught Error: Cannot find module 'C:\Users\ <user>.atom\packages\Hydrogen\node_modules\ansi-to-react\lib\index.js'. Please verify that the package.json has a valid "main" entry



internal/modules/cjs/loader.js:248
Hide Stack Trace
Error: Cannot find module 'C:\Users\ <user>\.atom\packages\Hydrogen\node_modules\ansi-to-react\lib\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:240:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:378:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:670:27)
    at Module._resolveFilename (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\electron.asar\common\reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:155434)
    at Module.require (file:///C:/Users/ <user>/AppData/Local/atom/app-1.47.0/resources/app.asar/static/index.js:61:43)
    at require (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:146766)
    at Object.<anonymous> (C:\Users\ <user>\.atom\packages\Hydrogen\node_modules\@nteract\outputs\lib\components\kernel-output-error.js:13:41)
    at Object.<anonymous> (C:\Users\ <user>\.atom\packages\Hydrogen\node_modules\@nteract\outputs\lib\components\kernel-output-error.js:44:3)
    at Module.get_Module._compile (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:147450)
    at Object.value [as .js] (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (file:///C:/Users/ <user>/AppData/Local/atom/app-1.47.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:146766)
    at Object.<anonymous> (C:\Users\ <user>\.atom\packages\Hydrogen\node_modules\@nteract\outputs\lib\index.js:14:29)
    at Object.<anonymous> (C:\Users\ <user>\.atom\packages\Hydrogen\node_modules\@nteract\outputs\lib\index.js:27:3)
    at Module.get_Module._compile (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:147450)
    at Object.value [as .js] (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (file:///C:/Users/ <user>/AppData/Local/atom/app-1.47.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:146766)
    at Object.<anonymous> (file:///C:/Users/ <user>/.atom/packages/Hydrogen/lib/components/result-view/display.js:5:38)
    at Object.<anonymous> (file:///C:/Users/ <user>/.atom/packages/Hydrogen/lib/components/result-view/display.js:82:23)
    at Module.get_Module._compile (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:147450)
    at Object.value [as .js] (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (file:///C:/Users/ <user>/AppData/Local/atom/app-1.47.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:146766)
    at Object.<anonymous> (file:///C:/Users/ <user>/.atom/packages/Hydrogen/lib/store/output.js:8:25)
    at Object.<anonymous> (file:///C:/Users/ <user>/.atom/packages/Hydrogen/lib/store/output.js:62:33)
    at Module.get_Module._compile (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:147450)
    at Object.value [as .js] (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (file:///C:/Users/ <user>/AppData/Local/atom/app-1.47.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:146766)
    at Object.<anonymous> (file:///C:/Users/ <user>/.atom/packages/Hydrogen/lib/store/watch.js:3:30)
    at Object.<anonymous> (file:///C:/Users/ <user>/.atom/packages/Hydrogen/lib/store/watch.js:10:32)
    at Module.get_Module._compile (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:147450)
    at Object.value [as .js] (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (file:///C:/Users/ <user>/AppData/Local/atom/app-1.47.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:146766)
    at Object.<anonymous> (file:///C:/Users/ <user>/.atom/packages/Hydrogen/lib/store/watches.js:5:43)
    at Object.<anonymous> (file:///C:/Users/ <user>/.atom/packages/Hydrogen/lib/store/watches.js:13:34)
    at Module.get_Module._compile (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:147450)
    at Object.value [as .js] (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (file:///C:/Users/ <user>/AppData/Local/atom/app-1.47.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:146766)
    at Object.<anonymous> (file:///C:/Users/ <user>/.atom/packages/Hydrogen/lib/kernel.js:14:28)
    at Object.<anonymous> (file:///C:/Users/ <user>/.atom/packages/Hydrogen/lib/kernel.js:187:28)
    at Module.get_Module._compile (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:147450)
    at Object.value [as .js] (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (file:///C:/Users/ <user>/AppData/Local/atom/app-1.47.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:146766)
    at Object.<anonymous> (file:///C:/Users/ <user>/.atom/packages/Hydrogen/lib/kernel-manager.js:7:37)
    at Object.<anonymous> (file:///C:/Users/ <user>/.atom/packages/Hydrogen/lib/kernel-manager.js:178:35)
    at Module.get_Module._compile (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:147450)
    at Object.value [as .js] (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (file:///C:/Users/ <user>/AppData/Local/atom/app-1.47.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:146766)
    at Object.<anonymous> (file:///C:/Users/ <user>/.atom/packages/Hydrogen/lib/store/index.js:21:36)
    at Object.<anonymous> (file:///C:/Users/ <user>/.atom/packages/Hydrogen/lib/store/index.js:297:31)
    at Module.get_Module._compile (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:147450)
    at Object.value [as .js] (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (file:///C:/Users/ <user>/AppData/Local/atom/app-1.47.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:146766)
    at Object.<anonymous> (file:///C:/Users/ <user>/.atom/packages/Hydrogen/lib/utils.js:10:30)
    at Object.<anonymous> (file:///C:/Users/ <user>/.atom/packages/Hydrogen/lib/utils.js:295:2)
    at Module.get_Module._compile (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:147450)
    at Object.value [as .js] (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (file:///C:/Users/ <user>/AppData/Local/atom/app-1.47.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:146766)
    at Object.<anonymous> (file:///C:/Users/ <user>/.atom/packages/Hydrogen/lib/panes/inspector.js:5:26)
    at Object.<anonymous> (file:///C:/Users/ <user>/.atom/packages/Hydrogen/lib/panes/inspector.js:11:35)
    at Module.get_Module._compile (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:147450)
    at Object.value [as .js] (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (file:///C:/Users/ <user>/AppData/Local/atom/app-1.47.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:146766)
    at Object.<anonymous> (file:///C:/Users/ <user>/.atom/packages/Hydrogen/lib/main.js:13:26)
    at Object.<anonymous> (file:///C:/Users/ <user>/.atom/packages/Hydrogen/lib/main.js:577:24)
    at Module.get_Module._compile (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:147450)
    at Object.value [as .js] (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (file:///C:/Users/ <user>/AppData/Local/atom/app-1.47.0/resources/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:1:735013)
    at Package.requireMainModule (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:3310163)
    at Package.activateConfig (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:3299451)
    at PackageManager.packageHasSettings (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:920062)
    at PackageCard.hasSettings (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:14:2543563)
    at PackageCard.updateSettingsState (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:14:2533843)
    at PackageCard.updateInterfaceState (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:14:2533666)
    at C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:14:2541796
    at C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:14:2543814
    at Function.simpleDispatch (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:1201250)
    at Emitter.emit (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:1202691)
    at PackageManager.emitPackageEvent (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:929519)
    at C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:926651
    at r (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:921181)
    at n (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:14:1063434)
    at ChildProcess.<anonymous> (C:\Users\ <user>\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:14:1063640)
    at ChildProcess.emit (events.js:194:13)

**Comment by danfridman** [comment]
See

https://github.com/nteract/hydrogen/issues/1948

which tells you to install an earlier version (suggests 2.8) or directs you to the following solution:

https://github.com/tomato-300yen/ansi_to_react_lib_for_hydrogen

**Comment by AdamRj-765** [comment]
Thank you kindly
