### ISSUE TITLE
Uncaught Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?inva...

### ISSUE THREAD

**Issue by IGurkovskiy** [nteract/hydrogen#1950]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.5
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.1

### Stack Trace

Uncaught Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130

**Comment by gsidorov** [comment]
I think I am having the same issue:

![image](https://user-images.githubusercontent.com/55404877/83540356-7d583980-a4f8-11ea-97ce-03a84b03ce8b.png)

Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
stack trace

**Comment by gsidorov** [comment]
Atom: 1.47.0 x64
OS: Windows 10
Thrown from: Hydrogen package 2.14.1

C:\Users\aicrypto\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:209 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ug (C:\Users\aicrypto\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:275:129)
    at C:\Users\aicrypto\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:148:174
    at R (C:\Users\aicrypto\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:173:103)
    at Rj (C:\Users\aicrypto\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:262:428)
    at Qj (C:\Users\aicrypto\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:246:265)
    at Kj (C:\Users\aicrypto\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:246:194)
    at yj (C:\Users\aicrypto\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:239:172)
    at C:\Users\aicrypto\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:123:115
    at exports.unstable_runWithPriority (C:\Users\aicrypto\.atom\packages\Hydrogen\node_modules\scheduler\cjs\scheduler.production.min.js:19:467)
    at cg (C:\Users\aicrypto\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:122:325)
    at fg (C:\Users\aicrypto\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:123:61)
    at gg (C:\Users\aicrypto\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:122:496)
    at Ig (C:\Users\aicrypto\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:230:156)
    at Object.enqueueForceUpdate (C:\Users\aicrypto\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js:133:76)
    at ResultViewComponent.F.forceUpdate (C:\Users\aicrypto\.atom\packages\Hydrogen\node_modules\react\cjs\react.production.min.js:12:456)
    at e.onInvalidate (C:\Users\aicrypto\.atom\packages\Hydrogen\node_modules\mobx-react\dist\mobxreact.cjs.production.min.js:1:3180)
    at e.runReaction (C:\Users\aicrypto\.atom\packages\Hydrogen\node_modules\mobx\lib\mobx.min.js:1:26685)
    at runReactionsHelper (C:\Users\aicrypto\.atom\packages\Hydrogen\node_modules\mobx\lib\mobx.min.js:1:28732)
    at reactionScheduler (C:\Users\aicrypto\.atom\packages\Hydrogen\node_modules\mobx\lib\mobx.min.js:1:28230)
    at runReactions (C:\Users\aicrypto\.atom\packages\Hydrogen\node_modules\mobx\lib\mobx.min.js:1:28314)
    at endBatch (C:\Users\aicrypto\.atom\packages\Hydrogen\node_modules\mobx\lib\mobx.min.js:1:23125)
    at _endAction (C:\Users\aicrypto\.atom\packages\Hydrogen\node_modules\mobx\lib\mobx.min.js:1:14750)
    at executeAction (C:\Users\aicrypto\.atom\packages\Hydrogen\node_modules\mobx\lib\mobx.min.js:1:14121)
    at OutputStore.n (C:\Users\aicrypto\.atom\packages\Hydrogen\node_modules\mobx\lib\mobx.min.js:1:13939)
    at file:///C:/Users/aicrypto/.atom/packages/Hydrogen/lib/result.js:66:23
    at file:///C:/Users/aicrypto/.atom/packages/Hydrogen/lib/kernel.js:381:9
    at file:///C:/Users/aicrypto/.atom/packages/Hydrogen/lib/kernel.js:312:9
    at wrappedOnResults (file:///C:/Users/aicrypto/.atom/packages/Hydrogen/lib/kernel.js:78:5)
    at ZMQKernel.onIOMessage (file:///C:/Users/aicrypto/.atom/packages/Hydrogen/lib/zmq-kernel.js:333:7)
    at Socket.<anonymous> (C:\Users\aicrypto\.atom\packages\Hydrogen\node_modules\jmp\index.js:350:17)

**Comment by OscarWan** [comment]
Same issue here for Mac 10.15, Atom 1.47.0, Hydrogen 2.14.1
Error message:
```
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ug (/Users/oscar/.atom/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:275:129)
    at /Users/oscar/.atom/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:148:174
    at R (/Users/oscar/.atom/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:173:118)
    at Rj (/Users/oscar/.atom/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:264:383)
    at Qj (/Users/oscar/.atom/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:246:265)
    at Kj (/Users/oscar/.atom/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:246:194)
    at yj (/Users/oscar/.atom/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:239:172)
    at Ig (/Users/oscar/.atom/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:230:137)
    at bk (/Users/oscar/.atom/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:281:43)
    at /Users/oscar/.atom/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:284:301
    at Nj (/Users/oscar/.atom/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:240:120)
    at ik (/Users/oscar/.atom/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:284:287)
    at Object.exports.render (/Users/oscar/.atom/packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:290:293)
    at reactFactory (/Users/oscar/.atom/packages/Hydrogen/lib/utils.js:25:12)
    at new ResultView (/Users/oscar/.atom/packages/Hydrogen/lib/components/result-view/index.js:80:5)
    at /Users/oscar/.atom/packages/Hydrogen/lib/result.js:51:27
    at Object.createResult (/Users/oscar/.atom/packages/Hydrogen/lib/result.js:74:2)
    at /Users/oscar/.atom/packages/Hydrogen/lib/main.js:341:14
    at /Users/oscar/.atom/packages/Hydrogen/lib/main.js:564:7
    at Object.checkForKernel (/Users/oscar/.atom/packages/Hydrogen/lib/main.js:574:4)
    at Object.run (/Users/oscar/.atom/packages/Hydrogen/lib/main.js:340:10)
    at HTMLElement.hydrogenRun (/Users/oscar/.atom/packages/Hydrogen/lib/main.js:103:36)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349576)
    at KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1242036)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1238170)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284782)
```

**Comment by OscarWan** [comment]
Hi @IGurkovskiy ! I am wondering whether you solve this issue or not, since I'm still stuck with this error

**Comment by IGurkovskiy** [comment]
Hi,

I’m don’t know how but it works. May be last update of  macOS 10.15.5 (19F101), and reinstallation of Atom and Hydrogen solved this problem.


Best Regards,

IgG

**Comment by OscarWan** [comment]
Thanks a lot
