### ISSUE TITLE
Uncaught Error: Cannot find module 'lodash'Require stack:- $ATOM_HOME/packages\hydrogen-2.14.3\...

### ISSUE THREAD

**Issue by Taotao114** [nteract/hydrogen#1971]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Unknown Windows version
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.3

### Stack Trace

Uncaught Error: Cannot find module 'lodash'
Require stack:
- C:\Users\zwt\.atom\packages\hydrogen-2.14.3\lib\main.js
- C:\Users\zwt\AppData\Local\atom\app-1.48.0\resources\app.asar\static\index.html

```
At internal/modules/cjs/loader.js:686

Error: Cannot find module 'lodash'
Require stack:
- C:\Users\zwt\.atom\packages\hydrogen-2.14.3\lib\main.js
- C:\Users\zwt\AppData\Local\atom\app-1.48.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.48.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:155487)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:146819)
    at /packages/hydrogen-2.14.3/lib/main.js:9:14)
    at /packages/hydrogen-2.14.3/lib/main.js:567:24)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:1:735013)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:3308385)
    at Package.activateConfig (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:3297673)
    at PackageManager.packageHasSettings (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:920272)
    at PackageCard.hasSettings (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:2543559)
    at PackageCard.updateSettingsState (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:2533839)
    at PackageCard.updateInterfaceState (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:2533662)
    at new PackageCard (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:2525259)
    at InstallPanel.getPackageCardView (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:781181)
    at InstallPanel.addPackageViews (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:780912)
    at ~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:782402
    at AtomIoClient.featuredPackages (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:739853)
    at InstallPanel.loadFeaturedPackages (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:782263)
    at new InstallPanel (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:775306)
    at Object.Install (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:940412)
    at SettingsView.getOrCreatePanel (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:942238)
```

### Commands

```
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-clock 0.1.18 
atom-file-icons 0.7.1 
atom-html-preview 0.2.6 
atom-minify 0.8.0 
atom-python-run 0.9.7 
busy-signal 2.0.1 
color-picker 2.3.0 
docblockr 0.13.7 
double-tag 1.7.0 
emmet 2.4.3 
git-log 0.4.1 
git-plus 8.7.1 
highlight-selected 0.17.0 
Hydrogen 2.14.3 
intentions 1.1.5 
language-markdown 0.37.0 
linter 2.3.1 
linter-ui-default 1.8.1 
markdown-preview-plus 3.11.5 
markdown-table-editor 1.1.2 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
open-in-browser 0.5.2 
pigments 0.40.2 
project-manager 3.3.8 
python-tools 0.6.9 
regex-railroad-diagram 0.19.4 
simplified-chinese-menu 5.3.5 
sync-settings 4.3.3 
```

**Comment by aminya** [comment]
Please redownload the latest version.
