### ISSUE TITLE
Cannot install Hydrogen from command line (Mac) or within Atom

### ISSUE THREAD

**Issue by cdestael** [nteract/hydrogen#1974]
Thanks in advance for any advice with the following issue -- 

I am trying to install Hydrogen from the command line (terminal) on my Mac, using: `apm install hydrogen`

However I receive the following error: "Request for package information failed: tunneling socket could not be established, cause=connect ETIMEDOUT 9.0.2.1:443 (5 attempts) (ECONNRESET)"

I am using the following versions:

$ atom -v
Atom    : 1.48.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0

$ npm -v
6.14.4

However, I also get the following error for apm version:
$ apm -v
/Applications/Atom.app/Contents/Resources/app/apm/lib/apm-cli.js:171
      spawned.stderr.on('data', function(chunk) {
                     ^

TypeError: Cannot read property 'on' of undefined
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/lib/apm-cli.js:171:22)
    at process._tickCallback (internal/process/next_tick.js:61:11)

I don't have a proxy and I don't have a firewall, and am working at home.  Can anyone help please?

**Comment by Lee1125** [comment]
There are many bugs in hydrogen package. I tried many times to install this package with command lines. But all failed.

**Comment by BenRussert** [comment]
@cdestael Can you try this again and see if the issue may have been resolved upstream? 

If that doesn't work, are you able to install other atom packages via apm without trouble? What about if you try installing in the atom gui itself instead of apm?
