### ISSUE TITLE
Uncaught Error: Cannot find module '$ATOM_HOME/packages\Hydrogen\node_modules\@nteract\markdown\l...

### ISSUE THREAD

**Issue by fhosseinij** [nteract/hydrogen#1975]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.3

### Stack Trace

Uncaught Error: Cannot find module 'C:\Users\fhose.LAPTOP-FP5CTMK0\.atom\packages\Hydrogen\node_modules\@nteract\markdown\lib\index.js'. Please verify that the package.json has a valid "main" entry

```
At internal/modules/cjs/loader.js:248

Error: Cannot find module 'C:\Users\fhose.LAPTOP-FP5CTMK0\.atom\packages\Hydrogen\node_modules\@nteract\markdown\lib\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:240:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:378:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:670:27)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.48.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:155487)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:146819)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/markdown.js:13:36)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/markdown.js:27:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:146819)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/index.js:11:18)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/index.js:20:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:146819)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/index.js:24:28)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/index.js:27:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
```

### Commands

```
     -5:25.2.0 core:close (ul.list-inline.tab-bar.inset-panel)
     -5:12.6.0 editor:newline-below (input.hidden-input)
     -5:10.8.0 core:backspace (input.hidden-input)
     -5:06.2.0 core:move-up (input.hidden-input)
  3x -5:06.0 core:move-right (input.hidden-input)
  2x -4:54.1.0 editor:newline-below (input.hidden-input)
```

### Non-Core Packages

```
Hydrogen 2.14.3 
language-latex 1.2.0 
latex 0.50.2 
platformio-ide-terminal 2.10.0 
```

**Comment by Tohmua** [comment]
I got the same error when installing the plugin

[Enter steps to reproduce:]

1. install package

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.5
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.3


### Stack Trace

Uncaught Error: Cannot find module '<PATH>/.atom/packages/Hydrogen/node_modules/@nteract/markdown/lib/index.js'. Please verify that the package.json has a valid "main" entry

**Comment by Zielzor** [comment]
Same  - here is the log:

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.3


### Stack Trace

Uncaught Error: Cannot find module 'C:\Users\Ukasz\.atom\packages\Hydrogen\node_modules\@nteract\markdown\lib\index.js'. Please verify that the package.json has a valid "main" entry

```
At internal/modules/cjs/loader.js:248

Error: Cannot find module 'C:\Users\Ukasz\.atom\packages\Hydrogen\node_modules\@nteract\markdown\lib\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:240:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:378:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:670:27)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.48.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:155487)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:146819)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/markdown.js:13:36)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/markdown.js:27:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:146819)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/index.js:11:18)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/index.js:20:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:146819)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/index.js:24:28)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/index.js:27:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:146819)
    at /packages/Hydrogen/lib/components/result-view/display.js:5:38)
    at /packages/Hydrogen/lib/components/result-view/display.js:82:23)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:146819)
    at /packages/Hydrogen/lib/store/output.js:8:25)
    at /packages/Hydrogen/lib/store/output.js:62:33)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:146819)
    at /packages/Hydrogen/lib/store/watch.js:3:30)
    at /packages/Hydrogen/lib/store/watch.js:10:32)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:146819)
    at /packages/Hydrogen/lib/store/watches.js:5:43)
    at /packages/Hydrogen/lib/store/watches.js:13:34)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:146819)
    at /packages/Hydrogen/lib/kernel.js:14:28)
    at /packages/Hydrogen/lib/kernel.js:187:28)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:146819)
    at /packages/Hydrogen/lib/kernel-manager.js:7:37)
    at /packages/Hydrogen/lib/kernel-manager.js:180:35)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:146819)
    at /packages/Hydrogen/lib/store/index.js:21:36)
    at /packages/Hydrogen/lib/store/index.js:297:31)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:146819)
    at /packages/Hydrogen/lib/utils.js:10:30)
    at /packages/Hydrogen/lib/utils.js:282:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:146819)
    at /packages/Hydrogen/lib/panes/inspector.js:5:26)
    at /packages/Hydrogen/lib/panes/inspector.js:11:35)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:146819)
    at /packages/Hydrogen/lib/main.js:13:26)
    at /packages/Hydrogen/lib/main.js:567:24)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:1:735013)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:3308385)
    at Package.activateConfig (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:3297673)
    at PackageManager.packageHasSettings (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:920272)
    at PackageCard.hasSettings (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:2543559)
    at PackageCard.updateSettingsState (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:2533839)
    at PackageCard.updateInterfaceState (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:2533662)
    at ~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:2541792
    at ~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:2543810
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:1201460)
    at Emitter.emit (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:1202901)
    at PackageManager.emitPackageEvent (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:929729)
    at ~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:926861
    at r (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:921391)
    at n (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:1063434)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:1063640)
    at ChildProcess.emit (events.js:194:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
```

### Commands

```
     -7:29 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -7:24.8.0 settings-view:view-installed-packages (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  3x -5:28.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
Hydrogen 2.14.3 
platformio-ide-terminal 2.10.0 
script 3.26.0 
```

**Comment by aviatesk** [comment]
try the latest
