### ISSUE TITLE
Uncaught Error: Cannot find module '$ATOM_HOME/packages/Hydrogen/node_modules/@nteract/markdown/l...

### ISSUE THREAD

**Issue by rocketbarn** [nteract/hydrogen#1977]
[Enter steps to reproduce:]

1. Updated Hydrogen to 2.14.3. Received this error. 
2. Uninstalled and reinstalled Hydrogen. Same issue. 
3. Went to '/Users/Dmtearpak/.atom/packages/Hydrogen/node_modules/@nteract/markdown/lib/index.js' as guided from the error flag. There was know 'lib' folder, therefore no index.js file.

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.5
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.3

### Stack Trace

Uncaught Error: Cannot find module '/Users/Dmtearpak/.atom/packages/Hydrogen/node_modules/@nteract/markdown/lib/index.js'. Please verify that the package.json has a valid "main" entry

```
At internal/modules/cjs/loader.js:248

Error: Cannot find module '/Users/Dmtearpak/.atom/packages/Hydrogen/node_modules/@nteract/markdown/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:240:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:378:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:670:27)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155487)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146819)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/markdown.js:13:36)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/markdown.js:27:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146819)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/index.js:11:18)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/index.js:20:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146819)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/index.js:24:28)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/index.js:27:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
```

### Commands

```
     -4:15.3.0 hydrogen:run (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
autocomplete-python 1.16.0 
dark-python-syntax 2.3.0 
file-icons 2.1.41 
Hydrogen 2.14.3 
minimap 4.29.9 
```

**Comment by bcastex** [comment]
I had the same problem just now. Updated Hydrogen. Uninstalled and reinstalled. Went to look at the indicated directory and there was no lib folder.

**Comment by Oberonhive** [comment]
Installing previous versions of hydrogen doesn't help :((

**Comment by glocalglocal** [comment]
Same here. The lib folder is missing. My setup is like rocketbarn but running Windows 10 x64.

**Comment by aviatesk** [comment]
try the latest

**Comment by bcastex** [comment]
@aviatesk Thank you, it is working perfectly now.
