### ISSUE TITLE
Uncaught Error: Cannot find module 'jmp'Require stack:- $ATOM_HOME/packages\hydrogen\lib\zmq-ke...

### ISSUE THREAD

**Issue by zGISer** [nteract/hydrogen#1983]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Unknown Windows version
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.4

### Stack Trace

Uncaught Error: Cannot find module 'jmp'
Require stack:
- C:\Users\琛琛\.atom\packages\hydrogen\lib\zmq-kernel.js
- C:\Users\琛琛\.atom\packages\hydrogen\lib\kernel-manager.js
- C:\Users\琛琛\.atom\packages\hydrogen\lib\store\index.js
- C:\Users\琛琛\.atom\packages\hydrogen\lib\utils.js
- C:\Users\琛琛\.atom\packages\hydrogen\lib\panes\inspector.js
- C:\Users\琛琛\.atom\packages\hydrogen\lib\main.js
- D:\other software\Atom x64\resources\app.asar\static\index.html

```
At internal/modules/cjs/loader.js:686

Error: Cannot find module 'jmp'
Require stack:
- C:\Users\琛琛\.atom\packages\hydrogen\lib\zmq-kernel.js
- C:\Users\琛琛\.atom\packages\hydrogen\lib\kernel-manager.js
- C:\Users\琛琛\.atom\packages\hydrogen\lib\store\index.js
- C:\Users\琛琛\.atom\packages\hydrogen\lib\utils.js
- C:\Users\琛琛\.atom\packages\hydrogen\lib\panes\inspector.js
- C:\Users\琛琛\.atom\packages\hydrogen\lib\main.js
- D:\other software\Atom x64\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Module._resolveFilename (D:/other software/Atom x64/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (D:/other software/Atom x64/resources/app/static/<embedded>:11:155434)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (D:/other software/Atom x64/resources/app/static/<embedded>:11:146766)
    at /packages/hydrogen/lib/zmq-kernel.js:3:20)
    at /packages/hydrogen/lib/zmq-kernel.js:26:31)
    at Module.get_Module._compile (D:/other software/Atom x64/resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (D:/other software/Atom x64/resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (D:/other software/Atom x64/resources/app/static/<embedded>:11:146766)
    at /packages/hydrogen/lib/kernel-manager.js:5:33)
    at /packages/hydrogen/lib/kernel-manager.js:180:35)
    at Module.get_Module._compile (D:/other software/Atom x64/resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (D:/other software/Atom x64/resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (D:/other software/Atom x64/resources/app/static/<embedded>:11:146766)
    at /packages/hydrogen/lib/store/index.js:21:36)
    at /packages/hydrogen/lib/store/index.js:297:31)
    at Module.get_Module._compile (D:/other software/Atom x64/resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (D:/other software/Atom x64/resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-python-run 0.9.7 
autocomplete-python 1.16.0 
Hydrogen 2.14.4 
minimap 4.29.9 
```

**Comment by captainsafia** [comment]
@zGISer Can you share the steps to reproduce?

**Comment by zGISer** [comment]
> 
> 
> @zGISer Can you share the steps to reproduce?
![图片](https://user-images.githubusercontent.com/63902699/87369186-779f4a80-c5b2-11ea-8b28-6ca3a36ae6b4.png)
![图片](https://user-images.githubusercontent.com/63902699/87369398-001deb00-c5b3-11ea-80d0-e365bd77579d.png)

**Comment by zGISer** [comment]
I use apm install instead of npm install.
And it can work now.
