### ISSUE TITLE
Uncaught Error: The module '$ATOM_HOME/packages/Hydrogen/node_modules/zeromq/build/Release/zmq.no...

### ISSUE THREAD

**Issue by pawansingh06** [nteract/hydrogen#1994]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Linux Mint
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.4

### Stack Trace

Uncaught Error: The module '/home/pawan/.atom/packages/Hydrogen/node_modules/zeromq/build/Release/zmq.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

```
At electron/js2c/asar.js:138

Error: The module '/home/pawan/.atom/packages/Hydrogen/node_modules/zeromq/build/Release/zmq.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:138:31)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/node_modules/zeromq/lib/index.js:6:11)
    at /packages/Hydrogen/node_modules/zeromq/lib/index.js:857:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/node_modules/zeromq/index.js:2:18)
    at /packages/Hydrogen/node_modules/zeromq/index.js:3:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/node_modules/jmp/index.js:37:11)
    at /packages/Hydrogen/node_modules/jmp/index.js:450:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:151046)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-flask 0.2.3 
atom-html-preview 0.2.6 
atom-live-server 2.3.0 
atom-material-ui 2.1.3 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
autocomplete 0.47.0 
autocomplete-json 5.5.2 
autocomplete-python 1.16.0 
busy-signal 2.0.1 
color-picker 2.3.0 
css-snippets 1.1.0 
emmet 2.4.3 
file-icons 2.1.42 
flask-snippets 0.3.3 
html-to-css 0.2.2 
Hydrogen 2.14.4 
ide-css 0.3.4 
ide-html 0.6.0 
intentions 1.1.5 
language-ejs 0.4.0 
linter 2.3.1 
linter-eslint 8.5.5 
linter-tslint 1.10.43 
linter-ui-default 1.8.1 
pigments 0.40.2 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.10.0 
python-indent 1.2.6 
script 3.26.0 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by DeeDeeG** [comment]
NODE_MODULE_VERSION 53 isw either Node 8, or Electron ">=1.8, < 3".

NODE_MODULE_VERSION 70 is Electron 5.

Sounds like the Hydrogen package does need to be rebuilt.

You can do `Edit` > `Preferences` in the menu, ten from the Settings tab, click `Packages` > `Community Packages` > `Hydrogen`, then click "uninstall", wait for it to uninstall, and then hit "install" to install it and build it fresh against your newer Atom/Electron version.
