### ISSUE TITLE
installing bugs （content copied from bug report)

### ISSUE THREAD

**Issue by Donna019** [nteract/hydrogen#1996]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.5
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.4

### Stack Trace

Uncaught Error: Cannot find module 'babel-runtime/helpers/typeof'
Require stack:
- /Users/shaw/.atom/packages/Hydrogen/node_modules/react-base16-styling/lib/index.js
- /Users/shaw/.atom/packages/Hydrogen/node_modules/react-json-tree/lib/createStylingFromTheme.js
- /Users/shaw/.atom/packages/Hydrogen/node_modules/react-json-tree/lib/index.js
- /Users/shaw/.atom/packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/json.js
- /Users/shaw/.atom/packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/index.js
- /Users/shaw/.atom/packages/Hydrogen/node_modules/@nteract/outputs/lib/index.js
- /Users/shaw/.atom/packages/Hydrogen/lib/components/result-view/display.js
- /Users/shaw/.atom/packages/Hydrogen/lib/store/output.js
- /Users/shaw/.atom/packages/Hydrogen/lib/store/watch.js
- /Users/shaw/.atom/packages/Hydrogen/lib/store/watches.js
- /Users/shaw/.atom/packages/Hydrogen/lib/kernel.js
- /Users/shaw/.atom/packages/Hydrogen/lib/kernel-manager.js
- /Users/shaw/.atom/packages/Hydrogen/lib/store/index.js
- /Users/shaw/.atom/packages/Hydrogen/lib/utils.js
- /Users/shaw/.atom/packages/Hydrogen/lib/panes/inspector.js
- /Users/shaw/.atom/packages/Hydrogen/lib/main.js
- /Applications/Atom.app/Contents/Resources/app.asar/static/index.html

```
At internal/modules/cjs/loader.js:686

Error: Cannot find module 'babel-runtime/helpers/typeof'
Require stack:
- /Users/shaw/.atom/packages/Hydrogen/node_modules/react-base16-styling/lib/index.js
- /Users/shaw/.atom/packages/Hydrogen/node_modules/react-json-tree/lib/createStylingFromTheme.js
- /Users/shaw/.atom/packages/Hydrogen/node_modules/react-json-tree/lib/index.js
- /Users/shaw/.atom/packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/json.js
- /Users/shaw/.atom/packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/index.js
- /Users/shaw/.atom/packages/Hydrogen/node_modules/@nteract/outputs/lib/index.js
- /Users/shaw/.atom/packages/Hydrogen/lib/components/result-view/display.js
- /Users/shaw/.atom/packages/Hydrogen/lib/store/output.js
- /Users/shaw/.atom/packages/Hydrogen/lib/store/watch.js
- /Users/shaw/.atom/packages/Hydrogen/lib/store/watches.js
- /Users/shaw/.atom/packages/Hydrogen/lib/kernel.js
- /Users/shaw/.atom/packages/Hydrogen/lib/kernel-manager.js
- /Users/shaw/.atom/packages/Hydrogen/lib/store/index.js
- /Users/shaw/.atom/packages/Hydrogen/lib/utils.js
- /Users/shaw/.atom/packages/Hydrogen/lib/panes/inspector.js
- /Users/shaw/.atom/packages/Hydrogen/lib/main.js
- /Applications/Atom.app/Contents/Resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155482)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/node_modules/react-base16-styling/lib/index.js:8:16)
    at /packages/Hydrogen/node_modules/react-base16-styling/lib/index.js:267:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/node_modules/react-json-tree/lib/createStylingFromTheme.js:8:27)
    at /packages/Hydrogen/node_modules/react-json-tree/lib/createStylingFromTheme.js:211:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/node_modules/react-json-tree/lib/index.js:14:54)
    at /packages/Hydrogen/node_modules/react-json-tree/lib/index.js:243:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/json.js:14:43)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/json.js:60:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/index.js:5:14)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/index.js:20:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/index.js:24:28)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/index.js:27:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/lib/components/result-view/display.js:5:38)
    at /packages/Hydrogen/lib/components/result-view/display.js:82:23)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/lib/store/output.js:8:25)
    at /packages/Hydrogen/lib/store/output.js:62:33)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/lib/store/watch.js:3:30)
    at /packages/Hydrogen/lib/store/watch.js:10:32)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/lib/store/watches.js:5:43)
    at /packages/Hydrogen/lib/store/watches.js:13:34)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/lib/kernel.js:14:28)
    at /packages/Hydrogen/lib/kernel.js:187:28)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/lib/kernel-manager.js:7:37)
    at /packages/Hydrogen/lib/kernel-manager.js:180:35)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/lib/store/index.js:21:36)
    at /packages/Hydrogen/lib/store/index.js:297:31)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/lib/utils.js:10:30)
    at /packages/Hydrogen/lib/utils.js:282:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/lib/panes/inspector.js:5:26)
    at /packages/Hydrogen/lib/panes/inspector.js:11:35)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/lib/main.js:13:26)
    at /packages/Hydrogen/lib/main.js:567:24)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:695414)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3204227)
    at Package.activateConfig (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3193515)
    at PackageManager.packageHasSettings (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:920312)
    at PackageCard.hasSettings (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2542491)
    at PackageCard.updateSettingsState (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2532771)
    at PackageCard.updateInterfaceState (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2532594)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2540724
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2542742
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1201500)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1202941)
    at PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:929769)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:926901
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:921431)
    at n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1063432)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1063638)
    at ChildProcess.emit (events.js:194:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
```

### Commands

```
     -9:10.7.0 core:paste (input.hidden-input)
     -4:05.8.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-material-ui 2.1.3 
Hydrogen 2.14.4 
```

**Comment by Taborski** [comment]
Same issue here, I'm new on atom. i do not know if it could help people but I am on ubuntu 18.04

**Comment by BenRussert** [comment]
I'm not able to repro on Ubuntu 20.04, 

```
apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.50.0
python 2.7.18rc1
git 2.25.1
```

It seems possible to me this was fixed in a patch release [here](https://github.com/nteract/outputs/pull/16), so should work for you too if you uninstall then reinstall hydrogen. If that doesn't work perhaps upgrade to the latest atom version and try again.
