### ISSUE TITLE
Uncaught Error: mobx-react-lite@3 requires mobx at least version 6 to be available

### ISSUE THREAD

**Issue by sbar365** [nteract/hydrogen#2008]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.6
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.5

### Stack Trace

Uncaught Error: mobx-react-lite@3 requires mobx at least version 6 to be available

```
At /Users/Stefanos/.atom/packages/Hydrogen/node_modules/mobx-react-lite/lib/utils/assertEnvironment.js:9

Error: mobx-react-lite@3 requires mobx at least version 6 to be available
    at /packages/Hydrogen/node_modules/mobx-react-lite/lib/utils/assertEnvironment.js:9:11)
    at /packages/Hydrogen/node_modules/mobx-react-lite/lib/utils/assertEnvironment.js:12:3)
    at Module.get_Module._compile (/private/var/folders/8v/q6m26w716_995ss22_1r_84w0000gr/T/AppTranslocation/E29DFF61-824C-4183-A91B-739505004399/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/private/var/folders/8v/q6m26w716_995ss22_1r_84w0000gr/T/AppTranslocation/E29DFF61-824C-4183-A91B-739505004399/d/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/private/var/folders/8v/q6m26w716_995ss22_1r_84w0000gr/T/AppTranslocation/E29DFF61-824C-4183-A91B-739505004399/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/node_modules/mobx-react-lite/lib/index.js:3:1)
    at /packages/Hydrogen/node_modules/mobx-react-lite/lib/index.js:42:3)
    at Module.get_Module._compile (/private/var/folders/8v/q6m26w716_995ss22_1r_84w0000gr/T/AppTranslocation/E29DFF61-824C-4183-A91B-739505004399/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/private/var/folders/8v/q6m26w716_995ss22_1r_84w0000gr/T/AppTranslocation/E29DFF61-824C-4183-A91B-739505004399/d/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/private/var/folders/8v/q6m26w716_995ss22_1r_84w0000gr/T/AppTranslocation/E29DFF61-824C-4183-A91B-739505004399/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/node_modules/mobx-react/dist/mobxreact.cjs.production.min.js:1:324)
    at /packages/Hydrogen/node_modules/mobx-react/dist/mobxreact.cjs.production.min.js:4:3)
    at Module.get_Module._compile (/private/var/folders/8v/q6m26w716_995ss22_1r_84w0000gr/T/AppTranslocation/E29DFF61-824C-4183-A91B-739505004399/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/private/var/folders/8v/q6m26w716_995ss22_1r_84w0000gr/T/AppTranslocation/E29DFF61-824C-4183-A91B-739505004399/d/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/private/var/folders/8v/q6m26w716_995ss22_1r_84w0000gr/T/AppTranslocation/E29DFF61-824C-4183-A91B-739505004399/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/node_modules/mobx-react/dist/index.js:5:20)
    at /packages/Hydrogen/node_modules/mobx-react/dist/index.js:10:3)
    at Module.get_Module._compile (/private/var/folders/8v/q6m26w716_995ss22_1r_84w0000gr/T/AppTranslocation/E29DFF61-824C-4183-A91B-739505004399/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
```

### Commands

```
     -7:43.3.0 hydrogen:run (input.hidden-input)
     -7:31.2.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -3:46.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
Hydrogen 2.14.5 
kite 0.187.0 
platformio-ide-terminal 2.10.0 
script 3.26.0 
```

**Comment by allisonmcampbell** [comment]
I also had this issue this morning.  Threw a major wrench in my workday.  I don't (knowingly) use mobx, and don't know where this issue came from.  I did a complete uninstall of atom ( https://discuss.atom.io/t/how-to-completely-uninstall-atom-for-mac/9084/41 ), and then re-installed. Now the problem is gone.

**Comment by captainsafia** [comment]
Thanks for reporting the issue, folks!

We did push out a new release of Hydrogen but we haven't modified any of our MobX dependencies recently. It looks like this is limited to macOS so something funky might be going on there.

**Comment by captainsafia** [comment]
Oof. Based on #2006 it looks like we aren't on the right version of mobx.

@aviatesk @BenRussert  Would it suffice to merge the PR referenced above?

**Comment by BenRussert** [comment]
It's interesting that a reinstall of atom worked, I wonder if there is some dependency conflict. I wonder if an uninstall/reinstall of hydrogen would have done the trick?

> Would it suffice to merge the PR referenced above?

@captainsafia I think there's a good chance that we're already upgrade compatible to mobx 6 [based on a skim of the breaking changes](https://github.com/mobxjs/mobx/blob/mobx6/CHANGELOG.md#600), but someone will need to try bumping the version and a little qa on it locally to see if anything breaks.

**Comment by captainsafia** [comment]
@BenRussert Thanks for confirming!

Anyone in the thread interested in testing this out?

**Comment by BenRussert** [comment]
On second thought, I saw the CI errors for #2006 and it looks like a bit of a chore.

I wonder if anyone can repro? or this may have possibly been a fluke conflict with atom or another package. If it's not happening anymore we may as well stick with mobx 5 for now.
