### ISSUE TITLE
Uncaught Error: mobx-react-lite@3 requires mobx at least version 6 to be available

### ISSUE THREAD

**Issue by AndrewQuinn2020** [nteract/hydrogen#2009]
This error got thrown as soon as I tried to install Hydrogen on my Atom build.

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Ubuntu 20.04.1
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.5

### Stack Trace

Uncaught Error: mobx-react-lite@3 requires mobx at least version 6 to be available

```
At /home/andrew/.atom/packages/Hydrogen/node_modules/mobx-react-lite/lib/utils/assertEnvironment.js:9

Error: mobx-react-lite@3 requires mobx at least version 6 to be available
    at /packages/Hydrogen/node_modules/mobx-react-lite/lib/utils/assertEnvironment.js:9:11)
    at /packages/Hydrogen/node_modules/mobx-react-lite/lib/utils/assertEnvironment.js:12:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/node_modules/mobx-react-lite/lib/index.js:3:1)
    at /packages/Hydrogen/node_modules/mobx-react-lite/lib/index.js:42:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/node_modules/mobx-react/dist/mobxreact.cjs.production.min.js:1:324)
    at /packages/Hydrogen/node_modules/mobx-react/dist/mobxreact.cjs.production.min.js:4:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/node_modules/mobx-react/dist/index.js:5:20)
    at /packages/Hydrogen/node_modules/mobx-react/dist/index.js:10:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147498)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-python-jedi 1.10.3-0 
busy-signal 2.0.1 
Hydrogen 2.14.5 
intentions 1.1.5 
linter 3.1.0 
linter-flake8 2.4.0 
linter-ui-default 2.1.2 
minimap 4.29.9 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-hide 0.3.0 
minimap-lens 0.8.1 
minimap-linter 2.2.1 
minimap-pigments 0.2.2 
minimap-plus 4.32.0 
python-autopep8 0.1.3 
script 3.26.0 
seti-icons 1.5.4 
```

**Comment by AndrewQuinn2020** [comment]
Oh, not sure if this will help, but here's the output message from trying to install it again.

```
Installing “Hydrogen@2.14.5” failed.Hide output…
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/home/andrew/.atom/packages/Hydrogen/node_modules/lodash.camelcase/README.md'
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at WriteStream.onerror (_stream_readable.js:734:7)
    at WriteStream.emit (events.js:198:13)
    at /usr/share/atom/resources/app/apm/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:303:14
    at /usr/share/atom/resources/app/apm/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:333:16
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
```

![Screenshot from 2020-09-30 14-50-48](https://user-images.githubusercontent.com/53230903/94727197-5c7be580-032c-11eb-9880-d1436b00dafb.png)

**Comment by aviatesk** [comment]
dup of #2008
