### ISSUE TITLE
Uncaught Error: Cannot find module './mobx.min.js'Require stack:- $ATOM_HOME/packages/Hydrogen/...

### ISSUE THREAD

**Issue by tiagohlazarini** [nteract/hydrogen#2012]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Pop!_OS 20.04
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.5

### Stack Trace

Uncaught Error: Cannot find module './mobx.min.js'
Require stack:
- /home/shao/.atom/packages/Hydrogen/node_modules/mobx/lib/index.js
- /home/shao/.atom/packages/Hydrogen/lib/main.js
- /usr/share/atom/resources/app.asar/static/index.html

```
At internal/modules/cjs/loader.js:686

Error: Cannot find module './mobx.min.js'
Require stack:
- /home/shao/.atom/packages/Hydrogen/node_modules/mobx/lib/index.js
- /home/shao/.atom/packages/Hydrogen/lib/main.js
- /usr/share/atom/resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/node_modules/mobx/lib/index.js:3:22)
    at /packages/Hydrogen/node_modules/mobx/lib/index.js:8:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/lib/main.js:11:23)
    at /packages/Hydrogen/lib/main.js:567:24)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:695413)
    at Package.requireMainModule (/usr/share/atom/resources/app/static/<embedded>:11:3193818)
    at Package.activateConfig (/usr/share/atom/resources/app/static/<embedded>:11:3183106)
    at PackageManager.packageHasSettings (/usr/share/atom/resources/app/static/<embedded>:11:909109)
    at PackageCard.hasSettings (/usr/share/atom/resources/app/static/<embedded>:14:2582215)
    at PackageCard.updateSettingsState (/usr/share/atom/resources/app/static/<embedded>:14:2572495)
    at PackageCard.updateInterfaceState (/usr/share/atom/resources/app/static/<embedded>:14:2572318)
    at new PackageCard (/usr/share/atom/resources/app/static/<embedded>:14:2563915)
    at PackageDetailView.completeInitialization (/usr/share/atom/resources/app/static/<embedded>:14:780778)
    at PackageDetailView.loadPackage (/usr/share/atom/resources/app/static/<embedded>:14:781345)
    at new PackageDetailView (/usr/share/atom/resources/app/static/<embedded>:14:777931)
    at SettingsView.getOrCreatePanel (/usr/share/atom/resources/app/static/<embedded>:11:931188)
    at SettingsView.showPanel (/usr/share/atom/resources/app/static/<embedded>:11:931909)
    at SettingsView.showDeferredPanel (/usr/share/atom/resources/app/static/<embedded>:11:931833)
    at SettingsView.initializePanels (/usr/share/atom/resources/app/static/<embedded>:11:929290)
    at /usr/share/atom/resources/app/static/<embedded>:11:926466
    at processTicksAndRejections (internal/process/task_queues.js:79:9)
```

### Commands

```
```

### Non-Core Packages

```
Hydrogen 2.14.5 
```

**Comment by aminya** [comment]
Please redownload the latest version.
