### ISSUE TITLE
Uncaught Error: Cannot find module 'lodash'Require stack:- $ATOM_HOME/packages/Hydrogen/lib/mai...

### ISSUE THREAD

**Issue by watersro** [nteract/hydrogen#2017]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Kali GNU/Linux
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.6

### Stack Trace

Uncaught Error: Cannot find module 'lodash'
Require stack:
- /home/kali/.atom/packages/Hydrogen/lib/main.js
- /usr/share/atom/resources/app.asar/static/index.html

```
At internal/modules/cjs/loader.js:630

Error: Cannot find module 'lodash'
Require stack:
- /home/kali/.atom/packages/Hydrogen/lib/main.js
- /usr/share/atom/resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (<embedded>:11:146814)
    at /packages/Hydrogen/lib/main.js:13:15)
    at /packages/Hydrogen/lib/main.js:624:3)
    at Module.get_Module._compile (<embedded>:11:147498)
    at Object.value [as .js] (<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (<embedded>:1:695477)
    at Package.requireMainModule (<embedded>:11:3196655)
    at Package.activateConfig (<embedded>:11:3185943)
    at PackageManager.packageHasSettings (<embedded>:11:909322)
    at PackageCard.hasSettings (<embedded>:14:2582082)
    at PackageCard.updateSettingsState (<embedded>:14:2572362)
    at PackageCard.updateInterfaceState (<embedded>:14:2572185)
    at <embedded>:14:2580315
    at <embedded>:14:2582333
    at Function.simpleDispatch (<embedded>:11:1190511)
    at Emitter.emit (<embedded>:11:1191952)
    at PackageManager.emitPackageEvent (<embedded>:11:918779)
    at <embedded>:11:915911
    at r (<embedded>:11:910441)
    at n (<embedded>:14:1088976)
    at <embedded>:14:1089130
    at Socket.<anonymous> (<embedded>:14:1087732)
    at Socket.emit (events.js:205:15)
    at Pipe.<anonymous> (net.js:586:12)

```

### Commands

```
     -9:13.9.0 application:open-file (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-one-dark-ui)
     -7:41.8.0 editor:paste-without-reformatting (input.hidden-input)
     -6:40.5.0 core:copy (span.syntax--string.syntax--quoted)
     -6:24.5.0 core:paste (span.syntax--text.syntax--plain.syntax--null-grammar)
     -6:15 core:copy (span.syntax--string.syntax--quoted)
     -6:06.4.0 core:paste (input.hidden-input)
     -5:57.1.0 core:copy (input.hidden-input)
     -5:48.7.0 core:paste (input.hidden-input)
     -5:41.5.0 core:copy (input.hidden-input)
     -5:33.1.0 core:paste (input.hidden-input)
     -5:09.6.0 core:save-as (input.hidden-input)
     -4:11.9.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -4:11.8.0 application:open-file (input.hidden-input)
  4x -4:05.7.0 core:backspace (input.hidden-input)
     -4:02.0 command-palette:toggle (input.hidden-input)
     -3:22.7.0 welcome:show (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
Hydrogen 2.14.6 
scroll-through-time 0.3.1 
```

**Comment by captainsafia** [comment]
@MrLakes Can you share the repro steps?

**Comment by aminya** [comment]
Please redownload the latest version.
