### ISSUE TITLE
Uncaught Error: Cannot find module './lib/rng'Require stack:- $ATOM_HOME/packages\Hydrogen\node...

### ISSUE THREAD

**Issue by GoodGuyDoc** [nteract/hydrogen#2018]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.6

### Stack Trace

Uncaught Error: Cannot find module './lib/rng'
Require stack:
- C:\Users\chris\.atom\packages\Hydrogen\node_modules\jmp\node_modules\uuid\v4.js
- C:\Users\chris\.atom\packages\Hydrogen\node_modules\jmp\index.js
- C:\Users\chris\.atom\packages\Hydrogen\lib\zmq-kernel.js
- C:\Users\chris\.atom\packages\Hydrogen\lib\kernel-manager.js
- C:\Users\chris\.atom\packages\Hydrogen\lib\store\index.js
- C:\Users\chris\.atom\packages\Hydrogen\lib\utils.js
- C:\Users\chris\.atom\packages\Hydrogen\lib\panes\inspector.js
- C:\Users\chris\.atom\packages\Hydrogen\lib\main.js
- C:\Users\chris\AppData\Local\atom\app-1.52.0\resources\app.asar\static\index.html

```
At internal/modules/cjs/loader.js:630

Error: Cannot find module './lib/rng'
Require stack:
- C:\Users\chris\.atom\packages\Hydrogen\node_modules\jmp\node_modules\uuid\v4.js
- C:\Users\chris\.atom\packages\Hydrogen\node_modules\jmp\index.js
- C:\Users\chris\.atom\packages\Hydrogen\lib\zmq-kernel.js
- C:\Users\chris\.atom\packages\Hydrogen\lib\kernel-manager.js
- C:\Users\chris\.atom\packages\Hydrogen\lib\store\index.js
- C:\Users\chris\.atom\packages\Hydrogen\lib\utils.js
- C:\Users\chris\.atom\packages\Hydrogen\lib\panes\inspector.js
- C:\Users\chris\.atom\packages\Hydrogen\lib\main.js
- C:\Users\chris\AppData\Local\atom\app-1.52.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.52.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/node_modules/jmp/node_modules/uuid/v4.js:1:166)
    at /packages/Hydrogen/node_modules/jmp/node_modules/uuid/v4.js:31:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/node_modules/jmp/index.js:36:12)
    at /packages/Hydrogen/node_modules/jmp/index.js:450:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/lib/zmq-kernel.js:3:20)
    at /packages/Hydrogen/lib/zmq-kernel.js:26:31)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/lib/kernel-manager.js:5:33)
```

### Commands

```
```

### Non-Core Packages

```
deepcode 2.0.1 
Hydrogen 2.14.6 
ide-c-cpp 0.1.0 
ide-html 0.6.2 
js-to-string 1.0.4 
kite 0.195.0 
```

**Comment by aminya** [comment]
Please redownload the latest version.
