### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, unlink '~/AppData\Roaming\jupyter\runtime\kern...

### ISSUE THREAD

**Issue by knhoman** [nteract/hydrogen#2021]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Unknown Windows version
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.6

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, unlink 'C:\Users\Андрей\AppData\Roaming\jupyter\runtime\kernel-7797dd9d-f4fb-46d2-82ef-20b38d4da995.json'

```
At fs.js:126

Error: ENOENT: no such file or directory, unlink 'C:\Users\Андрей\AppData\Roaming\jupyter\runtime\kernel-7797dd9d-f4fb-46d2-82ef-20b38d4da995.json'
    at Object.unlinkSync (fs.js:976:3)
    at ZMQKernel.destroy (/packages/Hydrogen/lib/zmq-kernel.js:393:8)
    at Kernel.destroy (/packages/Hydrogen/lib/kernel.js:433:20)
    at /packages/Hydrogen/lib/main.js:293:14)
    at Object.handleKernelCommand (/packages/Hydrogen/lib/main.js:303:4)
    at HTMLElement.hydrogenShutdownKernel (/packages/Hydrogen/lib/main.js:132:16)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:349963)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:348438)
    at AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:1:765678)
    at EventEmitter.t (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:1:773684)
    at EventEmitter.emit (events.js:200:13)
    at Object.onMessage (~/AppData/Local/atom/app-1.52.0/resources/electron.asar/renderer/init.js:42:16)
```

### Commands

```
     -5:30.9.0 hydrogen:run (input.hidden-input)
     -5:30.9.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
  6x -1:28.5.0 core:backspace (input.hidden-input)
     -1:19.9.0 hydrogen:run (input.hidden-input)
     -1:19.9.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -1:12.8.0 core:backspace (input.hidden-input)
     -1:12.2.0 hydrogen:run (input.hidden-input)
     -1:12.2.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:58.2.0 core:undo (input.hidden-input)
     -0:56.9.0 core:save (input.hidden-input)
     -0:35.6.0 hydrogen:run (input.hidden-input)
     -0:35.6.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:15.1.0 hydrogen:restart-kernel (div.line.cursor-line)
     -0:11.5.0 hydrogen:run (input.hidden-input)
     -0:11.5.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:06.0 hydrogen:shutdown-kernel (div.line.cursor-line)
```

### Non-Core Packages

```
Hydrogen 2.14.6 
hydrogen-launcher 1.2.2 
hydrogen-python 0.0.8 
minimap 4.29.9 
script 3.26.0 
```

**Comment by captainsafia** [comment]
Can you share the repro steps?

From the error, it looks like you are trying to connect to a kernel but don't have access to runtime config for the kernel anymore. If that is the case, I'd recommend connecting to a new kernel.

**Comment by knhoman** [comment]
Hello!
I'm sorry that I haven't discribed my issue before.

I use Atom and Python, I connect a big dataframe (~10^6-10^7 lines) and than do some actions with it using Hydrogen. So, sometimes after 5 minutes, sometimes after several houres I have a problem with Python 3 process that use RAM upto all free space. Than I need to sutdown this process in a Task Manager and restart Hydrogen kernel to use it.
I don't have this problem, if I run Python code as a scipt (not by Hydrogen) and if I don't use a big dataframe.

**Comment by aminya** [comment]
Please redownload the latest version.

**Comment by morganhiggin2** [comment]
I have this issue too and wondering what to do
