### ISSUE TITLE
Uncaught Error: Cannot find module 'lodash'Require stack:- $ATOM_HOME/packages\hydrogen\lib\mai...

### ISSUE THREAD

**Issue by ferino75** [nteract/hydrogen#2022]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.6

### Stack Trace

Uncaught Error: Cannot find module 'lodash'
Require stack:
- D:\Apps\Atom64\.atom\packages\hydrogen\lib\main.js
- D:\Apps\Atom64\Atom\resources\app.asar\static\index.html

```
At internal/modules/cjs/loader.js:630

Error: Cannot find module 'lodash'
Require stack:
- D:\Apps\Atom64\.atom\packages\hydrogen\lib\main.js
- D:\Apps\Atom64\Atom\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (D:/Apps/Atom64/Atom/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (D:/Apps/Atom64/Atom/resources/app/static/<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (D:/Apps/Atom64/Atom/resources/app/static/<embedded>:11:146814)
    at /packages/hydrogen/lib/main.js:9:14)
    at /packages/hydrogen/lib/main.js:567:24)
    at Module.get_Module._compile (D:/Apps/Atom64/Atom/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (D:/Apps/Atom64/Atom/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (D:/Apps/Atom64/Atom/resources/app/static/<embedded>:1:736531)
    at Package.requireMainModule (D:/Apps/Atom64/Atom/resources/app/static/<embedded>:11:3711337)
    at Package.activateConfig (D:/Apps/Atom64/Atom/resources/app/static/<embedded>:11:3700625)
    at PackageDetailView.activateConfig (D:/Apps/Atom64/Atom/resources/app/static/<embedded>:14:806325)
    at PackageDetailView.completeInitialization (D:/Apps/Atom64/Atom/resources/app/static/<embedded>:14:805023)
    at PackageDetailView.loadPackage (D:/Apps/Atom64/Atom/resources/app/static/<embedded>:14:805257)
    at new PackageDetailView (D:/Apps/Atom64/Atom/resources/app/static/<embedded>:14:801843)
    at SettingsView.getOrCreatePanel (D:/Apps/Atom64/Atom/resources/app/static/<embedded>:11:932187)
    at SettingsView.showPanel (D:/Apps/Atom64/Atom/resources/app/static/<embedded>:11:932908)
    at HTMLButtonElement.clickHandler (D:/Apps/Atom64/Atom/resources/app/static/<embedded>:14:2626327)
```

### Commands

```
```

### Non-Core Packages

```
Hydrogen 2.14.6 
```

**Comment by captainsafia** [comment]
@ferino75 What are the repro step for this? Have you confirmed that you are installing Hydrogen via `apm`?

**Comment by ferino75** [comment]
Atom X64 for Windows - Portable version
Install via Atom - Packages...

**Comment by aminya** [comment]
Please re-download the latest version.
