### ISSUE TITLE
atom "Failed to activate the Hydrogen package"

### ISSUE THREAD

**Issue by piparsforever** [nteract/hydrogen#2032]
Hi! Just updated Hydrogen package 2.14.6
Any ides how to solve this?

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: macOS 11.0.1
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.6

### Stack Trace

Failed to activate the Hydrogen package

```
At Cannot find module '/Users/janispipars/.atom/packages/Hydrogen/node_modules/ansi-to-react/lib/index.js'. Please verify that the package.json has a valid "main" entry

Error: Cannot find module '/Users/janispipars/.atom/packages/Hydrogen/node_modules/ansi-to-react/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:232:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:369:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:614:27)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/kernel-output-error.js:13:41)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/kernel-output-error.js:44:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/index.js:14:29)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/index.js:27:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/lib/components/result-view/display.js:5:38)
    at /packages/Hydrogen/lib/components/result-view/display.js:82:23)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/lib/store/output.js:8:25)
    at /packages/Hydrogen/lib/store/output.js:62:33)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
```

### Commands

```
     -0:27.5.0 hydrogen:run-cell (input.hidden-input)
  3x -0:06.8.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-beautify 0.33.4 
autocomplete-python 1.16.0 
busy-signal 2.0.1 
file-icons 2.1.45 
git-blame 1.8.0 
git-plus 8.7.1 
highlight-selected 0.17.0 
Hydrogen 2.14.6 
intentions 1.1.5 
kite 0.197.0 
linter 3.1.1 
linter-flake8 2.4.0 
linter-ui-default 2.1.5 
lodash-snippets 2.0.0 
minimap 4.35.6 
minimap-highlight-selected 4.6.2 
script 3.26.0 
todo-show 2.3.2 
```

**Comment by mattgebert** [comment]
I have the same issue, having just updated my atom packages last night. I think it's similar to this bug here: https://github.com/nteract/hydrogen/issues/1945#event-3600138748. Previously the ansi_to_react lib for hydrogen wasn't shipped. I notice this time, while I have files, I don't have the "ansi-to-react\lib" folder.

I proceeded to add the missing folder (again), posted for the previous bug found here: https://github.com/tomato-300yen/ansi_to_react_lib_for_hydrogen. 

Hope this helps.

**Comment by shekeru** [comment]
Same Issue :/

**Comment by piparsforever** [comment]
> I have the same issue, having just updated my atom packages last night. I think it's similar to this bug here: [#1945 (comment)](https://github.com/nteract/hydrogen/issues/1945#event-3600138748). Previously the ansi_to_react lib for hydrogen wasn't shipped. I notice this time, while I have files, I don't have the "ansi-to-react\lib" folder.
> 
> I proceeded to add the missing folder (again), posted for the previous bug found here: https://github.com/tomato-300yen/ansi_to_react_lib_for_hydrogen. This solved my problem, hydrogen is working again.
> 
> Hope this helps.

It works now.
Thank you!

**Comment by Miquel1981** [comment]
Works for me, thanks a lot.

**Comment by avanavana** [comment]
Atom is telling me this is the same issue, which is why I am posting this here, though it doesn't seem so to me… 

1. Try to run any cell in, with any kernel.
2. *Error*

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Mac OS X 10.15.6
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.6


### Stack Trace

Failed to activate the Hydrogen package

```
At The module '/Users/avanavana/.atom/packages/Hydrogen/node_modules/zeromq/build/Release/zmq.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 73. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

Error: The module '/Users/avanavana/.atom/packages/Hydrogen/node_modules/zeromq/build/Release/zmq.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 73. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:138:31)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/node_modules/zeromq/lib/index.js:6:11)
    at /packages/Hydrogen/node_modules/zeromq/lib/index.js:857:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/node_modules/zeromq/index.js:2:18)
    at /packages/Hydrogen/node_modules/zeromq/index.js:3:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/Hydrogen/node_modules/jmp/index.js:37:11)
    at /packages/Hydrogen/node_modules/jmp/index.js:450:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
```

### Commands

```
     -1:08.9.0 hydrogen:run (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 2.0.1 
Chromo-Color-Previews 1.8.3 
color-picker 2.3.0 
Hydrogen 2.14.6 
intentions 1.1.5 
jekyll 2.1.0 
jekyll-syntax-highlighting 0.1.0 
language-babel 2.85.0 
language-graphql 1.0.0 
linter 3.1.1 
linter-eslint 8.5.5 
linter-ui-default 2.3.4 
pigments 0.40.6 
platformio-ide-terminal 2.10.1 
prettier-atom 0.60.1 
process-palette 0.17.0 
teletype 0.13.4 
termination 0.7.6 
zotero-citations 5.2.0 
```

Note:  this happened AFTER i tried `npm rebuild` in the `.atom/packages/Hydrogen` directory.   I had previously tried uninstalling/reinstalling, running `apm rebuild`, etc to no avail.    I thought this might be happening because I upgraded my node to 14.15, but then I read that atom uses its own version—so I don't know what's going on.  Can't seem to fix it.
