### ISSUE TITLE
Uncaught Error: Cannot find module './../utils'Require stack:- $ATOM_HOME/packages/Hydrogen/lib...

### ISSUE THREAD

**Issue by paragpatil1999** [nteract/hydrogen#2043]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: KDE neon
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.6

### Stack Trace

Uncaught Error: Cannot find module './../utils'
Require stack:
- /home/kaneki99/.atom/packages/Hydrogen/lib/panes/inspector.js
- /home/kaneki99/.atom/packages/Hydrogen/lib/main.js
- /usr/share/atom/resources/app.asar/static/index.html

```
At internal/modules/cjs/loader.js:630

Error: Cannot find module './../utils'
Require stack:
- /home/kaneki99/.atom/packages/Hydrogen/lib/panes/inspector.js
- /home/kaneki99/.atom/packages/Hydrogen/lib/main.js
- /usr/share/atom/resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (<embedded>:11:146814)
    at /packages/Hydrogen/lib/panes/inspector.js:17:14)
    at /packages/Hydrogen/lib/panes/inspector.js:65:3)
    at Module.get_Module._compile (<embedded>:11:147498)
    at Object.value [as .js] (<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (<embedded>:11:146814)
    at /packages/Hydrogen/lib/main.js:23:23)
    at /packages/Hydrogen/lib/main.js:624:3)
    at Module.get_Module._compile (<embedded>:11:147498)
    at Object.value [as .js] (<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (<embedded>:1:696928)
    at Package.requireMainModule (<embedded>:11:3578827)
    at Package.activateConfig (<embedded>:11:3568115)
    at PackageManager.packageHasSettings (<embedded>:11:910108)
    at PackageCard.hasSettings (<embedded>:14:2639258)
    at PackageCard.updateSettingsState (<embedded>:14:2629526)
    at PackageCard.updateInterfaceState (<embedded>:14:2629349)
    at <embedded>:14:2637491
    at <embedded>:14:2639509
    at Function.simpleDispatch (<embedded>:11:1190051)
    at Emitter.emit (<embedded>:11:1191492)
    at PackageManager.emitPackageEvent (<embedded>:11:919565)
    at <embedded>:11:916697
    at r (<embedded>:11:911227)
    at s (<embedded>:14:1134638)
    at <embedded>:14:1134792
    at Socket.<anonymous> (<embedded>:14:1133394)
    at Socket.emit (events.js:205:15)
    at Pipe.<anonymous> (net.js:586:12)

```

### Commands

```
     -2:59.2.0 application:add-project-folder (div.panels-item)
  7x -2:01.7.0 core:backspace (input.hidden-input)
     -1:33 core:cancel (div.package-detail)
 18x -0:21.8.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-material-ui 2.1.3 
Hydrogen 2.14.6 
```

**Comment by aminya** [comment]
Please redownload the latest version.
