### ISSUE TITLE
Giant IPKernelApp Error Popping Up in Atom

### ISSUE THREAD

**Issue by Panda-Farmer** [nteract/hydrogen#2044]
Starting a few days ago, after months without issue, I began having a giant error box keep popping up when editing my code in Atom. I believe it is from the Hydrogen plugin, the weird thing is even with this error the code still runs and does what I want it too.

I even created a new conda environment, installing only what I needed (pandas, geopandas, descartes, jupyter) and even when using the new environment I am getting this issue. I've tried upgrading ipykernel but it is already the most recent version.

I'm about to lose my mind having this giant red error box keep popping up 10 seconds after I exit it out. Please let me know if there is any additional information I can provide to help diagnose the issue.

Error Message: "[IPKernelApp] ERROR | Exception in message handler: Traceback (most recent call last): File "/home/username/anaconda3/envs/fresh/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 268, in dispatch_shell yield gen.maybe_future(handler(stream, idents, msg)) File "/home/username/anaconda3/envs/fresh/lib/python3.8/site-packages/tornado/gen.py", line 762, in run value = future.result() File "/home/username/anaconda3/envs/fresh/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper yielded = ctx_run(next, result) File "/home/username/anaconda3/envs/fresh/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 583, in complete_request matches = yield gen.maybe_future(self.do_complete(code, cursor_pos)) File "/home/username/anaconda3/envs/fresh/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 360, in do_complete return self._experimental_do_complete(code, cursor_pos) File "/home/username/anaconda3/envs/fresh/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 385, in _experimental_do_complete completions = list(_rectify_completions(code, raw_completions)) File "/home/username/anaconda3/envs/fresh/lib/python3.8/site-packages/IPython/core/completer.py", line 484, in rectify_completions completions = list(completions) File "/home/username/anaconda3/envs/fresh/lib/python3.8/site-packages/IPython/core/completer.py", line 1818, in completions for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000): File "/home/username/anaconda3/envs/fresh/lib/python3.8/site-packages/IPython/core/completer.py", line 1861, in _completions matched_text, matches, matches_origin, jedi_matches = self._complete( File "/home/username/anaconda3/envs/fresh/lib/python3.8/site-packages/IPython/core/completer.py", line 2029, in _complete completions = self._jedi_matches( File "/home/username/anaconda3/envs/fresh/lib/python3.8/site-packages/IPython/core/completer.py", line 1373, in _jedi_matches interpreter = jedi.Interpreter( File "/home/username/anaconda3/envs/fresh/lib/python3.8/site-packages/jedi/api/init.py", line 725, in init super().init(code, environment=environment, TypeError: init() got an unexpected keyword argument 'column'"

**Comment by Vlasko** [comment]
I am having a very similar issue with a new virtual environment that I have set up, but it does not replicate with old virtual environments. The error message is almost exactly the same (apart from user details) and it ends with `TypeError: init() got an unexpected keyword argument 'column'`

**Comment by Cassio-Lima** [comment]
Same case here.

**Comment by n-riesco** [comment]
It looks like an IPython issue: https://github.com/ipython/ipython/issues/12740

[Pinning jedi](https://github.com/jupyter/notebook/issues/5925#issuecomment-754619913) should workaround the issue:

```
conda install jedi==0.17.1
```
