### ISSUE TITLE
Uncaught Error: Cannot find module './existing-kernel-picker'Require stack:- $ATOM_HOME/package...

### ISSUE THREAD

**Issue by seylab** [nteract/hydrogen#2048]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.6

### Stack Trace

Uncaught Error: Cannot find module './existing-kernel-picker'
Require stack:
- C:\Users\Cevdet Anamakine\.atom\packages\Hydrogen\lib\main.js
- C:\Users\Cevdet Anamakine\AppData\Local\atom\app-1.54.0\resources\app.asar\static\index.html

```
At internal/modules/cjs/loader.js:630

Error: Cannot find module './existing-kernel-picker'
Require stack:
- C:\Users\Cevdet Anamakine\.atom\packages\Hydrogen\lib\main.js
- C:\Users\Cevdet Anamakine\AppData\Local\atom\app-1.54.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.54.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (<embedded>:11:155387)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (<embedded>:11:146720)
    at /packages/Hydrogen/lib/main.js:63:29)
    at /packages/Hydrogen/lib/main.js:624:3)
    at Module.get_Module._compile (<embedded>:11:147404)
    at Object.value [as .js] (<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (<embedded>:1:723602)
    at Package.requireMainModule (<embedded>:11:3670531)
    at Package.activateConfig (<embedded>:11:3659819)
    at PackageManager.packageHasSettings (<embedded>:11:910238)
    at PackageCard.hasSettings (<embedded>:14:2650992)
    at PackageCard.updateSettingsState (<embedded>:14:2641260)
    at PackageCard.updateInterfaceState (<embedded>:14:2641083)
    at <embedded>:14:2649225
    at <embedded>:14:2651243
    at Function.simpleDispatch (<embedded>:11:1190181)
    at Emitter.emit (<embedded>:11:1191622)
    at PackageManager.emitPackageEvent (<embedded>:11:919695)
    at <embedded>:11:916827
    at r (<embedded>:11:911357)
    at s (<embedded>:14:1121307)
    at ChildProcess.<anonymous> (<embedded>:14:1121513)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

```

### Commands

```
     -4:46.1.0 github:toggle-github-tab (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:17 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
Hydrogen 2.14.6 
teletype 0.13.4 
```

**Comment by ramantehlan** [comment]
@seylab, Thank you for raising an issue. 
It seems like a similar this #1822 

It is most probably a problem with your environment. Do you have the right kernels installed in your system?

**Comment by aminya** [comment]
Please redownload the latest version.
