### ISSUE TITLE
Uncaught Error: Cannot find module './cjs/scheduler.production.min.js'Require stack:- $ATOM_HOM...

### ISSUE THREAD

**Issue by andreamu002** [nteract/hydrogen#2051]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Unknown Windows version
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.7

### Stack Trace

Uncaught Error: Cannot find module './cjs/scheduler.production.min.js'
Require stack:
- C:\Users\ANDREA MUTTI\.atom\packages\Hydrogen\node_modules\scheduler\index.js
- C:\Users\ANDREA MUTTI\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js
- C:\Users\ANDREA MUTTI\.atom\packages\Hydrogen\node_modules\react-dom\index.js
- C:\Users\ANDREA MUTTI\.atom\packages\Hydrogen\lib\utils.js
- C:\Users\ANDREA MUTTI\.atom\packages\Hydrogen\lib\panes\inspector.js
- C:\Users\ANDREA MUTTI\.atom\packages\Hydrogen\lib\main.js
- C:\Users\ANDREA MUTTI\AppData\Local\atom\app-1.54.0\resources\app.asar\static\index.html

```
At internal/modules/cjs/loader.js:630

Error: Cannot find module './cjs/scheduler.production.min.js'
Require stack:
- C:\Users\ANDREA MUTTI\.atom\packages\Hydrogen\node_modules\scheduler\index.js
- C:\Users\ANDREA MUTTI\.atom\packages\Hydrogen\node_modules\react-dom\cjs\react-dom.production.min.js
- C:\Users\ANDREA MUTTI\.atom\packages\Hydrogen\node_modules\react-dom\index.js
- C:\Users\ANDREA MUTTI\.atom\packages\Hydrogen\lib\utils.js
- C:\Users\ANDREA MUTTI\.atom\packages\Hydrogen\lib\panes\inspector.js
- C:\Users\ANDREA MUTTI\.atom\packages\Hydrogen\lib\main.js
- C:\Users\ANDREA MUTTI\AppData\Local\atom\app-1.54.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.54.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:155387)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:146720)
    at /packages/Hydrogen/node_modules/scheduler/index.js:4:20)
    at /packages/Hydrogen/node_modules/scheduler/index.js:9:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:146720)
    at /packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:13:67)
    at /packages/Hydrogen/node_modules/react-dom/cjs/react-dom.production.min.js:294:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:146720)
    at /packages/Hydrogen/node_modules/react-dom/index.js:35:20)
    at /packages/Hydrogen/node_modules/react-dom/index.js:40:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:146720)
    at /packages/Hydrogen/lib/utils.js:4:26)
```

### Commands

```
```

### Non-Core Packages

```
Hydrogen 2.14.7 
```

**Comment by aminya** [comment]
Please redownload the latest version.
