### ISSUE TITLE
Uncaught Error: Cannot find module './ws-kernel-picker'Require stack:- $ATOM_HOME/packages\Hydr...

### ISSUE THREAD

**Issue by CemRoot** [nteract/hydrogen#2057]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.7

### Stack Trace

Uncaught Error: Cannot find module './ws-kernel-picker'
Require stack:
- C:\Users\eminc\.atom\packages\Hydrogen\lib\main.js
- C:\Users\eminc\AppData\Local\atom\app-1.54.0\resources\app.asar\static\index.html

```
At internal/modules/cjs/loader.js:630

Error: Cannot find module './ws-kernel-picker'
Require stack:
- C:\Users\eminc\.atom\packages\Hydrogen\lib\main.js
- C:\Users\eminc\AppData\Local\atom\app-1.54.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.54.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:155387)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:146720)
    at /packages/Hydrogen/lib/main.js:59:23)
    at /packages/Hydrogen/lib/main.js:624:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:1:723602)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3670531)
    at Package.activateConfig (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3659819)
    at PackageManager.packageHasSettings (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:910238)
    at PackageCard.hasSettings (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:2650992)
    at PackageCard.updateSettingsState (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:2641260)
    at PackageCard.updateInterfaceState (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:2641083)
    at ~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:2649225
    at ~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:2651243
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:1191622)
    at PackageManager.emitPackageEvent (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:919695)
    at ~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:916827
    at r (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:911357)
    at s (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:1121307)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:1121513)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

### Commands

```
     -8:52.1.0 bracket-matcher:remove-matching-brackets (input.hidden-input)
  2x -8:51.9.0 core:backspace (input.hidden-input)
     -8:47.9.0 core:cut (input.hidden-input)
     -8:45.9.0 core:backspace (input.hidden-input)
     -8:45.4.0 snippets:next-tab-stop (input.hidden-input)
     -8:45.4.0 snippets:expand (input.hidden-input)
     -8:45.4.0 editor:indent (input.hidden-input)
 88x -8:45.1.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
Hydrogen 2.14.7 
platformio-ide-terminal 2.10.1 
```

**Comment by aminya** [comment]
Please redownload the latest version.
