### ISSUE TITLE
Uncaught Error: The module '$ATOM_HOME/packages/Hydrogen/node_modules/@aminya/zeromq/build/Releas...

### ISSUE THREAD

**Issue by genistefano** [nteract/hydrogen#2095]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.2.3
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.15.3

### Stack Trace

Uncaught Error: The module '/Users/GenyTheLion/.atom/packages/Hydrogen/node_modules/@aminya/zeromq/build/Release/zmq.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 80. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

```
At electron/js2c/asar.js:140

Error: The module '/Users/GenyTheLion/.atom/packages/Hydrogen/node_modules/@aminya/zeromq/build/Release/zmq.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 80. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149153)
    at load (/packages/Hydrogen/node_modules/node-gyp-build/index.js:21:10)
    at /packages/Hydrogen/node_modules/@aminya/zeromq/binding.js:1:198)
    at /packages/Hydrogen/node_modules/@aminya/zeromq/binding.js:3:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149153)
    at /packages/Hydrogen/node_modules/@aminya/zeromq/lib/index.js:6:11)
    at /packages/Hydrogen/node_modules/@aminya/zeromq/lib/index.js:857:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149153)
    at /packages/Hydrogen/node_modules/@aminya/zeromq/index.js:2:18)
    at /packages/Hydrogen/node_modules/@aminya/zeromq/index.js:3:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149153)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.18 
atom-html-preview 0.2.6 
atom-ide-ui 0.13.0 
atom-language-r 1.4.8 
hey-pane 1.2.0 
Hydrogen 2.15.3 
hydrogen-launcher 1.2.2 
ide-r 0.1.8 
language-r 0.4.2 
platformio-ide-terminal 2.10.1 
scroll-through-time 0.3.1 
```

**Comment by n-riesco** [comment]
I guess this happened after updating to the latest Atom. If that's the case, uninstalling and installing again Hydrogen should fix the issue.
