### ISSUE TITLE
Uncaught Error: Cannot find module 'lodash'Require stack:- $ATOM_HOME/packages\hydrogen\dist\ma...

### ISSUE THREAD

**Issue by ferino75** [nteract/hydrogen#2100]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.15.3

### Stack Trace

Uncaught Error: Cannot find module 'lodash'
Require stack:
- E:\WINapps64\Atom\.atom\packages\hydrogen\dist\main.js
- E:\WINapps64\Atom\Atom x64\resources\app.asar\static\index.html

```
At internal/modules/cjs/loader.js:800

Error: Cannot find module 'lodash'
Require stack:
- E:\WINapps64\Atom\.atom\packages\hydrogen\dist\main.js
- E:\WINapps64\Atom\Atom x64\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (E:/WINapps64/Atom/Atom x64/resources/app/static/<embedded>:11:157820)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (E:/WINapps64/Atom/Atom x64/resources/app/static/<embedded>:11:149153)
    at /packages/hydrogen/dist/main.js:27:34)
    at /packages/hydrogen/dist/main.js:447:3)
    at Module.get_Module._compile (E:/WINapps64/Atom/Atom x64/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (E:/WINapps64/Atom/Atom x64/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (E:/WINapps64/Atom/Atom x64/resources/app/static/<embedded>:1:802772)
    at requireModule (E:/WINapps64/Atom/Atom x64/resources/app/static/<embedded>:14:1191588)
    at Package.requireMainModule (E:/WINapps64/Atom/Atom x64/resources/app/static/<embedded>:11:3520819)
    at Package.activateConfig (E:/WINapps64/Atom/Atom x64/resources/app/static/<embedded>:11:3510107)
    at PackageDetailView.activateConfig (E:/WINapps64/Atom/Atom x64/resources/app/static/<embedded>:14:858241)
    at PackageDetailView.completeInitialization (E:/WINapps64/Atom/Atom x64/resources/app/static/<embedded>:14:856939)
    at PackageDetailView.loadPackage (E:/WINapps64/Atom/Atom x64/resources/app/static/<embedded>:14:857173)
    at new PackageDetailView (E:/WINapps64/Atom/Atom x64/resources/app/static/<embedded>:14:853759)
    at SettingsView.getOrCreatePanel (E:/WINapps64/Atom/Atom x64/resources/app/static/<embedded>:11:930054)
    at SettingsView.showPanel (E:/WINapps64/Atom/Atom x64/resources/app/static/<embedded>:11:930775)
    at SettingsView.showDeferredPanel (E:/WINapps64/Atom/Atom x64/resources/app/static/<embedded>:11:930699)
    at SettingsView.initializePanels (E:/WINapps64/Atom/Atom x64/resources/app/static/<embedded>:11:928156)
    at E:/WINapps64/Atom/Atom x64/resources/app/static/<embedded>:11:925332
    at processTicksAndRejections (internal/process/task_queues.js:76:11)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-material-ui 2.1.3 
Hydrogen 2.15.3 
```

**Comment by ferino75** [comment]
Path "E:\WINapps64\Atom.atom\packages\hydrogen\dist\main.js" is wrong - why?
correct path: "E:\WINapps64\Atom\.atom\packages\hydrogen\dist\main.js"

**Comment by aminya** [comment]
Have you tried reinstalling?
