### ISSUE TITLE
Uncaught Error: Cannot find module '$ATOM_HOME/packages\Hydrogen\node_modules\react-table\lib\ind...

### ISSUE THREAD

**Issue by UdayX** [nteract/hydrogen#2133]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 11 Pro Insider Preview
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.16.3

### Stack Trace

Uncaught Error: Cannot find module 'C:\Users\USER\.atom\packages\Hydrogen\node_modules\react-table\lib\index.js'. Please verify that the package.json has a valid "main" entry

```
At internal/modules/cjs/loader.js:309

Error: Cannot find module 'C:\Users\USER\.atom\packages\Hydrogen\node_modules\react-table\lib\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:301:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:532:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:784:27)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (<embedded>:11:157920)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (<embedded>:11:149207)
    at /packages/Hydrogen/dist/components/kernel-monitor.js:26:36)
    at /packages/Hydrogen/dist/components/kernel-monitor.js:180:3)
    at Module.get_Module._compile (<embedded>:11:149891)
    at Object.value [as .js] (<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (<embedded>:11:149207)
    at /packages/Hydrogen/dist/panes/kernel-monitor.js:9:42)
    at /packages/Hydrogen/dist/panes/kernel-monitor.js:28:3)
    at Module.get_Module._compile (<embedded>:11:149891)
    at Object.value [as .js] (<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (<embedded>:11:149207)
    at /packages/Hydrogen/dist/main.js:32:42)
    at /packages/Hydrogen/dist/main.js:456:3)
    at Module.get_Module._compile (<embedded>:11:149891)
    at Object.value [as .js] (<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (<embedded>:1:802772)
    at requireModule (<embedded>:14:1195622)
    at Package.requireMainModule (<embedded>:11:3520513)
    at Package.activateConfig (<embedded>:11:3509801)
    at PackageManager.packageHasSettings (<embedded>:11:908520)
    at PackageCard.hasSettings (<embedded>:14:2729736)
    at PackageCard.updateSettingsState (<embedded>:14:2720004)
    at PackageCard.updateInterfaceState (<embedded>:14:2719827)
    at <embedded>:14:2727969
    at <embedded>:14:2729987
    at Function.simpleDispatch (<embedded>:11:1186925)
    at Emitter.emit (<embedded>:11:1188366)
    at PackageManager.emitPackageEvent (<embedded>:11:917977)
    at <embedded>:11:915109
    at r (<embedded>:11:909639)
    at n (<embedded>:14:1194945)
    at ChildProcess.<anonymous> (<embedded>:14:1195151)
    at ChildProcess.emit (events.js:223:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

```

### Commands

```
```

### Non-Core Packages

```
Hydrogen 2.16.3 
monokai 0.28.0 
run 0.0.1 
```

**Comment by nikolaus1804a** [comment]
[GT](www.ftp_saca112/8080:369) 
Duplicate of #

**Comment by nikolaus1804a** [comment]
Gt
