### ISSUE TITLE
ArchLinux. @aminya/zeromq install error

### ISSUE THREAD

**Issue by AlertRED** [nteract/hydrogen#2139]
Hello. I tried to install hydrogen `apm install hydrogen` but I have got message:

```
npm ERR! code ELIFECYCLE
npm ERR! errno 243
npm ERR! @aminya/zeromq@5.2.16 install: `node-gyp-build || npm run build:libzmq`
npm ERR! Exit status 243
npm ERR! 
npm ERR! Failed at the @aminya/zeromq@5.2.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.atom/.apm/_logs/2021-12-08T20_18_47_269Z-debug.log
```
Of course I installed zeromq package in my system with code `pacman -S zeromq`.
Also I cleared cache 
```
rm -r ~/.atom/compile-cache
rm -r ~/.atom/blob-store
```
but I get some error... I would be grateful for any help

**Comment by sdsaati** [comment]
I also can't install it (I'm using endeavouros):
```bash
apm install hydrogen               
Installing hydrogen to /home/sdsaati/.atom/packages ✗

> @aminya/zeromq@5.2.16 install /tmp/apm-install-dir-20211118-14711-3bbtry.af1o8/node_modules/Hydrogen/node_modules/@aminya/zeromq
> node-gyp-build || npm run build:libzmq


> @aminya/zeromq@5.2.16 build:libzmq
> node-gyp rebuild


npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated json-parser@1.1.5: `json-parser` is deprecated. Please use `comment-json` instead
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
(node:14842) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 5.15.6-arch2-1
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-20211118-14711-3bbtry.af1o8/node_modules/Hydrogen/node_modules/@aminya/zeromq
gyp ERR! node -v v17.1.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:353:16)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 5.15.6-arch2-1
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-20211118-14711-3bbtry.af1o8/node_modules/Hydrogen/node_modules/@aminya/zeromq
gyp ERR! node -v v17.1.0
gyp ERR! node-gyp -v v8.2.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-20211118-14711-3bbtry.af1o8/package.json'
npm WARN @nteract/outputs@3.0.11 requires a peer of react@^16.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN @nteract/transform-vega@7.0.10 requires a peer of react@^16.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-table@6.11.5 requires a peer of react@^16.x.x but none is installed. You must install peer dependencies yourself.
npm WARN react-table@6.11.5 requires a peer of react-dom@^16.x.x but none is installed. You must install peer dependencies yourself.
npm WARN @nteract/markdown@4.6.2 requires a peer of react@^16.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nteract/markdown@4.6.2 requires a peer of react-dom@^16.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN mobx-react@6.3.1 requires a peer of react@^16.8.0 || 16.9.0-alpha.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-markdown@4.3.1 requires a peer of react@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nteract/presentational-components@3.4.12 requires a peer of react@^16.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-json-tree@0.12.1 requires a peer of react@^16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-json-tree@0.12.1 requires a peer of react-dom@^16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN mobx-react-lite@2.2.2 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN apm-install-dir-20211118-14711-3bbtry.af1o8 No description
npm WARN apm-install-dir-20211118-14711-3bbtry.af1o8 No repository field.
npm WARN apm-install-dir-20211118-14711-3bbtry.af1o8 No README data
npm WARN apm-install-dir-20211118-14711-3bbtry.af1o8 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @aminya/zeromq@5.2.16 install: `node-gyp-build || npm run build:libzmq`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @aminya/zeromq@5.2.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sdsaati/.atom/.apm/_logs/2021-12-18T04_08_12_841Z-debug.log
```

**Comment by noorhe** [comment]
Hi! Looks like the same issue here
```
> @aminya/zeromq@5.2.16 install /tmp/apm-install-dir-20211119-82617-m6l22x.ruzm/node_modules/Hydrogen/node_modules/@aminya/zeromq
> node-gyp-build || npm run build:libzmq


> @aminya/zeromq@5.2.16 build:libzmq
> node-gyp rebuild


npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated json-parser@1.1.5: `json-parser` is deprecated. Please use `comment-json` instead
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
(node:82696) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 5.13.19-2-MANJARO
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-20211119-82617-m6l22x.ruzm/node_modules/Hydrogen/node_modules/@aminya/zeromq
gyp ERR! node -v v17.2.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:261:16)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 5.13.19-2-MANJARO
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-20211119-82617-m6l22x.ruzm/node_modules/Hydrogen/node_modules/@aminya/zeromq
gyp ERR! node -v v17.2.0
gyp ERR! node-gyp -v v8.3.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-20211119-82617-m6l22x.ruzm/package.json'
npm WARN @nteract/outputs@3.0.11 requires a peer of react@^16.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN @nteract/transform-vega@7.0.10 requires a peer of react@^16.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN mobx-react@6.3.1 requires a peer of react@^16.8.0 || 16.9.0-alpha.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nteract/markdown@4.6.2 requires a peer of react@^16.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nteract/markdown@4.6.2 requires a peer of react-dom@^16.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-table@6.11.5 requires a peer of react@^16.x.x but none is installed. You must install peer dependencies yourself.
npm WARN react-table@6.11.5 requires a peer of react-dom@^16.x.x but none is installed. You must install peer dependencies yourself.
npm WARN react-markdown@4.3.1 requires a peer of react@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nteract/presentational-components@3.4.12 requires a peer of react@^16.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-json-tree@0.12.1 requires a peer of react@^16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-json-tree@0.12.1 requires a peer of react-dom@^16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN mobx-react-lite@2.2.2 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN apm-install-dir-20211119-82617-m6l22x.ruzm No description
npm WARN apm-install-dir-20211119-82617-m6l22x.ruzm No repository field.
npm WARN apm-install-dir-20211119-82617-m6l22x.ruzm No README data
npm WARN apm-install-dir-20211119-82617-m6l22x.ruzm No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @aminya/zeromq@5.2.16 install: `node-gyp-build || npm run build:libzmq`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @aminya/zeromq@5.2.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by julibeg** [comment]
same for me on Manjaro 5.13.19-2

**Comment by georgebwang** [comment]
same here, running Arch Linux 5.15.12-arch1-1 kernel. GNOME 41.2desktop environment.

**Comment by salperinlea** [comment]
Same issue, confirming that the workaround mentioned by @georgebwang using the same kernel and the Plasma DE has fixed it.

**Comment by salperinlea** [comment]
Update: my previous comment is not true, with kernel 5.16; command line installation fails, while settings-view installation "succeeds", but produces a package which does nothing at all and provides no feedback.

**Comment by bjstarosta** [comment]
Confirming I also have this problem on Arch 5.16.2-arch1-1

```
$ apm --version
apm  2.6.4
npm  6.14.9
node 17.3.0 x64
atom 1.58.0
python 3.10.2
git 2.35.0
$ atom --version
Atom    : 1.58.0
Electron: 9.4.4
Chrome  : 83.0.4103.122
Node    : 12.14.1
```

**Comment by rafhdriva** [comment]
Hey, everyone! Hope you all are doing well. I'm still with this issue on my Arch Linux and Hydrogen is the thing that I use the most for work. I tried the fix mentioned above but nothing works, any update on this? Really thank you for this amazing work!

**Comment by zepadovani** [comment]
Tried to modify AUR as suggested by @georgebwang, but, even if I have suceeded to install Atom this way, Hydrogen does not install.

GNOME Shell 41.4

DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.2.5
DISTRIB_CODENAME=Qonos
DISTRIB_DESCRIPTION="Manjaro Linux"

Kernel:
5.16.2-2-rt19-MANJARO #1 SMP PREEMPT_RT Tue Feb 15 09:37:27 CET 2022 x86_64 GNU/Linux

atom --version:
Atom    : 1.61.0-beta0
Electron: 11.4.12
Chrome  : 87.0.4280.141
Node    : 12.18.3

apm --version:
apm  2.6.4
npm  6.14.9
node 17.7.1 x64
atom unknown
python 3.10.2
git 2.35.1

**Comment by EKYS12** [comment]
Just wanted to add that I have this issue as well.

DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.2.5
DISTRIB_CODENAME=Qonos
DISTRIB_DESCRIPTION="Manjaro Linux"

kernel 5.15.28-1
