### ISSUE TITLE
Can't install with APM

### ISSUE THREAD

**Issue by TheJarmanitor** [nteract/hydrogen#2141]
### Prerequisites

- [Y] Have you checked the solutions in our [troubleshooting guide](https://nteract.gitbooks.io/hydrogen/docs/Troubleshooting.html) for common problems ?
- [Y] Have you checked that your issue [isn't already filed](https://github.com/nteract/hydrogen/issues) ?

### Description

i can't install hydrogen using APM, i looked for similar problems in the issues tab but none seem to work

```
> @aminya/zeromq@5.2.16 install /tmp/apm-install-dir-20211117-2101-xccwf8.n2ias/node_modules/Hydrogen/node_modules/@aminya/zeromq
> node-gyp-build || npm run build:libzmq


> @aminya/zeromq@5.2.16 build:libzmq
> node-gyp rebuild


npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated json-parser@1.1.5: `json-parser` is deprecated. Please use `comment-json` instead
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
(node:2171) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 5.15.8-arch1-1
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-20211117-2101-xccwf8.n2ias/node_modules/Hydrogen/node_modules/@aminya/zeromq
gyp ERR! node -v v17.2.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:259:16)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 5.15.8-arch1-1
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-20211117-2101-xccwf8.n2ias/node_modules/Hydrogen/node_modules/@aminya/zeromq
gyp ERR! node -v v17.2.0
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-20211117-2101-xccwf8.n2ias/package.json'
npm WARN @nteract/outputs@3.0.11 requires a peer of react@^16.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN @nteract/markdown@4.6.2 requires a peer of react@^16.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nteract/markdown@4.6.2 requires a peer of react-dom@^16.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN @nteract/transform-vega@7.0.10 requires a peer of react@^16.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN mobx-react@6.3.1 requires a peer of react@^16.8.0 || 16.9.0-alpha.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-table@6.11.5 requires a peer of react@^16.x.x but none is installed. You must install peer dependencies yourself.
npm WARN react-table@6.11.5 requires a peer of react-dom@^16.x.x but none is installed. You must install peer dependencies yourself.
npm WARN react-markdown@4.3.1 requires a peer of react@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nteract/presentational-components@3.4.12 requires a peer of react@^16.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-json-tree@0.12.1 requires a peer of react@^16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-json-tree@0.12.1 requires a peer of react-dom@^16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN mobx-react-lite@2.2.2 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN apm-install-dir-20211117-2101-xccwf8.n2ias No description
npm WARN apm-install-dir-20211117-2101-xccwf8.n2ias No repository field.
npm WARN apm-install-dir-20211117-2101-xccwf8.n2ias No README data
npm WARN apm-install-dir-20211117-2101-xccwf8.n2ias No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @aminya/zeromq@5.2.16 install: `node-gyp-build || npm run build:libzmq`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @aminya/zeromq@5.2.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### Versions

OS version:
[Your OS's version]
EndeavourOS Atlantic

> `atom --version`

```
Atom    : 1.58.0
Electron: 9.4.4
Chrome  : 83.0.4103.122
Node    : 12.14.1
```

> `apm --version`

```
apm  2.6.4
npm  6.14.9
node 17.2.0 x64
atom 1.58.0
python 3.9.5


```

Hydrogen version:

[Your Hydrogen's version]
i'm trying to install 2.16.3

### Plugins

Have you installed and activated any of the Hydrogen plugins below ?

- [ ] hydrogen-python
- [ ] Hydrogen Launcher
- [ ] Data Explorer

**Comment by TheJarmanitor** [comment]
I was able to install it by modifying atom beta's[ AUR](https://aur.archlinux.org/packages/atom-editor-beta-bin/). Downloaded the GIT and removed "gconf" from the dependencies. 

I'm closing this
