### ISSUE TITLE
Hydrogen  successfully installed but can't execute on Atom

### ISSUE THREAD

**Issue by shanakap** [nteract/hydrogen#2143]
I am having trouble with executing codes with `Hydrogen`. I have tried #1538 but had no luck. I am trying to setup Atom on my new Mac hence running into this issue. 

1. Download Atom from https://atom.io
2. Dragged and dropped the file to `Applications`
3. Install all the shell commands : `Atom-> Install Shell commands`
4. On terminal : 
```
python3 -m venv new_env
source new_env/bin/activate 
python3 -m pip install ipykernel
python3 -m ipykernel install --user --name new_env
```
5. Install `Hydrogen`

6. When I try to execute  for example `import numpy` it gives the following error on the side after it prompts to select the virtual env - `new_env` :

```
new_env

Traceback (most recent call last): File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
```

**Versions:**
Python 3.10.2
macOS Monterey
Atom 1.59
Hydrogen 2.16.3

**Comment by nikolaus1804a** [comment]
> I am having trouble with executing codes with `Hydrogen`. I have tried #1538 but had no luck. I am trying to setup Atom on my new Mac hence running into this issue.
> 
> 1. Download Atom from https://atom.io
> 2. Dragged and dropped the file to `Applications`
> 3. Install all the shell commands : `Atom-> Install Shell commands`
> 4. On terminal :
> 
> ```
> python3 -m venv new_env
> source new_env/bin/activate 
> python3 -m pip install ipykernel
> python3 -m ipykernel install --user --name new_env
> ```
> 
> 5. Install `Hydrogen`
> 6. When I try to execute  for example `import numpy` it gives the following error on the side after it prompts to select the virtual env - `new_env` :
> 
> ```
> new_env
> 
> Traceback (most recent call last): File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
> ```
> 
> **Versions:** Python 3.10.2 macOS Monterey Atom 1.59 Hydrogen 2.16.3
> 
> **Additional details:**
> 
> ```
> {
>   "kernelspecs": {
>     "new_env": {
>       "resource_dir": "/Users/shanaka/Library/Jupyter/kernels/new_env",
>       "spec": {
>         "argv": [
>           "/Users/shanaka/Python/new_env/bin/python3",
>           "-m",
>           "ipykernel_launcher",
>           "-f",
>           "{connection_file}"
>         ],
>         "env": {},
>         "display_name": "new_env",
>         "language": "python",
>         "interrupt_mode": "signal",
>         "metadata": {
>           "debugger": true
>         }
>       }
>     },
>     "python3": {
>       "resource_dir": "/Users/shanaka/Python/new_env/share/jupyter/kernels/python3",
>       "spec": {
>         "argv": [
>           "python",
>           "-m",
>           "ipykernel_launcher",
>           "-f",
>           "{connection_file}"
>         ],
>         "env": {},
>         "display_name": "Python 3 (ipykernel)",
>         "language": "python",
>         "interrupt_mode": "signal",
>         "metadata": {
>           "debugger": true
>         }
>       }
>     }
>   }
> }
> ```

Sc
