### ISSUE TITLE
hydrogen fails to install on Atom

### ISSUE THREAD

**Issue by LeighDudenhoeffer** [nteract/hydrogen#2149]
hydrogen doesn't install on Atom. It tries then freezes and says 'failing' just under the title.
I tried twice. What am I missing?
![image](https://user-images.githubusercontent.com/69485246/161312026-79306918-457f-47b8-8dc8-97ab85bdad1f.png)

**Comment by probabilityhill** [comment]
I am facing the same problem. I checked the error log but I can't find out why.

![スクリーンショット (267)](https://user-images.githubusercontent.com/74280232/164004017-ad70e8ab-eb76-4c06-b95b-fc779668264f.png)

```
npm ERR! code E500
npm ERR! 500 Internal Server Error - GET https://www.atom.io/api/packages/hydrogen/versions/2.16.3/tarball

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nao\.atom\.apm\_logs\2022-04-19T08_48_27_195Z-debug.log
```
<details><summary>error log</summary>

```:2022-04-19T08_48_27_195Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Users\\nao\\AppData\\Local\\atom\\app-1.60.0\\resources\\app\\apm\\bin\\node.exe',
1 verbose cli   'C:\\Users\\nao\\AppData\\Local\\atom\\app-1.60.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   'C:\\Users\\nao\\.atom\\.apm\\.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   'C:\\Users\\nao\\.atom\\.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/hydrogen/versions/2.16.3/tarball',
1 verbose cli   '--target=9.4.4',
1 verbose cli   '--disturl=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v12.14.1
4 verbose npm-session c6cf7519001f53bd
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 500 https://www.atom.io/api/packages/hydrogen/versions/2.16.3/tarball 72874ms attempt #3
8 silly fetchPackageMetaData error for https://www.atom.io/api/packages/hydrogen/versions/2.16.3/tarball 500 Internal Server Error - GET https://www.atom.io/api/packages/hydrogen/versions/2.16.3/tarball
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 72925ms
11 verbose stack Error: 500 Internal Server Error - GET https://www.atom.io/api/packages/hydrogen/versions/2.16.3/tarball
11 verbose stack     at C:\Users\nao\AppData\Local\atom\app-1.60.0\resources\app\apm\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:117:15
11 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:94:5)
12 verbose statusCode 500
13 verbose pkgid https://www.atom.io/api/packages/hydrogen/versions/2.16.3/tarball
14 verbose cwd C:\Users\nao\AppData\Local\Temp\apm-install-dir-2022319-22820-11s649r.phs4
15 verbose Windows_NT 10.0.22000
16 verbose argv "C:\\Users\\nao\\AppData\\Local\\atom\\app-1.60.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\nao\\AppData\\Local\\atom\\app-1.60.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\nao\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\nao\\.atom\\.apmrc" "install" "https://www.atom.io/api/packages/hydrogen/versions/2.16.3/tarball" "--target=9.4.4" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
17 verbose node v12.14.1
18 verbose npm  v6.14.13
19 error code E500
20 error 500 Internal Server Error - GET https://www.atom.io/api/packages/hydrogen/versions/2.16.3/tarball
21 verbose exit [ 1, true ]
```
</details>

**Comment by n-riesco** [comment]
https://github.com/atom/apm/issues/946
