### ISSUE TITLE
npm WARN deprecated uuid@3.4.0

### ISSUE THREAD

**Issue by benoitseron** [nteract/hydrogen#2151]
I'm trying to install Hydrogen but encounter the following

`> @aminya/zeromq@5.2.16 install /tmp/apm-install-dir-202232-11380-pdca51.vct18/node_modules/Hydrogen/node_modules/@aminya/zeromq
> node-gyp-build || npm run build:libzmq

> @aminya/zeromq@5.2.16 build:libzmq
> node-gyp rebuild

npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated json-parser@1.1.5: `json-parser` is deprecated. Please use `comment-json` instead
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
(node:11418) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.16.16-zen1-1-zen
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-202232-11380-pdca51.vct18/node_modules/Hydrogen/node_modules/@aminya/zeromq
gyp ERR! node -v v17.8.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:261:16)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.16.16-zen1-1-zen
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-202232-11380-pdca51.vct18/node_modules/Hydrogen/node_modules/@aminya/zeromq
gyp ERR! node -v v17.8.0
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-202232-11380-pdca51.vct18/package.json'
npm WARN @nteract/outputs@3.0.11 requires a peer of react@^16.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN @nteract/transform-vega@7.0.10 requires a peer of react@^16.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN @nteract/markdown@4.6.2 requires a peer of react@^16.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nteract/markdown@4.6.2 requires a peer of react-dom@^16.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN mobx-react@6.3.1 requires a peer of react@^16.8.0 || 16.9.0-alpha.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-table@6.11.5 requires a peer of react@^16.x.x but none is installed. You must install peer dependencies yourself.
npm WARN react-table@6.11.5 requires a peer of react-dom@^16.x.x but none is installed. You must install peer dependencies yourself.
npm WARN react-markdown@4.3.1 requires a peer of react@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nteract/presentational-components@3.4.12 requires a peer of react@^16.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-json-tree@0.12.1 requires a peer of react@^16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-json-tree@0.12.1 requires a peer of react-dom@^16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN mobx-react-lite@2.2.2 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN apm-install-dir-202232-11380-pdca51.vct18 No description
npm WARN apm-install-dir-202232-11380-pdca51.vct18 No repository field.
npm WARN apm-install-dir-202232-11380-pdca51.vct18 No README data
npm WARN apm-install-dir-202232-11380-pdca51.vct18 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @aminya/zeromq@5.2.16 install: `node-gyp-build || npm run build:libzmq`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @aminya/zeromq@5.2.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/benoitseron/.atom/.apm/_logs/2022-04-02T11_28_18_659Z-debug.log`

however, I ran the command I could find to update uuid but it seems to already be up to date

`npm install uuid@latest

up to date, audited 2 packages in 583ms

found 0 vulnerabilities`

I am using Garuda linux and made the install a few days ago. Any help would be greatly appreciated!

**Comment by EKYS12** [comment]
I encounter the same/similar error. 

`> @aminya/zeromq@5.2.16 install /tmp/apm-install-dir-2022313-7614-88yc1q.tkpoc/node_modules/Hydrogen/node_modules/@aminya/zeromq
> node-gyp-build || npm run build:libzmq


> @aminya/zeromq@5.2.16 build:libzmq
> node-gyp rebuild


npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated json-parser@1.1.5: `json-parser` is deprecated. Please use `comment-json` instead
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
(node:7691) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.15.28-1-MANJARO
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-2022313-7614-88yc1q.tkpoc/node_modules/Hydrogen/node_modules/@aminya/zeromq
gyp ERR! node -v v17.7.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:261:16)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.15.28-1-MANJARO
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-2022313-7614-88yc1q.tkpoc/node_modules/Hydrogen/node_modules/@aminya/zeromq
gyp ERR! node -v v17.7.1
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-2022313-7614-88yc1q.tkpoc/package.json'
npm WARN @nteract/markdown@4.6.2 requires a peer of react@^16.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nteract/markdown@4.6.2 requires a peer of react-dom@^16.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN @nteract/transform-vega@7.0.10 requires a peer of react@^16.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN @nteract/outputs@3.0.11 requires a peer of react@^16.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN mobx-react@6.3.1 requires a peer of react@^16.8.0 || 16.9.0-alpha.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-table@6.11.5 requires a peer of react@^16.x.x but none is installed. You must install peer dependencies yourself.
npm WARN react-table@6.11.5 requires a peer of react-dom@^16.x.x but none is installed. You must install peer dependencies yourself.
npm WARN @nteract/presentational-components@3.4.12 requires a peer of react@^16.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-markdown@4.3.1 requires a peer of react@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-json-tree@0.12.1 requires a peer of react@^16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-json-tree@0.12.1 requires a peer of react-dom@^16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN mobx-react-lite@2.2.2 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN apm-install-dir-2022313-7614-88yc1q.tkpoc No description
npm WARN apm-install-dir-2022313-7614-88yc1q.tkpoc No repository field.
npm WARN apm-install-dir-2022313-7614-88yc1q.tkpoc No README data
npm WARN apm-install-dir-2022313-7614-88yc1q.tkpoc No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @aminya/zeromq@5.2.16 install: `node-gyp-build || npm run build:libzmq`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @aminya/zeromq@5.2.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

I have also installed the latest uuid package with 

`npm i uuid@8.3.2`

to force it to the latest one, which I know to be the case because of this output

`npm list
syasser126@ /home/syasser126
└── uuid@8.3.2`

yet my error still says uuid@3.4.0 and to upgrade to version 7 or higher. 

I am on a Manjaro KDE linux install.

**Comment by EKYS12** [comment]
After further scrolling I see that this issue has also already posted [https://github.com/nteract/hydrogen/issues/2139](here)
