### ISSUE TITLE
Failed to activate the Hydrogen package

### ISSUE THREAD

**Issue by LucerysVelaryon** [nteract/hydrogen#2152]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Hi ! I was never able to run Hydrogen, tried a lot but can't manage to find a solution. Have you got any ideas ? Thank you

### Versions

**Atom**: 1.61.0-beta0 x64
**Electron**: 11.4.12
**OS**: linux 5.15.32-213.current
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.16.3

### Stack Trace

Failed to activate the Hydrogen package

```
At No native build was found for platform=linux arch=x64 runtime=electron abi=85 uv=1 libc=glibc node=12.18.3 electron=11.4.12
    loaded from: /home/pierre/.atom/packages/Hydrogen/node_modules/@aminya/zeromq


Error: No native build was found for platform=linux arch=x64 runtime=electron abi=85 uv=1 libc=glibc node=12.18.3 electron=11.4.12
    loaded from: /home/pierre/.atom/packages/Hydrogen/node_modules/@aminya/zeromq

    at Function.load.path (/packages/Hydrogen/node_modules/node-gyp-build/index.js:60:9)
    at load (/packages/Hydrogen/node_modules/node-gyp-build/index.js:22:30)
    at /packages/Hydrogen/node_modules/@aminya/zeromq/binding.js:1:198)
    at /packages/Hydrogen/node_modules/@aminya/zeromq/binding.js:3:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:149229)
    at /packages/Hydrogen/node_modules/@aminya/zeromq/lib/index.js:6:11)
    at /packages/Hydrogen/node_modules/@aminya/zeromq/lib/index.js:857:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:149229)
    at /packages/Hydrogen/node_modules/@aminya/zeromq/index.js:2:18)
    at /packages/Hydrogen/node_modules/@aminya/zeromq/index.js:3:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:149229)
    at /packages/Hydrogen/node_modules/@aminya/jmp/index.js:37:11)
    at /packages/Hydrogen/node_modules/@aminya/jmp/index.js:451:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:149229)
    at /packages/Hydrogen/dist/zmq-kernel.js:7:15)
    at /packages/Hydrogen/dist/zmq-kernel.js:325:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:149229)
    at /packages/Hydrogen/dist/main.js:34:38)
    at /packages/Hydrogen/dist/main.js:456:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:72:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:756277)
    at requireModule (/usr/share/atom/resources/app/static/<embedded>:14:1205795)
    at Package.requireMainModule (/usr/share/atom/resources/app/static/<embedded>:11:3184054)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:3172053)
    at /usr/share/atom/resources/app/static/<embedded>:14:1879
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1187641)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1189082)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:352326)
    at KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:1228444)
    at KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1224578)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:286682)
```

### Commands

```
     -7:28.2.0 hydrogen:run (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.18 
cell-navigation 0.1.0 
data-explorer 0.7.0 
file-icons 2.1.47 
Hydrogen 2.16.3 
hydrogen-cell-separator 0.4.1 
hydrogen-launcher 1.2.2 
hydrogen-python 0.0.8 
language-babel 2.85.0 
markdown-cell-highlight 1.2.0 
project-manager 3.3.8 
teletype 0.13.4 
```

**Comment by Ermes-28** [comment]
same problem, did u fix it?

**Comment by vandertilt** [comment]
Same issue here, any ideas?
For me the issue appeared after Hydrogen upgrade from 2.15.3 ->2.16.3
Albeit remain after rollback to 2.15.3

**Comment by antonscharton** [comment]
Same here, I managed to fix it once by uninstalling and reinstalling atom again but now the issue is still present

**Comment by sandrofsousa** [comment]
Same here, it happened immediately after updating to atom 1.63.0 so the update definitely broke things.

```
Atom    : 1.63.0
Electron: 11.5.0
Chrome  : 87.0.4280.141
Node    : 12.18.3
macos: 12.6.1 (21G217)
hydrogen: 2.16.3
```

**Comment by mariorossi1989** [comment]
> Same here, it happened immediately after updating to atom 1.63.0 so the update is most likely responsible for breaking things.
> 
> ```
> Atom    : 1.63.0
> Electron: 11.5.0
> Chrome  : 87.0.4280.141
> Node    : 12.18.3
> macos: 12.6.1 (21G217)
> hydrogen: 2.16.3
> ```

Same for me as well.

**Comment by ehsan27770** [comment]
same for me:
> ```
> Atom    : 1.63.0
> Electron: 11.5.0
> Chrome  : 107.0.5304.110
> Node    : 12.18.3
> macos: 13.0.1 
> hydrogen: 2.16.3
> ```

**Comment by Camilonfc** [comment]
same problem, did u fix it?

**Comment by Camilonfc** [comment]
Hello @aminya, any news, how to solve this problem? thanks in advance.

**Comment by danliu09** [comment]
the issue. any solution recommended?

**Comment by haleyk** [comment]
same, having this problem appear between this morning and afternoon.

**Comment by aminya** [comment]
Atom is going to be [sunsetted soon](https://github.blog/2022-06-08-sunsetting-atom/).  It is not possible to publish new packages anymore. If you have your Atom working offline locally, it should continue to work, but the servers are down.

You can directly download the code from here, copy it to `~/.atom/packages/hydrogen` and run `apm install` at the root
https://github.com/nteract/hydrogen/archive/refs/tags/v2.16.4.zip


 As someone who spent several years developing many of the IDE features for Atom, my recommendation is to use an alternative editor that has an active community around it.
VsCode, Jetbrains IDEs like Pycharm, Webstorm, Clion, and Fleet to name a few.
These have huge communities with officially supported plugins. Most of the programming languages and developer tools have official extensions for VSCode and Jetbrains.
See my recommendation about the Hydrogen alternative:
https://github.com/nteract/hydrogen/issues/2155#issuecomment-1151563694

**Comment by vandertilt** [comment]
Thanks alot @aminya!
Atom + Hydrogen is an uncontested winner for anyone wrangling data!
Guess I'll have to make do with moonshine for now.. 
Cheers!

**Comment by camall3n** [comment]
@aminya What does "run `apm install` at the root" mean? Which root?

**Comment by aminya** [comment]
At `~/.atom/packages/hydrogen`

**Comment by rubick1896** [comment]
@aminya Can you give instructions on how to install the new package on Windows?

**Comment by aminya** [comment]
The same instructions for all platforms

**Comment by ekkal** [comment]
> @aminya What does "run `apm install` at the root" mean? Which root?

Were any of your able to install Hydrogen patch successfully?
Agree to @vandertilt that Atom shines and especially so for someone working with data.

**Comment by ekkal** [comment]
> > @aminya What does "run `apm install` at the root" mean? Which root?
> 
> Were any of your able to install Hydrogen patch successfully? Agree to @vandertilt that Atom shines and especially so for someone working with data.

It indeed worked once the zip is extracted and after issuing the command `apm install` .  Thanks @aminya .

I'm looking forward to using VSCode provided they have light table implementation for data viewing:
https://nteract.gitbooks.io/hydrogen/content/
