### ISSUE TITLE
Uncaught Error: Cannot find module 'lodash/debounce'Require stack:- $ATOM_HOME/packages\Hydroge...

### ISSUE THREAD

**Issue by UwUEgoDeathUwU** [nteract/hydrogen#2156]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

### Versions

**Atom**: 1.60.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.16.3

### Stack Trace

Uncaught Error: Cannot find module 'lodash/debounce'
Require stack:
- C:\Users\cedri\.atom\packages\Hydrogen\dist\main.js
- C:\Users\cedri\AppData\Local\atom\app-1.60.0\resources\app.asar\static\index.html

```
At internal/modules/cjs/loader.js:800

Error: Cannot find module 'lodash/debounce'
Require stack:
- C:\Users\cedri\.atom\packages\Hydrogen\dist\main.js
- C:\Users\cedri\AppData\Local\atom\app-1.60.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (<embedded>:11:157942)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (<embedded>:11:149229)
    at /packages/Hydrogen/dist/main.js:27:36)
    at /packages/Hydrogen/dist/main.js:456:3)
    at Module.get_Module._compile (<embedded>:11:149913)
    at Object.value [as .js] (<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (<embedded>:1:802772)
    at requireModule (<embedded>:14:1175135)
    at Package.requireMainModule (<embedded>:11:3543231)
    at Package.activateConfig (<embedded>:11:3532534)
    at PackageManager.packageHasSettings (<embedded>:11:909286)
    at PackageCard.hasSettings (<embedded>:14:2709249)
    at PackageCard.updateSettingsState (<embedded>:14:2699517)
    at PackageCard.updateInterfaceState (<embedded>:14:2699340)
    at <embedded>:14:2707482
    at <embedded>:14:2709500
    at Function.simpleDispatch (<embedded>:11:1187666)
    at Emitter.emit (<embedded>:11:1189107)
    at PackageManager.emitPackageEvent (<embedded>:11:918743)
    at <embedded>:11:915875
    at r (<embedded>:11:910405)
    at n (<embedded>:14:1174458)
    at ChildProcess.<anonymous> (<embedded>:14:1174664)
    at ChildProcess.emit (events.js:223:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

```

### Commands

```
     -7:11.8.0 core:move-left (input.hidden-input)
  3x -5:50.5.0 core:backspace (input.hidden-input)
     -5:44.4.0 core:select-all (input.hidden-input)
 11x -5:43.8.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-ternjs 0.20.0 
Hydrogen 2.16.3 
hydrogen-python 0.0.8 
hyperclick 0.1.5 
```

**Comment by rchaklashiya** [comment]
I have the exact same issue, and am also not sure how to resolve it. This is my stack trace:

```
Cannot find module 'lodash/debounce'
Require stack:
- C:\Users\rajkc_n1emmcn\.pulsar\packages\hydrogen-2.16.5\dist\main.js
- C:\Users\rajkc_n1emmcn\AppData\Local\Programs\pulsar\resources\app.asar\src\module-utils.js
- C:\Users\rajkc_n1emmcn\AppData\Local\Programs\pulsar\resources\app.asar\src\package.js
- C:\Users\rajkc_n1emmcn\AppData\Local\Programs\pulsar\resources\app.asar\src\package-manager.js
- C:\Users\rajkc_n1emmcn\AppData\Local\Programs\pulsar\resources\app.asar\src\atom-environment.js
- C:\Users\rajkc_n1emmcn\AppData\Local\Programs\pulsar\resources\app.asar\src\initialize-application-window.js
- C:\Users\rajkc_n1emmcn\AppData\Local\Programs\pulsar\resources\app.asar\static\index.html
[Hide Stack Trace](https://github.com/nteract/hydrogen/issues/2156#)
Error: Cannot find module 'lodash/debounce'
Require stack:
- C:\Users\rajkc_n1emmcn\.pulsar\packages\hydrogen-2.16.5\dist\main.js
- C:\Users\rajkc_n1emmcn\AppData\Local\Programs\pulsar\resources\app.asar\src\module-utils.js
- C:\Users\rajkc_n1emmcn\AppData\Local\Programs\pulsar\resources\app.asar\src\package.js
- C:\Users\rajkc_n1emmcn\AppData\Local\Programs\pulsar\resources\app.asar\src\package-manager.js
- C:\Users\rajkc_n1emmcn\AppData\Local\Programs\pulsar\resources\app.asar\src\atom-environment.js
- C:\Users\rajkc_n1emmcn\AppData\Local\Programs\pulsar\resources\app.asar\src\initialize-application-window.js
- C:\Users\rajkc_n1emmcn\AppData\Local\Programs\pulsar\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at o._resolveFilename (electron/js2c/renderer_init.js:33:1118)
    at Function.Module._resolveFilename (C:\Users\rajkc_n1emmcn\AppData\Local\Programs\pulsar\resources\app.asar\src\module-cache.js:317:28)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (C:\Users\rajkc_n1emmcn\AppData\Local\Programs\pulsar\resources\app.asar\src\native-compile-cache.js:67:27)
    at Object.<anonymous> (C:\Users\rajkc_n1emmcn\.pulsar\packages\hydrogen-2.16.5\dist\main.js:31:36)
    at Object.<anonymous> (C:\Users\rajkc_n1emmcn\.pulsar\packages\hydrogen-2.16.5\dist\main.js:460:3)
    at Module._compile (C:\Users\rajkc_n1emmcn\AppData\Local\Programs\pulsar\resources\app.asar\src\native-compile-cache.js:120:30)
    at Object.value [as .js] (C:\Users\rajkc_n1emmcn\AppData\Local\Programs\pulsar\resources\app.asar\src\compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (C:\Users\rajkc_n1emmcn\AppData\Local\Programs\pulsar\resources\app.asar\src\native-compile-cache.js:67:27)
    at requireModule (C:\Users\rajkc_n1emmcn\AppData\Local\Programs\pulsar\resources\app.asar\src\module-utils.js:3:17)
    at Package.requireMainModule (C:\Users\rajkc_n1emmcn\AppData\Local\Programs\pulsar\resources\app.asar\src\package.js:909:27)
    at Package.activateNow (C:\Users\rajkc_n1emmcn\AppData\Local\Programs\pulsar\resources\app.asar\src\package.js:232:34)
    at C:\Users\rajkc_n1emmcn\AppData\Local\Programs\pulsar\resources\app.asar\src\package.js:1046:24
    at Function.simpleDispatch (C:\Users\rajkc_n1emmcn\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\event-kit\dist\emitter.js:64:14)
    at Emitter.emit (C:\Users\rajkc_n1emmcn\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\event-kit\dist\emitter.js:257:28)
    at CommandRegistry.handleCommandEvent (C:\Users\rajkc_n1emmcn\AppData\Local\Programs\pulsar\resources\app.asar\src\command-registry.js:379:18)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\rajkc_n1emmcn\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:617:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\rajkc_n1emmcn\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:408:22)
    at WindowEventHandler.handleDocumentKeyEvent (C:\Users\rajkc_n1emmcn\AppData\Local\Programs\pulsar\resources\app.asar\src\window-event-handler.js:153:34)
```

**Comment by rchaklashiya** [comment]
*actually now I'm thinking it might be possible to fix with the Lodash module snippets package, there is a specific snippet that can implement the missing lodash/debounce. I'm currently trying to figure out how/where to put that snippet to get it to work though, that's where I'm currently stuck.

**Comment by alesarac** [comment]
please, has anyone managed to solve it?
