### ISSUE TITLE
Uncaught error: no native build was found for platforms

### ISSUE THREAD

**Issue by Alice-Renee** [nteract/hydrogen#2157]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

### Versions

**Atom**: 1.63.0-nightly1 x64
**Electron**: 11.5.0
**OS**: macOS 12.5.1
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.16.3

### Stack Trace

Uncaught Error: No native build was found for platform=darwin arch=x64 runtime=electron abi=85 uv=1 libc=glibc node=12.18.3 electron=11.5.0
    loaded from: /Users/alice/.atom/packages/Hydrogen/node_modules/@aminya/zeromq

```
At /Users/alice/.atom/packages/Hydrogen/node_modules/node-gyp-build/index.js:60

Error: No native build was found for platform=darwin arch=x64 runtime=electron abi=85 uv=1 libc=glibc node=12.18.3 electron=11.5.0
    loaded from: /Users/alice/.atom/packages/Hydrogen/node_modules/@aminya/zeromq

    at Function.load.path (/packages/Hydrogen/node_modules/node-gyp-build/index.js:60:9)
    at load (/packages/Hydrogen/node_modules/node-gyp-build/index.js:22:30)
    at /packages/Hydrogen/node_modules/@aminya/zeromq/binding.js:1:198)
    at /packages/Hydrogen/node_modules/@aminya/zeromq/binding.js:3:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:120:30)
    at /app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at /packages/Hydrogen/node_modules/@aminya/zeromq/lib/index.js:6:11)
    at /packages/Hydrogen/node_modules/@aminya/zeromq/lib/index.js:857:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:120:30)
    at /app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at /packages/Hydrogen/node_modules/@aminya/zeromq/index.js: 2:18)
    at /packages/Hydrogen/node_modules/@aminya/zeromq/index.js:3:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:120:30)
    at /app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at /packages/Hydrogen/node_modules/@aminya/jmp/index.js:37:11)
    at /packages/Hydrogen/node_modules/@aminya/jmp/index.js:451:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:120:30)
    at /app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at /packages/Hydrogen/dist/zmq-kernel.js:7:15)
    at /packages/Hydrogen/dist/zmq-kernel.js:325:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:120:30)
    at /app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at /packages/Hydrogen/dist/main.js:34:38)
    at /packages/Hydrogen/dist/main.js:456:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:120:30)
    at /app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at requireModule (/app.asar/src/module-utils.js:3:17)
    at Package.requireMainModule (/app.asar/src/package.js:909:27)
    at Package.activateConfig (/app.asar/src/package.js:292:10)
    at PackageManager.module.exports.PackageManager.packageHasSettings (/app.asar/node_modules/settings-view/lib/package-manager.js:54:14)
    at PackageCard.hasSettings (/app.asar/node_modules/settings-view/lib/package-card.js:800:34)
    at PackageCard.updateSettingsState (/app.asar/node_modules/settings-view/lib/package-card.js:446:16)
    at PackageCard.updateInterfaceState (/app.asar/node_modules/settings-view/lib/package-card.js:438:12)
    at /app.asar/node_modules/settings-view/lib/package-card.js:734:16
    at /app.asar/node_modules/settings-view/lib/package-card.js:817:11
    at Function.simpleDispatch (/app.asar/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/app.asar/node_modules/event-kit/dist/emitter.js:257:28)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (/app.asar/node_modules/settings-view/lib/package-manager.js:662:27)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:484:26
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:114:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:280:9)
    at /app.asar/src/buffered-process.js:301:9
    at /app.asar/src/buffered-process.js:169:7)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:674:12)

```

### Commands

```
     -2:20.9.0 application:open-your-stylesheet (atom-workspace.workspace.scrollbars-visible-when-scrolling.teletype-Authenticated.theme-base16-tomorrow-light-theme.theme-one-light-ui)
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
Hydrogen 2.16.3 
my-package 0.0.0 
teletype 0.13.4 
```

**Comment by Alice-Renee** [comment]
![Screen Shot 2022-09-07 at 4 07 44 AM](https://user-images.githubusercontent.com/101138886/188838991-a6d9dca2-53f4-4b7b-b2f4-bec20166f3f9.png)

**Comment by Ermes-28** [comment]
same problem, did u fix it?

**Comment by Camilonfc** [comment]
same problem, did u fix it?

**Comment by aminya** [comment]
Duplicate of #2152
