### ISSUE TITLE
Uncaught Error: No native build was found for platform=darwin arch=x64 runtime=electron abi=85 uv...

### ISSUE THREAD

**Issue by chimidata** [nteract/hydrogen#2160]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

### Versions

**Atom**: 1.63.0 x64
**Electron**: 11.5.0
**OS**: macOS 12.6.1
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.16.3

### Stack Trace

Uncaught Error: No native build was found for platform=darwin arch=x64 runtime=electron abi=85 uv=1 libc=glibc node=12.18.3 electron=11.5.0
    loaded from: /Users/tadamichi/.atom/packages/Hydrogen/node_modules/@aminya/zeromq

```
At /Users/tadamichi/.atom/packages/Hydrogen/node_modules/node-gyp-build/index.js:60

Error: No native build was found for platform=darwin arch=x64 runtime=electron abi=85 uv=1 libc=glibc node=12.18.3 electron=11.5.0
    loaded from: /Users/tadamichi/.atom/packages/Hydrogen/node_modules/@aminya/zeromq

    at Function.load.path (/packages/Hydrogen/node_modules/node-gyp-build/index.js:60:9)
    at load (/packages/Hydrogen/node_modules/node-gyp-build/index.js:22:30)
    at /packages/Hydrogen/node_modules/@aminya/zeromq/binding.js:1:198)
    at /packages/Hydrogen/node_modules/@aminya/zeromq/binding.js:3:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:120:30)
    at /app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at /packages/Hydrogen/node_modules/@aminya/zeromq/lib/index.js:6:11)
    at /packages/Hydrogen/node_modules/@aminya/zeromq/lib/index.js:857:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:120:30)
    at /app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at /packages/Hydrogen/node_modules/@aminya/zeromq/index.js:2:18)
    at /packages/Hydrogen/node_modules/@aminya/zeromq/index.js:3:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:120:30)
    at /app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at /packages/Hydrogen/node_modules/@aminya/jmp/index.js:37:11)
```

### Commands

```
```

### Non-Core Packages

```
Hydrogen 2.16.3 
```

**Comment by Camilonfc** [comment]
same problem, did u fix it?
