### ISSUE TITLE
Install failed: python2.7: command not found

### ISSUE THREAD

**Issue by gnilrets** [nteract/hydrogen#263]
I'm on a Mac (El Capitan) and I installed pkg-config, zeromq, and ipython as instructed.  I do have Python 2.7 installed (via pyenv), but when I try to install the package I get the following error:

````
➜  ~ PYTHON=python2.7 apm install hydrogen
Installing hydrogen to /Users/gnilrets/.atom/packages ✗

> zmq@2.14.0 install /private/var/folders/lv/hm7tw5rj60g3j58yjwfdshjw0000gn/T/apm-install-dir-116318-68902-1b7hji8/node_modules/Hydrogen/node_modules/jmp/node_modules/zmq
> node-gyp rebuild


gyp ERR! configure error 
gyp ERR! stack Error: Command failed: pyenv: python2.7: command not found
gyp ERR! stack 
gyp ERR! stack The `python2.7' command exists in these Python versions:
gyp ERR! stack   2.7.10
gyp ERR! stack 
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:658:15)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at maybeClose (child_process.js:766:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:979:11)
gyp ERR! stack     at Socket.emit (events.js:95:17)
gyp ERR! stack     at Pipe.close (net.js:466:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/lv/hm7tw5rj60g3j58yjwfdshjw0000gn/T/apm-install-dir-116318-68902-1b7hji8/node_modules/Hydrogen/node_modules/jmp/node_modules/zmq
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 15.4.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/gnilrets/.atom/.apm/.apmrc" "--userconfig" "/Users/gnilrets/.atom/.apmrc" "install" "/private/var/folders/lv/hm7tw5rj60g3j58yjwfdshjw0000gn/T/d-116318-68902-61yzzl/package.tgz" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.14.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmq@2.14.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/lv/hm7tw5rj60g3j58yjwfdshjw0000gn/T/apm-install-dir-116318-68902-1b7hji8/npm-debug.log


````

**Comment by mangecoeur** [comment]
I think when you use pyenv the python version won't be on your PATH, so you might have to either update your PATH before running and change it back after, or see if you can specify the location of the python binary.

Personally, every time Hydrogen updates I have to edit my PATH first (I use Anaconda Python 3). It's pretty annoying.

It would be nice to nuke the GYP dependence somehow - I have lost hope in them fixing Python3 support before the heat death of the universe at this point (there is an issue open since 2009! 7 years and counting!). It seems it's all down to needing to build the ZMQ bindings.

**Comment by lgeiger** [comment]
Take a look at #305

**Comment by n-riesco** [comment]
We've added [TROUBLESHOOTING.md](https://github.com/nteract/hydrogen/blob/v0.12.0/TROUBLESHOOTING.md) document.
