### ISSUE TITLE
can't install, mac os x, anaconda4, python3

### ISSUE THREAD

**Issue by mmngreco** [nteract/hydrogen#301]
Hi all,

My device:

- Anaconda 4
- Mac OS X captain
- Python 3.5

I get this error log:

```bash
mmngreco:~ mmngreco$ apm install hydrogen
Installing hydrogen to /Users/mmngreco/.atom/packages ✗

> zmq@2.15.3 install /private/var/folders/cx/7r49499n39z2fw1fq707kym80000gn/T/apm-install-dir-116521-22461-s4jn8s/node_modules/Hydrogen/node_modules/jmp/node_modules/zmq
> node-gyp rebuild


gyp ERR! configure error
gyp ERR! stack Error: Python executable "python" is v3.5.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:119:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:656:7)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at maybeClose (child_process.js:766:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:979:11)
gyp ERR! stack     at Socket.emit (events.js:95:17)
gyp ERR! stack     at Pipe.close (net.js:466:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/cx/7r49499n39z2fw1fq707kym80000gn/T/apm-install-dir-116521-22461-s4jn8s/node_modules/Hydrogen/node_modules/jmp/node_modules/zmq
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Darwin 15.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/mmngreco/.atom/.apm/.apmrc" "--userconfig" "/Users/mmngreco/.atom/.apmrc" "install" "/private/var/folders/cx/7r49499n39z2fw1fq707kym80000gn/T/d-116521-22461-btpopa/package.tgz" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.15.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zmq@2.15.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/cx/7r49499n39z2fw1fq707kym80000gn/T/apm-install-dir-116521-22461-s4jn8s/npm-debug.log

mmngreco:~ mmngreco$ npm -v
3.9.5
mmngreco:~ mmngreco$ apm -v
apm  1.9.2
npm  2.13.3
node 0.10.40
python 3.5.1
git 2.7.4
```

**Comment by n-riesco** [comment]
Node.js requires Python 2 to install native modules (see Hydrogen's requirements [here](https://github.com/nteract/hydrogen/blob/master/README.md#homebrew-on-os-x)). Note that Python2 and Python3 can coexist.

**Comment by lgeiger** [comment]
Mac OS X has Python 2 preinstalled.
Running `PYTHON=python2 apm install hydrogen` should work for you.

**Comment by mmngreco** [comment]
@n-riesco Thanks, so should install py2 with brew or anaconda?

---

@lgeiger Thanks, I forget this... but that not solve the problem, here de trace:

```bash
mmngreco:~ mmngreco$ PYTHON=python2 apm install hydrogen
Installing hydrogen to /Users/mmngreco/.atom/packages ✗

> zmq@2.15.3 install /private/var/folders/cx/7r49499n39z2fw1fq707kym80000gn/T/apm-install-dir-116521-22675-1531zg2/node_modules/Hydrogen/node_modules/jmp/node_modules/zmq
> node-gyp rebuild


gyp ERR! configure error
gyp ERR! stack Error: Python executable "python" is v3.5.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:119:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:656:7)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at maybeClose (child_process.js:766:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:979:11)
gyp ERR! stack     at Socket.emit (events.js:95:17)
gyp ERR! stack     at Pipe.close (net.js:466:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/cx/7r49499n39z2fw1fq707kym80000gn/T/apm-install-dir-116521-22675-1531zg2/node_modules/Hydrogen/node_modules/jmp/node_modules/zmq
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Darwin 15.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/mmngreco/.atom/.apm/.apmrc" "--userconfig" "/Users/mmngreco/.atom/.apmrc" "install" "/private/var/folders/cx/7r49499n39z2fw1fq707kym80000gn/T/d-116521-22675-13xowfc/package.tgz" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.15.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zmq@2.15.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/cx/7r49499n39z2fw1fq707kym80000gn/T/apm-install-dir-116521-22675-1531zg2/npm-debug.log

mmngreco:~ mmngreco$
```

**Comment by lgeiger** [comment]
You could also try `PYTHON=/usr/bin/python apm install hydrogen`. This will use the system python for building.

**Comment by n-riesco** [comment]
@mmngreco This would work in linux: `apm config set python $(which python2)`

**Comment by mmngreco** [comment]
@lgeiger Yey, It's works, Many thanks!

**Comment by lgeiger** [comment]
Great! 🎉 
Now you can run `apm config set python /usr/bin/python` to set this as the default for `apm`.  And in the future just use `apm install hydrogen`.

**Comment by mmngreco** [comment]
Cool, nice tip. Thanks again. 

bests!

**Comment by lgeiger** [comment]
I still don't understand why `PYTHON=python2 apm install hydrogen` didn't work with anaconda.

@mmngreco can you run `which python2` and post the output?

**Comment by mmngreco** [comment]
of course, here is:

```bash
mmngreco:Documents mmngreco$ which python2
```
There no output

With run `which python`:
```bash
mmngreco:Documents mmngreco$ which python
/Users/mmngreco/anaconda3/bin/python
```

**Comment by lgeiger** [comment]
Thanks! I see, the `python2` variable isn't set by default. Can you try if  `which python2.7` returns something?

**Comment by mmngreco** [comment]
yes, now get this output:

```bash
mmngreco:anaconda3 mmngreco$ which python2.7
/usr/bin/python2.7
```

**Comment by lgeiger** [comment]
Awesome! I just wanted to know if we need to update the readme for anaconda and mac os x.
