### ISSUE TITLE
Uncaught TypeError: matches.map is not a function

### ISSUE THREAD

**Issue by yahiaetman** [nteract/hydrogen#434]
I am trying to use Atom with Hydrogen to write lua code using iTorch.

```lua
local torch = require "torch"
local nn = require "nn"

local mlp = nn.Sequential()
```
The steps are:

1. After writing the first 2 lines of code, I do "Hydrogen: Run All".
2. While writing "mlp" in the last line, the following error appears in a red popup.

The error also occurs whenever I try to use "mlp" or any other name that is not recognized by the autocomplete.

Even if I run the last line, autocomplete still doesn't recognize "mlp". the same happens with any other variable or function that autocomplete doesn't recognize.

I used [this gist](https://gist.github.com/szagoruyko/45472e83421eb42bce64) as a guide to install the needed packages (except vim-mode) plus nuclide on a fresh install of Atom.

**Atom Version**: 1.10.0
**Electron Version**: 0.37.8
**System**: Ubuntu 14.04.5
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package, v0.13.0

### Stack Trace

Uncaught TypeError: matches.map is not a function

```
At events.js:154

TypeError: matches.map is not a function
    at /home/yahia/.atom/packages/Hydrogen/lib/autocomplete-provider.coffee:58:39
    at ZMQKernel.module.exports.ZMQKernel.onShellMessage (/home/yahia/.atom/packages/Hydrogen/lib/zmq-kernel.coffee:229:17)
    at Socket.<anonymous> (/home/yahia/.atom/packages/Hydrogen/node_modules/jmp/index.js:334:17)
    at emitMany (events.js:121:13)
    at Socket.emit (events.js:195:7)
    at Socket._flushRead (/home/yahia/.atom/packages/Hydrogen/node_modules/zmq/lib/index.js:638:15)
    at Socket._flushReads (/home/yahia/.atom/packages/Hydrogen/node_modules/zmq/lib/index.js:676:23)
    at _zmq.onReadReady (/home/yahia/.atom/packages/Hydrogen/node_modules/zmq/lib/index.js:297:10)
```

### Commands

```
     -1:04.6.0 nuclide-home:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:45.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:40.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:30.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:28.6.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:28 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:23.6.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:07.6.0 hydrogen:run-all (atom-text-editor.editor.is-focused)
     -0:03.9.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2 (active)
Hydrogen, v0.13.0 (active)
language-ipynb, v1.3.0 (active)
language-lua, v0.9.11 (active)
nuclide, v0.166.0 (active)
script, v3.9.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.241.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (inactive)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by lgeiger** [comment]
Could you try to run Hydrogen again and then open the dev console (`shift-ctrl-i`) and post a screenshot of the errors reported?

**Comment by yahiaetman** [comment]
![scr](https://cloud.githubusercontent.com/assets/6162181/18233004/70120f1e-72dc-11e6-8557-c139c8c0c802.png)

**Comment by lgeiger** [comment]
Thanks! Could you expand the two `shell messages` before the errors and post an other screenshot?

**Comment by yahiaetman** [comment]
first:
![shellmsg1](https://cloud.githubusercontent.com/assets/6162181/18233097/5d75d82a-72de-11e6-83ac-91be26d4180d.png)
second:
![shellmsg2](https://cloud.githubusercontent.com/assets/6162181/18233099/65d18762-72de-11e6-89cb-c799c048bfa3.png)

**Comment by lgeiger** [comment]
Oh I see. iTorch doesn't comply fully with the [jupyter messaging protocol] (https://jupyter-client.readthedocs.io/en/latest/messaging.html#completion). `matches` should be an array but in your case iTorch returns a Object.
I think we can fix this in Hydrogen by using `_.map` instead of the default one.

Could you post one more screenshot from the expanded matches object?

**Comment by yahiaetman** [comment]
![matches1](https://cloud.githubusercontent.com/assets/6162181/18233276/d9d8f0f6-72e2-11e6-8226-3a21b681cb9d.png)

**Comment by lgeiger** [comment]
Oh that Object is empty (except `__proto__`). That isn't really helpful then.
But I'm confident using `_.map` will fix your problem.

I may also open an issue on iTorch regarding this.

**Comment by rgbkrk** [comment]
Interesting, what's the structure they're using for matches?

**Comment by rgbkrk** [comment]
One thing I can tell from there is that it looks like `matched_text` part is pre-5.0.

**Comment by lgeiger** [comment]
@rgbkrk As far as I can tell it's an [object with the matches](https://github.com/facebook/iTorch/blob/master/completer.lua#L138)

**Comment by yahiaetman** [comment]
Thank you. I tried `_.map` fix and it stopped the error popup. Then, I removed iTorch and cloned the newest version. matches is now an array filled with suggestions. The autocomplete suggestions list is now similar to the one appearing directly in iTorch. 
![fixed](https://cloud.githubusercontent.com/assets/6162181/18233618/8749a95c-72ec-11e6-8cfa-b2bbee0972ea.png)
