### ISSUE TITLE
node-gyp issue resurfacing when attempting to upgrade to 0.14.0

### ISSUE THREAD

**Issue by respatialized** [nteract/hydrogen#439]
I'm up and running with Hydrogen on Windows 10, after following the correct build instructions, but a familiar problem is resurfacing when I try to upgrade. The same error occurs either via the in-app package manager or when trying to use apm to upgrade via command line. Here's the error log:

```
> zmq@2.15.3 install C:\~User\AppData\Local\Temp\apm-install-dir-11689-5632-h1yopw\node_modules\Hydrogen\node_modules\zmq
> node-gyp rebuild


C:\~User\AppData\Local\Temp\apm-install-dir-11689-5632-h1yopw\node_modules\Hydrogen\node_modules\zmq>if not defined npm_config_node_gyp (node "C:\~User\AppData\Local\atom\app-1.10.2\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\~User\AppData\Local\atom\app-1.10.2\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...". [C:\~User\AppData\Local\Temp\apm-install-dir-11689-5632-h1yopw\node_modules\Hydrogen\node_modules\zmq\build\zmq.vcxproj]
C:\~User\AppData\Local\Temp\apm-install-dir-11689-5632-h1yopw
`-- (empty)


gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\~User\AppData\Local\atom\app-1.10.2\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\~User\\AppData\\Local\\atom\\app-1.10.2\\resources\\app\\apm\\bin\\node.exe" "C:\\~User\\AppData\\Local\\atom\\app-1.10.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\~User\AppData\Local\Temp\apm-install-dir-11689-5632-h1yopw\node_modules\Hydrogen\node_modules\zmq
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\~User\AppData\Local\Temp\apm-install-dir-11689-5632-h1yopw\package.json'
npm WARN apm-install-dir-11689-5632-h1yopw No description
npm WARN apm-install-dir-11689-5632-h1yopw No repository field.
npm WARN apm-install-dir-11689-5632-h1yopw No README data
npm WARN apm-install-dir-11689-5632-h1yopw No license field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\~User\\AppData\\Local\\atom\\app-1.10.2\\resources\\app\\apm\\bin\\node.exe" "C:\\~User\\AppData\\Local\\atom\\app-1.10.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\~User\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\~User\\.atom\\.apmrc" "install" "C:\\~User\\AppData\\Local\\Temp\\d-11689-5632-12235mi\\package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=ia32" "--global-style" "--msvs_version=2015"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.15.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmq@2.15.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zmq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\~User\AppData\Local\Temp\apm-install-dir-11689-5632-h1yopw\npm-debug.log
npm ERR! code 1
```

Apologies for duplicating a previously closed issue, but I wasn't sure where else to raise this.

**Comment by lgeiger** [comment]
> Apologies for duplicating a previously closed issue, but I wasn't sure where else to raise this.

You found the right place 👍 😄 
Sorry about the messy installation on windows. We're getting very close to be able to provide precompiled binaries for zeromq to end the installation horror.

It looks like it doesn't find your compiler. We require [Visual Studio 2013 ](https://www.microsoft.com/en-US/download/details.aspx?id=44914) for zeromq to build correctly. The 2015 edition won't work because there are some tools required for zeromq to build correctly which are not included.

There have been a quite some similar issues with windows using the wrong compiler if both versions of Visual Studio are installed. Have a look [at them](https://www.google.de/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=error+MSB8020%3A+The+build+tools+for+v140+(Platform+Toolset+%3D+'v140')+cannot+be+found.+To+build+using+the+v140+build+tools%2C+please+install+v140+build+tools.+Alternatively%2C+you+may+upgrade+to+the+current+Visual+Studio+tools+by+selecting+the+Project+menu+or+right-click+the+solution%2C+and+then+selecting+%22Upgrade+Solution...%22.).

Also you could try `apm rebuild hydrogen` in the command line.

**Comment by lgeiger** [comment]
After looking more into the windows installation process I realized you can compile with visual studio 2015 as well. For this to work, you need to make sure to have visual studio with the `C++` compilers installed. They are not included in the default installation anymore.

**Comment by respatialized** [comment]
It's not clear to me that this is the underlying issue, as I still have the installation of Visual Studio 2013 with the c++ compilers from when I first got Hydrogen installed successfully. I could try to reinstall Visual Studio and attempt the update again, just to make sure.

**Comment by lgeiger** [comment]
@respatialized It could be that `node-gyp` tries to use the wrong compilers. We recently updated our [troubleshooting guide](https://github.com/nteract/hydrogen/blob/master/TROUBLESHOOTING.md) for this issue.

Could you run `apm --version` and post the output?

**Comment by respatialized** [comment]
Looks like you might be right.

```
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.9.2.windows.1
visual studio 2015
```

**Comment by lgeiger** [comment]
Please run `set GYP_MSVS_VERSION=2013` and try `apm install hydrogen` again.

**Comment by lgeiger** [comment]
Awesome! That's great 🎉

**Comment by sheperdsonbrown** [comment]
I left a comment in a different thread earlier, but I believe this thread addresses the issue I am having. Here is the error and I have tried the above fixes. I am using git bash on windows 10. 

 Cannot find module 'C:\Users\Alex Brown\AppData\Local\atom\app-1.10.2\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\ALEXBR~1\AppData\Local\Temp\apm-install-dir-116826-10300-k1gj55\package.json'
npm WARN apm-install-dir-116826-10300-k1gj55 No description
npm WARN apm-install-dir-116826-10300-k1gj55 No repository field.
npm WARN apm-install-dir-116826-10300-k1gj55 No README data
npm WARN apm-install-dir-116826-10300-k1gj55 No license field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Users\\Alex Brown\\AppData\\Local\\atom\\app-1.10.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Alex Brown\\AppData\\Local\\atom\\app-1.10.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Alex Brown\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Alex Brown\\.atom\\.apmrc" "install" "C:\\Users\\ALEXBR~1\\AppData\\Local\\Temp\\d-116826-10300-1e8gk2s\\package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=ia32" "--global-style" "--msvs_version=2015"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.15.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zmq@2.15.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zmq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ALEXBR~1\AppData\Local\Temp\apm-install-dir-116826-10300-k1gj55\npm-debug.log
npm ERR! code 1

Let me know what I need to do from here. 

Thanks,

**Comment by lgeiger** [comment]
@sheperdsonbrown Have you tried running 
```
apm config set msvs_version 2013 -g
set GYP_MSVS_VERSION=2013
```
as described in our [troubleshooting guide](https://github.com/nteract/hydrogen/blob/master/TROUBLESHOOTING.md)?

**Comment by sheperdsonbrown** [comment]
Yes,

I just tried that in git bash and the same error is still being produced.

**Comment by lgeiger** [comment]
I think git bash is a linux terminal emulator so maybe you have the use `export GYP_MSVS_VERSION=2013` instead of `set GYP_MSVS_VERSION=2013`.

Could try it with the default windows command line if the above didn't work?

**Comment by sheperdsonbrown** [comment]
Thank you for responding quickly and providing helpful tips, but the
download is still not working.

I will try to do a fresh install on everything and get back to you with any
issues
