### ISSUE TITLE
Remote Kernel issue

### ISSUE THREAD

**Issue by josh-gree** [nteract/hydrogen#483]
Hi,

Whilst trying to start a remote kernel I am getting an error thrown from either marked or possibly from notifications. The following is the stack trace and other info;

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.3
**Thrown From**: [notifications](https://github.com/atom/notifications) package, v0.65.1

### Stack Trace

Uncaught TypeError: src.replace is not a function
Please report this to https://github.com/chjj/marked.

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/marked/lib/marked.js:1227

TypeError: src.replace is not a function
Please report this to https://github.com/chjj/marked.
    at Lexer.lex (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/marked/lib/marked.js:138:6)
    at Function.Lexer.lex (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/marked/lib/marked.js:129:16)
    at marked (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/marked/lib/marked.js:1219:31)
    at atom-notification.NotificationElement.render (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:113:33)
    at atom-notification.NotificationElement.initialize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:50:33)
    at Object.createView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/main.js:89:42)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:119:78)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:86:21)
    at Object.Notifications.addNotificationView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/main.js:126:58)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/main.js:27:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at NotificationManager.module.exports.NotificationManager.addNotification (/Applications/Atom.app/Contents/Resources/app.asar/src/notification-manager.js:54:20)
    at NotificationManager.module.exports.NotificationManager.addError (/Applications/Atom.app/Contents/Resources/app.asar/src/notification-manager.js:41:19)
    at Object.module.exports.Config.getJson (/Users/joshua/.atom/packages/Hydrogen/lib/config.coffee:10:32)
    at WSKernelPicker.module.exports.WSKernelPicker.toggle (/Users/joshua/.atom/packages/Hydrogen/lib/ws-kernel-picker.coffee:46:27)
    at Object.module.exports.Hydrogen.showWSKernelPicker (/Users/joshua/.atom/packages/Hydrogen/lib/main.coffee:393:25)
    at atom-text-editor.subscriptions.add.atom.commands.add.hydrogen:connect-to-remote-kernel (/Users/joshua/.atom/packages/Hydrogen/lib/main.coffee:62:54)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:114:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:18.2.0 application:open (atom-pane.pane.active)
     -0:04.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:00.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.1.0 hydrogen:connect-to-remote-kernel (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "markdown-preview"
    ],
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
Hydrogen, v0.15.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by nikitakit** [comment]
Your `gateways` config has some sort of error in it, e.g. invalid syntax. Double-checking the JSON should make things work for you.

In the meantime, I'm working on a fix that will provide better error messages in this situation.

**Comment by josh-gree** [comment]
Thanks! Was missing a bracket, all working now. The error is very misleading...
