### ISSUE TITLE
Installation Error (python 2.7)

### ISSUE THREAD

**Issue by Kiminaka** [nteract/hydrogen#484]
Hi,

I am having trouble installing hydrogen on Atom. 
I got the below error. 
```
> zmq@2.15.3 install /private/var/folders/3n/nvqqx4xn4_7_7cdfgr3q2lm40000gn/T/apm-install-dir-116922-9091-f0rarq/node_modules/Hydrogen/node_modules/zmq
> node-gyp rebuild

/private/var/folders/3n/nvqqx4xn4_7_7cdfgr3q2lm40000gn/T/apm-install-dir-116922-9091-f0rarq
└── (empty)


/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config libzmq --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.0.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/3n/nvqqx4xn4_7_7cdfgr3q2lm40000gn/T/apm-install-dir-116922-9091-f0rarq/node_modules/Hydrogen/node_modules/zmq
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/3n/nvqqx4xn4_7_7cdfgr3q2lm40000gn/T/apm-install-dir-116922-9091-f0rarq/package.json'
npm WARN apm-install-dir-116922-9091-f0rarq No description
npm WARN apm-install-dir-116922-9091-f0rarq No repository field.
npm WARN apm-install-dir-116922-9091-f0rarq No README data
npm WARN apm-install-dir-116922-9091-f0rarq No license field.
npm ERR! Darwin 16.0.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/kn/.atom/.apm/.apmrc" "--userconfig" "/Users/kn/.atom/.apmrc" "install" "/private/var/folders/3n/nvqqx4xn4_7_7cdfgr3q2lm40000gn/T/d-116922-9091-giu3th/package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.15.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmq@2.15.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zmq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/3n/nvqqx4xn4_7_7cdfgr3q2lm40000gn/T/apm-install-dir-116922-9091-f0rarq/npm-debug.log
npm ERR! code 1

```
I use MacOS Sierra. 
Could someone help me with this error?
Thanks!

**Comment by rgbkrk** [comment]
Can you `brew install pkg-config`?

**Comment by Kiminaka** [comment]
Ah I see. Thanks, it fixed the problem :)
