### ISSUE TITLE
Upgrading to “Hydrogen@1.1.0” failed

### ISSUE THREAD

**Issue by mandarup** [nteract/hydrogen#527]
```atom``` freezes when trying to run ```Hydrogen@1.0.1```. so I cloned ```atom``` repo and rebuilt and installed successfully.  ```Hydrogen@1.0.1``` still freezes and attempt to upgrade fails.

```$apm -v```

    apm  1.15.1
    npm  3.10.5
    node 4.4.5 x64
    python 2.7.10
    git 2.6.2

```node -v```

    v6.6.0
related issue nteract/hydrogen#525 
    

Updating to “Hydrogen@1.1.0” failed with following output

    > zeromq@3.2.3 install /private/var/folders/n9/2qhmckcj4yd2vqmfhsxdvylc0000gp/T/apm-install-dir-116112-97517-1vfz6x7/node_modules/Hydrogen/node_modules/zeromq
    > prebuild --install --preinstall "npm run build:libzmq"

    /private/var/folders/n9/2qhmckcj4yd2vqmfhsxdvylc0000gp/T/apm-install-dir-116112-97517-1vfz6x7
    └── (empty)

    /private/var/folders/n9/2qhmckcj4yd2vqmfhsxdvylc0000gp/T/apm-install-dir-116112-97517-1vfz6x7
    └── (empty)

    (node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
    Trace
        at TLSSocket.addListener (events.js:239:17)
        at TLSSocket.Readable.on (_stream_readable.js:673:33)
        at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
        at emitOne (events.js:77:13)
        at Request.emit (events.js:169:7)
        at ClientRequest.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/request/request.js:823:10)
        at emitOne (events.js:82:20)
        at ClientRequest.emit (events.js:169:7)
        at tickOnSocket (_http_client.js:502:7)
        at onSocketNT (_http_client.js:514:5)
    (node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
    Trace
        at TLSSocket.addListener (events.js:239:17)
        at TLSSocket.Readable.on (_stream_readable.js:673:33)
        at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
        at emitOne (events.js:77:13)
        at Request.emit (events.js:169:7)
        at ClientRequest.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/request/request.js:823:10)
        at emitOne (events.js:82:20)
        at ClientRequest.emit (events.js:169:7)
        at tickOnSocket (_http_client.js:502:7)
        at onSocketNT (_http_client.js:514:5)
    (node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
    Trace
        at TLSSocket.addListener (events.js:239:17)
        at TLSSocket.Readable.on (_stream_readable.js:673:33)
        at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
        at emitOne (events.js:77:13)
        at Request.emit (events.js:169:7)
        at ClientRequest.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/request/request.js:823:10)
        at emitOne (events.js:82:20)
        at ClientRequest.emit (events.js:169:7)
        at tickOnSocket (_http_client.js:502:7)
        at onSocketNT (_http_client.js:514:5)
    (node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
    Trace
        at TLSSocket.addListener (events.js:239:17)
        at TLSSocket.Readable.on (_stream_readable.js:673:33)
        at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
        at emitOne (events.js:77:13)
        at Request.emit (events.js:169:7)
        at ClientRequest.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/request/request.js:823:10)
        at emitOne (events.js:82:20)
        at ClientRequest.emit (events.js:169:7)
        at tickOnSocket (_http_client.js:502:7)
        at onSocketNT (_http_client.js:514:5)
    (node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
    Trace
        at TLSSocket.addListener (events.js:239:17)
        at TLSSocket.Readable.on (_stream_readable.js:673:33)
        at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
        at emitOne (events.js:77:13)
        at Request.emit (events.js:169:7)
        at ClientRequest.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/request/request.js:823:10)
        at emitOne (events.js:82:20)
        at ClientRequest.emit (events.js:169:7)
        at tickOnSocket (_http_client.js:502:7)
        at onSocketNT (_http_client.js:514:5)
    (node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
    Trace
        at TLSSocket.addListener (events.js:239:17)
        at TLSSocket.Readable.on (_stream_readable.js:673:33)
        at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
        at emitOne (events.js:77:13)
        at Request.emit (events.js:169:7)
        at ClientRequest.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/request/request.js:823:10)
        at emitOne (events.js:82:20)
        at ClientRequest.emit (events.js:169:7)
        at tickOnSocket (_http_client.js:502:7)
        at onSocketNT (_http_client.js:514:5)
    (node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
    Trace
        at TLSSocket.addListener (events.js:239:17)
        at TLSSocket.Readable.on (_stream_readable.js:673:33)
        at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
        at emitOne (events.js:77:13)
        at Request.emit (events.js:169:7)
        at ClientRequest.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/request/request.js:823:10)
        at emitOne (events.js:82:20)
        at ClientRequest.emit (events.js:169:7)
        at tickOnSocket (_http_client.js:502:7)
        at onSocketNT (_http_client.js:514:5)
    (node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
    Trace
        at TLSSocket.addListener (events.js:239:17)
        at TLSSocket.Readable.on (_stream_readable.js:673:33)
        at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
        at emitOne (events.js:77:13)
        at Request.emit (events.js:169:7)
        at ClientRequest.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/request/request.js:823:10)
        at emitOne (events.js:82:20)
        at ClientRequest.emit (events.js:169:7)
        at tickOnSocket (_http_client.js:502:7)
        at onSocketNT (_http_client.js:514:5)
    (node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
    Trace
        at TLSSocket.addListener (events.js:239:17)
        at TLSSocket.Readable.on (_stream_readable.js:673:33)
        at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
        at emitOne (events.js:77:13)
        at Request.emit (events.js:169:7)
        at ClientRequest.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/request/request.js:823:10)
        at emitOne (events.js:82:20)
        at ClientRequest.emit (events.js:169:7)
        at tickOnSocket (_http_client.js:502:7)
        at onSocketNT (_http_client.js:514:5)
    (node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
    Trace
        at TLSSocket.addListener (events.js:239:17)
        at TLSSocket.Readable.on (_stream_readable.js:673:33)
        at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
        at emitOne (events.js:77:13)
        at Request.emit (events.js:169:7)
        at ClientRequest.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/request/request.js:823:10)
        at emitOne (events.js:82:20)
        at ClientRequest.emit (events.js:169:7)
        at tickOnSocket (_http_client.js:502:7)
        at onSocketNT (_http_client.js:514:5)
    (node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
    Trace
        at TLSSocket.addListener (events.js:239:17)
        at TLSSocket.Readable.on (_stream_readable.js:673:33)

        at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
        at emitOne (events.js:77:13)
        at Request.emit (events.js:169:7)
        at ClientRequest.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/request/request.js:823:10)
        at emitOne (events.js:82:20)
        at ClientRequest.emit (events.js:169:7)
        at tickOnSocket (_http_client.js:502:7)
        at onSocketNT (_http_client.js:514:5)
    (node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
    Trace
        at TLSSocket.addListener (events.js:239:17)
        at TLSSocket.Readable.on (_stream_readable.js:673:33)
        at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
        at emitOne (events.js:77:13)
        at Request.emit (events.js:169:7)
        at ClientRequest.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/request/request.js:823:10)
        at emitOne (events.js:82:20)
        at ClientRequest.emit (events.js:169:7)
        at tickOnSocket (_http_client.js:502:7)
        at onSocketNT (_http_client.js:514:5)
    (node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
    Trace
        at TLSSocket.addListener (events.js:239:17)
        at TLSSocket.Readable.on (_stream_readable.js:673:33)
        at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
        at emitOne (events.js:77:13)
        at Request.emit (events.js:169:7)
        at ClientRequest.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/request/request.js:823:10)
        at emitOne (events.js:82:20)
        at ClientRequest.emit (events.js:169:7)
        at tickOnSocket (_http_client.js:502:7)
        at onSocketNT (_http_client.js:514:5)
    npm WARN install:zeromq@3.2.3 zeromq@3.2.3 install: `prebuild --install --preinstall "npm run build:libzmq"`
    npm WARN install:zeromq@3.2.3 Exit status -2
    npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/n9/2qhmckcj4yd2vqmfhsxdvylc0000gp/T/apm-install-dir-116112-97517-1vfz6x7/package.json'
    npm WARN apm-install-dir-116112-97517-1vfz6x7 No description
    npm WARN apm-install-dir-116112-97517-1vfz6x7 No repository field.
    npm WARN apm-install-dir-116112-97517-1vfz6x7 No README data
    npm WARN apm-install-dir-116112-97517-1vfz6x7 No license field.
    npm ERR! Darwin 15.6.0
    npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/mupadhye/.atom/.apm/.apmrc" "--userconfig" "/Users/mupadhye/.atom/.apmrc" "install" "/private/var/folders/n9/2qhmckcj4yd2vqmfhsxdvylc0000gp/T/d-116112-97517-10b84yj/package.tgz" "--runtime=electron" "--target=1.3.9" "--arch=x64" "--global-style"
    npm ERR! node v4.4.5
    npm ERR! npm  v3.10.5
    npm ERR! file sh
    npm ERR! path sh
    npm ERR! code ELIFECYCLE
    npm ERR! errno ENOENT
    npm ERR! syscall spawn sh

    npm ERR! zeromq@3.2.3 install: `prebuild --install --preinstall "npm run build:libzmq"`
    npm ERR! spawn sh ENOENT
    npm ERR! 
    npm ERR! Failed at the zeromq@3.2.3 install script 'prebuild --install --preinstall "npm run build:libzmq"'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the zeromq package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     prebuild --install --preinstall "npm run build:libzmq"
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs zeromq
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls zeromq
    npm ERR! There is likely additional logging output above.
    npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/n9/2qhmckcj4yd2vqmfhsxdvylc0000gp/T/apm-install-dir-116112-97517-1vfz6x7/package.json'
    npm WARN apm-install-dir-116112-97517-1vfz6x7 No description
    npm WARN apm-install-dir-116112-97517-1vfz6x7 No repository field.
    npm WARN apm-install-dir-116112-97517-1vfz6x7 No README data
    npm WARN apm-install-dir-116112-97517-1vfz6x7 No license field.
    npm ERR! Darwin 15.6.0
    npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/mupadhye/.atom/.apm/.apmrc" "--userconfig" "/Users/mupadhye/.atom/.apmrc" "install" "/private/var/folders/n9/2qhmckcj4yd2vqmfhsxdvylc0000gp/T/d-116112-97517-10b84yj/package.tgz" "--runtime=electron" "--target=1.3.9" "--arch=x64" "--global-style"
    npm ERR! node v4.4.5
    npm ERR! npm  v3.10.5

    npm ERR! Callback called more than once.
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>

    npm ERR! Please include the following file with any support request:
    npm ERR!     /private/var/folders/n9/2qhmckcj4yd2vqmfhsxdvylc0000gp/T/apm-install-dir-116112-97517-1vfz6x7/npm-debug.log
    npm ERR! code 1

**Comment by lgeiger** [comment]
Unfortunately it looks like you are running into: https://github.com/atom/apm/issues/648

**Comment by lgeiger** [comment]
This should be fixed in the [latest release](https://github.com/nteract/hydrogen/releases/tag/v1.2.0) 🎉 

Please try again and report if it works.
