### ISSUE TITLE
Error Installing Hydrogen

### ISSUE THREAD

**Issue by eskemojoe007** [nteract/hydrogen#558]
I recently installed hydrogen for Atom on a windows machine following the instructions where I installed visual C++ build tools and pointed atom at the proper build tools (it took me a while to figure it out because I didn't read the documentation carefully).

This time I have completely wiped machine and would love to install hydrogen again.  Since [commit 3b818ad92a489d8516183da79330ab873f2396c9](https://github.com/nteract/hydrogen/commit/3b818ad92a489d8516183da79330ab873f2396c9), these instructions have been removed.  @n-riesco claims that these dependencies are no longer needed and that it should install out of the box.  

I am using windows 7, Atom 1.12.7 and installing through the Atom GUI.

Installing “Hydrogen@1.4.0” failed.Hide output…
INFO: Could not find files for the given pattern(s).

> zeromq@4.1.0 install D:\Users\212333~1\AppData\Local\Temp\apm-install-dir-1161121-5388-14baxk1\node_modules\Hydrogen\node_modules\zeromq
> prebuild-install || (npm run build:libzmq && node-gyp rebuild)

> zeromq@4.1.0 build:libzmq D:\Users\212333~1\AppData\Local\Temp\apm-install-dir-1161121-5388-14baxk1\node_modules\Hydrogen\node_modules\zeromq
> node scripts/preinstall.js

Downloading libzmq for Windows
D:\Users\212333~1\AppData\Local\Temp\apm-install-dir-1161121-5388-14baxk1
`-- (empty)

prebuild-install info begin Prebuild-install version 2.0.3
prebuild-install info looking for local prebuild @ prebuilds\zeromq-v4.1.0-electron-v49-win32-ia32.tar.gz
prebuild-install info looking for cached prebuild @ D:\Users\212333077\AppData\Roaming\npm-cache\_prebuilds\https-github.com-zeromq-zeromq.js-releases-download-v4.1.0-zeromq-v4.1.0-electron-v49-win32-ia32.tar.gz
prebuild-install http request GET https://github.com/zeromq/zeromq.js/releases/download/v4.1.0/zeromq-v4.1.0-electron-v49-win32-ia32.tar.gz
prebuild-install WARN install getaddrinfo ENOTFOUND github.com github.com:443
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND github.com github.com:443
    at errnoException (dns.js:27:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Users\\212333077\\AppData\\Local\\atom\\app-1.12.7\\resources\\app\\apm\\bin\\node.exe" "D:\\Users\\212333077\\AppData\\Local\\atom\\app-1.12.7\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:libzmq"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! zeromq@4.1.0 build:libzmq: `node scripts/preinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@4.1.0 build:libzmq script 'node scripts/preinstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zeromq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/preinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zeromq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zeromq
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Users\212333~1\AppData\Local\Temp\apm-install-dir-1161121-5388-14baxk1\node_modules\Hydrogen\node_modules\zeromq\npm-debug.log
npm WARN enoent ENOENT: no such file or directory, open 'D:\Users\212333~1\AppData\Local\Temp\apm-install-dir-1161121-5388-14baxk1\package.json'
npm WARN apm-install-dir-1161121-5388-14baxk1 No description
npm WARN apm-install-dir-1161121-5388-14baxk1 No repository field.
npm WARN apm-install-dir-1161121-5388-14baxk1 No README data
npm WARN apm-install-dir-1161121-5388-14baxk1 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Users\\212333077\\AppData\\Local\\atom\\app-1.12.7\\resources\\app\\apm\\bin\\node.exe" "D:\\Users\\212333077\\AppData\\Local\\atom\\app-1.12.7\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "D:\\Users\\212333077\\.atom\\.apm\\.apmrc" "--userconfig" "D:\\Users\\212333077\\.atom\\.apmrc" "install" "D:\\Users\\212333~1\\AppData\\Local\\Temp\\d-1161121-5388-n1qul6\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=ia32" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! zeromq@4.1.0 install: `prebuild-install || (npm run build:libzmq && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@4.1.0 install script 'prebuild-install || (npm run build:libzmq && node-gyp rebuild)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zeromq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || (npm run build:libzmq && node-gyp rebuild)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zeromq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zeromq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Users\212333~1\AppData\Local\Temp\apm-install-dir-1161121-5388-14baxk1\npm-debug.log
npm ERR! code 1

**Comment by lgeiger** [comment]
> @n-riesco claims that these dependencies are no longer needed and that it should install out of the box.

That's true. Since `v1.2.0` we rely on prebuilt binaries of ZMQ. This means you don't need C++ build tools to build ZMQ from source.

Unfortunately the download of the prebuilt fails on your machine:
```
prebuild-install http request GET https://github.com/zeromq/zeromq.js/releases/download/v4.1.0/zeromq-v4.1.0-electron-v49-win32-ia32.tar.gz
prebuild-install WARN install getaddrinfo ENOTFOUND github.com github.com:443
```
In return we fall back and try to build ZMQ from source which fails the same way as described in #507.

@eskemojoe007 Are you behind a proxy or somehow unable to access the URL mentioned in the error log?

What's also strange is that zeromq tries to build from source (` node scripts/preinstall.js`) before the `prebuild` error message appears.
@rgbkrk @n-riesco Any idea why this may be the case?

@eskemojoe007 Could you try to install Hydrogen from the console with `apm install hydrogen`?

**Comment by eskemojoe007** [comment]
I am behind a proxy, but I've set up the proxy using the `.apmrc` file per usual without strict SSL.  The errors I'm getting are consistent with what I got last time including the 'zeromq' lines.  I had to tell it which python to use according the old instructions.

I tried installing using 'apm install hydrogen' and got the following output

```
D:\Users\212333077>apm install hydrogen
INFO: Could not find files for the given pattern(s).
Installing hydrogen to D:\Users\212333077\.atom\packages failed

> zeromq@4.1.0 install D:\Users\212333~1\AppData\Local\Temp\apm-install-dir-1161
122-12220-10sm5cl\node_modules\Hydrogen\node_modules\zeromq
> prebuild-install || (npm run build:libzmq && node-gyp rebuild)


> zeromq@4.1.0 build:libzmq D:\Users\212333~1\AppData\Local\Temp\apm-install-dir
-1161122-12220-10sm5cl\node_modules\Hydrogen\node_modules\zeromq
> node scripts/preinstall.js

Downloading libzmq for Windows
D:\Users\212333~1\AppData\Local\Temp\apm-install-dir-1161122-12220-10sm5cl
`-- (empty)


prebuild-install info begin Prebuild-install version 2.0.3
prebuild-install info looking for local prebuild @ prebuilds\zeromq-v4.1.0-elect
ron-v49-win32-ia32.tar.gz
prebuild-install info looking for cached prebuild @ D:\Users\212333077\AppData\R
oaming\npm-cache\_prebuilds\https-github.com-zeromq-zeromq.js-releases-download-
v4.1.0-zeromq-v4.1.0-electron-v49-win32-ia32.tar.gz
prebuild-install http request GET https://github.com/zeromq/zeromq.js/releases/d
ownload/v4.1.0/zeromq-v4.1.0-electron-v49-win32-ia32.tar.gz
prebuild-install WARN install getaddrinfo ENOTFOUND github.com github.com:443
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND github.com github.com:443
    at errnoException (dns.js:27:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Users\\212333077\\AppData\\Local\\atom\\app-1.12.7\\resources
\\app\\apm\\bin\\node.exe" "D:\\Users\\212333077\\AppData\\Local\\atom\\app-1.12
.7\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:libzmq
"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! zeromq@4.1.0 build:libzmq: `node scripts/preinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zeromq@4.1.0 build:libzmq script 'node scripts/preinstall
.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zeromq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/preinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zeromq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zeromq
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to in
stall?

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Users\212333~1\AppData\Local\Temp\apm-install-dir-1161122-12220-
10sm5cl\node_modules\Hydrogen\node_modules\zeromq\npm-debug.log
npm WARN enoent ENOENT: no such file or directory, open 'D:\Users\212333~1\AppDa
ta\Local\Temp\apm-install-dir-1161122-12220-10sm5cl\package.json'
npm WARN apm-install-dir-1161122-12220-10sm5cl No description
npm WARN apm-install-dir-1161122-12220-10sm5cl No repository field.
npm WARN apm-install-dir-1161122-12220-10sm5cl No README data
npm WARN apm-install-dir-1161122-12220-10sm5cl No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Users\\212333077\\AppData\\Local\\atom\\app-1.12.7\\resources
\\app\\apm\\bin\\node.exe" "D:\\Users\\212333077\\AppData\\Local\\atom\\app-1.12
.7\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "D
:\\Users\\212333077\\.atom\\.apm\\.apmrc" "--userconfig" "D:\\Users\\212333077\\
.atom\\.apmrc" "install" "D:\\Users\\212333~1\\AppData\\Local\\Temp\\d-1161122-1
2220-tm5jh1\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=ia32" "
--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! zeromq@4.1.0 install: `prebuild-install || (npm run build:libzmq && nod
e-gyp rebuild)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zeromq@4.1.0 install script 'prebuild-install || (npm run
 build:libzmq && node-gyp rebuild)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zeromq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || (npm run build:libzmq && node-gyp rebuild)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zeromq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zeromq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Users\212333~1\AppData\Local\Temp\apm-install-dir-1161122-12220-
10sm5cl\npm-debug.log
npm ERR! code 1
```

**Comment by rgbkrk** [comment]
> prebuild-install WARN install getaddrinfo ENOTFOUND github.com github.com:443

Definitely looks like your proxy is not allowing a connection to github at install time here.

**Comment by rgbkrk** [comment]
Do you have node locally? I'm curious if we can boil this down to an issue for `prebuild-install` or node.

**Comment by eskemojoe007** [comment]
I don't believe I have node locally.  I can change networks this evening to try my home non-proxy setup.

**Comment by eskemojoe007** [comment]
Ah....I actually think this is a proxy problem.  Even though I set up my apm to access my proxy, another package sync-settings had an issue syncing to github until they changed to another branch of github and I set my user variables to have the proper proxy.  See https://github.com/atom-community/sync-settings/issues/142.  The same change might need to be done here.

**Comment by rgbkrk** [comment]
To be more generic, we'll probably need to add support for working with the proxy in prebuild (assuming we know what to do). To help us figure this out, would you be able to install node https://nodejs.org/en/ then run `npm install zeromq` in a new directory somewhere?

**Comment by rgbkrk** [comment]
`prebuild-install` does have [proxy configuration](https://github.com/mafintosh/prebuild-install/blob/8517efc85cd74da9ec0a37562cf1adb20c0e8569/rc.js#L36-L37), so I want to see if we can find the specific issue inside there.

**Comment by eskemojoe007** [comment]
I installed node out of the box and tried `npm install zeromq` which failed with the following error:

```
D:\Users\212333077>npm install zeromq

> zeromq@4.1.0 install D:\Users\212333077\node_modules\zeromq
> prebuild-install || (npm run build:libzmq && node-gyp rebuild)

prebuild-install info begin Prebuild-install version 2.0.3
prebuild-install info looking for local prebuild @ prebuilds\zeromq-v4.1.0-node-
v48-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ D:\Users\212333077\AppData\R
oaming\npm-cache\_prebuilds\https-github.com-zeromq-zeromq.js-releases-download-
v4.1.0-zeromq-v4.1.0-node-v48-win32-x64.tar.gz
prebuild-install http request GET https://github.com/zeromq/zeromq.js/releases/d
ownload/v4.1.0/zeromq-v4.1.0-node-v48-win32-x64.tar.gz
prebuild-install WARN install getaddrinfo ENOTFOUND github.com github.com:443

> zeromq@4.1.0 build:libzmq D:\Users\212333077\node_modules\zeromq
> node scripts/preinstall.js

Downloading libzmq for Windows
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND github.com github.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "build:libzmq"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! zeromq@4.1.0 build:libzmq: `node scripts/preinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zeromq@4.1.0 build:libzmq script 'node scripts/preinstall
.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zeromq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/preinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zeromq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zeromq
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to in
stall?

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Users\212333077\node_modules\zeromq\npm-debug.log
npm WARN enoent ENOENT: no such file or directory, open 'D:\Users\212333077\pack
age.json'
npm WARN 212333077 No description
npm WARN 212333077 No repository field.
npm WARN 212333077 No README data
npm WARN 212333077 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "zeromq"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! zeromq@4.1.0 install: `prebuild-install || (npm run build:libzmq && nod
e-gyp rebuild)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zeromq@4.1.0 install script 'prebuild-install || (npm run
 build:libzmq && node-gyp rebuild)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zeromq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || (npm run build:libzmq && node-gyp rebuild)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zeromq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zeromq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Users\212333077\npm-debug.log
```

I then set the npm proxy up following https://jjasonclark.com/how-to-setup-node-behind-web-proxy/ with strict `npm config set strict-ssl false` as well.  Same errors.

**Comment by eskemojoe007** [comment]
I also verified that my env variable are set:

```
D:\Users\212333077\Desktop>echo %HTTP_PROXY%
http://foo.com:80

D:\Users\212333077\Desktop>echo %HTTPS_PROXY%
http://foo.com:80
```

**Comment by rgbkrk** [comment]
Ok, great thank you. Now for another to try out, can you `npm install leveldown`?

**Comment by ianfiske** [comment]
I am still getting this exact error, even though it's pulling zeromq.js@4.1.1, which should have fixed the error.  @eskemojoe007 Is it working for you now?

**Comment by ianfiske** [comment]
Sorry, not exact same error.  Just very similar:

```
> zeromq@4.1.1 build:libzmq C:\Users\y3044\node_modules\zeromq
> node scripts/preinstall.js

Downloading libzmq for Windows
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 192.30.253.113:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
.
.
.
```

**Comment by eskemojoe007** [comment]
@ianfiske, I eventually installed in a proxy-less environment.  Sorry.

**Comment by lgeiger** [comment]
> it's pulling zeromq.js@4.1.1, which should have fixed the error.

That's true, downloading the prebuilt binaries should now be possible behind a proxy.
I'm not familiar with using `apm` or `npm` behind a proxy, but I think you need to set up `apm` correctly.
Try running:
```
apm config set proxy your-url
apm config set https-proxy your-url
```
---
Unfortunately downloading of the prebuilt binaries is failing on your machine and `zeromq` falls back to building from source.
For this additional assets have to be downloaded. Latter download doesn't yet support proxies. 

Could you post the entire log? Especially the lines before `> node scripts/preinstall.js` are interesting.

**Comment by ianfiske** [comment]
The entire log is 10k lines, so I'll just post that relevant part right before  `node scripts/preinstall.js` for now :).  Looks like `'prebuild-install' is not recognized as an internal or external command,
operable program or batch file.` is the cause here.  Googling didn't help me find a solution to that.

```
.
.
.
REQUEST end event https://registry.npmjs.org/ultron
REQUEST emitting complete https://registry.npmjs.org/ultron
REQUEST onRequestResponse https://registry.npmjs.org/options 304 { server: 'nginx/1.10.1',
  'content-type': 'application/json',
  'last-modified': 'Thu, 17 Nov 2016 23:21:00 GMT',
  etag: 'W/"582e3b5c-1fda"',
  'cache-control': 'max-age=300',
  'accept-ranges': 'bytes',
  date: 'Tue, 10 Jan 2017 13:55:19 GMT',
  via: '1.1 varnish',
  'x-served-by': 'cache-dfw1847-DFW',
  'x-cache': 'HIT',
  'x-cache-hits': '3',
  'x-timer': 'S1483999417.300902,VS0,VE0',
  vary: 'Accept-Encoding',
  connection: 'close',
  'content-encoding': 'gzip',
  age: '263' }
REQUEST reading response's body
REQUEST finish init function https://registry.npmjs.org/options
REQUEST response end https://registry.npmjs.org/options 304 { server: 'nginx/1.10.1',
  'content-type': 'application/json',
  'last-modified': 'Thu, 17 Nov 2016 23:21:00 GMT',
  etag: 'W/"582e3b5c-1fda"',
  'cache-control': 'max-age=300',
  'accept-ranges': 'bytes',
  date: 'Tue, 10 Jan 2017 13:55:19 GMT',
  via: '1.1 varnish',
  'x-served-by': 'cache-dfw1847-DFW',
  'x-cache': 'HIT',
  'x-cache-hits': '3',
  'x-timer': 'S1483999417.300902,VS0,VE0',
  vary: 'Accept-Encoding',
  connection: 'close',
  'content-encoding': 'gzip',
  age: '263' }
REQUEST end event https://registry.npmjs.org/options
REQUEST emitting complete https://registry.npmjs.org/options

> zeromq@4.1.1 install C:\Users\USER\AppData\Local\Temp\apm-install-dir-117010-28436-1i5fg5a\node_modules\Hydrogen\node_modules\zeromq
> prebuild-install || (npm run build:libzmq && node-gyp rebuild)

'prebuild-install' is not recognized as an internal or external command,
operable program or batch file.

> zeromq@4.1.1 build:libzmq C:\Users\USER\AppData\Local\Temp\apm-install-dir-117010-28436-1i5fg5a\node_modules\Hydrogen\node_modules\zeromq
> node scripts/preinstall.js

Downloading libzmq for Windows
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 192.30.253.113:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:libzmq"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! zeromq@4.1.1 build:libzmq: `node scripts/preinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zeromq@4.1.1 build:libzmq script 'node scripts/preinstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zeromq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/preinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zeromq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zeromq
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\USER\AppData\Local\Temp\apm-install-dir-117010-28436-1i5fg5a\node_modules\Hydrogen\node_modules\zeromq\npm-debug.log
C:\Users\USER\AppData\Local\Temp\apm-install-dir-117010-28436-1i5fg5a
`-- (empty)

npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\USER\AppData\Local\Temp\apm-install-dir-117010-28436-1i5fg5a\package.json'
npm WARN apm-install-dir-117010-28436-1i5fg5a No description
npm WARN apm-install-dir-117010-28436-1i5fg5a No repository field.
npm WARN apm-install-dir-117010-28436-1i5fg5a No README data
npm WARN apm-install-dir-117010-28436-1i5fg5a No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\USER\\AppData\\Local\\atom\\app-1.12.9\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\USER\\AppData\\Local\\atom\\app-1.12.9\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\USER\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\USER\\.atom\\.apmrc" "install" "C:\\Users\\USER\\AppData\\Local\\Temp\\d-117010-28436-15vpniu\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=ia32" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! zeromq@4.1.1 install: `prebuild-install || (npm run build:libzmq && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zeromq@4.1.1 install script 'prebuild-install || (npm run build:libzmq && node-gyp rebuild)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zeromq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || (npm run build:libzmq && node-gyp rebuild)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zeromq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zeromq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\USER\AppData\Local\Temp\apm-install-dir-117010-28436-1i5fg5a\npm-debug.log
npm ERR! code 1
failed
```

**Comment by ianfiske** [comment]
I just noticed that I get a different error from `prebuild-install` depending on whether I run in CMD or Git Bash.  The above error (`'prebuild-install' is not recognized as an internal or external command, operable program or batch file`)  was using Git Bash.  When I run with Windows CMD, I get 

```
...
> zeromq@4.1.1 install C:\Users\USER\AppData\Local\Temp\apm-install-dir-117011-24824-1l45jlg\node_modules\Hydrogen\nod
_modules\zeromq
> prebuild-install || (npm run build:libzmq && node-gyp rebuild)

prebuild-install info begin Prebuild-install version 2.1.0
prebuild-install info looking for local prebuild @ prebuilds\zeromq-v4.1.1-electron-v49-win32-ia32.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\USER\AppData\Roaming\npm-cache\_prebuilds\https-github.com-zeromq-zeromq.js-releases-download-v4.1.1-zeromq-v4.1.1-electron-v49-win32-ia32.tar.gz
prebuild-install http request GET https://github.com/zeromq/zeromq.js/releases/download/v4.1.1/zeromq-v4.1.1-electron-v49-win32-ia32.tar.gz
prebuild-install WARN install unable to get local issuer certificate

> zeromq@4.1.1 build:libzmq C:\Users\USER\AppData\Local\Temp\apm-install-dir-117011-24824-1l45jlg\node_modules\Hydroge
\node_modules\zeromq
> node scripts/preinstall.js

Downloading libzmq for Windows
events.js:141
      throw er; // Unhandled 'error' event
	  
...
```

Looks like maybe there is an issue with the certificate?  Incidentally, my .apmrc and .npmrc both do specify a cafile, which is required for my proxy settings to work normally.  Is it possible that prebuild is not using the correct cafile?

**Comment by lgeiger** [comment]
Sorry for the vague answers, I've never used a proxy.

> Is it possible that prebuild is not using the correct cafile?

I'm pretty sure [`prebuild-install`](https://github.com/mafintosh/prebuild-install) currently doesn't support certificates. It would be great if you open a issue (or even better a PR 😄 ) there.

Unfortunately I guess you either have to install Hydrogen without a proxy or install the [developement version](https://github.com/nteract/hydrogen#development) and manually download the prebuilt binary from https://github.com/zeromq/zeromq.js/releases/download/v4.1.1/zeromq-v4.1.1-electron-v49-win32-ia32.tar.gz and copy it to `Hydrogen\node_modules\zeromq\build\Release\zmq.node`.

**Comment by lgeiger** [comment]
As mentioned in the error log, `prebuild-install` will look for cached prebuilts:
```
prebuild-install info looking for cached prebuild @ C:\Users\USER\AppData\Roaming\npm-cache\_prebuilds\https-github.com-zeromq-zeromq.js-releases-download-v4.1.1-zeromq-v4.1.1-electron-v49-win32-ia32.tar.gz
```

You could manually download the relevant prebuilt binary and place it at the path mentioned above.
