### ISSUE TITLE
Uncaught TypeError: Cannot read property 'kernelSpec' of undefined

### ISSUE THREAD

**Issue by Earthson** [nteract/hydrogen#595]
[Enter steps to reproduce below:]

1. restart kernel again and again

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package, v1.5.3

### Stack Trace

Uncaught TypeError: Cannot read property 'kernelSpec' of undefined

```
At /Users/earthson/.atom/packages/Hydrogen/lib/signal-list-view.js:66

TypeError: Cannot read property 'kernelSpec' of undefined
    at /Users/earthson/.atom/packages/Hydrogen/lib/signal-list-view.js:66:54
    at Array.map (native)
    at SignalListView.attach (/Users/earthson/.atom/packages/Hydrogen/lib/signal-list-view.js:65:46)
    at SignalListView.toggle (/Users/earthson/.atom/packages/Hydrogen/lib/signal-list-view.js:45:12)
    at Object.showKernelCommands (/Users/earthson/.atom/packages/Hydrogen/lib/main.js:215:25)
```

### Commands

```
  2x -0:44.5.0 hydrogen:run-cell (input.hidden-input)
     -0:36.7.0 core:save (input.hidden-input)
     -0:34.7.0 command-palette:toggle (input.hidden-input)
     -0:33.6.0 core:confirm (input.hidden-input)
     -0:33.6.0 hydrogen:restart-kernel (input.hidden-input)
  2x -0:32.1.0 hydrogen:run-cell (input.hidden-input)
     -0:19 command-palette:toggle (input.hidden-input)
     -0:17.2.0 core:confirm (input.hidden-input)
     -0:17.2.0 hydrogen:restart-kernel (input.hidden-input)
     -0:11.1.0 editor:consolidate-selections (input.hidden-input)
     -0:11.1.0 core:cancel (input.hidden-input)
     -0:04.7.0 editor:consolidate-selections (input.hidden-input)
     -0:04.7.0 core:cancel (input.hidden-input)
     -0:03.0 command-palette:toggle (input.hidden-input)
     -0:02.1.0 editor:consolidate-selections (input.hidden-input)
     -0:02.1.0 core:cancel (input.hidden-input)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-light-syntax"
    ]
  },
  "Hydrogen": {
    "gateways": "[{\n  \"name\": \"w1.q-phantom.com\",\n  \"options\": {\n    \"baseUrl\": \"http://jupyter201.q-phantom.com/earthson\"\n  }\n}]",
    "kernelspec": "{\n  \"kernelspecs\": {\n    \"python3\": {\n      \"resource_dir\": \"/Users/earthson/.opt/anaconda/lib/python3.5/site-packages/ipykernel/resources\",\n      \"spec\": {\n        \"argv\": [\n          \"/Users/earthson/.opt/anaconda/bin/python\",\n          \"-m\",\n          \"ipykernel\",\n          \"-f\",\n          \"{connection_file}\"\n        ],\n        \"display_name\": \"Python 3\",\n        \"env\": {},\n        \"language\": \"python\"\n      }\n    }\n  }\n}"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v1.8.27 (active)
Hydrogen, v1.5.3 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (active)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (active)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by lgeiger** [comment]
Are you using a remote or local kernel?

By the way you shouldn't need to manually edit the kernelspec setting in hydrogen.

**Comment by Earthson** [comment]
I'm using local kernel. And there is no problem now, I can not reproduce it.
