### ISSUE TITLE
Uncaught Error: Tried loading "pdfjs-dist/build/pdf.worker" at /usr/share/atom/resources/app.asar...

### ISSUE THREAD

**Issue by jeb2239** [nteract/hydrogen#616]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.10
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 1.5.5

### Stack Trace

Uncaught Error: Tried loading "pdfjs-dist/build/pdf.worker" at /usr/share/atom/resources/app.asar/static/pdfjs-dist/build/pdf.worker.js then tried node's require("pdfjs-dist/build/pdf.worker") and it failed with error: Error: Cannot find module 'pdfjs-dist/build/pdf.worker'

```
At /home/barriosj/.atom/packages/Hydrogen/node_modules/requirejs/bin/r.js:2604

Error: Tried loading "pdfjs-dist/build/pdf.worker" at /usr/share/atom/resources/app.asar/static/pdfjs-dist/build/pdf.worker.js then tried node's require("pdfjs-dist/build/pdf.worker") and it failed with error: Error: Cannot find module 'pdfjs-dist/build/pdf.worker'
    at /packages/Hydrogen/node_modules/requirejs/bin/r.js:2597:27
    at Object.execCb (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1943:33)
    at Object.check (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1131:51)
    at Object.enable (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1423:22)
    at Object.init (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1036:26)
    at callGetModule (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1450:63)
    at Object.completeLoad (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1837:21)
    at Function.req.load (/packages/Hydrogen/node_modules/requirejs/bin/r.js:2610:17)
    at Object.load (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1932:21)
    at Object.load (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1082:29)
    at Object.fetch (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1072:66)
    at Object.check (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1104:30)
    at Object.enable (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1423:22)
    at Object.enable (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1804:39)
    at /packages/Hydrogen/node_modules/requirejs/bin/r.js:1408:33)
    at /packages/Hydrogen/node_modules/requirejs/bin/r.js:384:23
    at each (/packages/Hydrogen/node_modules/requirejs/bin/r.js:309:31)
    at Object.enable (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1360:17)
    at Object.init (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1036:26)
    at /packages/Hydrogen/node_modules/requirejs/bin/r.js:1707:36
```

### Commands

```
     -0:52 autocomplete-plus:confirm (input.hidden-input)
     -0:51.4.0 core:move-right (input.hidden-input)
     -0:51 editor:newline (input.hidden-input)
     -0:49.5.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -0:47.1.0 autocomplete-plus:confirm (input.hidden-input)
     -0:46.2.0 hydrogen:run-all (input.hidden-input)
     -0:38.1.0 core:backspace (input.hidden-input)
     -0:37.5.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  9x -0:36.7.0 core:move-right (input.hidden-input)
     -0:33.7.0 core:move-up (input.hidden-input)
 11x -0:33.1.0 core:move-left (input.hidden-input)
     -0:30.6.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
 11x -0:30.2.0 core:move-right (input.hidden-input)
     -0:27.8.0 hydrogen:run-all (input.hidden-input)
     -0:17 pane:show-next-recently-used-item (input.hidden-input)
     -0:16.8.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-bracket-highlight 0.3.2 
autocomplete-clang 0.10.0 
autocomplete-cmake 0.3.1 
autocomplete-python 1.8.50 
Hydrogen 1.5.5 
language-cmake 0.3.0 
language-elm 1.5.0 
language-latex 1.0.0 
language-markdown 0.19.1 
language-ocaml 1.1.2 
language-sage 0.3.2 
language-vala-modern 0.3.2 
language-x86-64-assembly 2.2.8 
markdown-preview-plus 2.4.2 
ocaml-merlin 0.9.6 
pandoc 0.2.2 
pdf-view 0.54.0 
tablr 1.8.1 
```

**Comment by lgeiger** [comment]
This error is thrown from a package required by Hydrogen. Could you please provide steps to reproduce?

**Comment by BenRussert** [comment]
@jeb2239 Are you still seeing this issue? It may just be a question of updating your packages. If you can provide steps to reproduce we may be able to look into the cause here.
