### ISSUE TITLE
Uncaught Error: Cannot find module './ws-kernel'

### ISSUE THREAD

**Issue by bapoo1998** [nteract/hydrogen#633]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: KDE neon
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 1.6.0

### Stack Trace

Uncaught Error: Cannot find module './ws-kernel'

```
At module.js:457

Error: Cannot find module './ws-kernel'
  at Module._resolveFilename (module.js:455:15)
  at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
  at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:403:25)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at /packages/Hydrogen/lib/signal-list-view.js:21:17)
  at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
  at /app.asar/src/compile-cache.js:216:21)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at /packages/Hydrogen/lib/main.js:19:23)
  at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
  at /app.asar/src/compile-cache.js:216:21)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
  at Package.module.exports.Package.activateConfig (/app.asar/src/package.js:266:12)
  at PackageManager.module.exports.PackageManager.packageHasSettings (/app.asar/node_modules/settings-view/lib/package-manager.js:53:14)
  at PackageCard.module.exports.PackageCard.hasSettings (/app.asar/node_modules/settings-view/lib/package-card.js:728:34)
  at PackageCard.module.exports.PackageCard.updateSettingsState (/app.asar/node_modules/settings-view/lib/package-card.js:402:16)
  at PackageCard.module.exports.PackageCard.updateInterfaceState (/app.asar/node_modules/settings-view/lib/package-card.js:395:12)
  at /app.asar/node_modules/settings-view/lib/package-card.js:665:24
  at /app.asar/node_modules/settings-view/lib/package-card.js:741:20
  at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/app.asar/node_modules/settings-view/lib/package-manager.js:652:27)
  at /app.asar/node_modules/settings-view/lib/package-manager.js:491:26
  at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
  at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
  at /app.asar/src/buffered-process.js:343:11
  at /app.asar/src/buffered-process.js:204:9)
  at emitOne (events.js:101:20)
  at Socket.emit (events.js:188:7)
  at Pipe._handle.close [as _onclose] (net.js:493:12)

```

### Commands

```
     -3:14.6.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.6 
Hydrogen 1.6.0 
```

**Comment by lgeiger** [comment]
Could you post steps to reproduce this error?

**Comment by lgeiger** [comment]
Could you try and run `apm rebuild-module-cache`?

**Comment by BenRussert** [comment]
@bapoo1998 If you have any questions please feel free to reply.
