### ISSUE TITLE
Uncaught Error: Module version mismatch. Expected 49, got 47.

### ISSUE THREAD

**Issue by mr742** [nteract/hydrogen#634]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: linux 4.9.13-201.fc25.x86_64
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 1.6.0

### Stack Trace

Uncaught Error: Module version mismatch. Expected 49, got 47.

```
At ELECTRON_ASAR.js:168

Error: Module version mismatch. Expected 49, got 47.
    at Error (native)
    at process.module.(anonymous function) (ELECTRON_ASAR.js:168:20)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/lib64/atom/src/native-compile-cache.js:50:27)
    at /packages/Hydrogen/node_modules/jmp/node_modules/zeromq/lib/index.js:6:11)
    at Module._compile (/usr/lib64/atom/src/native-compile-cache.js:109:30)
    at Object.value [as .js] (/usr/lib64/atom/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/lib64/atom/src/native-compile-cache.js:50:27)
    at /packages/Hydrogen/node_modules/jmp/node_modules/zeromq/index.js:2:18)
    at Module._compile (/usr/lib64/atom/src/native-compile-cache.js:109:30)
    at Object.value [as .js] (/usr/lib64/atom/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/lib64/atom/src/native-compile-cache.js:50:27)
    at /packages/Hydrogen/node_modules/jmp/index.js:37:11)
    at Module._compile (/usr/lib64/atom/src/native-compile-cache.js:109:30)
    at Object.value [as .js] (/usr/lib64/atom/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-latex 0.7.0 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
busy-signal 1.3.0 
file-type-icons 1.3.3 
git-control 0.8.2 
git-history 3.2.0 
git-plus 7.3.3 
git-projects 1.17.0 
git-time-machine 1.5.6 
highlight-line 0.12.0 
highlight-selected 0.12.0 
Hydrogen 1.6.0 
ink 0.6.5 
intentions 1.1.2 
julia-client 0.5.12 
language-julia 0.10.0 
language-latex 1.0.0 
language-markdown 0.20.0 
latex 0.42.3 
latex-completions 0.3.2 
latexer 0.3.0 
linter 2.1.0 
linter-chktex 1.3.0 
linter-markdown 3.1.0 
linter-ui-default 1.1.0 
linter-write-good 0.8.0 
markdown-pdf 1.5.0 
markdown-preview-plus 2.4.9 
markdown-scroll-sync 2.1.2 
markdown-themeable-pdf 1.2.0 
markdown-toc 0.4.2 
markdown-writer 2.6.4 
minimap 4.26.8 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.5.0 
minimap-linter 1.6.0 
minimap-pigments 0.2.2 
minimap-selection 4.4.0 
open-recent 5.0.0 
pdf-view 0.55.0 
pigments 0.39.0 
script 3.14.1 
tidy-markdown 3.0.1 
tool-bar 1.1.0 
tree-view-git-status 1.3.1 
uber-juno 0.1.1 
wordcount 2.10.4 
```

**Comment by lgeiger** [comment]
Updating Atom sometimes requires rebuilding of native modules. Try:
```bash
apm rebuild hydrogen
```

**Comment by BenRussert** [comment]
@mr742 Just following up here. Have you had a chance to try the suggestion above?

**Comment by BenRussert** [comment]
I'll close for now, but let me know if you have any questions
