### ISSUE TITLE
Uncaught Error: Cannot find module './config'

### ISSUE THREAD

**Issue by derek1032** [nteract/hydrogen#682]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 1.8.0

### Stack Trace

Uncaught Error: Cannot find module './config'

```
At module.js:457

Error: Cannot find module './config'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/Hydrogen/lib/kernel-manager.js:27:15)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/Hydrogen/lib/signal-list-view.js:25:22)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/Hydrogen/lib/main.js:27:23)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateConfig (/app.asar/src/package.js:266:12)
    at PackageManager.module.exports.PackageManager.packageHasSettings (/app.asar/node_modules/settings-view/lib/package-manager.js:53:14)
    at PackageCard.module.exports.PackageCard.hasSettings (/app.asar/node_modules/settings-view/lib/package-card.js:728:34)
    at PackageCard.module.exports.PackageCard.updateSettingsState (/app.asar/node_modules/settings-view/lib/package-card.js:402:16)
    at PackageCard.module.exports.PackageCard.updateInterfaceState (/app.asar/node_modules/settings-view/lib/package-card.js:395:12)
    at /app.asar/node_modules/settings-view/lib/package-card.js:665:24
    at /app.asar/node_modules/settings-view/lib/package-card.js:741:20
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (/app.asar/node_modules/settings-view/lib/package-manager.js:652:27)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:491:26
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -7:35.9.0 core:move-right (input.hidden-input)
  3x -7:35.5.0 core:backspace (input.hidden-input)
     -7:33.4.0 core:save (input.hidden-input)
  2x -7:20.2.0 core:copy (input.hidden-input)
     -6:35.8.0 core:backspace (input.hidden-input)
     -6:35.6.0 core:paste (input.hidden-input)
     -6:23.3.0 core:copy (input.hidden-input)
     -6:12.5.0 core:move-left (input.hidden-input)
     -6:12.2.0 core:paste (input.hidden-input)
     -6:10.4.0 core:copy (input.hidden-input)
     -6:06.8.0 core:move-left (input.hidden-input)
     -6:06.6.0 core:paste (input.hidden-input)
     -6:02.8.0 core:copy (input.hidden-input)
     -5:54.1.0 core:move-left (input.hidden-input)
     -5:51 core:save (input.hidden-input)
  2x -5:46.6.0 core:copy (input.hidden-input)
```

### Non-Core Packages

```
Hydrogen 1.8.0 
script 3.14.1 
```

**Comment by BenRussert** [comment]
@derek1032 As a starting point I might suggest uninstalling and reinstalling hydrogen. Have you been able to get hydrogen working in the past?

**Comment by lgeiger** [comment]
Could you try and run `apm rebuild-module-cache`?

**Comment by BenRussert** [comment]
@derek1032 have you been able to try reinstalling hydrogen? I think the suggestion above to run `apm rebuild-module-cache` could fix the issue as well.

**Comment by BenRussert** [comment]
I'll close for now, but let me know if you have any questions.
