### ISSUE TITLE
Uncaught Error: Cannot find module './utils'

### ISSUE THREAD

**Issue by Benjamincreator** [nteract/hydrogen#692]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 1.9.0

### Stack Trace

Uncaught Error: Cannot find module './utils'

```
At module.js:457

Error: Cannot find module './utils'
  at Module._resolveFilename (module.js:455:15)
  at Module._resolveFilename (/Users/Benjamin/Downloads/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
  at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:403:25)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at /packages/Hydrogen/lib/result-view.js:13:14)
  at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
  at /app.asar/src/compile-cache.js:216:21)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at /packages/Hydrogen/lib/main.js:23:19)
  at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
  at /app.asar/src/compile-cache.js:216:21)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
  at Package.module.exports.Package.activateConfig (/app.asar/src/package.js:266:12)
  at PackageManager.module.exports.PackageManager.packageHasSettings (/app.asar/node_modules/settings-view/lib/package-manager.js:53:14)
  at PackageCard.module.exports.PackageCard.hasSettings (/app.asar/node_modules/settings-view/lib/package-card.js:728:34)
  at PackageCard.module.exports.PackageCard.updateSettingsState (/app.asar/node_modules/settings-view/lib/package-card.js:402:16)
  at PackageCard.module.exports.PackageCard.updateInterfaceState (/app.asar/node_modules/settings-view/lib/package-card.js:395:12)
  at /app.asar/node_modules/settings-view/lib/package-card.js:665:24
  at /app.asar/node_modules/settings-view/lib/package-card.js:741:20
  at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/app.asar/node_modules/settings-view/lib/package-manager.js:652:27)
  at /app.asar/node_modules/settings-view/lib/package-manager.js:491:26
  at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
  at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
  at /app.asar/src/buffered-process.js:343:11
  at /app.asar/src/buffered-process.js:204:9)
  at emitOne (events.js:101:20)
  at Socket.emit (events.js:188:7)
  at Pipe._handle.close [as _onclose] (net.js:493:12)

```

### Commands

```
     -8:21.2.0 core:save (input.hidden-input)
  2x -8:19.8.0 script:run (input.hidden-input)
  6x -5:51.6.0 core:select-up (input.hidden-input)
     -3:35.3.0 script:run-options (div.package-detail.panels-item)
```

### Non-Core Packages

```
autocomplete-python 1.8.62 
Hydrogen 1.9.0 
python-indent 1.0.2 
script 3.14.1 
```

**Comment by lgeiger** [comment]
Have you tried reinstalling Hydrogen?

We've recently seen a few similar issues: #633, #682. Could it be that Atom messes up the babel transpilation?

**Comment by BenRussert** [comment]
@Benjamincreator Have you had a chance to try reinstalling Hydrogen?

**Comment by BenRussert** [comment]
I'll close this for now, but feel free to reply if you're still looking for help.
