### ISSUE TITLE
Uncaught Error: Cannot find module './lib/React'

### ISSUE THREAD

**Issue by EngineHH** [nteract/hydrogen#700]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Education
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 1.10.1

### Stack Trace

Uncaught Error: Cannot find module './lib/React'

```
At module.js:457

Error: Cannot find module './lib/React'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.15.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/Hydrogen/node_modules/react/react.js:3:18)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/Hydrogen/lib/main.js:6:31)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateConfig (/app.asar/src/package.js:266:12)
    at PackageDetailView.module.exports.PackageDetailView.activateConfig (/app.asar/node_modules/settings-view/lib/package-detail-view.js:216:26)
    at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (/app.asar/node_modules/settings-view/lib/package-detail-view.js:160:12)
    at PackageDetailView.module.exports.PackageDetailView.loadPackage (/app.asar/node_modules/settings-view/lib/package-detail-view.js:171:21)
    at PackageDetailView.module.exports.PackageDetailView.initialize (/app.asar/node_modules/settings-view/lib/package-detail-view.js:146:12)
    at /app.asar/node_modules/space-pen/lib/space-pen.js:184:25)
    at /app.asar/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.6 
build 0.67.0 
highlight-selected 0.13.1 
Hydrogen 1.10.1 
language-latex 1.0.0 
latex 0.43.0 
latextools 0.8.5 
script 3.14.1 
synced-sidebar 0.4.3 
```

**Comment by lgeiger** [comment]
Strange, this looks like Atom corrupted the installation. Could you try to reinstall Hydrogen?

**Comment by BenRussert** [comment]
@EngineHH Have you continued to see this issue? We can reopen if reinstalling did not work.
