### ISSUE TITLE
Uncaught Error: Cannot find module 'core-js/library/fn/symbol/iterator'

### ISSUE THREAD

**Issue by weltall216** [nteract/hydrogen#725]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 1.11.2

### Stack Trace

Uncaught Error: Cannot find module 'core-js/library/fn/symbol/iterator'

```
At module.js:457

Error: Cannot find module 'core-js/library/fn/symbol/iterator'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.16.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/Hydrogen/node_modules/babel-runtime/core-js/symbol/iterator.js:1:110)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/Hydrogen/node_modules/babel-runtime/helpers/typeof.js:5:17)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/Hydrogen/node_modules/babel-runtime/helpers/possibleConstructorReturn.js:5:16)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.22 
atom-clock 0.1.7 
atom-latex 0.7.5 
code-peek 1.4.18 
highlight-selected 0.13.1 
Hydrogen 1.11.2 
minimap 4.27.1 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
pdf-view 0.57.0 
seti-icons 1.4.3 
sync-settings 0.8.1 
wakatime 6.0.14 
```

**Comment by lgeiger** [comment]
Thanks for reporting. Reinstalling should fix this.
