### ISSUE TITLE
Uncaught Error: Cannot find module './signal-list-view'

### ISSUE THREAD

**Issue by DRosenman** [nteract/hydrogen#745]
[Enter steps to reproduce:]

1. ...Tried to install Hydrogen package on atom.
2. ...Following error came up

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 1.11.2

### Stack Trace

Uncaught Error: Cannot find module './signal-list-view'

```
At module.js:457

Error: Cannot find module './signal-list-view'
  at Module._resolveFilename (module.js:455:15)
  at Module._resolveFilename (~/AppData/Local/atom/app-1.16.0/resources/electron.asar/common/reset-search-paths.js:35:12)
  at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:403:25)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at /packages/Hydrogen/lib/main.js:27:23)
  at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
  at /app.asar/src/compile-cache.js:216:21)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
  at Package.module.exports.Package.activateConfig (/app.asar/src/package.js:266:12)
  at PackageManager.module.exports.PackageManager.packageHasSettings (/app.asar/node_modules/settings-view/lib/package-manager.js:53:14)
  at PackageCard.hasSettings (/app.asar/node_modules/settings-view/lib/package-card.js:785:34)
  at PackageCard.updateSettingsState (/app.asar/node_modules/settings-view/lib/package-card.js:430:16)
  at PackageCard.updateInterfaceState (/app.asar/node_modules/settings-view/lib/package-card.js:422:12)
  at /app.asar/node_modules/settings-view/lib/package-card.js:719:16
  at /app.asar/node_modules/settings-view/lib/package-card.js:802:11
  at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/app.asar/node_modules/settings-view/lib/package-manager.js:652:27)
  at /app.asar/node_modules/settings-view/lib/package-manager.js:491:26
  at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
  at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
  at /app.asar/src/buffered-process.js:352:11)
  at emitTwo (events.js:106:13)
  at ChildProcess.emit (events.js:191:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

```

### Commands

```
     -7:31.5.0 core:confirm (input.hidden-input)
     -7:23.9.0 core:move-down (atom-pane.pane.active)
  5x -5:51.2.0 core:backspace (input.hidden-input)
     -5:48.5.0 core:confirm (input.hidden-input)
     -5:17.1.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -2:53.5.0 core:backspace (input.hidden-input)
  5x -2:51.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
Hydrogen 1.11.2 
platformio-ide-terminal 2.5.0 
```

**Comment by rgbkrk** [comment]
Reinstall on the command line with `apm install hydrogen`

**Comment by BenRussert** [comment]
I bet the reinstall works, please reply if not.
