### ISSUE TITLE
Uncaught Error: %1 is not a valid Win32 application./\?\$ATOM_HOME\packages\Hydrogen\node_modul...

### ISSUE THREAD

**Issue by manoj062006** [nteract/hydrogen#765]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 1.12.1

### Stack Trace

Uncaught Error: %1 is not a valid Win32 application.
\\?\C:\Users\manoj\.atom\packages\Hydrogen\node_modules\zeromq\build\Release\zmq.node

```
At ELECTRON_ASAR.js:168

Error: %1 is not a valid Win32 application.
\\?\C:\Users\manoj\.atom\packages\Hydrogen\node_modules\zeromq\build\Release\zmq.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/Hydrogen/node_modules/zeromq/lib/index.js:6:11)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/Hydrogen/node_modules/zeromq/index.js:2:18)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/Hydrogen/node_modules/jmp/index.js:37:11)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

### Commands

```
     -2:56.7.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.7 
autoclose-html 0.23.0 
emmet 2.4.3 
Hydrogen 1.12.1 
script 3.14.1 
```

**Comment by lgeiger** [comment]
This looks like `apm` didn't rebuild `zeromq` for the correct electron version.

Could you try running `apm rebuild hydrogen`?

If this doesn't help, try reinstalling Hydrogen with
```bash
apm uninstall hydrogen
apm install hydrogen
```

**Comment by BenRussert** [comment]
I think the rebuild solution will work. Let us know if you have questions.
