### ISSUE TITLE
Uncaught Error: A dynamic link library (DLL) initialization routine failed./\?\$ATOM_HOME\packa...

### ISSUE THREAD

**Issue by zhangguanghui1** [nteract/hydrogen#776]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 1.12.1

### Stack Trace

Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\Administrator\.atom\packages\hydrogen\node_modules\zeromq\build\Release\zmq.node

```
At ELECTRON_ASAR.js:168

Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\Administrator\.atom\packages\hydrogen\node_modules\zeromq\build\Release\zmq.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/hydrogen/node_modules/zeromq/lib/index.js:6:11)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/hydrogen/node_modules/zeromq/index.js:2:18)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/hydrogen/node_modules/jmp/index.js:37:11)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.7 
script 3.14.1 
autocomplete-clang 0.11.3 
autocomplete-clang.git4 undefined 
autocomplete-python 1.8.63 
busy-signal 1.4.1 
highlight-selected 0.13.1 
Hydrogen 1.12.1 
intentions 1.1.2 
linter 2.1.4 
linter-ui-default 1.2.4 
node_modules undefined 
python-indent 1.0.2 
python-tools 0.6.9 
```

**Comment by lgeiger** [comment]
Try to rebuild hydrogen with `apm rebuild hydrogen`

**Comment by lgeiger** [comment]
Closing in favor of #765
