### ISSUE TITLE
Uncaught Error: Tried loading "pdfjs-dist/build/pdf.worker" at ~/Applications/Atom.app/Contents/R...

### ISSUE THREAD

**Issue by sriram0339** [nteract/hydrogen#777]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 1.12.1

### Stack Trace

Uncaught Error: Tried loading "pdfjs-dist/build/pdf.worker" at /Users/macuser/Applications/Atom.app/Contents/Resources/app.asar/static/pdfjs-dist/build/pdf.worker.js then tried node's require("pdfjs-dist/build/pdf.worker") and it failed with error: Error: Cannot find module 'pdfjs-dist/build/pdf.worker'

```
At /Users/macuser/.atom/packages/Hydrogen/node_modules/requirejs/bin/r.js:2607

Error: Tried loading "pdfjs-dist/build/pdf.worker" at /Users/macuser/Applications/Atom.app/Contents/Resources/app.asar/static/pdfjs-dist/build/pdf.worker.js then tried node's require("pdfjs-dist/build/pdf.worker") and it failed with error: Error: Cannot find module 'pdfjs-dist/build/pdf.worker'
    at /packages/Hydrogen/node_modules/requirejs/bin/r.js:2600:27
    at Object.execCb (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1946:33)
    at Object.check (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1133:51)
    at Object.enable (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1426:22)
    at Object.init (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1038:26)
    at callGetModule (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1453:63)
    at Object.completeLoad (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1840:21)
    at Function.req.load (/packages/Hydrogen/node_modules/requirejs/bin/r.js:2613:17)
    at Object.load (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1935:21)
    at Object.load (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1084:29)
    at Object.fetch (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1074:66)
    at Object.check (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1106:30)
    at Object.enable (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1426:22)
    at Object.enable (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1807:39)
    at /packages/Hydrogen/node_modules/requirejs/bin/r.js:1411:33)
    at /packages/Hydrogen/node_modules/requirejs/bin/r.js:384:23
    at each (/packages/Hydrogen/node_modules/requirejs/bin/r.js:309:31)
    at Object.enable (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1363:17)
    at Object.init (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1038:26)
    at /packages/Hydrogen/node_modules/requirejs/bin/r.js:1710:36
```

### Commands

```
     -2:50.4.0 application:open (input.hidden-input)
     -2:22.2.0 latex:build (input.hidden-input)
     -2:09.4.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -1:37.2.0 core:confirm (input.hidden-input)
  5x -1:33.3.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.24 
atomic-emacs 0.10.0 
Hydrogen 1.12.1 
language-latex 1.0.0 
language-ocaml 1.8.0 
latex 0.43.0 
pdf-view 0.58.0 
```

**Comment by BenRussert** [comment]
We had a similar issue #616, both issues had `pdf-view` installed. Maybe try reinstalling that package?

This is just a guess, if you give more detail on how the error occurred I could try to reproduce.

**Comment by BenRussert** [comment]
See #793
