### ISSUE TITLE
Uncaught Error: Cannot find module 'core-js/library/fn/object/define-property'

### ISSUE THREAD

**Issue by davestroud** [nteract/hydrogen#890]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 1.18.0

### Stack Trace

Uncaught Error: Cannot find module 'core-js/library/fn/object/define-property'

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:1

Error: Cannot find module 'core-js/library/fn/object/define-property'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/Hydrogen/node_modules/babel-runtime/core-js/object/define-property.js:1:110)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/Hydrogen/node_modules/babel-runtime/helpers/createClass.js:5:23)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/Hydrogen/node_modules/anser/lib/index.js:9:21)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/Hydrogen/node_modules/ansi-to-react/lib/index.js:8:13)
```

### Commands

```
     -0:26.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
atom-clock 0.1.10 
atom-html-preview 0.1.22 
autocomplete-clang 0.11.3 
autocomplete-java 1.2.7 
build 0.68.0 
busy 0.7.0 
clang-format 1.29.0 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.7 
Hydrogen 1.18.0 
hydrogen-launcher 1.2.1 
intentions 1.1.2 
language-ini 1.19.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-javac 1.9.4 
linter-ui-default 1.6.2 
minimap 4.28.2 
platformio-ide 2.0.0-beta.6 
platformio-ide-debugger 1.2.3 
platformio-ide-terminal 2.5.1 
tool-bar 1.1.0 
```

**Comment by lgeiger** [comment]
Could you try reinstalling hydrogen with `apm install hydrogen`?

**Comment by davestroud** [comment]
That worked.  Thank you!

**Comment by lgeiger** [comment]
Great!
