### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBuffer' of null

### ISSUE THREAD

**Issue by dimacio** [nteract/hydrogen#905]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 ia32
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 1.18.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getBuffer' of null

```
At /home/akira/.atom/packages/Hydrogen/lib/main.js:362

TypeError: Cannot read property 'getBuffer' of null
    at Object.insertResultBubble (/packages/Hydrogen/lib/main.js:362:26)
    at Object._createResultBubble (/packages/Hydrogen/lib/main.js:336:30)
    at /packages/Hydrogen/lib/main.js:321:12
    at /packages/Hydrogen/lib/kernel-manager.js:155:24
    at ZMQKernel.onConnect (/packages/Hydrogen/lib/zmq-kernel.js:122:21)
    at emitThree (events.js:116:13)
    at Socket.emit (events.js:194:7)
    at self._zmq.onMonitorEvent (/packages/Hydrogen/node_modules/zeromq/lib/index.js:535:12)
```

### Commands

```
     -0:17 hydrogen:run (input.hidden-input)
```

### Non-Core Packages

```
atom-python-virtualenv 0.14.0 
Hydrogen 1.18.0 
```

**Comment by lgeiger** [comment]
I'm pretty sure this was fixed in #888. I'll ship a new version.

**Comment by lgeiger** [comment]
Could you check if this exception still occurs in Hydrogen `v1.19.0`?

**Comment by lgeiger** [comment]
I'm going to close this for now. Feel free to reopen the issue if you still have problems.
